### ISSUE TITLE
Add clickable links to arXiv documents in the latex templates

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1003]
In the template files we need to add 
`\usepackage[hidelinks]{hyperref}`

Then we can use 
`  volume = {\href{https://arxiv.org/abs/1605.01746}{arXiv:1605.01746}},`

To create clickable links to the documents on arXiv

**Comment by nikohansen** [comment]
I usually use the options `colorlinks=true, linkcolor=blue` for the `hyperref` package.

**Comment by brockho** [comment]
This issue should be solved now. I can remember that we postponed this change because some of the tests have not been running correctly, but now everything seems to be fine, hence, I close the issue.
