### ISSUE TITLE
coco_optimizer_t should have a maximal budget parameter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#102]
```
coco_optimizer_t should take maximal budget as an argument: to change the 
budget is a very basic feature in benchmarking, if only to control the time how 
long an experiment will take at most. 
```

Original issue reported on code.google.com by `nikolaus...@gmail.com` on 22 Mar 2015 at 8:10

**Comment by nikohansen** [comment]
Is the `coco_optimizer_t` still in use or deprecated?

**Comment by ttusar** [comment]
It is still used and still does not have a `max_budget` parameter. I'm not sure it needs one...

**Comment by nikohansen** [comment]
What do we need this type for and how to we control the length of the experiment, if it is used?

**Comment by ttusar** [comment]
I guess at this point it's only used by the `example_experiment` in C, because none of the other languages interfaces it. It's a function pointer with only one argument - the problem to evaluate. 

I realize now we would need a `max_budget` too...

**Comment by nikohansen** [comment]
And how about the search domain of interest as further input parameter to the solver...

Or the current best known solution (single objective)...

The problem is that this interface is somewhat versatile and will depend on the solver used.

**Comment by ttusar** [comment]
Eventually remove the `coco_optimizer_t` type and the `coco_run_benchmark` function.

**Comment by ttusar** [comment]
Done.
