### ISSUE TITLE
python-dev required to run python code

### ISSUE THREAD

**Issue by oaelhara** [numbbo/coco#1020]
When trying to run the python code on a distant machine, and after having setuptools installed, 

`python do.py build-python`

results in the following error message:

> AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cython/coco.c
> COPY	code-experiments/src/coco.h -> code-experiments/build/python/cython/coco.h
> ...
> RUN	   python setup.py install --user in code-experiments/build/python
> ERROR: return value=1
> /users/ao/oaelhara/.local/lib/python2.7/site-packages/setuptools-20.10.1-py2.7.egg/setuptools/dist.py:285: UserWarning: Normalizing '0.7.beta' to '0.7b0'
> NOTE: Using precompiled C file to build interface.
> running install
> ...
> building 'cocoex.interface' extension
> x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/lib/python2.7/dist-packages/numpy/core/include -I/usr/include/python2.7 -c cython/interface.c -o build/temp.linux-x86_64-2.7/cython/interface.o
> cython/interface.c:4:20: fatal error: Python.h: No such file or directory
>  #include "Python.h"
>                     ^
> compilation terminated.
> error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
> 
> Traceback (most recent call last):
>   File "do.py", line 729, in <module>
>     main(sys.argv[1:])
>   File "do.py", line 712, in main
>     run_python(False) if len(args) > 1 and args[1] == 'no-tests' else run_python()
>   File "do.py", line 217, in run_python
>     build_python()
>   File "do.py", line 211, in build_python
>     run(join('code-experiments', 'build', 'python'), ['python', 'setup.py', 'install', '--user'])
>   File "/users/ao/oaelhara/numbbo/code-experiments/tools/cocoutils.py", line 103, in run
>     universal_newlines=True)
>   File "/usr/lib/python2.7/subprocess.py", line 573, in check_output
>     raise CalledProcessError(retcode, cmd, output=output)
> subprocess.CalledProcessError: Command '['python', 'setup.py', 'install', '--user']' returned non-zero exit status 1

It seems to be due to the absence of `python-dev` and works once the latter package is installed. 
This should probably be added as a requirement to run the python code in the documentation.

**Comment by nikohansen** [comment]
Thanks for reporting, this has already been observed and documented, see [here](https://github.com/numbbo/coco#compilation-during-install-of-cocoex-fails-under-linux), I will update the description though.
