### ISSUE TITLE
isFig does not affect all figures in postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1021]
The flag `isFig = False` in `genericsetting.py` currently still (tries to) produce(s) some ECDF plots although I would guess that they are also turned off. Scaling graphs on the contrary are correctly affected by this `isFig`.

**Comment by dtusar** [comment]
We have four options:
- tab-only: only tables (applies to pptable, pptable2 and pptables)
- fig-only: only convergence and aRT figures (applies to ppfigdim, ppfig2 and ppfigs)
- rld-only: only runlength distribution figures (applies to pprldmany, pprldistr and pprldistr2)
- los-only: only aRT loss ratio figures (applies to pplogloss)

A combination of any two of these options results in no output.

The description above is copied from the docstring. In the parenthesis are the figures/tables that are affected by the option. Please check if something is not clear enough (in the description) or if any of these options should apply to some other figures/tables.

**Comment by dtusar** [comment]
This is Ok for now.
