### ISSUE TITLE
Postprocessing crashes when no bestalg filename is specified

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1022]
The postprocessing crashes with the following error if no bestalg filename is specified in testbedsettings via `self.best_algorithm_filename = ''` for a single-objective testbed (such as `GECCOBBOBTestbed`):

```
ECDF graphs...
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.7810-py2.7.egg\bbob_pproc\__main__.py", line 301, in <module>
    rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.7810-py2.7.egg\bbob_pproc\rungeneric.py", line 271, in main
    + ["-o", outputdir, alg])
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.7810-py2.7.egg\bbob_pproc\rungeneric1.py", line 410, in main
    genericsettings.single_algorithm_file_name)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.7810-py2.7.egg\bbob_pproc\compall\pprldmany.py", line 512, in all_single_func
tions
    parentHtmlFileName=parentHtmlFileName)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-0
.0.7810-py2.7.egg\bbob_pproc\compall\pprldmany.py", line 667, in main
    bestalgentry = bestalgentries[(dim, f)]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

When setting `self.best_algorithm_filename = ''`, I expect that simply no best algorithm line is plotted in any graph as it is already the case for the bi-objective testbed. But since we still have a lot of those `isBiobjective` checks, some of the plots might not check for `testbedsettings.current_testbed.self.best_algorithm_filename` but instead rely on `isBiobjective`?

**Comment by dtusar** [comment]
Partially fixed. Still crashes with the `--expensive` option (runlength based targets), where it's a little more complicated to fix.

**Comment by nikohansen** [comment]
I might be wrong, but with runlength-based target, isn't it mandatory to have the best algorithm data?

**Comment by dtusar** [comment]
If you use the runlength-based targets with no best algorithm then an exception is raised.
