### ISSUE TITLE
Figures in "Average number of f-evaluations to reach target" are quite strange in large scale.

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#1026]
Hi, please find enclosed the result of post-processing for dataset in large scale (Random Search  for dimension from 20 to 1280). With the BUDGET = 1.0e4, it's hard to reach the easiest target, say 1.0e1, for even easy functions such as sphere, ellipsoid,.... In this case, I and Dimo have found some strange figures in "Average number of f-evaluations to reach target" (click on link `Average runtime versus dimension for selected targets`).
[largescale51.zip](https://github.com/numbbo/coco/files/264739/largescale51.zip)

**Comment by nikohansen** [comment]
It looks like the budget is 1e4, not the budget multiplier. 

Generally it's not a big surprise to see nothing with random search in large dimension. Can you cross check with the random search papers / data which we have already in 20- and 40-D? That's one reason why we have overlapping dimensions. 

What is strange is that there is not even a maximum budget shown for example on the sphere or attractive sector. Did you check that the data look fine?

**Comment by brockho** [comment]
It's not surprising that we see no ERT marker for RANDOMSEARCH for many functions (cp. http://sci2s.ugr.es/sites/default/files/files/TematicWebSites/EAMHCO/contributionsGECCO09/p2479-auger.pdf), but the marker for the final budget we should always see. Hence, I consider this a bug (except if the data is corrupt, but I doubt this).

**Comment by NDManh** [comment]
`It looks like the budget is 1e4, not the budget multiplier.`
You're right, sorry since in this case I run the experiment in C in stead of Matlab and I am confused about this parameter. 

`Did you check that the data look fine?`
I might be wrong but I think that the data is normal. You can find the data set I post below. 

I'll carefully study the second term (cross check with the random search papers / data) and report soon.
[largescale51.zip](https://github.com/numbbo/coco/files/265135/largescale51.zip)

**Comment by NDManh** [comment]
There is marker for the final budget with data of random search which I get from http://coco.gforge.inria.fr/doku.php?id=bbob-2009-algorithms. 

[ppdata.zip](https://github.com/numbbo/coco/files/265209/ppdata.zip)

**Comment by NDManh** [comment]
For figures in `largescale51`: it seems that when 0 is on top-left corner we don't see the marker of maximum budget, i.e, there is nothing below 0. The other cases, we see these marker as usual.

**Comment by NDManh** [comment]
I think I know where this bug comes from, and can solve it but I need your advice to make it optimal.
1) This issue is due to the line codes `ylim = plt.ylim()` (line 479) and `plt.ylim(slim)`(line 483) in the file `ppfigdim.py` (the branch `level-test3`), when the value of `ylim` is close to zero. If we add an additional code `print("Value of ylim = ", ylim)` below the `ylim = plt.ylim()`, like :
```
if 1 < 3: # maxevals
            ylim = plt.ylim()
            print("Value of ylim = ", ylim)
            res.extend(plt.plot(tmp[:, 0], maxevals / tmp[:, 0]**ynormalize_by_dimension,
                       color=styles[len(valuesOfInterest) - 1]['color'],
                       ls='', marker='x', markersize=20))
            plt.ylim(ylim)
```
then run post-processing for the random search we can see that:
```
pc5-174:numbbo NGUYEN$ python -m bbob_pproc RS_largescale1

Post-processing: will generate output data in folder ppdata
  this might take several minutes.

Post-processing (1): will generate output data in folder ppdata/RS_largescale1
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
Scaling figures...
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
  Loading best algorithm data from bestalgentries2016LS.pickle ...
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (0.0, 250.0))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (500.0, 3000.0))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (100.0, 600.0))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (0.0, 9000.0))
('Value of ylim = ', (0.0, 10.0))
('Value of ylim = ', (0.0, 8000.0))
('Value of ylim = ', (0.0, 7.0))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
('Value of ylim = ', (0.0, 1.4000000000000001))
('Value of ylim = ', (0.0, 600.0))
('Value of ylim = ', (0.0, 1.4000000000000001))
('Value of ylim = ', (-0.059999999999999998, 0.059999999999999998))
  done (Tue Aug 30 23:02:33 2016).
Generating LaTeX tables...
  done (Tue Aug 30 23:02:34 2016).
ECDF graphs...
  done (Tue Aug 30 23:02:48 2016).
ECDF graphs per function...
  done (Tue Aug 30 23:05:58 2016).
aRT loss ratio figures and tables...
  done (Tue Aug 30 23:06:06 2016).
Output data written to folder ppdata/RS_largescale1
  done (Tue Aug 30 23:06:07 2016).
pc5-174:numbbo NGUYEN$ 
```
The result of post-processsing is as reported.

2) To solve this issue, we can remove the two line codes above or change like this one:
```
if 1 < 3: # maxevals
           res.extend(plt.plot(tmp[:, 0], maxevals / tmp[:, 0]**ynormalize_by_dimension,
                       color=styles[len(valuesOfInterest) - 1]['color'],
                       ls='', marker='x', markersize=20))
           ylim = plt.ylim()
           plt.ylim(ylim)
```
We do not see this issue anymore, for example:
[ppfigdim_f001.pdf](https://github.com/numbbo/coco/files/445973/ppfigdim_f001.pdf)

3) However, test on the better algorithm (CMAES), I found something changed, for example:
- With the old code: 
[ppfigdim_f001.pdf](https://github.com/numbbo/coco/files/445974/ppfigdim_f001.pdf)
[ppfigdim_f002.pdf](https://github.com/numbbo/coco/files/445979/ppfigdim_f002.pdf)
[ppfigdim_f003.pdf](https://github.com/numbbo/coco/files/445980/ppfigdim_f003.pdf)
-  With the revised code as in 2) :
[ppfigdim_f001.pdf](https://github.com/numbbo/coco/files/445981/ppfigdim_f001.pdf)
[ppfigdim_f002.pdf](https://github.com/numbbo/coco/files/445982/ppfigdim_f002.pdf)
[ppfigdim_f003.pdf](https://github.com/numbbo/coco/files/445983/ppfigdim_f003.pdf)

The vertical axis of figures seems to be changed and I really don't know which is better?

**Comment by nikohansen** [comment]
the above code seems correct to me: it prevents changing the y-limits from plotting maximal evaluation markers, which seems to be the right thing to do. 

I think the main problem here is that there is nothing to plot, not how the nothing is plotted, am I wrong? 

_If_ there is nothing to plot in the entire figure, we could change the y-limits (such that the maxevals symbols become visible) and we would ideally print out a `no target reached` message.

**Comment by NDManh** [comment]
Thank @nikohansen for your comments.
> I think the main problem here is that there is nothing to plot, not how the nothing is plotted, am I wrong?

I've checked on the other figures and found that there is some cases though we have something to plot, the maxevals symbols is not displayed with the old code, for example
- random search : 
[ppfigdim_f019.pdf](https://github.com/numbbo/coco/files/446873/ppfigdim_f019.pdf)
[ppfigdim_f021.pdf](https://github.com/numbbo/coco/files/446874/ppfigdim_f021.pdf)
- CMAES:
[ppfigdim_f020.pdf](https://github.com/numbbo/coco/files/446880/ppfigdim_f020.pdf)

While with the revised code, we have:
- random search : 
[ppfigdim_f019.pdf](https://github.com/numbbo/coco/files/446884/ppfigdim_f019.pdf)
[ppfigdim_f021.pdf](https://github.com/numbbo/coco/files/446886/ppfigdim_f021.pdf)
- CMAES: 
[ppfigdim_f020.pdf](https://github.com/numbbo/coco/files/446891/ppfigdim_f020.pdf)

> we would ideally print out a `no target reached` message.

where would you like to print out this message? directly on figures or just on console?

**Comment by nikohansen** [comment]
> I've checked on the other figures and found that there is some cases though we have something to plot, the maxevals symbols are not displayed with the old code, for example

sure, if the maxevals symbols are beyond the y-limits they cannot be seen, but that is rather a feature than a bug: AFAICS it seems preferable if maxevals symbols do not modify the y-limits. 

the message should go into the figure, not into the console.

**Comment by nikohansen** [comment]
However, the upper ylimit `log10(ylim()[1])` should IMHO always be an integer, that is, it should be set to `ceil(ylim()[1])` in the very end.

**Comment by NDManh** [comment]
Hi @nikohansen , what do you think about the following code:
```
if 1 < 3: # maxevals
            ylim = plt.ylim()
            res.extend(plt.plot(tmp[:, 0], maxevals / tmp[:, 0]**ynormalize_by_dimension,
                       color=styles[len(valuesOfInterest) - 1]['color'],
                       ls='', marker='x', markersize=20))
            ylim_maxevals = max(maxevals / tmp[:, 0]**ynormalize_by_dimension) #Manh: prepare for no target reached
            if no_target_reached:  # Manh: no target is reached
                ylim = (ylim[0], math.ceil(ylim_maxevals))
                plt.annotate('no target reached', xy=(0.5, 0.5), xycoords='axes fraction', fontsize=14,
                            horizontalalignment='center', verticalalignment='center')
            else:
                ylim = (ylim[0], math.ceil(ylim[1]))
            plt.ylim(ylim)
```
where `no_target_reached = 1` iff no target is reached over all dimensions. For more detail, please find the enclosed file  [ppfigdim.py.zip](https://github.com/numbbo/coco/files/449293/ppfigdim.py.zip)

- And here are some figures of RS obtained with the modified code: 
[ppfigdim_f001.pdf](https://github.com/numbbo/coco/files/449307/ppfigdim_f001.pdf)
[ppfigdim_f002.pdf](https://github.com/numbbo/coco/files/449311/ppfigdim_f002.pdf)
[ppfigdim_f003.pdf](https://github.com/numbbo/coco/files/449309/ppfigdim_f003.pdf)
[ppfigdim_f004.pdf](https://github.com/numbbo/coco/files/449312/ppfigdim_f004.pdf)
[ppfigdim_f005.pdf](https://github.com/numbbo/coco/files/449310/ppfigdim_f005.pdf)
[ppfigdim_f006.pdf](https://github.com/numbbo/coco/files/449313/ppfigdim_f006.pdf)
[ppfigdim_f007.pdf](https://github.com/numbbo/coco/files/449308/ppfigdim_f007.pdf)
[ppfigdim_f008.pdf](https://github.com/numbbo/coco/files/449314/ppfigdim_f008.pdf)
[ppfigdim_f009.pdf](https://github.com/numbbo/coco/files/449315/ppfigdim_f009.pdf)
[ppfigdim_f010.pdf](https://github.com/numbbo/coco/files/449316/ppfigdim_f010.pdf)
[ppfigdim_f011.pdf](https://github.com/numbbo/coco/files/449317/ppfigdim_f011.pdf)
[ppfigdim_f012.pdf](https://github.com/numbbo/coco/files/449318/ppfigdim_f012.pdf)
[ppfigdim_f013.pdf](https://github.com/numbbo/coco/files/449319/ppfigdim_f013.pdf)
[ppfigdim_f014.pdf](https://github.com/numbbo/coco/files/449320/ppfigdim_f014.pdf)
[ppfigdim_f015.pdf](https://github.com/numbbo/coco/files/449321/ppfigdim_f015.pdf)
[ppfigdim_f016.pdf](https://github.com/numbbo/coco/files/449322/ppfigdim_f016.pdf)
[ppfigdim_f017.pdf](https://github.com/numbbo/coco/files/449325/ppfigdim_f017.pdf)
[ppfigdim_f018.pdf](https://github.com/numbbo/coco/files/449324/ppfigdim_f018.pdf)
[ppfigdim_f019.pdf](https://github.com/numbbo/coco/files/449323/ppfigdim_f019.pdf)
[ppfigdim_f020.pdf](https://github.com/numbbo/coco/files/449327/ppfigdim_f020.pdf)
[ppfigdim_f021.pdf](https://github.com/numbbo/coco/files/449326/ppfigdim_f021.pdf)
[ppfigdim_f022.pdf](https://github.com/numbbo/coco/files/449328/ppfigdim_f022.pdf)
[ppfigdim_f023.pdf](https://github.com/numbbo/coco/files/449330/ppfigdim_f023.pdf)
[ppfigdim_f024.pdf](https://github.com/numbbo/coco/files/449329/ppfigdim_f024.pdf)
- Please also tell me your ideas about : the format, the position,... of the message `no target reached` on the figures if you want to change.

**Comment by nikohansen** [comment]
Seems to be on the right track. How do you assign `no_target_reached`? Why do you assign `ylim_maxevals`, even though it might never be used (when targets have been reached)?

the `: no target is reached` in the comment is unnecessary and should hence be removed.

**Comment by NDManh** [comment]
> How do you assign `no_target_reached`? 

You can find in the file `ppfigdim.py`I have attacked. For each function, initially `no_target_reached` is assigned to 1, and it would be changed to 0 if there is one target to be reached in one dimension of interest.  

> Why do you assign `ylim_maxevals`, even though it might never be used (when targets have been reached)?

You're right, Niko. I'll put it inside the `if` command, and remove the comments.

**Comment by brockho** [comment]
It seems that this problem of "empty plots" is still not solved and even happens with other test suites and algorithms, e.g. for GDE3 and the `bbob-biobj` suite:

![image](https://user-images.githubusercontent.com/13706996/33768402-2e2deb22-dc26-11e7-952d-b3450e7903b3.png)

**Comment by nikohansen** [comment]
Then the question is: what do we want or expect to see instead? Ideally a "no target reached" text would be printed, but what else could we expect to see?

**Comment by brockho** [comment]
I would have expected the red `maxbudget` crosses all over the place ("maximum number of function evaluations from the longest trial divided by dimension"). These should be always available and thus displayed.

**Comment by nikohansen** [comment]
I see, the "problem" is that in the default case the `maxbudget` values do not influence the y-limits and that they should not, in particular when the final target was hit. The reasoning is that, for example, the budget could be arbitrarily large without really changing anything else, hence the display should not change. If the success probability is `>0` and `<=1/2`, the symbols will always be within the displayed area automatically.

**Comment by brockho** [comment]
We did not see this problem for some time. It does not mean that it is fixed but together with @nikohansen and @ttusar we decided today to close the issue until it's happening again :-)
