### ISSUE TITLE
versioning and reference quality indicator

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1027]
It would be a nice-to-have feature to display in the figures, additionally to the release number, some indication of the used reference values, say for the first instance of the first function in the smallest dimension of the shown data. The final target could be shown additionally, if not already given in the legend. This would allow to know whether the shown data from two different versions are yet comparable.

**Comment by brockho** [comment]
In the `feature-refalg` branch and thanks to @dtusar, we now display a hash of the used reference values in (almost) all figures. From my point-of-view, this hash is a bit too long, but besides this, the issue can be closed I guess?

**Comment by dtusar** [comment]
The hash is now shorter.
