### ISSUE TITLE
NAN values in best_parameter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#103]
```
In f_bbob_step_ellipsoid and f_schwefel, all values in problem.best_parameter 
are set to NAN. It seems preferable, if best_parameter was just set to NULL 
(i.e. to do nothing). This seems more logical, because it cannot be only a few 
values in best_parameter NAN. It is also more generic to test later as if 
best_parameter != NULL instead of if best_parameter[0] != NAN.
```

Original issue reported on code.google.com by `nikolaus...@gmail.com` on 22 Mar 2015 at 8:18

**Comment by nikohansen** [comment]
@asmaatamna please confirm that this can be closed.

**Comment by asmaatamna** [comment]
best_parameter is still set to NAN in f_step_ellipsoid.c

**Comment by asmaatamna** [comment]
Not true: it's updated afterwards but it's initially set to NAN. Therefore the issue can be closed (if it's OK to initially set best_parameter to NAN...)

**Comment by nikohansen** [comment]
It wouldn't be desirable to have object instances in an inconsistent state at any point in time (e.g. as a return value). Why couldn't it be set to zero initially?

**Comment by asmaatamna** [comment]
Well I'm not sure zero is the best parameter of the raw step ellipsoid problem (I set it to zero though just to get rid of NAN)

**Comment by nikohansen** [comment]
What is the alternative? Are you suggesting zero is not the optimum? 

Compare http://coco.lri.fr/downloads/download15.01/bbobdocfunctions.pdf#page=29

**Comment by asmaatamna** [comment]
Right. I'm closing this issue then.
