### ISSUE TITLE
old paper links broken

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1047]
The page http://coco.gforge.inria.fr/doku.php?id=bbob-2009-algorithms
contains links like
http://sci2s.ugr.es/sites/default/files/files/TematicWebSites/EAMHCO/contributionsGECCO09/p2479-auger.pdf
which are broken, because http://sci2s.ugr.es seems down. 

One way to solve this could be linking to the Google scholar entry of the papers.

**Comment by brockho** [comment]
For some time now, the above mentioned links work again. There have been a few links to 2010 papers though that had to be updated to link to available pdfs or, if not possible, to the correct DOI at the ACM Digital Library. I therefore consider this issue to be closed. However, we anyway need to re-organize the data soon with the upcoming new data from 2016 and the biobjective test suite (and potentially for other new data on new suites).
