### ISSUE TITLE
Generic Testing of Suites

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1048]
We should have some generic code to generate tests for new test suites in the future. It will consist of two parts: a first part is run once and generates the objective functions' and constraint functions' values for a given set of fixed solutions and a second part compares these values with the outputs on the same solutions from the current code.

**Comment by ttusar** [comment]
We should do this in python, not C.

**Comment by nikohansen** [comment]
The result of the first part: a file for each test suite, where each line looks like, for example
```
1: [0.225, 0.445678], [154.667888], []
```
indicating the problem index, the x-value, the f-value(s), the constraint value(s).

**Comment by nikohansen** [comment]
Implemented in the development branch, `test/regression-test` folder.
