### ISSUE TITLE
bbob2009logger crashed if problem->best_value == NULL

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#105]
```
It should either abort with an coco_error, or give a coco_warning and proceed 
assuming best_value = 0.
```

Original issue reported on code.google.com by `nikolaus...@gmail.com` on 22 Mar 2015 at 11:45

**Comment by oaelhara** [comment]
Seems to already be addressed in logger_bbob2009 where a NULL problem->best_value generates a warning and sets the optimal value used by the logger (not that of the problem) to 0

**Comment by oaelhara** [comment]
Should this issue be closed?

**Comment by nikohansen** [comment]
_Seems to already be addressed..._ I assume you _know_ that it has been addressed because you addressed it, hence I am closing it.
