### ISSUE TITLE
Handling Rotated Functions with Optimal Value (of the raw function) not in the Origin

### ISSUE THREAD

**Issue by oaelhara** [numbbo/coco#1055]
`coco_warning("transform_vars_affine(): 'best_parameter' not updated, set to NAN");` is raised on the rotated Rosenbrock (f8) and the Composite Griewank-Rosenbrock Function (f19) since `problem = transform_vars_affine(problem, M, b, dimension);` is applied after allocating the problem(`coco_problem_t *problem = coco_problem_allocate_from_scalars("Rosenbrock function", f_rosenbrock_evaluate, NULL, number_of_variables, -5.0, 5.0, 1.0);`) which sets `problem->best_parameter[i] = 1.0`.

A work-around can is suggested in #1054 but doesn't seem optimal.

**Comment by brockho** [comment]
same as #814

**Comment by brockho** [comment]
Like #814, this can be closed.
