### ISSUE TITLE
Postprocessing crashes when two algorithms are compared

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1056]
I get the following message (most likely was the bug introduced by myself :-(, strange that the tests did not catch it):

```
C:\Users\dimo\Desktop\coco-master-git>python -m bbob_pproc -o myppdata --omit-single RS-100 MAT-SMS
Post-processing: will generate output data in folder myppdata
  this might take several minutes.
Post-processing will generate comparison data in folder myppdata
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\RS-100
  Data consistent according to test in consistency_check() in pproc.DataSet
  using: .\MAT-SMS
log aRT1/aRT0 vs target function values...
  done (Wed Jun 01 21:56:41 2016).
[...]
Generating old tables (pptable2.py)...
  done (Wed Jun 01 22:03:52 2016).
Generating new tables (pptables.py)...
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1
.0.2.286-py2.7.egg\bbob_pproc\__main__.py", line 300, in <module>
    rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1
.0.2.286-py2.7.egg\bbob_pproc\rungeneric.py", line 273, in main
    rungeneric2.main(genopts + ["-o", outputdir] + args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1
.0.2.286-py2.7.egg\bbob_pproc\rungeneric2.py", line 622, in main
    testbedsettings.testbed_name_bi) else True))
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-1
.0.2.286-py2.7.egg\bbob_pproc\compall\pptables.py", line 657, in main
    with open(filename) as infile:
IOError: [Errno 2] No such file or directory: 'myppdata\\templateBBOBmany.html'
```

**Comment by dtusar** [comment]
I fixed the error. The tests didn't catch this because the test for many algorithms is scheduled before the one for two algorithms. So, the file exists and you don't get the error. We should delete the files after each test.

Now we produce `pptable2.html` and `pptables.html` when running with two algorithms.I think that only the latter should be shown in html hierarchy. But currently the tables use different targets. Which targets should we use?

**Comment by brockho** [comment]
Thanks for fixing the error. The main reason for the different number in targets displayed was/is the width of the LaTeX/PDF page and the way, we put the table there (one column vs. two columns). Hence, I would always go for the larger number of targets for the html display, i.e., also `pptable_targetsOfInterest` for the `pptables.html`.

At some point, the single-objective LaTeX templates for 2 and the one for 3+ algorithms should be merged from my point-of-view into one such that we don't need the `pptable2` anymore in the long run.

**Comment by dtusar** [comment]
Currently we build in the same way the tables for the latex templates and for the html. This means they have the same targets. For the bi-objective case I tried using for `pptables `the targets from `pptable`, but that's too many targets for the latex template.

**Comment by dtusar** [comment]
Now after each test the produced files are deleted, so the CI tests should catch this in the future.
