### ISSUE TITLE
Post-processing unknow error 

### ISSUE THREAD

**Issue by strickler** [numbbo/coco#1058]
Dear all,
I was trying to run the post-processing for an algorithm, and I came cross an unknown error.

I executed this command: python -m bbob_pproc -o resultsTESTE exdata/NSGAII-P-U_on_bbob-biobj/
Post-processing: will generate output data in folder resultsTESTE
  this might take several minutes.
Post-processing (1): will generate output data in folder resultsTESTE/NSGAII-P-U_on_bbob-biobj
  this might take several minutes.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/__main__.py", line 300, in <module>
    rungeneric.main(args)
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/rungeneric.py", line 270, in main
    + ["-o", outputdir, alg])
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/rungeneric1.py", line 281, in main
    dsList = DataSetList(filelist, genericsettings.verbose)
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/pproc.py", line 1485, in **init**
    self.processIndexFile(name, verbose)
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/pproc.py", line 1556, in processIndexFile
    ds = DataSet(header, comment, data, indexFile, verbose)
File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/pproc.py", line 813, in **init**
    (adata, maxevals, finalfunvals) = alignData(data, self.isBiobjective())
  File "/home/andreistrickler/.local/lib/python2.7/site-packages/bbob_pproc-1.1.2-py2.7.egg/bbob_pproc/readalign.py", line 353, in alignData
    return (numpy.vstack(res), numpy.array(list(i.nextLine[idxEvals] for i in data)),
  File "/usr/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: need at least one array to concatenate

Where exactly could be the error. 
When I try with a different algorithm, this error does not appear.

If this have been commented in another issue, sorry for create this one.
Thanks in advance.

**Comment by dtusar** [comment]
Hi,

It looks like a part of data is missing for this algorithm, but it's not clear which part. In order to locate the problem it would be very helpful if you could upload the data (i.e. the folder `exdata/NSGAII-P-U_on_bbob-biobj/`) here.

**Comment by brockho** [comment]
@strickler: is this issue still appearing with the latest release? If yes, would you be so kind and send us your data folder as suggested by @dtusar such that we can investigate the bug?

Thanks,
Dimo

**Comment by brockho** [comment]
Given that there was no response for 25 days on this issue, we close this issue.

**Comment by strickler** [comment]
@brockho, I am so sorry for not responding you guys. I was full of work and did not realized your questions here.

I would be very grateful if you reopened that issue. 'Cause I tried to reproduce again with the new release (1.2.1), and the error keep the same.

**Comment by strickler** [comment]
I am sorry, the folder was not uploaded.
Here it is:
[NSGA2-CMAES-.tar.gz](https://github.com/numbbo/coco/files/601738/NSGA2-CMAES-.tar.gz)

**Comment by strickler** [comment]
Hi guys, I'm adding more information here.

I agree with what @dtusar suspects. About missing some data information during the run process and save the files.

If you find some incorrect data/information in this folder that I attached above, do not hesitate to contact me.

Many thanks.

**Comment by dtusar** [comment]
Hi @strickler,

Thank you for the data. I don't know what happened with your last two replies. Nevertheless, I could get your data using the link in the notification email. I saw that in the `bbob-biobj_f11_d02_hyp.tdat` file there is one instance that contains only data for evaluation 0 and 50000. All the evaluations in between are missing. Similar in the other `tdat` files of the function `f11`. Maybe also for some other function but I didn't check them all. I'm not sure how this happened. 

The post processing is currently not robust enough to handle this. We will fix it in the next release.

**Comment by strickler** [comment]
Hi @dtusar, many thanks for your reply.
Yes, I notice that too, and also, discover in my tests a little bug.
I do not know why, but for some reason the algorithm just do not execute and output exactly what you described above (0 and 50000). 
In addition to this, I discover that coco Post-processing do not accept this way of data (0 and 50000), but when I was investigating this I realize that if the 0 was changed for 1, this will be accept to run the post-processing. There is a simpler answer for this?

By the way, I realize that COCO uses only 5 of the 10 executions to 'compare' in the post-processing.
How could I 'remove' this bad execution and give to coco the 9 good ones?

Again, many thanks for your support.

**Comment by dtusar** [comment]
It was fixed with the commit fe1c2046d58e8009ba934094366e621115fea253 (currently on the `feature-refalg` branch) and it will be included in the next release.
