### ISSUE TITLE
Logging restarts in the bi-objective case

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1073]
For some reason, the bi-objective logger does not log restarts in `.rdat` files as in the single-objective case. Discussing with @ttusar about how to reconstruct the data sets from the archive files, it might be the best solution to log these restarts directly in the archive files (as additional comment lines) instead of writing `.rdat` files. Like that, runs can be fully reconstructed from the archive folder (as soon as the largest evaluation count per problem is written as well). Note that both the additional lines in the `.adat` and the `.rdat` files would be only produced for the convenience of the user without affecting the postprocessing.

**Comment by nikohansen** [comment]
The `code-experiment/build/python/example_experiment2.py` now records the stopping conditions from the algorithm after each launch.

**Comment by brockho** [comment]
Can this be closed? From discussions in the recent past, we realized that independent restarts do not make sense in our setting where the performance measure is based on the hypervolume of the entire set of non-dominated solutions, found so far.
