### ISSUE TITLE
Consistency check of hypervolume reference values

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1080]
Given that it is likely that the hypervolume reference values change over time for the `bbob-biobj` test suite, in the long run, we should implement a corresponding consistency check in the postprocessing. It shall compare for each function, dimension, and instance that the hypervolume reference values match for all algorithms (as written in the `.dat` files for example). If not, at least a warning shall be issued.

**Comment by brockho** [comment]
A good idea, after discussing with @dtusar and @nikohansen, seems to be to produce a hash from all hypervolume reference values over all instances, dimensions, and functions together with the hash from the first 5 instances (if present). These values should also be displayed in the plots according to #1027.

**Comment by brockho** [comment]
Detailing the last entry, we should create a dictionary of problem_id as key and the reference hypervolume value as value and then use the build-in python function for creating an (integer) hash from it.

**Comment by brockho** [comment]
see also #1027

**Comment by dtusar** [comment]
I have a couple of questions:
1. Now we return a warning if two algorithms have a different hash, i.e. different functions, dimensions, instances and/or any reference values. Is this OK, or did you have something else in mind?
2. @brockho Why do we need the hash for the first 5 instances? The hash for the currently used instances should be enough? Or not?
3. Do we allow creating the custom best algorithm from algorithms that have different hash values? I would say no, but the dimensions are a little more tricky. You can have an algorithm that does not have a particular dimension, but you can still use is in the other dimensions.

**Comment by nikohansen** [comment]
> Do we allow creating the custom best algorithm from algorithms that have different hash values?

Yes, for sure in the single-objective case. For one, instance numbers have changed each year. Having only portfolio best algorithms from single years would be too restrictive. That was one reason why we decided to only use one aggregated number, aRT, to represent the best algorithm on each function+dimension+target: no need to find a representation of a data set where instance numbers can change for each target.

**Comment by brockho** [comment]
The reason for proposing to compare the hash of the first 5 instances is that those instances 1-5 are expected to be kept the same for all algorithms benchmarked for the BBOB workshops and thus, comparing the hash for only those first five instances can detect a change in the reference value for the hypervolume computation. Only when the hash for instances 1-5 is different for some to-be-displayed algorithms, a warning should be given. The reason is that, as @nikohansen said, it should be possible to compare algorithms which were run on different sets of instances. If the hash for all instances changes, it can be because of a change in the hypervolume reference values or because the instances themselves are different...

**Comment by dtusar** [comment]
> Yes, for sure in the single-objective case. For one, instance numbers have changed each year. 

Do we even need to calculate the hash for the single objective case since we don't have the reference values? The hash would then only check if two algorithms used the same functions, dimensions and instances. 

> The reason for proposing to compare the hash of the first 5 instances is that those instances 1-5 are expected to be kept the same for all algorithms benchmarked for the BBOB workshops and thus, comparing the hash for only those first five instances can detect a change in the reference value for the hypervolume computation. Only when the hash for instances 1-5 is different for some to-be-displayed algorithms, a warning should be given. 

So the hash should be calculated for the instances 1-5 regardless if these instances are actually shown in the plots? Also, if the important hash is the one for the instances from 1-5 then I suppose this one should be visible in the plots. I'm not sure if we even have to calculate the hash for all used instances any more.

**Comment by nikohansen** [comment]
> Do we even need to calculate the hash for the single objective case since we don't have the reference values?

Right, good point, AFAICS we don't need them.

**Comment by dtusar** [comment]
The hash is generated from the first five instances and shown in the plots in the bi-objective case. With this I will close the issue.
