### ISSUE TITLE
Generalized Sharp Ridge Function

### ISSUE THREAD

**Issue by oaelhara** [numbbo/coco#1093]
Similarly to the number of short/long axes in the Discuss/Bent Cigar functions (respectively), the dimension of the linear part on the Sharp Ridge function needs to be a constant proportion of the problem dimension, not always 1

**Comment by nikohansen** [comment]
Done, but where do I find the updated versions of Discus and Cigar?

**Comment by oaelhara** [comment]
For now, and since not all the tests were passed, in the branch devel-test3 where a generalized sharp ridge is also included.
These can also be found in the devel-LS branch of my fork

**Comment by nikohansen** [comment]
Looks like this issue should have been closed some time ago.
