### ISSUE TITLE
Deal with (too) rich data sets

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#11]
```
Test the (already implemented?) feature that writes more data than needed 
(implemented in fgeneric) in the post-processing; especially skip additional 
data entries
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 9:01

**Comment by nikohansen** [comment]
as we are currently more leaning to the idea to use all data by making the processing fail-safe to a varying number of instances, see #1117
