### ISSUE TITLE
"Backward Compatibility" of Large Scale Test-Bed 

### ISSUE THREAD

**Issue by oaelhara** [numbbo/coco#1102]
On dimensions 20 and 40, the current version of the large-scale code does not reproduce "exactly" the same problems (instance-wise) as the bbob noiseless test-bed because of the permutations that are applied regardless.
For backward compatibility purposes, when dimension is not larger than 40, no permutation should be applied (the rotation matrix is full since `block_size(d <= 40) = d`).

**Comment by brockho** [comment]
I will add a test to `test_suites.py` that can be used to test the above by simply commenting in the lines at the end.

**Comment by brockho** [comment]
My part is now addressed with 044da6f. The code for creating the new data from the existing ones can be found as a comment within the `regression_test_2-bbobdata_for_bbob-largescalesuite.py` file.
