### ISSUE TITLE
Tables don't display function numbers in bbob-biobj case

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1109]
At least in the `bbob-biobj` case, the postprocessing is currently not displaying the lines with the function number in the html output, except for `f1`, when postprocessing more than 2 algorithms:

![nofunctionnumber](https://cloud.githubusercontent.com/assets/13706996/16821616/82850f38-4957-11e6-836e-ff49652a9783.png)

**Comment by brockho** [comment]
I'll have a look in the coming days.

**Comment by dtusar** [comment]
The reason why the header is visible only for some functions is last parameter in this call:
```
pptables.main(
                        tmpdictdim,
                        sortedAlgs,
                        outputdir,
                        genericsettings.verbose,
                        ([1, 20, 38] if (testbedsettings.current_testbed.name ==
                                         testbedsettings.testbed_name_bi) else True))
```

@brockho This is the commit info (I don't know how to get the link):

Author: brockhof <dimo.brockhoff@inria.fr>
Date: 10/05/2016 23:47:07
Message:
made table in many-algorithm output ready for bbob-biobj suite (Bonferroni correction still wrong)
Revision: 15f25bb71e03d4d579f592d71e405cbe8500c999
----
Modified: code-postprocessing/bbob_pproc/compall/pptables.py
Modified: code-postprocessing/bbob_pproc/config.py
Modified: code-postprocessing/bbob_pproc/genericsettings.py
Modified: code-postprocessing/bbob_pproc/rungenericmany.py
Modified: code-postprocessing/bbob_pproc/testbedsettings.py

Are these changes somehow related to the output of the latex template? What should be the correct behavior?

**Comment by brockho** [comment]
@dtusar: If I am not mistaken, the last parameter in `pptables.main` affects the very first line of the tables, i.e., the ones displaying the targets. The line, I was referring to, that is missing in the output when the bestalg is not present are the lines that display the function number (`f1` for example). Again, I will have a closer look in the coming days to see where the error is coming from.

I am relatively sure that the missing lines will appear again as soon as we add the bestalg also for the `bbob-biobj` test suite, but the error will arise again (if we don't solve it now) as soon as we have a new test suite without bestalg (for example the constrained or large-scale test suites).

**Comment by dtusar** [comment]
AFAICS it affects both lines. So what should be the correct behavior? The first line should be visible only at the specific functions? Is this OK also for `html` or only for latex template? The line with the function number should be visible for every functions in `html` and also latex?

**Comment by nikohansen** [comment]
At least the function number must be written, like it is for `f1`, for any and all functions.

**Comment by brockho** [comment]
Eventually, I tracked down the location of the bug: It was mainly due to a wrong order in which the html was produced together with the wrong line `curline = [r'\aRT{}$_{\text{best}}$'] if with_table_heading else [r'\textbf{f%d}' % df[1]]` instead of a simple `curline = [r'\textbf{f%d}' % df[1]]`. The fix is currently running through all tests on the `devel-test` branch and will be merged into `development` as soon as the tests pass.

I also removed the `--omit-single` from the first test of the nightly-build in order to be able to catch more bugs (because so far, all tests had this option turned on).
