### ISSUE TITLE
--conv output needs revision

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1113]
When producing the convergence graphs with the `--conv` option, the html output does not tell which functions are displayed. Actually, the function name/id should probably be displayed directly within the figures.

**Comment by nikohansen** [comment]
The `index.html` page should also have an entry for these graphs (even if they are not yet perfectly presented).

**Comment by dtusar** [comment]
Still missing the numbers of instances.

**Comment by dtusar** [comment]
This is solved.
