### ISSUE TITLE
clicking through pprldmany-single-functions/pprldmany_XXD.html...

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1114]
...on other than the first function is weird because it always jumps to the top of the page with the next dimension. We should add some anchors and link to the anchor of the corresponding function, when clicking.

**Comment by brockho** [comment]
I guess, we will not have this functionality soon since the new `previous dimension` and `next dimension` links work now for the set of all functions and no single-function-links-to-next-dimension seem to be planned.

**Comment by nikohansen** [comment]
One solution to the use case to sweep a single figure through different dimensions is to open each of these figures in a new tab. For me it is two clicks to prepare each tab: click on next dimension and alt-click on the respective figure.
