### ISSUE TITLE
shorten text with number of instances in many algo ECDFs

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1115]
The line with `10, 10, 10, ...,, 10 instances` in the ECDF graphs is too long when more than a few algorithms are displayed. The display should be shortened in this case, most likely to all appearing numbers of instances (if the data is not corrupted, it should display maximally two different numbers, I would guess).

**Comment by loshchil** [comment]
The font size might be adjusted to constraint the text to satisfy some
fixed maximum length of the line.

**Comment by brockho** [comment]
I had rather in mind to only display the different numbers appearing (and not one number per algorithm), e.g. `10 or 7 instances` instead of `10, 10, 10, 7, 10, 10 instances`. Changing the font size has the disadvantage that with too many algorithms the text becomes again not readable anymore.

**Comment by brockho** [comment]
This issue is solved now with the latest pull-request #1131 into the development branch and will be effective with the next release.
