### ISSUE TITLE
Expose reference worst f-values-of-interest to the solver

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1120]
in the bi- or multi-objective case (as suggested by @TGlas and others). The candidate would be the Nadir point, also because it defines the switch (from distance to hypervolume) when computing the currently used quality indicator.

Rationales: 
- In practical applications it is quite likely to be available and highly useful. 
- It might be "unfair" and result in an unwarranted bias to leave the solver completely in the dark about this information.

**Comment by loshchil** [comment]
if you consider constrained optimization, then yes, one can estimate the
worst f-value
if you consider unconstrained optimization (as in both variants of BBOB
now), then they are +inf for both objectives in many or all cases, right?

**Comment by nikohansen** [comment]
Sorry, the title was misleading, I meant to say worst f-value-of-interest rather than worst f-value. This value is meant to be additional information which cannot be unambiguously concluded from the black box itself.

**Comment by nikohansen** [comment]
Re https://github.com/numbbo/coco/issues/1304#issuecomment-276974513: Because the domain middle is trivially known by the solver, we may imply that only solutions not dominated by the domain middle are of interest. The domain middle is seems yet not sufficient to imply a worst f-value-of-interest in each objective.

**Comment by brockho** [comment]
I will take care of the Matlab wrapper then.

**Comment by ttusar** [comment]
This is now taken care of in C, Java and Python, only Matlab remains.

**Comment by brockho** [comment]
The Matlab/Octave wrapper now also supports the new `coco_problem_get_largest_fvalues_of_interest`. I have, however, not tested it on Matlab (only on Octave on my machine and on the CI) and I also did not add a test, see also the open question in #1627.

However, from my side, the issue can be closed.

**Comment by ttusar** [comment]
We still need to document this, see issue #1633
