### ISSUE TITLE
About the function `about_equal_value(const double a, const double b)`

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#1126]
I am not sure it is an issue but this function returns 1 for the case `a = 1 + E-06, b = 1 - E-06`, while it returns 0 for the case `a = E-06, b = - E-06`. Should we replace `relative_error = fabs((a - b) / larger)` with `relative_error_new  = fabs((a - b) / (1+larger))` to mesure the error since:
- If `a` and `b` are close to 0, then the `relative_error_new` --> `absolute_error`
- The other case, it is close to the relative error.

**Comment by nikohansen** [comment]
What is the problem with the current implementation? In other words, why do you suggest the change? It seems correct to me to compute and consider relative and absolute error independently. 

The only problem I see in the implementation https://github.com/numbbo/coco/blob/262a074d62ed87b3b0e18b809ed382c93a093401/code-experiments/test/unit-test/unit_test_utilities.c is division by zero, which I would even consider as a bug. That is, I think it should read `relative_error = fabs((a - b) / (1e-22+larger))`.

**Comment by NDManh** [comment]
The problem is that the implementation seems unfair for some cases. For example, if we consider `a1 = 1 + E-06, b1 = 1 - E-06` then `about_equal_value(a1, b1) = 1`, and  `a2 = E-06, b2 = -E-06` then `about_equal_value(a1, b1) = 0`; while the fact is `|a1 - b1| =  |a2 - b2| = 2E-06`. That is reason I suggest the change, for example as below:
```
static int about_equal_value(const double a, const double b) {
  /* Copied from an integration test.
   *
   * Shortcut to avoid the case where a - b is tiny and both a and b
   * are close to or equal to 0.
   *
   * Example: a = +EPS and b = -EPS then the relative error is 2 but
   * in fact the two numbers are both for all practical purposes 0.
   */
  if (a == b)
    return 1;
  {
    const double larger = fabs(a) > fabs(b) ? a : b;
    const double relative_error = fabs((a - b) / (1+larger));

    return relative_error < eps;   
  }
}
```
where `eps` is the precision we want to set.

**Comment by nikohansen** [comment]
I don't see in itself to be anything wrong if `-0.000001 \not\approx- 0.000001` while `0.999999\approx1.000001`. I would also suggest rather to try change the constants in the code if the current behavior turns out to be unwarranted.

**Comment by NDManh** [comment]
Sorry, you're right, ll should be: `relative_error = fabs(a - b) / (1+fabs(larger));`.

**Comment by nikohansen** [comment]
I fixed the division-by-zero bug in the current implementation. I will close this as I don't see the rationale behind to compound absolute and relative error in a single expression instead of keeping them separate.

**Comment by NDManh** [comment]
OK, no problem, it's just an effort for unification. Also, I found the same situation in the two other files: 
- the function `about_equal_value(const double a, const double b)` in `unit_test_utilities.c`
- the function `about_equal(a, b, precision=1e-6)` in `utilities.py`

**Comment by nikohansen** [comment]
thanks for the additional pointers
