### ISSUE TITLE
Merging run-LANGUAGE with install-postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1127]
In order to simplify the installation process, we should consider merging the `install-LANGUAGE` and the `install-postprocessing` parts of `do.py` to one command per language and (re-)name it to something like `install-and-test-LANGUAGE` or `install-coco-in-LANGUAGE`. The documentation should of course be updated accordingly.

**Comment by nikohansen** [comment]
just a remark: the reason though why we kept the installations separate is that we don't need to run the experiments and the post-processing on the same machine and the requirements for the Python post-processing installation are much greater than for just installing, say, the C code. 

Suggestions:

  - we have an opt-out option, like `--nopp` or something (should be consistent with current syntax which I don't remember by heart). 

  - if the post-processing installation fails, a warning is produced but it doesn't effect the experiments installation.

**Comment by brockho** [comment]
Okay, I see your point. I suggest to simply leave everything as is for now and close the issue.

**Comment by nikohansen** [comment]
OK, I think the additional burden to the user very small and has the advantage to educate the user that these _are_ different and "independent" Python modules.
