### ISSUE TITLE
Automated download of algorithm data

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1128]
It will be nice (and it should not be too difficult to implement) if any existing algorithm data set can be used directly in the postprocessing without having to download it by hand. The tests in part already do that: check whether the data set is available locally and if not then download it from our GForge webpage.

**Comment by nikohansen** [comment]
I suggest to implement this functionality in particular as Python-shell feature (and only as system-shell feature, if this doesn't add much complexity to the implementation). In particular should the user also be able to get a list of all available data sets from the shell. This functionality should probably be based on the spreadsheet doc that we have been considering in #69. Data can then be referenced by a short name or by a number or by a url like `http:...zip` (which could be any data set).

**Comment by brockho** [comment]
Note that some related discussion can be found in #1233 were it was finally off-topic and thus the issue has been closed.

**Comment by brockho** [comment]
Seems to be closable with the newest code by @nikohansen on that issue, right?

**Comment by nikohansen** [comment]
It seems to me that
```python
import cocopp
[cocopp.archive.get(name) for name in cocopp.archive]
```
is what you were looking.
