### ISSUE TITLE
Move documentation source code

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1129]
Different to our initial plan, it seems to be unavoidable to move all sources of the COCO documentation out of the normal `coco` repository directly into the `coco-doc` and `workshops` repositories.  The reason is that for some of the papers, we will need to store (and include) quite some figures which will take more than 100MB of space in the case of the `bbob-biobj` function definition paper and which is certainly too much for a normal COCO user to download and store with every release.

**Comment by ttusar** [comment]
@brockho I remember you once wrote down the steps to update the documentation in the `coco-doc` repository, but I cannot find them anywhere. It might be a good idea to paste them into a `Readme.md` in the `coco-doc` repository, so they are always at hand. What do you think (making them public shouldn't be a problem, right)?

**Comment by brockho** [comment]
@ttusar: The documentation you are searching for should be in https://github.com/numbbo/coco/blob/master/howtos/documentation-howto.md. However, due to the large amount of plots for the bi-objective function documentation, we will soon move the `docs/` folder directly into the `coco-doc` repository and I should therefore move also the `howto` there.

> making them public shouldn't be a problem, right

No, not at all. They have been public since we wrote them.

**Comment by brockho** [comment]
Okay, `docs/workshops/` now went to the `sources-webpage/` folder of the `workshops` github repository and the rest of the `docs/` folder is now in the `coco-doc` github repository. The `documentation-howto.md` has also moved there and the former `docs/` folder in the `numbbo-coco` repository could therefore be deleted. All should be therefore solved with pull-request #1150.
