### ISSUE TITLE
Postprocessing

### ISSUE THREAD

**Issue by EoghanRussell** [numbbo/coco#1132]
Hi Guys,
I have been trying to postprocess two sets of results for comparison but I don't believe I am understanding the documentation correctly.

I can run a single set using the command $ python -m bbob_pproc exdata/shotgun1
where shotgun1 is the data folder. I want to compare this to the CMA-ES result located also in the exdata folder so I was trying:

$ python -m bbob_pproc exdata/[shotgun1 [GP1-CMAES]]
 
as per the documentation but it is not working. Am I missing something very obvious. Any help is much appreciated.

Thanks

**Comment by dtusar** [comment]
Hi,
We will check if the documentation is misleading but I think you should call 

$ python -m bbob_pproc exdata/shotgun1 exdata/GP1-CMAES

**Comment by EoghanRussell** [comment]
Hi,
I did try that command exactly as you have it but the message I was getting was:

$ python -m bbob_pproc exdata/shotgun1 exdata/GP1-CMAES

Post-processing: will generate output data in folder ppdata
  this might take several minutes.

Post-processing (1): will generate output data in folder ppdata\exdata/shotgun1
  this might take several minutes.
Input file or folder .\exdata/shotgun1 could not be found.
Input file or folder .\exdata/shotgun1 could not be found.
For help use -h or --help

**Comment by dtusar** [comment]
Hi,
It seems OK. First each algorithm is processed separately and the output goes to ppdata/exdata/shotgun1 (or ppdata/exdata/GP1-CMAES). Afterwards also the comparison figures and tables are generated. These go in the ppdata folder. To avoid generating single algorithm output you can use the `--omit-single` option.

**Comment by nikohansen** [comment]
> the output is to one of the folders only

that doesn't look quite right to me?

**Comment by dtusar** [comment]
It starts with writing to the first algorithm folder then to the second algorithm folder and in the end to the `ppdata` folder. So it should be OK.

**Comment by brockho** [comment]
Seems to be solved. In case, it is not, please reopen the issue.
