### ISSUE TITLE
Standard colors get overwritten within many algorithm comparison

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1134]
During the postprocessing of many algorithms, the same ECDF plots seem to be written twice; once with nice colors (NavyBlue, Magenta, Orange, ...) as intended (and as it is the case when the `--omit-single` option is enabled) and then again with the same colors than for the scatter plots, indicating the dimension. This is definitely a bug and should be solved asap.

**Comment by dtusar** [comment]
Can you elaborate this a little more. So, is the same file (with the same name) written twice or are there two files with similar names and figures that are different only in the colors?

**Comment by brockho** [comment]
I will investigate this more carefully tomorrow. I mainly did not want to forget the issue.

**Comment by dtusar** [comment]
OK, if you need any help just let me know.

**Comment by brockho** [comment]
@dtusar: I checked today and the filenames are actually the same (all `pprldmany_*` files display the wrong colors without `--omit-single` while the `ppfigs*` files show the right colors). Actually, the files seem to be written only once in both cases, but in the case of no `--omit-single` the colors are simply not as expected:

![pprldmany_10d_noiselessall](https://cloud.githubusercontent.com/assets/13706996/17561794/0272fc24-5f28-11e6-95a9-d69d2286a28b.png)
![ppfigs_f012](https://cloud.githubusercontent.com/assets/13706996/17561797/02ab9fd4-5f28-11e6-95af-d5061b1fbaa3.png)


I did not have time today to investigate where the problem is, but it should not be too difficult to solve (and it was most likely introduced with the new ECDF plots for single algorithms and single functions, showing all dimensions in the same plot with exactly the colors appearing in the other many algorithms ECDFs now).

**Comment by dtusar** [comment]
Fixed with #1137
