### ISSUE TITLE
Spurious lines with % coco_version = 1.1.4 in .info files

### ISSUE THREAD

**Issue by LazyLysistrata** [numbbo/coco#1141]
For some reason the "% coco_version = 1.1.4" line now appears in 
coco .info files, for example:

funcId = 1, DIM = 2, Precision = 1.000e-08, algId = 'GS'
% coco_version = 1.1.4
%
data_f1/bbobexp_f1_DIM2_i1.dat, 1:20000|1.3e-03, 2:20000|2.0e-03, 3:20000|2.8e-04, 4:20000|3.6e-04, 5:20000|8.7e-04, 51:20000|6.7e-04, 52:20000|1.9e-03, 53:20000|3.1e-04, 54:20000|1.7e-03, 55:20000|5.4e-04, 56:20000|1.6e-03, 57:20000|1.4e-04, 58:20000|7.9e-04, 59:20000|1.6e-03, 60:20000|1.3e-03
funcId = 1, DIM = 3, Precision = 1.000e-08, algId = 'GS'
% coco_version = 1.1.4
%

The post-processor seems to choke on it. I issued the command:

leocomp@leocomp ~/leo_coco/coco-master/code-postprocessing $ python -m bbob_pproc -o first_comparisons GS_on_bbob

And got the following:

Post-processing: will generate output data in folder first_comparisons
  this might take several minutes.

Post-processing (1): will generate output data in folder first_comparisons/GS_on_bbob
  this might take several minutes.
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/leomint17/leo_coco/coco-master/code-postprocessing/bbob_pproc/__main__.py", line 341, in <module>
    rungeneric.main(args)
  File "bbob_pproc/rungeneric.py", line 271, in main
    + ["-o", outputdir, alg])
  File "bbob_pproc/rungeneric1.py", line 281, in main
    dsList = DataSetList(filelist, genericsettings.verbose)
  File "bbob_pproc/pproc.py", line 1487, in __init__
    self.processIndexFile(name, verbose)
  File "bbob_pproc/pproc.py", line 1558, in processIndexFile
    ds = DataSet(header, comment, data, indexFile, verbose)                    
  File "bbob_pproc/pproc.py", line 761, in __init__
    self.instancenumbers.append(ast.literal_eval(elem))
  File "/usr/lib/python2.7/ast.py", line 49, in literal_eval
    node_or_string = parse(node_or_string, mode='eval')
  File "/usr/lib/python2.7/ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 1
    %
    ^
SyntaxError: invalid syntax

Removing the % coco_version = 1.1.4 lines works, but did I miss something 
in the instructions that causes those lines to not appear in the output.

**Comment by nikohansen** [comment]
It might be that you need to update the post-processing to the latest version?

**Comment by LazyLysistrata** [comment]
I installed it per the directions in README.md, i.e.
python do.py install-postprocessing
I thought that was all I needed to do.

**Comment by nikohansen** [comment]
Right, this is the idea. It doesn't answer the question though whether you have installed the latest version. Calling `git pull` before `python do.py install-postprocessing` would make sure you have the current version.

**Comment by LazyLysistrata** [comment]
I downloaded the .zip file a few hours ago and used that originally.
I just checked again by getting the clone, and got exactly the same issue.

**Comment by nikohansen** [comment]
OK, thanks, we better wait for @dtusar to get a more insightful diagnosis then.

**Comment by ttusar** [comment]
This one is on me, sorry. A fix is on the way. 

However, I don't understand why our tests didn't catch it...

**Comment by ttusar** [comment]
The fix is now on the development branch. @LazyLysistrata can you try it?

**Comment by LazyLysistrata** [comment]
Just tested it and it seems fine now.

The coco_version = '1.1.4' is now in the correct place in the .info files as far as I can see, unlike it was in the previous buggy version.

For example it now looks like:
funcId = 1, DIM = 2, Precision = 1.000e-08, algId = 'RS', coco_version = '1.1.4'
%
data_f1/bbobexp_f1_DIM2_i1.dat, 1:4|2.7e+00, 2:4|1.9e+01, 3:4|1.2e+01, 4:4|1.1e+01, 5:4|6.7e+00, 51:4|3.7e-01, 52:4|5.0e+00, 53:4|2.0e+01, 54:4|1.2e+00, 55:4|2.7e+00, 56:4|1.7e+01, 57:4|8.7e+00, 58:4|2.6e+00, 59:4|6.9e+00, 60:4|2.9e+00
funcId = 1, DIM = 3, Precision = 1.000e-08, algId = 'RS', coco_version = '1.1.4'


I'm a complete novice with GitHub so please close the topic if that is necessary.

**Comment by ttusar** [comment]
No problem, I'm happy to close this issue. @brockho can you make a hot fix?

**Comment by brockho** [comment]
Yes, I will do a release asap today.
