### ISSUE TITLE
A postprocessing test should also use the latest data

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1144]
The issue #1141 has shown that postprocessing needs to be run also on the latest data (I mistakenly thought this was already the case). At least in the nightly build, if this takes too long to do every time.

**Comment by nikohansen** [comment]
For the next time I also suggest that we do not rely on integration testing to see whether a data format change breaks the data processing chain. I indeed doubt that this is what integration testing is meant to be for.

**Comment by ttusar** [comment]
It goes without saying (now).

**Comment by brockho** [comment]
Now that also the nightly build is passing again all tests,  the issue can be closed.
