### ISSUE TITLE
Uninstalling postprocessing in tests

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1147]
Today's error

> creating 'dist\bbob_pproc-1.1.3.145-py2.7.egg' and adding 'build\bdist.win32\egg' to it
> error: [Errno 28] No space left on device

showed again that we should take care of the disk space during the tests automatically if we don't want to delete everything from time to time by hand. Shall we try to uninstall the (all?) installed python postprocessing packages on the Jenkin slaves before testing within the nightly builds? @dtusar: or did the disk space problem come from something else?

**Comment by dtusar** [comment]
Lately the disk usage was more or less stable, but probably we have added some extra stuff. I will have to add external storage for the builds also to the windows slaves.

**Comment by dtusar** [comment]
The disk space problem should be solved now. I think we can close this issue.
