### ISSUE TITLE
Logger needs to provide information to postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1160]
In order to handle future test suites and loggers, we need that each logger writes some data to be read in by the postprocessing. Looking at what is needed at the moment, at least the following data need to be provided (and which are currently hard-coded in the postprocessing code):
- index of the column where to find the evaluations
- index of the column where to find the function values
- nb of target function values for each decade

In the long run, only the `bbob` and `bbob-biobj` data sets, written by an old version of the logger should become the exception for backwards compatibility.

**Comment by brockho** [comment]
Together with @nikohansen and @dtusar we discussed the issue today:

In particular, the logger should write its own name into the `.info` files as `logger=...` such that the postprocessing can reconstruct the combination of suite and logger from the data files. The above things like where to find the indices should probably be set within new logger-dependent classes in a new `loggersettings.py`.

Since we do not use multiple observers/loggers for the same suite at the moment, all this will only become critical once we implement #1367.

**Comment by brockho** [comment]
After another discussion today, a probably even better way of handling the things is that the logger writes `data_format=...` into the `.info` files, e.g. `data_format=bbob` or `data_format=bbob-constrained` instead of the `logger=...` above.

Like that, we have a clear indication of the data format within the data (and an easy way of specifying this in the documentation) and a logger can write different data formats if it wishes (like the current `bbob` logger writes different formats for constrained and unconstrained problems).

For debugging purposes, we should still keep the `logger=...` entries in the `.info` files to see who wrote the data.

**Comment by asmaatamna** [comment]
@brockho if I understand correctly, ```logger=...``` entry would have the same value than ```data_format=...```?

**Comment by brockho** [comment]
No. The `logger=...` entry should indicate the logger which wrote the data (e.g. `bbob`) and the `data_format=...` entry should indicate the type of data format (which e.g. for the `bbob` logger can then be either `bbob` or `bbob-constrained`).

**Comment by nikohansen** [comment]
See also https://github.com/numbbo/coco/issues/1381#issuecomment-329749931

**Comment by brockho** [comment]
Looks like solved to @dtusar and me.
