### ISSUE TITLE
Results Analysis

### ISSUE THREAD

**Issue by EoghanRussell** [numbbo/coco#1166]
Hi Guys,
I'm hoping you can help me out with my results as I am not sure if my understanding is correct for all of the graphs and there are aspects which I am not sure of. Some of the output html links don't include a description at the bottom.

![image](https://cloud.githubusercontent.com/assets/8921507/17805488/a75edb24-65f7-11e6-89f9-36dfa418fb7f.png)

In the above graph I am not sure the proportion of "function + target pairs ". I am also unsure of what the 6 marks are on each graph. Can you explain that for me please?

![image](https://cloud.githubusercontent.com/assets/8921507/17805558/f37bab36-65f7-11e6-8f96-0f72db1222ab.png)

In the "Scaling of aRT with dimension" shown above it doesn't indicate what the dark shapes are Vs the light ones. It mentions that the light ones refer to the longest run time but then for ten dimensions in the graph above it show a dark circle with a larger aRT above the lighter one so I am slightly confused on this one.

![image](https://cloud.githubusercontent.com/assets/8921507/17805636/41235172-65f8-11e6-8f13-7618fb9fce7b.png)

In the scatter plot above I am just unsure what each individual green triangle represents (for example). I understand that the triangles correspond to 3 dimensions but I am not sure why there are so many. Does each one correspond to a different trial?

Thanks for all of the help to date. It has been much appreciated. 

Regards

Eoghan

**Comment by nikohansen** [comment]
Many of your question are answered [here](http://numbbo.github.io/coco-doc/perf-assessment). 

Each pair of function+target defines a problem and we see in the first figure the proportion of solved problems. The marks are just markers to identify the different graphs. 

The longest single run can be shorter than the [average runtime](http://numbbo.github.io/coco-doc/perf-assessment/#averaging-runtime), as the latter takes into account unsuccessful runs. 

The symbols in the scatter plots show the average runtime to different target values.

**Comment by nikohansen** [comment]
Why don't we use the same colors and markers for the first two plots?

**Comment by EoghanRussell** [comment]
Hi Niko,
Thanks for the prompt reply. I have had a look at the link you provided but I am still unsure on one or two things.
For the first graph (similar to the link you provided) I don't see any reference to the upside down triangles. I'm not sure what you mean by different graphs when describing this. I'm just unsure of how to interpret each of these 5 triangles and the significance of their positions.
For the second graph your explanation makes sense, thank you. Can I safely assume that in the graph below, that our algorithm (in blue) is outperforming the 2009 best for >= 5 dimensions?
![image](https://cloud.githubusercontent.com/assets/8921507/17807066/4f2c1918-6600-11e6-9ea4-89fa2f821143.png)

For the third graph the algorithm we created is given on the X-Axis and so it outperformed by CMAES for most trials. If I am understanding you correctly am I correct in saying that our algorithm is outperforming CMAES in 3 dimensions for certain target functions (but I am unable to say what target functions?). If I am correct here, is there a way to find out which target functions. 
Also I should have asked. What do the right angle marks correspond to. I cannot find it in any documentation.

Once again, thanks for the quick response and your patience with my questions.

Eoghan

**Comment by nikohansen** [comment]
Just ignore the triangles. 

> Can I safely assume that in the graph below, that our algorithm (in blue) is outperforming the 2009 best for >= 5 dimensions?

No. Your algorithm doesn't reach the target at all in these dimensions. 

In the scatter plots, the target values are monotonous in the show runtimes and assume 46 values between `10^2` and `10^-8` as `self.ppscatter_target_values = targetValues(np.logspace(-8, 2, 46))`. Easier targets can hence be identified in the plot. More difficult targets are too dense. 

It would probably be better if we would plot fewer target values, e.g. 21 instead of 46.

**Comment by brockho** [comment]
> Why don't we use the same colors and markers for the first two plots?

That was issue #1134 and should be solved in release 1.2.
