### ISSUE TITLE
Figures and tables of 'aRT loss ratios' are not displayed when setting self.best_algorithm_filename = ''

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#1175]
When setting `self.best_algorithm_filename = '' ` in the small scale (and of course, large scale) testbed, we do not see any figure or table. I understand that the data `bestalgentries2009.pickle.gz` is always given in the small scale case. I am very interested in this situation because the post-processing of large scale testbed strongly depends on the small scale one, and we have no (real) best algorithm for large scale testbed until now. So I have a question: if we do not have the best algorithm, then is it possible we will not generate anything related to 'aRT loss ratios',  even the link named `Runtime loss ratios`? 

In fact, although the best algorithm is not provided, the captions of some figures and tables still show the information of the best algorithm. If we want to turn it off in that case, then we must change some the other files, such as the `latex_commands_for_html.html` and the latex templates . Please let me know if you have any suggestion?

**Comment by brockho** [comment]
We currently have a `feature-refalg` branch in which we try to solve those issues. Once we solve all the bugs (currently the doctests do not run through), we will merge this branch into the `development` branch and the functionality of turning off the `bestalg` algorithm in the background of the ECDF plots and in the tables should work.

**Comment by NDManh** [comment]
Ok, thank @brockho.

**Comment by dtusar** [comment]
In the `feature-refalg` branch are the `pplogloss.html` page and link now displayed correctly. If there is no best algorithm then the link is not shown and the page is not generated.
@brockho Is there anything else we should do here?

**Comment by nikohansen** [comment]
I know, I am somehow very late to the game, but it seems that a better name for (artificial) _best algorithm_ would be (artificial) _reference algorithm_. A reference algorithm could be the (artificial) best algorithm, but certainly doesn't need to be (as we already recognized). Having said that, there could be more than one reference algorithm. Having said that, doesn't become distinguishing between a reference and a non-reference algorithms useless unless for computing the loss ratio?

**Comment by loshchil** [comment]
portfolio 201x or best portfolio 201x or artificial portfolio ?

**Comment by nikohansen** [comment]
My remark was pointing towards the question whether it ultimately makes sense to have any specific _code_ dealing with a reference algorithm. What is the downside if it would just be another "algorithm" displayed in a specific line style?

**Comment by loshchil** [comment]
sorry, I was off-topic. I just had in mind "best2009" and thought that
"portfolio2009" might suit better because "best" sometimes confuses people.
I think it would be useful to be able to consider reference algorithms, I
don't see any downside.

**Comment by nikohansen** [comment]
In what way should a reference algorithm be different from any other algorithm displayed?

**Comment by loshchil** [comment]
a larger LineWidth + optionally, a unique / well visible color not used by
other algorithms, e.g., black

**Comment by nikohansen** [comment]
OK, these are attributes which should be settable for any displayed algorithm anyway, hence we would not need an code-exception (other than a mechanism to assign the attribute values respectively).

**Comment by dtusar** [comment]
OK, I agree that the name _reference algorithm_ is better than _best algorithm_, also I would leave its current color/style as it is. 

The reference algorithm is used for computing loss ratios and in the aRT tables. On other plots it usually behaves as any other algorithm. Having that said, I don't see any reason to have more than one reference algorithm.

**Comment by dtusar** [comment]
OK, I agree that the name _reference algorithm_ is better than _best algorithm_, also I would leave its current color/style as it is.
The reference algorithm is currently used for computing loss ratios and for the aRT tables. On other plots it behaves as any other algorithm. Having that said, I don't see any good reason for having more than one reference algorithm. Maybe we can add the possibility to change the default reference algorithm with a user defined one via a new command line option.

**Comment by brockho** [comment]
The latest commit to the `feature-refalg` branch has renamed the `best_algorithm` in the `testbedsettings.py` to `reference_algorithm` such that the issue can be closed for now.

**Comment by NDManh** [comment]
I might be wrong or you've implemented elsewhere but I think we should do the same thing for the other files, such as `ppfig.py` (line 248), `ppfigdim.py, ppfigs,...` etc. I've check but found that they are not updated in the current `feature-reflag` branch .
