### ISSUE TITLE
post-processing two algorithms, default output

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1177]
When processing two algorithms, by default the `Runtime distributions (ECDFs) per group and dimension` html-entry (link) is not generated. As this is our most referenced figure (in particular as it shows all data in one graph comparable over different publications), it should be generated by default. It should IMHO even always be the first entry in the list.

**Comment by dtusar** [comment]
If you click on the link `Runtime distributions (ECDFs) per group and dimension` for a single algorithm you get plots that show ECDFs for each function in a specific group. The text used for the link could be misleading. Adding another algorithms to these plots (you then have 4 or 5 graphs per algorithm in a single plot) would be IMO confusing.

Maybe you had in mind plots that would have 1 graph per algorithm showing the summary ECDF for all functions in a specific group? This type of plots could be added if needed.

**Comment by nikohansen** [comment]
> The text used for the link could be misleading. 

right, it should rather read `Runtime distribution of single functions` (which we already have for each function separately). In these figures, the combined graph for the entire group should be shown additionally.

Generally, name-wise, it seems more relevant to describe what the shown graphs are than to describe which graphs are put together in a single figure. 

> Adding another algorithms to these plots (you then have 4 or 5 graphs per algorithm in a single plot) would be IMO confusing.

agreed. 

> Maybe you had in mind plots that would have 1 graph per algorithm showing the summary ECDF for all functions in a specific group?

Yes. They seem to be missing when I process a single algorithm.

**Comment by brockho** [comment]
Update after yesterday's discussion and re-checking the postprocessing's output: The very first issue above is solved (`Runtime distributions (ECDFs) per group and dimension` link for 2 algorithms) but the last issue (`Runtime distributions (ECDFs) per group and dimension` for 1 algorithm) needs still to be solved.

For the moment, the plots behind this link for 1 algorithm to do aggregate over all functions within the groups but rather display the ECDFs of each function within the group separately. The (probably most informative) plots which aggregate over all functions of a suite are missing for 1 algorithm.
