### ISSUE TITLE
using html output

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1178]
A few suggestions to make the pages more user friendly. 
- the figure sizes should be smaller, about 1/3rd of what they are now, to have an easier overview. I find myself constantly sizing the page smaller and larger, while I cannot make it small enough to see as many figures as I would like to see. 
- clicking on the figure should always show the figure itself in its original size as the zoom-in feature, also in the ECDF plots. For showing the next dimension there should be a `next dimension` button, say on top and at the bottom of the page. 
- After release 2.0: the  `next dimension` button could also be present when a single figure is shown. This could be generalized to each parameter where different settings are available (next target or algorithm or function or function group).

**Comment by dtusar** [comment]
The first two items are solved, the third one was moved to #1224.

**Comment by nikohansen** [comment]
Which branch do I have to check out to test this?

**Comment by dtusar** [comment]
It's the `feature-refalg` branch where you use `cocopp`.

**Comment by nikohansen** [comment]
OK thanks, what do I have to do to play with the html settings?

**Comment by dtusar** [comment]
You can change the `height` property of the images in the `html` file in order to decrease their size even more.

**Comment by nikohansen** [comment]
the `html` file refers to which file? The output file? The source file? Which one?

**Comment by dtusar** [comment]
It's any particular output `html` file that you want to change. Once you figure out what is the best setting, I will change it in the code.

**Comment by nikohansen** [comment]
OK, I settled for `height=22%` as best setting for me, as it displays reliably four rows of figures. What remains is the problem that setting the percentage apparently prevents the possibility to resize the figures interactively in the browser without resizing the browser window. Any idea how to approach this?

**Comment by nikohansen** [comment]
FTR, in the root page for a single algorithm where we only see one figure, the figure should remain larger, 55% seems good.

**Comment by dtusar** [comment]
I made some changes, also the resizing works now. Please check if it's OK.

**Comment by nikohansen** [comment]
this looks much better, a few more points which spring in mind:

* all figures could be about 20% larger i.e. 135em -> 160em. 
* the default dimension to which the per function link points to should be 20 (possibly 10), but not 2D
* a previous dimension button would be helpful to go forth _and back_, combined with a display of the shown dimension like "previous dimension | **dimension = xx** | next dimension" would be helpful.
* the comparison sections in the `index.html` file should precede the single algorithms section, because the latter can be very long.
* it seems preferable to remove the section titles in `ppdata/pprldmany_xxD.html` (where each section only contains one figure). It is better to see all figures on the screen at once. Currently I am staring at a mostly blanc white page with a column of figures stacked up at the left border.  
* where we have less figures like for example
`ppdata/.../pprldmany-single-functions/pprldmany_gr_xxD.html` and `ppdata/pprldmany_xxD.html`, a larger default size is desirable (if this involves laborious changes we leave it for after the release).

**Comment by loshchil** [comment]
Sometimes I prefer to scroll instead of clicking next/prev, so I use a
simple html which lists all pprldmany_XXD_noiselessall.svg.

**Comment by nikohansen** [comment]
good point, all dimensions could be in the same html page and clicking previous/next dimension jumps within the page to the respective dimension tag.

**Comment by dtusar** [comment]
These items are solved:

> - all figures could be about 20% larger i.e. 135em -> 160em.
> - the comparison sections in the index.html file should precede the single algorithms section, because the latter can be very long.
> - it seems preferable to remove the section titles in ppdata/pprldmany_xxD.html (where each section only contains one figure). It is better to see all figures on the screen at once. Currently I am staring at a mostly blanc white page with a column of figures stacked up at the left border.
> - where we have less figures like for example
>     ppdata/.../pprldmany-single-functions/pprldmany_gr_xxD.html and ppdata/pprldmany_xxD.html, a larger default size is desirable (if this involves laborious changes we leave it for after the release).

The items with the dimensions are still open.

**Comment by dtusar** [comment]
Different dimensions are now on the same page. You can use the links for previous and next dimension to move up and down the page. If you click on an image get an enlarged image.

**Comment by nikohansen** [comment]
FTR, beside the abundance of warnings I now get repeatedly a number of `None`s as output, which was probably not intended. 

```
Post-processing (1): will generate output data in folder ppdata-all-2015/IPOPCMAv3p61
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
Scaling figures...
  done (Mon Dec  5 18:25:50 2016).
Generating LaTeX tables...
  done (Mon Dec  5 18:25:50 2016).
ECDF graphs...
  done (Mon Dec  5 18:26:12 2016).
ECDF graphs per function...
  done (Mon Dec  5 18:27:14 2016).
aRT loss ratio figures and tables...
  done (Mon Dec  5 18:27:26 2016).
None
None
None
None
None
None
None
None
None
Output data written to folder ppdata-all-2015/IPOPCMAv3p61
```

**Comment by brockho** [comment]
The latest report by @nikohansen is opened as #1252 such that this issue here can be closed.
