### ISSUE TITLE
number of targets in scatter plots

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1180]
By default, the number of target values is 46, which means we look at almost 300 (46 times 6) symbols. Shouldn't we try fewer symbols, like, say, 21?

**Comment by brockho** [comment]
In the multiobjective case, the number of symbols is even higher as we have 58 targets by default. So, yes, I would also vote for less targets displayed.

**Comment by nikohansen** [comment]
Set to 21 with commit https://github.com/numbbo/coco/commit/e6506a04cafb5fb004c86c773e49a3f854a2d9b7
