### ISSUE TITLE
Having potentially more than one reference algorithm?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1198]
At the moment, we use only one reference algorithm - for plotting in the displays, the definition of runlength-based targets, and also in relative plots such as the log-ratio plots.

Since there is no obvious reason against having several reference algorithms for each of those purposes, we should at least document what we do for now.

**Comment by nikohansen** [comment]
FTR, the obvious reason against would be added code complexity (without addressing an actual demand).

**Comment by brockho** [comment]
Can be closed as with the new feature of plotting algorithms in the background, the above can be already done.
