### ISSUE TITLE
dependency on C rand (constraints branch)

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1205]
Currently the constraints branch depends on `rand` to generate the instances of the (linear) constraints. Can we guaranty that `rand` produces always the same sequence for a given seed, on all systems and in future?

We probably should use `coco_rand...` which addresses this (potential) problem.

**Comment by brockho** [comment]
I guess that this is implemented now with the latest pull request 58f45eb by @asmaatamna, right?

**Comment by asmaatamna** [comment]
Yes.

Asma
----- Dimo Brockhoff <notifications@github.com> a écrit :
