### ISSUE TITLE
Result table in templateBIOBJarticle.tex needs revision

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1208]
The reason is that with the availability of a reference algorithm, the table will be too long for a letter page in its current form due to the 2x55 rows. I played already a bit with negative `\vspace`s but this can only be a short-term hack to be able to see anything. Until the next GECCO workshop, we should definitely split the table or organize its page differently.

**Comment by brockho** [comment]
The caption is now temporarily rotated and displayed besides the actual table in order to have all data visible for the moment. However, @dtusar is already working on splitting the table into smaller, per-function tables that can be moved around more easily in the LaTeX templates afterwards (similar to the many algorithms tables).

**Comment by dtusar** [comment]
Now we have one LaTeX table for each function/dimension pair. The `templateBBOBarticle.tex` and `templateBIOBJarticle.tex` templates are updated and use the new tables. @brockho Can you please check the templates and polish them?

**Comment by brockho** [comment]
Thanks @dtusar - the tables fit to the letter page in ACM style now. 

However, in order to make everything look nicer (again), we should probably take out the header into a single file, such that the line with the targets does not have to be repeated again and again:

```
\begin{table*}\tiny
\centering
\mbox{\begin{minipage}[t]{0.32\textwidth}\tiny
\centering
\input{\bbobdatapath\algfolder pptable_header_05D}
\input{\bbobdatapath\algfolder pptable_f001_05D}
[...]
\input{\bbobdatapath\algfolder pptable_f012_05D}
\end{tabular}
\end{minipage}
\hspace{0.002\textwidth}
\begin{minipage}[t]{0.32\textwidth}\tiny
\input{\bbobdatapath\algfolder pptable_header_05D}
\input{\bbobdatapath\algfolder pptable_f013_05D}
[...]
\input{\bbobdatapath\algfolder pptable_f024_05D}
\end{tabular}
\end{minipage}
```

with solely the header such as 
```
\begin{tabular}{@{}c@{}|*{6}{@{}r@{}@{}l@{}}|@{}r@{}@{}l@{}}
$\Delta f$ & \multicolumn{2}{c}{1e+0} & \multicolumn{2}{c}{1e-1} & \multicolumn{2}{c}{1e-2} & \multicolumn{2}{c}{1e-3} & \multicolumn{2}{c}{1e-4} & \multicolumn{2}{c}{1e-5} & \multicolumn{2}{|@{}r@{}}{\#succ}\\\hline
```
in file `pptable_header_05D.tex` and the `pptable_f024_05D.tex` files only containing the single line (in case of no refalg) respectively the two lines (in case of an available refalg) with the results.

**Comment by dtusar** [comment]
The headers of the tables are now stored in the `pptable_header_xxD.tex` files.

**Comment by dtusar** [comment]
This is fixed now.
