### ISSUE TITLE
Function Value Distributions wrong for >1 function

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1218]
It seems as if the function value distribution functions (anyway quite outdated; can be found in `pprldistr.py`) are wrong in the case where we aggregate over functions. Here is for example a plot when comparing RS-4 and RS-5 on the `bbob-biobj` test suite:

![fvdistr](https://cloud.githubusercontent.com/assets/13706996/20145491/9bbe455e-a6a0-11e6-84f7-c1ffdd05e611.png)

We can see  that the order of the colors as well as the number of solved instances/functions must be wrong (displaying ratios larger than 1 for the latter).

**Comment by nikohansen** [comment]
It might have been left behind when the processing of the bi-objective testbed was introduced. I don't quite see what you mean by order of colors, and why do we see the labels `-1`...`-5`?

**Comment by brockho** [comment]
After discussing with @nikohansen and @dtusar offline today, we agreed that this issue was just about a misunderstanding of what is actually displayed. This issue can therefore be closed.
