### ISSUE TITLE
Overlaped values in latex tables

### ISSUE THREAD

**Issue by AmerDraa** [numbbo/coco#1223]
Hello every one,

When generating the latex tables of ERT to be used in the templateBBOBmany.tex template of the BBOB, some of the comparison tables contain overlapped numbers, see the attached file please. I tried a lot to fix the problem but I could not.

Could anyone help in this iss
[tables.pdf](https://github.com/numbbo/coco/files/595382/tables.pdf)
ue please?

Thank you in advance.

**Comment by nikohansen** [comment]
Thanks for reporting, it looks like a bug ;-)  @dtusar, any idea where this problem comes from?

**Comment by dtusar** [comment]
I cannot reproduce this. @AmerDraa can you please upload a zip containing all the pptables_fXXX_05D.tex and pptables_fXXX_20D.tex files, where the XXX stands for the function numbers from 001 to 024. So altogether should be 48 files in the zip. 

Thank you.

**Comment by AmerDraa** [comment]
Hello every one, 

@nikohansen thanks for the prompt answer,
@dtusar thank you for the interest, here are attached for all function and dimensions compressed.

[ppdata_DE.zip](https://github.com/numbbo/coco/files/601371/ppdata_DE.zip)

Thank you in advance.

**Comment by AmerDraa** [comment]
Hello Everyone,
I almost could find out the source of the issue, or even get a solution,
I replaced the **'tabularx'** environment by the **'tabulary'** environment, and added to the main file (just after \begin{document}) the instruction: \newcolumntype{X}{c}.

See the file: 
[Almost.pdf](https://github.com/numbbo/coco/files/606651/Almost.pdf)


It remains how to fit these tables, in the main file, into the column width, because now some tables are overlapping other tables.

Would anyone tell me how to modify the **post-processing** Python codes to make it generic? in order to avoid making the whole series of changes on every file each time the rungeneric.py is called.

Thank you

**Comment by dtusar** [comment]
Hello @AmerDraa,
I have similar problems with the overlapping tables. In order to achieve the result similar to your `Almost.pf` file you can go in `post-processing/bbob_pproc/compall/pptables.py` and replace all the X@ with l@.

I will let you know as soon as I manage to solve the overlapping of the tables.

**Comment by AmerDraa** [comment]
Hello @dtusar 

Thank you so much,

I am waiting for your update if any solution emerges.

Thanks

**Comment by brockho** [comment]
One relative simple way to not have overlapping tables is to reduce the amount of data displayed, i.e. the number of columns in the tables. This should be very simple, by changing `self.pptablemany_targetsOfInterest` in the right testbedsetting class in `testbedsettings.py` (I guess you use the single-objective test suite, hence in `GECCOBBOBTestbed`).
[Don't forget to reinstall the postprocessing after this change: `python do.py install-postprocessing`]

I remember having seen these overlapping tables sometimes (but not by so much), in which case, I always reduced the amount of targets displayed.

**Comment by AmerDraa** [comment]
Hello again,
@dtusar: I am afraid that both solutions you proposed do not fit my needs:

1.  Replacing X@ by l@ in the post-processing/bbob_pproc/compall/pptables.py file, as it was in my previous proposition of using tabulary, would result in tables having different sizes which makes is quite difficult to group in only one table, they are even overlapping in some cases, see the file:

[myTables.pdf](https://github.com/numbbo/coco/files/607734/myTables.pdf)


2.  Changing the self.pptablemany_targetsOfInterest file would lead to lesser details than we want to put and use as comparison scale in our comparison between different algorithms.

I would be really grateful if such an issue would be treated.

Thanks in advance.

**Comment by dtusar** [comment]
Hello @AmerDraa,

Yes, you're right, the tables are all messed up. Please revert those changes and apply only the changes I made in the commit 4cc0e769129e3a001460e064a3502e03d60e32b5. It seems to work for me.

**Comment by AmerDraa** [comment]
Hello everyone,

@dtusar: The fix you proposed worked for the issue of overlapping tables, but there is still some issues (see the attached file please): 
- the tables of some functions contain a lot of space (f15, f16 and f23 for instance), 
- other tables are aligned to the left (f24). 




![right_aligned](https://cloud.githubusercontent.com/assets/20744596/20581300/5305fa30-b1d8-11e6-9ef7-bf5bcf06e2cf.jpg)


A quick analysis shows that the tables causing such problems are those containing a lot of infinity symbols.

waiting for your comments on how to make these tables look better.

Thank you again,

**Comment by brockho** [comment]
Can be closed since we moved the table header out to the top only.
