### ISSUE TITLE
dimensions for large-scale test suite

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1230]
The dimensions will be about ten times larger than for the `bbob` testbed, that is, instead of `[2,3,5,10,20,40]` it will be `[20, 40, 80, 160, 320, 640]`, where `640` is optional.

**Comment by brockho** [comment]
The dimensions for the large-scale test suite are fixed as above in the `devel-LS` branch for a while now. I'll therefore close the issue now.
