### ISSUE TITLE
memory leak in large scale suite?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1231]
In IPython:
```
In [1]: import time

In [2]: import cocoex

In [4]: cocoex.known_suite_names.append(b"bbob-largescale")

In [5]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,'); print(time.clock()-t0)
0.089222

In [6]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40'); print(time.clock()-t0)
0.251393

In [7]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40,80'); print(time.clock()-t0)
0.54006

In [8]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40,80,160'); print(time.clock()-t0)
1.084181

In [9]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40,80,160,320'); print(time.clock()-t0)
2.082882

In [10]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40,80,160,320,640'); print(time.clock()-t0)
4.044544

In [11]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40,80,160,320,640,1280'); print(time.clock()-t0)
7.917052

In [12]: t0=time.clock(); suite = cocoex.Suite('bbob-largescale', '', 'dimensions:20,40,80,160,320,640,1280,2560'); print(time.clock()-t0)
18.78798

```
leads reproducibly to excessive memory usage of Python. 

<img width="459" alt="screen shot 2016-11-29 at 13 39 43" src="https://cloud.githubusercontent.com/assets/7316439/20710646/acd2bbcc-b63b-11e6-9921-863f9b13d4d8.png">

**Comment by brockho** [comment]
I have a similar impression from running the C code under Windows: In the default dimension setting, the memory usage at the beginning of the 640-D runs is 118MB at `f1` and increases to 170 MB at `f16`, and up to 238MB at the end of the experiment. When only running dimension 640, I go from round 800KB in `f1` to 124MB in the end.

A closer look reveals that the increase is only happening for the non-separable functions, i.e., the cause must be in the new rotation matrix handling.

The `bbob-biobj` experiments, in comparison, which uses the old 24 `bbob` functions, stays at around 1MB of memory usage for all dimensions, increasing slightly during the smaller dimensions and fluctuating (i.e also decreasing sometimes) more in 40-D.

**Comment by brockho** [comment]
This issue seems to be solved now. The memory usage still goes up from less than 1MB for 2-D to slightly above 10MB at the end of the 640-D runs, but which is far less than before and we have to keep in mind that storing 640x640 matrices also takes up space. Now less than 6MB are used at the beginning of the 640-D runs compared to 118MB before.
