### ISSUE TITLE
instance notification in figures

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1232]
When I run the post-processing on the 2015 workshop data, I get this in 20-D:
<img width="1098" alt="screen shot 2016-11-29 at 14 16 25" src="https://cloud.githubusercontent.com/assets/7316439/20711199/b9d1df44-b63e-11e6-8529-557a6e160109.png">
How should we go about this to get a representable page?

**Comment by brockho** [comment]
Okay, I will change this such that only the set of different instance numbers is shown (i.e. no doubles anymore).

**Comment by brockho** [comment]
This issue can be closed now as the previous commit to the `development` branch solves the above problem by only displaying the different numbers of instances at any time (plus a warning per plot if it happens that more than one number is present).
