### ISSUE TITLE
Adjust the templateBIOBJmultiple.tex file

### ISSUE THREAD

**Issue by strickler** [numbbo/coco#1238]
Dear all,

I was trying to compile the templateBIOBJmultiple.tex file, included in coco-postprocessing/latex-templates folder. The pdflatex compiled everything without bugs. But, I realized that in the tables (Average runtime (aRT) to reach given targets...) in templateBIOBJmultiple.pdf were broke when I try to compare a large number of algorithms.
In my case, I am trying to compare 9 algorithms but what differentiate them is a pair of names. For example: NSGAII-SBX NSGAII-UMDA IBEA-SBX IBEA-UMDA and so on. 
With this kind of names, the tables are very confusing to be analyzed, as we can see in the figure that I uploaded here:
![exampletables](https://cloud.githubusercontent.com/assets/9552523/20801540/6c57d1b8-b7d0-11e6-9a6d-e69f33dfa93d.png)

Another problem that I noted is that, the tables are generated in order to fill only one single page, independently of the number of algorithms to be compared, and (what I got) there is missing some functions that should appear in the final of the tables because this large number of algorithms.

My question is: There is some way to work around this kind of problems that I faced?

Is there another issue that complain the same problems?

Thanks in advance.

**Comment by nikohansen** [comment]
Workaround one: assign different names. It seems anyway not a bad idea in general to have names which differentiate already within in the first four characters. I believe this can be done via latex commands or by renaming data folder. 

Workaround two: edit the resulting latex file by splitting one table in as many tables as needed. This shouldn't be too tedious to do manually.

**Comment by brockho** [comment]
I agree with @nikohansen.

The first issue can be done, as said, by renaming the data folders or by using the 

```
\newcommand{\algAtables}{ALTERNATIVE-NAME}
```
commands that you can find in the beginning of the LaTeX templates (e.g. lines 73ff. in the multiple-algorithm one).

Splitting the table to your wishes is easy as the provided LaTeX code is independent for each function and 
the `\input{\bbobdatapath pptables_f0XX_20D}` command for each function can be easily moved to another figure/page by hand if you wish.

**Comment by brockho** [comment]
A warning in the LaTeX output is now displayed whenever the table is too long, indicating that the user is supposed to split the table by hand as described above. The issue can therefore be closed. Thanks to @strickler for reporting the issue.
