### ISSUE TITLE
Largescale test suite has no instances_by_year

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1242]
The current `devel-LS` branch does not specify any instances by year so far, such that the obvious exchange of `bbob-biobj` with `bbob-largescale` gives the following error:

```
COCO FATAL ERROR: coco_suite_get_instances_by_year(): suite 'bbob-largescale' has no years defined
```

This should be definitely changed.

**Comment by oaelhara** [comment]
The fix was committed to the test-branch, as is the case for many other issues. 
I will let you know when the issues can be closed (tests passed and code merged to the large-scale branch)
