### ISSUE TITLE
Windows machine is down on CI?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1250]
The titles says it all.

**Comment by dtusar** [comment]
The ones we use are up and running.

**Comment by nikohansen** [comment]
They are all red, I don't see any working at the moment, maybe the disk is full?

**Comment by dtusar** [comment]
Then I would say that the title is not saying it right. The machines are working, just the tests fail. :)

I'm trying to figure out how to configure the system to be able to send correct notifications to both GitHub projects and show the correct status in Jenkins. That's why the tests failed.

**Comment by nikohansen** [comment]
> title is not saying it right

the title was (just) asking a question...

**Comment by nikohansen** [comment]
Any time frame when the tests will work again? Unfortunately I have a test which I expect to be different under Windows...

**Comment by dtusar** [comment]
I reverted the settings and restarted your `Coco-test2-win` test. Now it will show the correct values.

**Comment by nikohansen** [comment]
Thanks, sorry, I didn't mean to rush your investigations.
