### ISSUE TITLE
Reference algorithm should contain test suite name

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1254]
The reference algorithm data set should contain the information about the underlying test suite in a human-readable format, best in the `.info` files as `suite = SUITENAME`, see for example https://github.com/numbbo/coco/blob/development-constraints/code-experiments/src/logger_bbob.c#L282

**Comment by dtusar** [comment]
The reference algorithm already contains the suite name if it's generated from algorithms that also have the suite name defined. I added that the corresponding "default" suite name is written if the contributing algorithms don't have this information.

**Comment by nikohansen** [comment]
I am not sure assigning a default is a good strategy, because it seems that there is some chance that the assigned value can be simply wrong, in which case it seems better to assign no value than a wrong value.

**Comment by dtusar** [comment]
You have a point here. If also @brockho agrees I can revert the last change.

**Comment by brockho** [comment]
Sorry @dtusar for not replying earlier, but @nikohansen has a good point. The postprocessing will probably anyway assign the right "default" suite when reading in the reference algorithm, even if it does not have the right suite displayed. However, having a human-readable `bbob` or `bbob-biobj` displayed in the soon available reference algorithms will also not be too bad to better distinguish them in addition to their names. So maybe, we can add an optional string parameter to the `custom_generate` in `bestalg.py` that allows to add the suite name to the written files? I will then use this when I create the reference algorithms for the 2.0 release according to the open issue #41.

**Comment by dtusar** [comment]
If I understand this correctly you would like to have an optional parameter for `custom_generate` to set the suite for the best algorithm. Does this parameter overwrites the suite retrieved from the algorithms or only sets the suite if the algorithms don't have one?

**Comment by brockho** [comment]
The former is probably easier to implement while the latter makes more sense, I would say.

**Comment by dtusar** [comment]
I agree, so the latter it is.

**Comment by dtusar** [comment]
The change is available on the `feature-refalg` branch.
