### ISSUE TITLE
devel-LS not merged with feature-refalg

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1255]
It seems as if the `devel-LS` branch is not up-to-date with the `feature-refalg` branch. This will cause soon more troubles when the feature-refalg becomes part of the 2.0 release. In particular, the postprocessing name change from `bbob_pproc` to `cocopp` seems problematic.

**Comment by oaelhara** [comment]
The conflicts have been solved and I'm pulling from both `development` and the `feature-refalg` branches.
It's already the case for the code on my fork and the one being tested, thus this issues can be closed.
