### ISSUE TITLE
NotImplementedError for suites with no reference data

### ISSUE THREAD

**Issue by oaelhara** [numbbo/coco#1261]
When creating a new testbed/testsuite with no data yet for a reference algorithm (say the large-scale suite), creating a class with no reference algorithm:
`class LargeScaleTestbed(GECCOBBOBTestbed):
...
    self.reference_algorithm_filename = ''
    self.reference_algorithm_displayname = ''
`
results in the error message:
`NotImplementedError: no reference algorithm indicated in testbedsettings.py`
which comes from the generating the logloss plots and the tables.
Shouldn't the post-processing automatically skip these (while showing a warning maybe) and proceed with the rest? 
For the table, one can show, instead, the absolute values instead of values relative to the reference algorithm. 

There seems to be a test for the logloss plots in rungeneric:
`if genericsettings.isLogLoss:`
but it needs to be set manually by passing, for example, the --fig-only option.

One current solution is to add, in rungeneric, another test: 
`if genericsettings.isLogLoss and testbedsettings.current_testbed.reference_algorithm_filename:`

or set genericsettings.isLogLoss to False whenever no reference algorithm is provided.

**Comment by dtusar** [comment]
Fixed on the `feature-refalg` branch.
