### ISSUE TITLE
 Lunacek bi-Rastrigin Function: wrong documentation?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1266]
In the documentation of the `bbob` functions (http://coco.lri.fr/downloads/download15.03/bbobdocfunctions.pdf), the definition of the  Lunacek bi-Rastrigin Function (`f24`) says that the optimum is located in `$\mu_0 {\bf 1}\pm$` with `$\mu_0=2.5`. In the plots, however, and in COCO's implementation, the `best-parameter` value is either  `+1.25` or `-1.25`.

Is there a mistake in the documentation or am I missing something?

**Comment by oaelhara** [comment]
In the documentation, `${\bf x}$` is multiplied by 2 in order to obtain `$\hat{ {\bf x} }$` from which the `$\mu_0 {\bf 1}$` is subtracted. 
So the optimum in `${\bf x}$` is `+1.25` or`-1.25`...

**Comment by brockho** [comment]
We agreed on Jan 12, 2017 that the pdf should be updated in the sense that for f24, the optimum should be changed to `\frac{\mu_0}{2} {\bf 1\pm}`.

**Comment by nikohansen** [comment]
see also #837

**Comment by nikohansen** [comment]
Fixed in the document source. The available pdfs will be updated timely.

**Comment by nikohansen** [comment]
The fixed document were uploaded to [HAL](https://hal.inria.fr/inria-00362633) and to `http://coco.gforge.inria.fr/downloads/download16.00` and are used at the [COCO gforge home](http://coco.gforge.inria.fr) and in the links at the [latest old release](http://coco.gforge.inria.fr/doku.php?id=downloads).
