### ISSUE TITLE
Navigating the HTML tables

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1268]
Now that we provide the html tables for all available dimensions, it starts to be difficult to navigate through all the data. It will be therefore nice to have, similar to the ECDF plots pages, a navigation with buttons for the next and the previous dimension (at least) and probably even some quick way to access the data for single functions.

Given all the other important things, we are currently dealing with, I suggest to keep this at the lowest priority though for now.

**Comment by dtusar** [comment]
This is now implemented.
