### ISSUE TITLE
Inconsistent Tables with --expensive

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1280]
In the expensive setting, i.e., when postprocessing data with the `--expensive` switch, the tables are not displaying the right expensive targets but the absolute ones. The table caption, however, is the expensive one, stating for example that the success probability is for the target of the last column, which is, I guess, not what the tables with the fixed targets show.

Hence, we need to make sure that the right tables are shown (the ones with the reference budgets `0.5, 1.2, 3, 10, 50` in the first row).

**Comment by dtusar** [comment]
This was fixed.
