### ISSUE TITLE
Documentation of `bbob-largescale` functions

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1299]
Is the documentation of the `bbob-largescale` functions up-to-date? Can it go online?

**Comment by brockho** [comment]
We should not forget to link the documentation from both the LaTeX templates and the Github `README.md`.

**Comment by kostasvar** [comment]
Another spotted error is the normalisation factor `\gamma(n)` for `f19` that is not applied.

**Comment by brockho** [comment]
The pull request is accepted - I will take care of pushing the newest html version.

**Comment by brockho** [comment]
The newest version is online now.
