### ISSUE TITLE
Middle of domain evaluated by default

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1304]
In the python `example_experiment.py`, by default, the domain middle is sampled and evaluated before an algorithm is started which is, to the best of my knowledge, not the case in the other wrappers. Is this desired? I guess not.

**Comment by brockho** [comment]
Conclusion of our discussion from Feb 2, 2017: since the provided initial solution of COCO is also the domain middle and the current `example_experiment.py` in Python uses it but probably not all wrappers do, the domain middle might be added in the long run as 0th search point for all algorithms. However, it is not clear yet how exactly implement (and document) it.

A related question: should we expose the evaluation of the domain middle instead of the nadir (see #1120)?

**Comment by loshchil** [comment]
should not it be just that all target objective values or hypervolume
values are selected to be more difficult than the ones obtained from
evaluating the middle point?

**Comment by nikohansen** [comment]
By now, in the constrained case, the logger may write the problems provided `initial_solution` in the first evaluation. 

I believe, as a first step, we should _output_ the Delta-f-value of the initial solution, possibly as a comment before the first data lines in the data files, see #1387.
