### ISSUE TITLE
Preprocessing - find a better way to handle the bbob-biobj-ext suite

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1326]
Comit 8456f53 fixed preprocessing so that it workes for the bbob-biobj-ext suite as well. However, it's a rather "dirty" fix and should be improved at some point...

**Comment by brockho** [comment]
see also #1348

**Comment by ttusar** [comment]
@brockho If this is the same as issue #1348, we can close it, right?

**Comment by brockho** [comment]
Right.
