### ISSUE TITLE
why do coco_suite_get_next_problem(suite) and coco_suite_get_problem(suite, index) return problems with nearly same data but different name?

### ISSUE THREAD

**Issue by berndbischl** [numbbo/coco#1333]
1) I know this will give *you* not the best reproducibility, but for reference here is the R code i used to show the problem

```
s = cocoOpenSuite()
p1 = cocoSuiteGetProblem(s, 0)
print(p1)
p2 = cocoSuiteGetNextProblem(s)
print(p2)
```

returns 
```
CocoProblem
id          : bbob_f001_i01_d02
index       : 0
name        : BBOB suite problem f1 instance 1 in 2D
nobj        : 1
dim         : 2
constraints : 0
lower       : -5,-5
upper       : 5,5
init sol    : 0,0


CocoProblem
id          : bbob_f001_i01_d02
index       : 0
name        : bbob(BBOB suite problem f1 instance 1 in 2D)
nobj        : 1
dim         : 2
constraints : 0
lower       : -5,-5
upper       : 5,5
init sol    : 0,0
```
Note the difference ONLY in name.

2) 

The R functions directly call into your C API, and I don't change any data / slots of the objects at all.
For reference, current C code is here:
https://github.com/berndbischl/rcoco/blob/master/src/rcoco.c

(got to c_cocoSuiteGetProblem, c_cocoCreateProblem et al)

3)  
Is this intended behavior? 
This came up in my unit tests, and failed them because I compared the objects returned from get_next_problem to get_problem.

**Comment by brockho** [comment]
Dear @berndbischl. Thanks for letting us know and sorry for not replying earlier. The issue reported seems to me like a bug. We will have a look asap to make the output consistent.

**Comment by berndbischl** [comment]
@brockho dimo, thanks. was on holiday anyhow.

**Comment by brockho** [comment]
Hi @berndbischl,

We finally looked into the issue (actually @ttusar did): the behavior you see might be even intended :-) 

The first problem, that you get via `cocoSuiteGetProblem(s, 0)` looks like a simple problem, that is not observed in any way (in other words no data is written if you evaluate it). The second one, looks like being wrapped by the `bbob` obvserver, i.e. if you evaluate this problem, some data will be written to disk.

Whether this is *actually* intended and correctly documented, is another thing. To answer this, can you please tell us whether somewhere in your code, you add an observer?

**Comment by jakobbossek** [comment]
Thanks @brockho! Yes, indeed at the time of opening this issue our function `cocoSuiteGetNextProblem` internally generated an observer.

**Comment by brockho** [comment]
Thanks @jakobbossek, for the clarification. As your implementation of `cocoSuiteGetNextProblem` seems to follow the implementation of the C code (http://numbbo.github.io/coco-doc/C/coco__suite_8c.html#a422cee3f06f4b2524234102f75306fe7), I consider this issue solved.
