### ISSUE TITLE
Postprocessing error: AttributeError: 'module' object has no attribute 'shortoptlist'

### ISSUE THREAD

**Issue by AmerDraa** [numbbo/coco#1337]
Hello everyone, 

I am getting this error when posprocessing my data with python, could anyone help please ?

Thanks in advance.

-----------------------------------
c:\all2>python C:\all2\rungeneric.py cPSO ne_cGA ne_cSinDE pe_cGA pe_cSinDE
Traceback (most recent call last):
  File "C:\all2\rungeneric.py", line 44, in <module>
    for i in (rungeneric1.shortoptlist, rungeneric2.shortoptlist,
AttributeError: 'module' object has no attribute 'shortoptlist'
-----------------------------------

**Comment by dtusar** [comment]
Hello @AmerDraa,
Thank you for reporting the problem. I'm looking at the code but I cannot find this line:

`for i in (rungeneric1.shortoptlist, rungeneric2.shortoptlist,`

Can you please check if you have the latest version of the code?

**Comment by AmerDraa** [comment]
Hello @dtusar;

Exactly, it was a problem with the version; once I installed the last version of the package, it worked perfectly.

Thanks alot.
