### ISSUE TITLE
RuntimeWarning: invalid value encountered in log10

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1345]
@mariosky reported in #1335 the following, which we rather move to a new issue than keeping it there to not lose it:

> When I run the scripts with matplotlib version 2.0.0 a Warning is printed:
>
> ECDF graphs per function...
> /Users/mario/.local/lib/python2.7/site-packages/cocopp-2.0.1-py2.7.egg/cocopp/ppfig.py:487: RuntimeWarning: invalid value encountered in log10
> min([min(xdata), ax_limits[0], ax_limits[1]]) + 0.5) # np.log10(xdata[-1]) - np.log10(xdata[0])
> This occurs in Win, Mac, Ubuntu

**Comment by nikohansen** [comment]
Addressed in commit a47346c44227a6d1bb97aa0900dab0cbf8067914
