### ISSUE TITLE
Pre-processing has suite fixed to 'bbob-biobj-ext'

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1348]
The pre-processing has now the suite fixed to `bbob-biobj-ext`. It is relatively easy to change this back to `bbob-biobj` within the code and recompile, however, working with both `bbob-biobj` and `bbob-biobj-ext` in the future will be cumbersome. It will be nicer to not have to do things by hand but instead detect the suite from the data that is read in.

**Comment by ttusar** [comment]
Fixed by ec3cbd52a60f579fc3b750fd8168e694e8b381cc (to be merged into the `development` branch).
