### ISSUE TITLE
Postprocessing bbob-biobj and bbob-biobj-ext data

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1349]
When postprocessing data from the `bbob-biobj` and the `bbob-biobj-ext` suite (not yet fully supported and thus a medium priority issue), the current postprocessing behaves wrongly, to be more precise, the order of the algorithms matters! It seems that this will also be the case for other (intentionally compatible) test suites (e.g. `bbob` and `bbob-largescale`).

When a `bbob-biobj` algorithm (with reference algorithm) is first and a `bbob-biobj-ext` algorithm (without a reference algorithm) is second, the tables produced show relative values to the reference algorithm but the caption does not show a hv-hash (because the second algorithm does not have a reference algorithm with a hash). When a `bbob-biobj-ext` algorithm (without reference algorithm) is first and a `bbob-biobj` algorithm (with a reference algorithm) is second, the tables produced show absolute values and no reference algorithm but the caption shows now a hv-hash.

**Comment by brockho** [comment]
After today's discussion, we came to the following conclusions:
- The choice of the testbed class shall be chosen automatically (after reading in all data).
- The data shall be read in according to this testbed class, e.g. crop dimensions and function that are not compatible with this testbed
- We need new testbed classes that "join" compatible ones, for example one for the combined `bbob` and `bbob-largescale` suite.

**Comment by nikohansen** [comment]
The simplest first step for the biobjective case:
- make sure we can use an extended data set to instantiate the non-extended class cleanly
- use the non-extended class for all algorithms if any of the data sets is non-extended
