### ISSUE TITLE
Managing imports in postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1353]
We have many different imports that might not always be consistently called and thus might cause problems. One issue, related to that is #693.

What if we keep all necessary (cocopp-internal) imports in a single file, e.g. `toolsdivers.py` or even a new `cocoimports.py` and import this module from everywhere? Like that, we will not have duplicate code related to imports and everything will be consistent.

**Comment by nikohansen** [comment]
There should be a better solution than creating `cocoimports.py` and using ``from cocoimports import *``.

**Comment by brockho** [comment]
Can we finally close this issue?

**Comment by nikohansen** [comment]
I think that `cocopp.<TAB>` is a little crowded, but that's only loosely related, so I am fine with closing this one.

**Comment by brockho** [comment]
I just opened issue #1578 to discuss the `cocopp.<TAB>` issue further and therefore close this issue here.
