### ISSUE TITLE
Not appending to the Python path when calling a module as main

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1356]
Lines like ``sys.path.append(os.path.join(filepath, os.path.pardir))`` at
[L355](https://github.com/numbbo/coco/blob/master/code-postprocessing/cocopp/__main__.py#L355) look very much like a bug-prone hack and should go away. The same in `rungeneric2.py` etc. The problem might be how `do.py` is calling the test of the post-processing.

**Comment by nikohansen** [comment]
FTR, I am in favour that 

    python -m cocopp args...

is the only supported usage _from the system shell_. 

That is, all the 
 
    if __name__ == "__main__"

logic in `rungeneric*` can go away.

**Comment by dtusar** [comment]
Currently we have `if __name__ == "__main__"` in almost 20 files. This should probably remain only in `__main__.py` and `test.py`, right @nikohansen?

**Comment by nikohansen** [comment]
Yes, that seems to be right. Second thought/reasoning: generally it would make sense if we wanted to support/maintain the use-cases 
```
python -m cocopp.filename_with_main args...
```
My current idea remains to "gently force" the user to go with 
```
python -c "import cocopp; cocopp.filename_with_main.main(args...)"
```
instead. The latter allows a super-smooth transition to start working in the `(i)python` shell, as the exact same command works in any Python shell.

**Comment by dtusar** [comment]
I removed it from most of the files. There are still a few files for which I don't know if they are still used:
`changeAlgIdAndComment.py`, `dataoutput.py`, `determineFtarget.py` and `determineFtarget2.py`. In the last two files we already have a comment "this file/module is seemingly unused" from year 2012.

**Comment by brockho** [comment]
In `changeAlgIdAndComment.py`, we should definitely keep the `main` because this code is supposed to be called from the command line (in order to change the algorithm id and algorithm comment of a data set). 

The other files seem indeed outdated. `dataoutput.py` in particular might not even work anymore as a stand-alone script because `genericsettings` in line 120 cannot be resolved because it is not imported within the file. According to its documentation, it was used to generate pickle files from raw data files - a functionality, we do not support anymore.

**Comment by dtusar** [comment]
Can I then remove the files `dataoutput.py`, `determineFtarget.py` and `determineFtarget2.py` from the project?

**Comment by nikohansen** [comment]
I believe we considered to have script files in the project that are not part of the `cocopp` module/package, but they use `cocopp` for some useful data generation. For these, different `main` rules should apply. I can't speak for the moment regarding the removal of files.

**Comment by brockho** [comment]
`dataoutput.py` now moved to a `helper-scripts` folder that is also documented now in the `README.md`. The other two files are nowhere called anymore, `determineFtarget` does not even appear within the source code (except in some comments as a substring of `determineFtarget2`. I therefore would guess that they can be deleted safely. However, maybe we still want to quickly have a look which functionality we actually would throw away before we do :-)

**Comment by brockho** [comment]
Decision of June 20: delete the remaining three files

**Comment by dtusar** [comment]
The remaining files are deleted.
