### ISSUE TITLE
Output of postprocessing needs revision for bbob-constrained suite

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1360]
When postprocessing `bbob-constrained` data sets, it seems that the current postprocessing is not doing the optimal things (yet). Aggregating over the functions of the same `bbob` function group but also aggregating over problems with `1...n+1` constraints only seems suboptimal.

Also, we would probably like to see scaling graphs with the number of constraints on the x-axis? If yes, the latter should become a new issue.

**Comment by nikohansen** [comment]
Sounds like a good idea to have graphs displaying the dependency on the number of constraints.

**Comment by paulduf** [comment]
This is done in `pproc.py`, in `DataSetList.dictByFuncGroupSingleObjective` (may be not used anymore hence removed) and `DataSetList.getFuncGroups`.

As Niko mentioned, we would like to break aggregation by number of constraints. Then a question remains: what to do of the Rastrigin which is the only member of the multimodal group ?

**Comment by paulduf** [comment]
Done for [the release](https://github.com/numbbo/coco/pull/2068).
