### ISSUE TITLE
weird name attribute in the constrained suite

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1363]
For the `bbob-constrained` suite, the C-function `coco_problem_get_name` returns rather weird values, for example

```python
import cocoex 
s = cocoex.Suite('bbob-constrained', '', '')
for i in range(3):
    print(s[i].name)
```
```
bbob-constrained_f001_i01_d02__bbob-constrained_f001_i01_d02
bbob-constrained_f001_i02_d02__bbob-constrained_f001_i02_d02
bbob-constrained_f001_i03_d02__bbob-constrained_f001_i03_d02
```
Besides that this doesn't look like an ideal name, should this be considered as a bug?

**Comment by asmaatamna** [comment]
This is likely a bug, yes.

**Comment by nikohansen** [comment]
Line 431 in `c_linear.c`
```c
coco_problem_set_id(problem_c, "bbob-constrained_f%02lu_i%02lu_d%02lu",
```
should read somewhat like 
```c
coco_problem_set_id(problem_c, "bbob-%02lu-lin-constraints_f%02lu_i%02lu_d%02lu", (unsigned long) i,
```

**Comment by brockho** [comment]
I agree with your suggestion, @nikohansen. Having an API like the `f_PROBLEMNAME_c_linear_cons_bbob_problem_allocate(...)` that does not allow to set correctly the name/id for the function and the constraints part separately seems unfortunate but can also be relatively easily changed. It is just tedious to do.

As a consequence, and as discussed today, the issue should get a low priority and might even become a 'wontfix' at some point. But it might also be a good starting point to contribute for somebody outside of the core COCO community and I thus will give it the 'easy' label.
