### ISSUE TITLE
Replace c functions 'strncpy' and 'strncat' with coco functions in logger_bbob.c

### ISSUE THREAD

**Issue by asmaatamna** [numbbo/coco#1366]
At the moment, there is no coco equivalent for these two functions in coco_string.c. But maybe we don't need to use these two functions specifically (I don't understand enough what the logger does to decide whether it is possible to replace them with already existing coco string functions).

**Comment by nikohansen** [comment]
What was the problem to use these functions? Apparently they are even C89 compatible.

**Comment by brockho** [comment]
In our discussion with @asmaatamna and @nikohansen yesterday, we decided to keep the code as is and close this issue.
