### ISSUE TITLE
Digesting data in the constrained case

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1367]
After a discussion with @nikohansen, @asmaatamna, @anneauger, and @dtusar, we agreed to the following points:
* When producing data on the `bbob-constrained` suite, the logger should write two columns for the number of evaluations: one for the `f`- and one for the `g`-evaluations.
* The postprocessing is reading in both data columns, produces a `raw_fevals` and a `raw_gevals` attribute from the data and computes the current `evals` attribute based on a weighted sum of the two.

For the first item, we should definitely write down a specification of the data (for all test suites actually).

**Comment by nikohansen** [comment]
Just FTR, it is quite desirable to have a much smaller number of different data specifications than different test suites.

**Comment by nikohansen** [comment]
First step: we need to specify the way how to indicate/detect whether a data file has this additional column or not.

**Comment by brockho** [comment]
I opened a new issue #1610 to remember the generic weighted sum issue above such that this issue here can be closed.
