### ISSUE TITLE
Inaccurate label in "Runtime distributions (ECDFs) over all targets" when missing data

### ISSUE THREAD

**Issue by asmaatamna** [numbbo/coco#1368]
Currently, only the function indices where all the data is available are displayed. Ideally, we should have the function indices for every dimension in case of missing data.

**Comment by brockho** [comment]
Since we do not remember (jointly with @asmaatamna, @dtusar, @nikohansen, @ttusar, and @islandblue) what this issue relates to, we close it as `wontfix`.
