### ISSUE TITLE
have example output data online

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1372]
The final goal is to have for each workshop year and each testbed the post-processed results online with a link from the main readme and the workshop page. A link to a single example would already be a very good start.

**Comment by brockho** [comment]
In order to make this happen, a small bug should be solved first: the `file:` in front of the links to the single `.svg` files should be removed within all html files in order to allow the links work remotely on our server.

**Comment by dtusar** [comment]
The `file:` was removed.

**Comment by nikohansen** [comment]
[here](http://coco.gforge.inria.fr/ppdata-archive/bbob/all-2009/) and [here](http://coco.gforge.inria.fr/ppdata/sel-bbob-2009) are now some data online.

http://coco.gforge.inria.fr/ppdata-archive is to be completed.

**Comment by brockho** [comment]
http://coco.gforge.inria.fr/ppdata-archive is now completed with the single year plots.

The ppdata archive is also hyperlinked now from within the README.md (development branch) and the GForge page such that this issue can be finally closed (until the next workshop at least :-) ).
