### ISSUE TITLE
Splitting header, body, and footer in pptables

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1376]
Similar to the single algorithm tables (#1208), we should also split the tables for many algorithms into their header, body (per function), and footer to be more flexible within the LaTeX templates. This will also allow to get rid of the `pptable2` functionality which is producing the same data than `pptables` but with a slightly different layout.

This refactoring
(i) will reduce code duplication (`pptable2` and `pptables` are almost the same except mainly for layout differences),
(ii) will definitely make it easier to merge the LaTeX templates for two and more algorithms into a single template, and
(iii) will improve the readability of the HTML tables in the two algorithm case.

**Comment by dtusar** [comment]
I split the tables for many algorithms and updated the template accordingly. Also for two algorithms the `pptables` output is used in the `html`. @brockho and @nikohansen if you agree I would like to remove the `pptable2` and all related to it from the project.

**Comment by nikohansen** [comment]
Sounds good to me.

**Comment by dtusar** [comment]
The `pptable2.py` was removed from the project.
