### ISSUE TITLE
Fixing random seed in postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1379]
In order to test the postprocessing before the (automated) move to Python 3 (#20), we realized today together with @nikohansen that it will be important to be able to fix the seed of the pseudo random number generator in the postprocessing before actually calling the postprocessing.

Doing so will allow to have a deterministic postprocessing and thus a way to make a regression test, which compares all produced images before and after a code change (such as the automated translation towards Python 3).

**Comment by brockho** [comment]
Since it seems, we only use random numbers from `numpy.random`, the only thing, the test has to do is to set `numpy.random`'s seed once.

In order to expose this behavior to the user, we might want to have a `cocopp.seed` (or a `genericsettings.seed` that is linked to the seed of `numpy.random`. 

As a first step, we should implement the test and then think about the exposure of the new functionality to the user.

**Comment by nikohansen** [comment]
That would mean just to assign `seed = numpy.random.seed` in `__init__.py`.

**Comment by nikohansen** [comment]
```python
import cocopp
cocopp.genericsettings.np.random.seed(2)
cocopp.main('my_folder')
```
produces visibly the same output when performed twice. However the image files are different, e.g. in the svg files we see
```
   <g id="line2d_1">
    <path clip-path="url(#pe8096c7047)" d="M 41.159282 230.240853 
```
where the argument after `url(` changes.

**Comment by nikohansen** [comment]
We decided to expose `np.random.seed` in `genericsettings.py`.

**Comment by nikohansen** [comment]
The use case to get a specific non-random result is now (since a93c897e).
```python
import cocopp
cocopp.set_seed(3 or "whatever number is desired")
cocopp.main(...)
