### ISSUE TITLE
Broken Tables in Postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1392]
The names in the multiple algorithm tables (pptables.py) seem to be broken. When I postprocess three data sets of the `bbob-noisy` suite, I get doubled labels:
```
python -m cocopp -o ppdata-noisy-new-3-test --omit-single RCGA_tran_noisy.tar.gz AVGNEWUOA_ros_noisy.tar.gz 1komma4mirser_brockhoff_noisy.tar.gz
```
results in

![image](https://cloud.githubusercontent.com/assets/13706996/26556763/c8a59ba4-449c-11e7-8d18-5d90ac805cf5.png)

and 
```
python -m cocopp -o ppdata-noisy-new-3 --omit-single 1komma4_brockhoff_noisy.tar.gz RCGA_tran_noisy.tar.gz AVGNEWUOA_ros_noisy.tar.gz
```

results in

![image](https://cloud.githubusercontent.com/assets/13706996/26556827/2a634af8-449d-11e7-9ba0-68375fc3fdc3.png)

All data sets themselves look okay.

**Comment by nikohansen** [comment]
Similar as #1251?

**Comment by dtusar** [comment]
@brockho I tried post-processing the same data and I got the correct captions, both in `html` and `latex`. Do you maybe have any additional information how to reproduce this?

**Comment by brockho** [comment]
Indeed strange, @dtusar: with the latest version, I can also not reproduce the issue anymore with the same data as before. I therefore close the issue.
