### ISSUE TITLE
mixup of interfaces

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1407]
The value of the constraints are available via the function `coco_evaluate_constraint`. The function`coco_is_feasible` in `coco.h` is on the other hand not meant to be used "externally", meaning that the solver is not allowed to use the result of calling this function. For this reason, in order to prevent confusion, I think this function should neither have the prefix `coco_` nor should it be listed in `coco.h`.

On the other hand, there are a few functions in `coco_utilities.c` with the prefix `coco_`, which could be used externally, but are not listed in `coco.h`. This is somewhat inconsistent yet not a big problem. It has the advantage to make `coco.h` leaner.

**Comment by nikohansen** [comment]
`coco_is_feasible` is removed from `coco.h` with commit 15750b6e3cc18d3ed9ee2fcf22660a07bcb4bd00 (coming).

It seems that `coco_evaluate_gradient` also should be removed from `coco.h`.

**Comment by nikohansen** [comment]
On the generic interface question: functions in `coco_utilities.c` are defined as `static` and it seems more logical to me if they would not have the `coco_` prefix. Am I missing something here?

**Comment by brockho** [comment]
Looking again at `coco.h` together with @ttusar and @nikohansen, we decided today to close the issue.
