### ISSUE TITLE
Add a simpler Python example experiment

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1419]
In the current example experiment the focus is not so much on code readability and the exposition of the benchmarking concept, but rather on running an experiment in an effective way and on flexibility to common setup changes. 

In particular for educational purposes we may want to add example code which is still functional but better serves to expose the idea of the benchmarking setup without much clutter.

**Comment by nikohansen** [comment]
A starting point: 
```python
import cocoex
from scipy.optimize import fmin
observer = cocoex.Observer("bbob", "result_folder: scipy-optimize-fmin")
suite = cocoex.Suite("bbob", "", "")
for problem in suite:  # this loop will take several minutes
    observer.observe(problem)  # generates the data for cocopp post-processing
    fmin(problem, problem.initial_solution)
```
It definitely looks to be short enough. 

And post-processing these data
```python
import cocopp
cocopp.main("exdata/scipy-optimize-fmin")
```
And now we open `ppdata/index.html` in a browser. 

```python 
import os, webbrowser
webbrowser.open("file://" + os.getcwd() + "/ppdata/index.html")
```

**Comment by nikohansen** [comment]
This is is the example given in http://numbbo.github.io/coco-doc/
```python
"""Python script to benchmark fmin of scipy.optimize"""
from numpy.random import rand
import cocoex
try: import cocopp  # new (future) name
except ImportError: import bbob_pproc as cocopp  # old name
from scipy.optimize import fmin

suite = cocoex.Suite("bbob", "year: 2016", "")
budget_multiply = 1e4  # use 1e1 or even 2 for a quick first test run
observer = cocoex.Observer("bbob", "result_folder: myoptimizer-on-bbob")

for p in suite:  # loop over all problems
    observer.observe(p)  # prepare logging of necessary data
    fmin(p, p.initial_solution)  # disp=False would silence fmin output
    while (not p.final_target_hit and  # apply restarts, if so desired
           p.evaluations < p.dimension * budget_multiplier):
        fmin(p, p.lower_bounds + (rand(p.dimension) + rand(p.dimension)) *
                    (p.upper_bounds - p.lower_bounds) / 2)
```

**Comment by nikohansen** [comment]
Combining the above: 
```python
import cocoex, cocopp
import scipy.optimize

### input
suite_name = "bbob"
output_folder = "scipy-optimize-fmin"
fmin = scipy.optimize.fmin
budget_multiplier = 2  # increase to 10, 100, ...

### prepare
suite = cocoex.Suite(suite_name, "", "")
observer = cocoex.Observer(suite_name, "result_folder: " + output_folder)

### go
for problem in suite:  # this loop will take several minutes
    observer.observe(problem)  # generates the data for cocopp post-processing
    x0 = problem.initial_solution
    # apply restarts as long the problem was not solved and the budget_was not exceeded
    while (not problem.final_target_hit and
           problem.evaluations < problem.dimension * budget_multiplier):
        fmin(problem, x0)
        x0 = problem.lower_bounds + (rand(problem.dimension) + rand(problem.dimension)) *
                    (problem.upper_bounds - problem.lower_bounds) / 2)

### post-process data
cocopp.main("exdata/" + output_folder + "")  # caveat: re-run folders look like "...-001" etc

```

**Comment by nikohansen** [comment]
My only concern is now that an `example_experiment_for_dummies.py` will prevent quite a few people from using `example_experiment.py`, even if it would serve their needs better.

**Comment by brockho** [comment]
It's probably just about the name whether people will use it? What about using something like you have for the CMA-ES in Matlab, @nikohansen, such as `example_experiment_for_reading.py` or `example_experiment_pure.py`?

**Comment by nikohansen** [comment]
In my experience people use e.g. `purecmaes.m` and never look back. I might well do the same in this case.

**Comment by nikohansen** [comment]
In order to improve interfacing, we should consider to let the user define a standard solver call from the solver to be benchmarked. In Python this is as simple as `def solver(p, restart): mymodule.mysolver(p, p.initial_solution if restart==0 else p.initial_solution + rand...)` in the most simple case. This looks like a significant improve for the original example experiment.

**Comment by nikohansen** [comment]
Done with commit 646ae06b8882ac7d7f44ce2df089c7157c3a874d
