### ISSUE TITLE
non-anytime example

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1420]
It seems comparatively simple to simulate a pseudo-anytime benchmarking experiment for a non-anytime algorithm. For a start, we should have an example code to play with, maybe based on #1419.

Requirement: the non-anytime algorithm under consideration must have a budget input parameter and respect this budget exactly.

A first test would take random search as non-anytime algorithm and compare to the anytime version. We expect to see a bias, for rather obvious reasons, where random search is likely to be the worst case scenario (strongest bias) at least when looking at the difference in non-log scale.

Code snippet: 
```python
budget_multiplier = 2
suite = ...
observer = ...

for problem_idx, problem in enumerate(suite):
    x0 = ...
    problem_observed = suite[problem_idx].observe_with(observer)
    problem_observed(x0)
    budget_list = list(range(2, budget_multiplier * problem.dimension + 1))  # or use np.logspace
    for budget in budget_list:
        x_final = fmin(problem, x0, budget)
        if problem.evaluations != sum(budget_list[:budget_list.index(budget)+1]):
            raise RunTimeError("algorithm does not conform with budget")
        problem_observed(x_final)
    problem_observed.free()
```

**Comment by ttusar** [comment]
We need to account for cases where the algorithm does not stop at the given budget (we need to record the actual number of evaluations).

**Comment by ttusar** [comment]
The non-continuous `budget_list` can be handled by either (1) adding a loop of evaluations of the previous point or (2) artificially increasing the number of evaluations.

**Comment by nikohansen** [comment]
After a discussion with the BBOBies team, there seems to be a much more generic solution which doesn't rely on the algorithm abiding by the prescribed budget: 
```python
def budget_list(dimension):
    """any sequence or generator works"""
    return range(2, 2 * dimension)
suite = ...
observer = ...

for problem_idx, problem in enumerate(suite):
    x0 = ...
    problem_observed = suite[problem_idx].observe_with(observer)
    for budget in budget_list():
        eval0 = problem.evaluations
        x_final = fmin(problem, x0, budget)
        evals_done = problem.evaluations - eval0
        if evals_done <= problem_observed.evaluations:
            warnings.warn(
                "this trial remains unrecorded, because %d evaluations "
                "is smaller than the already %d recorded evaluations"
                % (evals_done, problem_observed.evaluations))
            continue  # not really necessary
        while problem_observed.evaluations + 1 < evals_done:
            problem_observed(problem.initial_solution)
        if problem_observed.evaluations < evals_done:
            problem_observed(x_final)  # the single new record
        assert problem_observed.evaluations >= evals_done
    problem_observed.free()
```

**Comment by nikohansen** [comment]
A quick impression of the result on random search. The visible difference in the beginning is most likely do to evaluating the domain middle. This can be prevented by starting with budget 1 instead of 2. 
<img width="856" alt="screen shot 2017-06-21 at 15 18 04" src="https://user-images.githubusercontent.com/7316439/27386136-2931560c-5695-11e7-8207-970e7eb34420.png">

**Comment by nikohansen** [comment]
It turns out this had already been addressed in #28 in a different and somewhat nicer way.

**Comment by ttusar** [comment]
I wanted to try this example (as well as the other from #28), but I have a problem with both - the information on the experiments for the last dimension is not output to the `info` files, although it's computed (everything is there in the `tdat` and `dat` files).

For example, the `info` file ends like this if only dimensions up to 20 are used:
````
%
data_f4/bbobexp_f4_DIM10_i1.dat, 1:10000|9.1e+01
suite = 'bbob', funcId = 4, DIM = 20, Precision = 1.000e-08, algId = 'RS_non_anytime', coco_version = '2.0.422'
%
data_f4/bbobexp_f4_DIM20_i1.dat, 1:20000|4.0e+02
````

It looks as if the observer is not finalizing the output. I'm baffled because @nikohansen didn't have this problem in the code above... Could it have something to do with issue #681?

@nikohansen could you try running `example_non_anytime.py` from https://github.com/ttusar/coco/tree/rw-non-anytime/code-experiments/build/python to see if you have the same problem?

**Comment by nikohansen** [comment]
I can't currently see what is wrong with the above info file entry. I agree that the `%` is in an annoyingly "wrong" place, and it has been since the beginning of time ;-( but technically speaking the snippet looks OK to me.

**Comment by ttusar** [comment]
This is embarassing... I cannot belive it I missed it after looking at it several times! Of course the problem is in the unfortunate placement of `%` and not me (she muttered while crawling under the desk...)

**Comment by ttusar** [comment]
These are the two approaches I'm trying out (the first one is from issue #28 and the second is from this one):

```python
class ProblemNonAny(object):
    # Showing only the relevant functions... 
    def __init__(self, suite, observer, index):
        self.suite = suite
        self.index = index
        self.p_unobserved = suite[index]
        self.p_observed = suite[index].add_observer(observer)
        self.p = self.p_observed
        self.evaluations = 0

    def __call__(self, *arg, **args):
        if self.evaluations > self.p_observed.evaluations:
            raise ValueError("evaluations %d are larger than observed evaluations %d"
                             % (self.evaluations, self.p_observed.evaluations))
        if self.evaluations >= self.p_observed.evaluations:
            self.p = self.p_observed
        self.evaluations += 1
        return self.p(*arg, **args)

    def reset(self):
        self.evaluations = 0
        self.p = self.p_unobserved


def anytime_benchmark_loop_1(fmin, suite, observer, budget_list, budget_multiplier):
    """Anytime benchmarking of a non-anytime solver `fmin` on `suite` using ProblemNonAny.
    """
    for index, _ in enumerate(suite):
        with ProblemNonAny(suite, observer, index) as problem:
            for budget in budget_list(problem.dimension, budget_multiplier):
                problem.reset()
                fmin(problem, problem.lower_bounds, problem.upper_bounds, budget)
            problem.free()


def anytime_benchmark_loop_2(fmin, suite, observer, budget_list, budget_multiplier):
    """Anytime benchmarking of a non-anytime solver `fmin` on `suite`.
    """
    for problem_idx, problem in enumerate(suite):
        problem_observed = suite[problem_idx].observe_with(observer)
        x_last = problem.initial_solution
        for budget in budget_list(problem.dimension, budget_multiplier):
            # launch solver
            eval0 = problem.evaluations
            x_pending = fmin(problem, problem.lower_bounds, problem.upper_bounds, budget)  ### this interface may vary
            evals_done = problem.evaluations - eval0
            # warn if budget was not exhausted over the previous budget
            if evals_done <= problem_observed.evaluations:
                raise Warning("this trial remains unrecorded, because %d evaluations "
                              "is smaller than the already %d recorded evaluations"
                              % (evals_done, problem_observed.evaluations))
            # wind problem_observed forward to evals_done - 1 evaluations
            while problem_observed.evaluations + 1 < evals_done:
                problem_observed(x_last)
            # enter the new single record
            if problem_observed.evaluations < evals_done:
                problem_observed(x_pending)
                x_last = x_pending  # useful if the logger looks for a stable recommendation
            assert problem_observed.evaluations >= evals_done
        problem_observed.free()  # otherwise the bbob-logger crashes
````

And here are the results:
- `RS_anytime` is the "normal" random search from `example_experiment.py`
- `RS_1_non_anytime` is random search with the first approach
- `RS_2_non_anytime` is random search with the second approach

<img width="363" alt="screen shot 2017-09-05 at 11 48 03" src="https://user-images.githubusercontent.com/13745935/30055702-8fee29ca-9230-11e7-8dd8-0d105bf9d582.png">

I thought that the two approaches were equivalent, but apparently not. Where is the difference coming from?

Also, why does random search from the "normal" example experiment start by evaluating the middle of the domain and the one from the "non-anytime" experiment doesn't? The same function is being used...

**Comment by ttusar** [comment]
In today's call we realized that the first approach ignores all the points up to the given budget, which is what we actually want in a non-anytime benchmarking scenario. I will produce a non-anytime example experiment from the "simple" example experiment (when available). 

> Also, why does random search from the "normal" example experiment start by evaluating the middle of the domain and the one from the "non-anytime" experiment doesn't? The same function is being used...

The evaluation of the domain middle does not come from random search, but from the example experiment.

**Comment by nikohansen** [comment]
I am just realizing that ``class ProblemNonAnytime(object)`` should probably inherit from `cocoex.Problem` like ``class ProblemNonAnytime(cocoex.Problem)``. This would make it much simpler to use as an replacement in any example experiment code (accessing `x0` or `final_target_hit` etc).

**Comment by nikohansen** [comment]
@ttusar , I don't understand how the above `anytime_benchmark_loop_1` can work, in particular it seems to me that `problem.lower_bounds` etc. should not exist. I can see that `_.lower_bounds` contains what we want there.

**Comment by ttusar** [comment]
I haven't pasted the entire code here (to keep it simple), the class has a `lower_bounds` property:
```python 
    @property
    def lower_bounds(self):
        return self.p.lower_bounds
````

**Comment by nikohansen** [comment]
> I haven't pasted the entire code here (to keep it simple). 

Has made it more complicated for me :-(

I figured that we want within the `ProblemNonAnytime` class code from #28 something like this
```python
    def __init__(self, suite, observer, index):
        self.p_unobserved = suite[index]
        self.p_observed = suite[index].add_observer(observer)
        self._p = self.p_observed
        self.evaluations = 0
        for key in ['dimension',
                    'id',
                    'index',
                    'info',
                    'initial_solution',
                    'lower_bounds',
                    'name',
                    'number_of_constraints',
                    'number_of_objectives',
                    'number_of_variables',
                    'suite',
                    'upper_bounds'
                   ]:
            setattr(self, key, getattr(self._p, key))
    @property
    def final_target_hit(self):
        return self.p_observed.final_target_hit
    @property
    def best_observed_fvalue1(self):
        return self.p_observed.best_observed_fvalue1
```

**Comment by ttusar** [comment]
> Has made it more complicated for me :-(

Sorry about that. I did add a comment `# Showing only the relevant functions... ` to the class, but it's of course very easy to miss.

Thanks for the code! I was just thinking there must be a nicer way to deal with all those properties...

**Comment by ttusar** [comment]
Instead of listing all the properties `ProblemNonAnytime` should "inherit" from `Problem`, what if it "inherits" all its properties except those explicitly named? Something like this:
```python
properties = [attr for attr in dir(cocoex.Problem) if isinstance(getattr(cocoex.Problem, attr), property) and 
              attr not in ['best_observed_fvalue1', 'evaluations', 'final_target_hit']]
for key in properties:
    setattr(self, key, getattr(self._p, key))
````

**Comment by nikohansen** [comment]
I tend to prefer to control tightly what I mangle with instead of what I not mangle this. This was the reason for the positive list. I realized that I don't want `observe_with` or `add_observe` available. I also realized that the assignment only works for static values, because the assigned attributes may or may not change when the original value is changed, depending on whether the object remains the same or the attribute is assigned a new object.

Having a closer look on the result of `dir(cocoex.Problem)` suggests that this is a terrible idea. You overwrite all attributes, including `__call__`, `__doc__`, `__dict__`,... which possibly breaks pretty much everything you could possibly break. Of course you could exclude internal attributes, but you still remain susceptible to later changes of `Problem`.

My first idea had been to use `cocoex.Problem.__dict__.keys()` which seems to be a subset of `dir(cocoex.Problem)`, but then I realized...

**Comment by ttusar** [comment]
I thought such code might be easier to maintain - if at some point another property is added to `Problem`, it's in supported here as well. 

BTW, the resulting list of properties is as follows:
```python
['dimension', 'final_target_fvalue1', 'id', 'index', 'info', 'initial_solution', 'is_observed', 
'lower_bounds', 'name', 'number_of_constraints', 'number_of_objectives', 'number_of_variables', 
'observers', 'suite', 'upper_bounds']
````
I thought it wouldn't hurt to keep `'is_observed'` and `'observers'`, but you are right - those are not static, so they cannot be supported like this...

Okay then, I'll use your code above.

**Comment by nikohansen** [comment]
The upside is that your version is shorter. The downside is that it is more susceptible to changes in the `Problem` class and in this way less maintainable. It somehow depends on whether we semantically consider to be `ProblemNotAnytime` a `cocoex.Problem` subclass. 

`observers` is a list of which we should actually see the changes in `p_observed`, because we have assigned the _reference_ to this list. It shouldn't change anyways. For `is_observed` I haven't made up my mind which may be the desired value to deliver to the outside.

It makes probably sense to have a class attribute `inherited_attributes` for maintaining the list and write
```python
for key in ProblemNotAnytime.inherited_attributes:
    ...
```
in the `__init__` function.

**Comment by ttusar** [comment]
> For `is_observed` I haven't made up my mind which may be the desired value to deliver to the outside.

`is_observed` could be used to find out whether the problem is currently being observed, i.e., `is_observed` could equal `self._p.is_observed`.

**Comment by nikohansen** [comment]
But isn't the problem only unobserved from the anytime-perspective (`_p` is an anytime problem and we make a smart switch between two anytime problems to generate a non-anytime problem)? From the non-anytime perspective we could well say that `ProblemNonAnytime` is observed all the time.

**Comment by ttusar** [comment]
Yes, but the information content of such a variable would be 0. Exposing `self._p.is_observed` would be more interesting - it would allow peeking under the hood. Of course this might not be wanted/needed by the user, which is enough of an argument to keep it dull :-)

**Comment by nikohansen** [comment]
Keep in mind that everybody _can_ access `_p.is_observed` at any time if they are interested. We are only talking about semantic exposure here!

**Comment by ttusar** [comment]
Then I would think the non-anytime perspective is more appropriate, i.e. the problem is always observed.

**Comment by nikohansen** [comment]
FTR, I added the [example experiment for beginners](https://github.com/numbbo/coco/commit/646ae06b8882ac7d7f44ce2df089c7157c3a874d)
