### ISSUE TITLE
--omit-single

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1431]
should become default (as suggested by @brockho)? This is probably the much more common use case. Even without knowing this option, one can run `cocopp.main` on each single result folder independently, in case.

Do we need the "reverse" option `--no-omit-single` and how should it be called, `--do-single`?

**Comment by brockho** [comment]
Could also be `--include-single` or `--add-single`. But `--do-single` is also fine with me.

**Comment by brockho** [comment]
The option '--omit-single' became now the default. To call the postprocessing on each single argument, the new option reads now '--include-single'.

One thing that remains is to do an update of our [cocopp API documentation](http://coco.gforge.inria.fr/apidocs-cocopp/cocopp.html).

**Comment by brockho** [comment]
The cocopp API documentation is now updated and the issue can be closed.
