### ISSUE TITLE
Changing displayed target values for bbob-constrained

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1432]
It is not immediately obvious to me how to change the displayed targets for the `bbob-constrained` test suite. My first idea was to add in the `CONSBBOBTestbed` class of `testbedsettings.py` the following:

```
settings = dict(
[...]
        pprldmany_target_values = 10 ** np.arange(2, -6.2, -0.2),
        pprldmany_target_range_latex = '$10^{[-6..2]}$',
[...]
    )
```

and then have the `super(CONSBBOBTestbed, self).__init__(target_values)` move to the end of `def __init__(self, target_values):` which, unfortunately, gave the following error message:

```
C:\Users\dimo\Desktop\randopt-pub\asma>python -m cocopp cobyla_0.0feasthresh-on_bbob-constrained_budget1234xD

Post-processing (1): will generate output data in folder ppdata\cobyla_0.0feasthresh-on_bbob-constrained_budget1234xD
  this might take several minutes.
[...]
Generating LaTeX tables...
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.379-py2.7.egg\cocopp\
__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.379-py2.7.egg\cocopp\
rungeneric.py", line 260, in main
    dsld = rungeneric1.main(genopts + ["-o", outputdir, alg])
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.379-py2.7.egg\cocopp\
rungeneric1.py", line 374, in main
    pptable.main(sliceNoise, dims, algoutputdir, latex_commands_file)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.379-py2.7.egg\cocopp\
pptable.py", line 172, in main
    refalgentry = refalgentries[(d, f)]
KeyError: (2, 25)
```

Note that changing the displayed targets works for the bi-objective test suite for some time but there, the testbed class inherits directly from `Testbed` and not from `GECCOBBOBTestbed` such that the `__init__` method does not (have to) call `super`.

**Comment by dtusar** [comment]
If I understand this correctly the reference algorithm does not have data for function 25, dimension 2.

**Comment by nikohansen** [comment]
On a general note, to avoid lots of code duplication, initialising the `TargetValues` class instance should be done in a parent class, as it seems to be a rather generic procedure. Then, something like this:
```python
self.ppfigdim_target_values = targetValues(self.ppfigdim_target_values)
self.pprldistr_target_values = targetValues(self.pprldistr_target_values)
self.pprldmany_target_values = targetValues(self.pprldmany_target_values)
self.ppscatter_target_values = targetValues(self.ppscatter_target_values)
self.pptable_targetsOfInterest = targetValues(self.pptable_targetsOfInterest)
self.pptablemany_targetsOfInterest = targetValues(self.pptablemany_targetsOfInterest)
```
may rather read
```python
list_of_target_values = [
    self.ppfigdim_target_values,
    self.pprldistr_target_values,
    self.pprldmany_target_values,
    self.ppscatter_target_values,
    self.pptable_targetsOfInterest,
    self.pptablemany_targetsOfInterest]
for i in range(len(list_of_target_values)):
    list_of_target_values[i] = targetValues(list_of_target_values[i])
```
separating data from code.

**Comment by brockho** [comment]
I agree with the separation of data and code. However, it is not clear to me how the rest of the code will access the target values from the list_of_target_values. How do I know which `i` corresponds to `pptable_targetsOfInterest` for example?

**Comment by nikohansen** [comment]
Right, I am revising the above example.

**Comment by brockho** [comment]
@dtusar: hmm, within the child class (`CONSBBOBTestbed`), we set `reference_algorithm_filename = ''`, but this is overwritten by the superclass as I call `super` after setting all `bbob-constrained`-related things:

```
In [4]: debug
C:\Users\dimo\Anaconda2\lib\site-packages\IPython\core\debugger.py:238: DeprecationWarning: The `col
or_scheme` argument is deprecated since version 5.1
  DeprecationWarning)
> c:\users\dimo\appdata\roaming\python\python27\site-packages\cocopp-2.0.387-py2.7.egg\cocopp\pptabl
e.py(172)main()
    170
    171             if refalgentries:
--> 172                 refalgentry = refalgentries[(d, f)]
    173                 refalgdata = refalgentry.detERT(targetsOfInterest((f,d)))
    174                 if isinstance(targetsOfInterest, pproc.RunlengthBasedTargetValues):

ipdb> testbed.reference_algorithm_filename
'refalgs/best2009-bbob.tar.gz'
ipdb>
```

**Comment by nikohansen** [comment]
Calling `super` at the end of `__init__` feels like it may introduce unexpected problems. Usually, the derived class wants to control and possibly modify the already initialised parent class instance.

**Comment by dtusar** [comment]
The problem here is that in the __init__ function of the base attributes are set and then also used for the initialization of the target values. But you would want in `__init__` to call `super` which only sets the default attributes, update those attributes and then call "something" that sets the target values.

**Comment by brockho** [comment]
Right, we have to split the setting of initial values and the setting of the actual target values in some way or another.

With the suggestion of @nikohansen above, however, it might not work either: if, like in the current code, we continue to overwrite the values within the `__init__` by calling the "something" there, we will also overwrite them already when calling `super` from a sub-class. Calling the "something" then in the sub-class after the `super` as suggested will most likely not work because the values we initially specified are lost in the meantime, right?

**Comment by nikohansen** [comment]
If push comes to shove, we might consider implementing a method `instantiate_targets` in the base class, which is called whenever necessary in the inherited class? I could definitely be missing something here though...

**Comment by brockho** [comment]
As long as this method does not overwrite the initial settings of the sub-class, this seems to be the right way to go.

**Comment by nikohansen** [comment]
It may just do something like:
```python
def instantiate_attributes(self, class_, suffix_list=['target_values', 'targetsOfInterest'])
    for name in self.__dict__:
        for suffix in suffix_list:
            if name.endswith(suffix):
                self.setattr(name, class_(self.getattr(name)))
```

**Comment by dtusar** [comment]
Now we have the method `instantiate_attributes` in `Testbed` class. In the `__init__` of `CONSBBOBTestbed` you should first call `super`, update the attributes values and then call `instantiate_attributes`.

**Comment by brockho** [comment]
@dtusar: unfortunately, the new code does not work, or I am doing something wrong. I now do within the constrained testbed class as you suggest:

```python
class CONSBBOBTestbed(GECCOBBOBTestbed):
    shortinfo_filename = 'bbob-constrained-benchmarkshortinfos.txt'
    settings = dict(
        [...]
        pprldmany_target_values=10 ** np.arange(2, -6.2, -0.2),
        pprldmany_target_range_latex='$10^{[-6..2]}$'
    )

    def __init__(self, target_values):
        super(CONSBBOBTestbed, self).__init__(target_values)
        for key, val in CONSBBOBTestbed.settings.items():
            setattr(self, key, val)
        self.instantiate_attributes(target_values)
```

and what I get this error:

```
Post-processing (3+): will generate output data in folder ppdata-test-04
  this might take several minutes.
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
rungeneric.py", line 264, in main
    dsld = rungenericmany.main(genopts + ["-o", outputdir] + args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
rungenericmany.py", line 281, in main
    dsList, sortedAlgs, dictAlg = processInputArgs(args, True)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
pproc.py", line 2629, in processInputArgs
    process_arguments(args, current_hash, dictAlg, dsList, sortedAlgs)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
pproc.py", line 2649, in process_arguments
    tmpDsList = DataSetList(filelist)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
pproc.py", line 1690, in __init__
    self.processIndexFile(name)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
pproc.py", line 1761, in processIndexFile
    ds = DataSet(header, comment, data, indexFile)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
pproc.py", line 832, in __init__
    testbedsettings.load_current_testbed(self.testbed_name, TargetValues)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
testbedsettings.py", line 48, in load_current_testbed
    current_testbed = constructor(target_values)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
testbedsettings.py", line 277, in __init__
    self.instantiate_attributes(target_values)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
testbedsettings.py", line 173, in instantiate_attributes
    setattr(self, name, class_(getattr(self, name)))
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.415-py2.7.egg\cocopp\
pproc.py", line 128, in __init__
    self.target_values = sorted(target_values, reverse=True)
TypeError: 'TargetValues' object is not iterable
```

**Comment by dtusar** [comment]
By default it instantiate all of the `..._target_values` and `.._targetsOfInterest`. 
In your case you should call 
`self.instantiate_attributes(target_values, ['pprldmany_target_values'])` 
since it's the only one you've changed.

**Comment by brockho** [comment]
Thanks for the clarification. It works now :-)

However, it is more than annoying that one has to remember to add an additional line like 
`self.instantiate_attributes(target_values, ['pprldmany_target_values'])` (and to remember how to do that) instead of simply adding the `pprldmany_target_values=10 ** np.arange(2, -6.2, -0.2),` line within the `settings` dictionary.

Maybe, we should therefore have a generic code at the end of each `__init__` that checks which of the local entries in `settings` have to be updated and then calls the `self.instantiate_attributes` for all of them automatically? I suggest the following:

```python
class CONSBBOBTestbed(GECCOBBOBTestbed):

    shortinfo_filename = 'bbob-constrained-benchmarkshortinfos.txt'
    pptable_targetsOfInterest = (10, 1, 1e-1, 1e-2, 1e-3, 1e-5, min_target)  # for pptable and pptablemany

    settings = dict(
        [...]
        pprldmany_target_values = 10 ** np.arange(2, -6.2, -0.2),
        pprldmany_target_range_latex = '$10^{[-6..2]}$',
        ppscatter_target_values = np.logspace(-6, 2, 21),
        [...]
    )

    if 11 < 3:
        # override settings further if needed...
        settings.reference_algorithm_filename = 'best2018-bbob-constrained.tar.gz'  # TODO: implement
        settings.reference_algorithm_displayname = 'best 2018'  # TODO: should be read in from data set in reference_algorithm_filename


    def __init__(self, target_values):
        super(CONSBBOBTestbed, self).__init__(target_values)

        for key, val in CONSBBOBTestbed.settings.items():
            setattr(self, key, val)
            if 'target_values' in key or 'targetsOfInterest' in key:
                self.instantiate_attributes(target_values, [key])

```

**Comment by brockho** [comment]
The current code in the `development` branch uses now the above proposed code of @dtusar for all testbeds such that the issue can be closed now.

The `bbob-constrained` test suite is displayed with targets `[100, ..., 1e-6]` for now to showcase that the change works but the choice of `1e-6` is of course open for discussions...
