### ISSUE TITLE
Title of templateBBOBarticle.html

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1433]
when clicking on a single algorithm result, the webpage title is "ALG". It seems that not too much love has gone into this title. 

How about "Benchmarking Results for Algorithm %s on the %s Suite" % (algorithm_name, suite_name)?

**Comment by dtusar** [comment]
Done.

**Comment by nikohansen** [comment]
The title produced by default is rather meaningless, because no meaningful `algorithm_name` is used.

**Comment by nikohansen** [comment]
Addressed with commit 3be30e6b73753f5316ff98c8809fc7166a3a9a33, in that a meaningless algorithm name is ignored.
