### ISSUE TITLE
wrong pprldmany_02D_noiselessall.svg figure

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1434]
I was post-processing two algorithms and get the following figure as overview in 2D (see browser address line). All other figures seem to be fine, see https://github.com/numbbo/coco/issues/1420#issuecomment-310087969

<img width="568" alt="screen shot 2017-06-21 at 15 56 53" src="https://user-images.githubusercontent.com/7316439/27387996-79859e1a-569a-11e7-9790-4532a98e93ff.png">

**Comment by dtusar** [comment]
I cannot reproduce this. Did you have any background algorithms?

**Comment by nikohansen** [comment]
I used the default setting(s).

**Comment by nikohansen** [comment]
I assume this is solved.
