### ISSUE TITLE
TypeError without tdat files

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1443]
I get a strange TypeError when postprocessing our `NEWUOA` data set with the latest version which I never got before: 

```
C:\Users\dimo\Desktop\test\dfo-tr\dfo-algorithm-master\dfo-algorithm-master\blackbox_opt\DFO_src\exd
ata>python -m cocopp -o ppdata_COMP NEWUOA_ros_noiseless.tgz

Post-processing (1): will generate output data in folder ppdata_COMP\NEWUOA_ros_noiseless
  this might take several minutes.
Traceback (most recent call last):
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Users\dimo\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.423-py2.7.egg\cocopp\
__main__.py", line 30, in <module>
    res = rungeneric.main(args)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.423-py2.7.egg\cocopp\
rungeneric.py", line 261, in main
    dsld = rungeneric1.main(genopts + ["-o", outputdir, alg])
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.423-py2.7.egg\cocopp\
rungeneric1.py", line 270, in main
    dsList = DataSetList(filelist)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.423-py2.7.egg\cocopp\
pproc.py", line 1692, in __init__
    self.processIndexFile(name)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.423-py2.7.egg\cocopp\
pproc.py", line 1763, in processIndexFile
    ds = DataSet(header, comment, data, indexFile)
  File "C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.423-py2.7.egg\cocopp\
pproc.py", line 935, in __init__
    raise Usage("Missing tdat files in '{0}'. Please rerun the experiments." % filepath)
TypeError: not all arguments converted during string formatting
```

Did something related to this changed recently, @dtusar? I thought that `.tdat` files have been always optional so far and should stay that way, or am I wrong?

**Comment by dtusar** [comment]
There was no recent change related to this. I will check but it could be that we already have this behavior for a long time.

**Comment by dtusar** [comment]
The data for this algorithm in the gforge data archive contains also tdat files. Where did you get your data?

**Comment by dtusar** [comment]
But it's true, without the tdat files the post-processing stops.

**Comment by nikohansen** [comment]
This should be considered as a bug. The `.tdat` files should not be necessary, as the maxevals-info can (and should) be taken from the `.info` files, am I wrong? This relates to #1381

**Comment by brockho** [comment]
It turned out that the problem was a broken `.extracted_...` folder. As soon as I deleted this one and run the postprocessing again, it worked.

However, the problem with missing `'tdat' files should be addressed - even if we don't provide those data files for the moment.

At the same time, we should consider a check while extracting the files that everything worked well (and to clean up if the extraction did not work well).

**Comment by brockho** [comment]
I opened two new issues #1445 and #1446 detailing the above two open things from my last comment. This issue can, thus, be closed.
