### ISSUE TITLE
INF written to .dat file gives warning

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1444]
While looking at results for the DFO-TR algorithm (https://github.com/TheClimateCorporation/dfo-algorithm), I observed the following warning in the COCO postprocessing:
```
C:\Users\dimo\AppData\Roaming\Python\Python27\site-packages\cocopp-2.0.421-py2.7.egg\cocopp\readali
n.py:487: UserWarning: +1.#INF00000e+000 is not a valid number!
  warnings.warn('%s is not a valid number!' % data[index])
```
Note that @islandblue and I had to tweak a bit the example experiment to make the algorithm work with COCO:
```python
        elif solver.__name__ in ("dfo_tr",):
            options = {"maxfev": 100000, "init_delta": 20,
                       "tol_delta": 1e-25, "tol_f": 1e-26, "tol_norm_g": 1e-5,
                       "sample_gen": "auto", "verbosity": 0}
            x0 = fun.initial_solution
            def dfofun(x):
                f = fun(np.squeeze(x))
                if f > 1e30:
                    return 1e30
                else:
                    return f

            solver(dfofun, x0, options)
```

The reason for the above warning is a strange data file, written by the observer (here for an f3 instance):
```
51 +1.014120672e+001 +1.014120672e+001 +1.010141207e+003 +1.010141207e+003 +4.5918e+000 +3.3352e+000 -9.6221e-001
54 +9.954570538e+000 +9.954570538e+000 +1.009954571e+003 +1.009954571e+003 +4.6217e+000 +3.3353e+000 -9.6894e-001
250 +1.#INF00000e+000 +9.949560299e+000 +1.#INF00000e+000 +1.009949560e+003 +4.6217e+000 +3.3328e+000 +3.0024e+015
```
This must be considered as a bug.

The corresponding data files that resulted in the above warning are to be found here: 
[dfo_tr_upto5D-warning.zip](https://github.com/numbbo/coco/files/1119016/dfo_tr_upto5D-warning.zip)

**Comment by nikohansen** [comment]
This looks indeed quite strange, as the best fitness (3rd column) seems to improve, while the measured fitness (2nd column) computes to something like inf. The later seems to make sense as the third parameter value is `+3.0024e+015`. The improvement of the best f-value therefor may hint to a bug in the logger. Is there a reason we see this exactly at evaluation 250?

**Comment by brockho** [comment]
The error after 250 evaluations is by chance, I guess. On an instance of f6, for example, the same `#INF` appears at evaluation 1570.

**Comment by brockho** [comment]
To precise, the error appears on `f3` in 3-D, instance 6, but also on `f6` in 2-D on instance 7, and on `f6` in 3-D, instance 3.

All cases have in mind that the relative objective function value already went below `1e-8` and kept recording. The evaluated points when the problem happens also all have one variable extremely high, compared to the previously evaluated points (i.e. >1e+15 vs. <10).

**Comment by brockho** [comment]
This issue might get solved together with #1518.

**Comment by brockho** [comment]
@islandblue: do you still have the code of the above experiment such that we can reproduce the bug?

**Comment by nikohansen** [comment]
Should be resolved in the `devel-cons-v2` branch, I appreciate any stress-testing ;-)

**Comment by brockho** [comment]
The latest experiment, I did with the DFO-TR algorithm, is postprocessible now. Don't know how much it is by chance though :-) But what I can observe is that the entire data set does not contain any `INF` this time.

I also tested the experiments/logger code with the CMA-ES in python and also here the data files look consistent to me. Hence, I am fine to close the issue.

**Comment by brockho** [comment]
Joint decision of today: can be closed because also addressed with the latest version in `devel-cons`.
