### ISSUE TITLE
How to adapt the post-processing to new suites

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1449]
https://github.com/numbbo/coco/blob/development/howtos/create-a-suite-howto.md

should be updated to give at least a quick overview (or a pointer to where such overview can be found) as to which parts of the post-processing need to be modified when an unknown, new suite is processed, including to give the _minimal_ necessary modifications.

**Comment by nikohansen** [comment]
@dtusar , could you take care of this swifty?

**Comment by dtusar** [comment]
Added to the above mentioned file.
