### ISSUE TITLE
Changing the number of constraints in bbob-constrained suite

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1458]
Looking at first data on the `bbob-constrained` test suite with @nikohansen a couple of weeks ago, we thought about changing the set of constraints used for the `bbob-constrained` suite. Instead of `1, 2, 10, n/2, n-1, n+1` we should probably use `1, 2, 8, n/2, n, 3n` or something similar.

**Comment by nikohansen** [comment]
We may use `1,2,6` as we can express the n-dependent values as `[k * n // 2 for k in [1,2,6]]`.

**Comment by brockho** [comment]
Okay for the latest suggestion. I will then implement it next week to proceed towards the second stage of the [bbob-constrained project](https://github.com/numbbo/coco/projects/16).

**Comment by brockho** [comment]
Implemented with pull request #1491 (though later than promised).
