### ISSUE TITLE
Continuous Gray code optimization.

### ISSUE THREAD

**Issue by S6Regen** [numbbo/coco#1461]
I don't know if you have this algorithm in your collection:
[https://drive.google.com/open?id=0BwsgMLjV0BnhR2h6WWpNeVJpS00](url)
[https://forum.processing.org/two/discussion/23422/a-simple-way-to-optimize](url)

**Comment by nikohansen** [comment]
I am pretty confident that we do _not_ have Gray-code ES from the 2004 Rowe and Hidovic paper. The list of algorithms for which we have archived data sets is available here:

http://coco.gforge.inria.fr/doku.php?id=algorithms

**Comment by S6Regen** [comment]
I don't have time to study the coco files and submit a proper contribution. 
However I do have more information related to optimization.  That is a fast way to generate Gaussian random numbers: [https://drive.google.com/open?id=0BwsgMLjV0BnhOGNxOTVITHY1U28](url)
If you have a population of 2^n numbers (ie 256) you can directly generate Gaussian random numbers with the same variance as the population by processing with a random projection.

However, I really think the continuous Gray code optimizer is far better for most problems.

**Comment by nikohansen** [comment]
> However, I really think the continuous Gray code optimizer is far better for most problems.

What's the evidence you can share with us to come to this conclusion?

**Comment by S6Regen** [comment]
I think the Trefethen function is difficult even if it is only 2 dimensions.
[http://infinity77.net/global_optimization/test_functions_nd_T.html#go_benchmark.Trefethen](url)
It is number 9 on the list here:
[http://infinity77.net/global_optimization/test_functions.html](url)

I'll try Gray code optimization with DeVilliersGlasser02 (N=5) and see if it can solve that.   The only other option would be for you to try it with the test code you already have and understand!

**Comment by S6Regen** [comment]
Ok, the best I got was:
Cost:8.096747342236746E-11
At:
X1:53.809986 X2:1.2700002
X3:3.012019 X4:127.793686
X5:0.507
You can see that X4 is different to what the documentation says it should be???

// subject to 500≤xi≤500. The global minimum is f(x) = 0
// At `x = [53.81, 1.27, 3.012, 2.13, 0.507]
// elements of vec are -1 to 1
double fnDeVilliersGlasser02(float[] vec) {
  double x1=vec[0]*500f;
  double x2=vec[1]*500f;
  double x3=vec[2]*500f;
  double x4=vec[3]*500f;
  double x5=vec[4]*500f;
  double result=0f;
  for (int i=1; i<=16; i++) {
    double t=0.1*(i-1.0);
    double y=53.81*Math.pow(1.27, t)*Math.tanh(3.012*t+Math.sin(2.13*t))*Math.cos(Math.exp(0.507)*t);
    double r=x1*Math.pow(x2, t)*Math.tanh(x3*t+Math.sin(x4*t))*Math.cos(t*Math.exp(x5))-y;
    result+=r*r;
  }
  
  if(Double.isNaN(result)) result=Double.POSITIVE_INFINITY;
  return result;
}

I'm not doing any more.  I'm only do this kind of thing for a hobby.   I don't have to prove or substantiate anything to anyone!!!
