### ISSUE TITLE
Invalid syntax in algportfolio.py

### ISSUE THREAD

**Issue by islandblue** [numbbo/coco#1479]
In commit `699cf4e` @FloopCZ changed `except Usage, err:` to `except Usage err:`, which causes an invalid syntax message that is normally swallowed. I noticed it while working on issue #1436. The intended change may have been `except Usage as err:`. Added a comment on the commit as well. Will see if I can get a confirmation from @FloopCZ. If not I'll just go ahead and fix it.

**Comment by FloopCZ** [comment]
@islandblue Nice catch, you are right!

**Comment by islandblue** [comment]
@FloopCZ Thank you for the prompt confirmation.

**Comment by islandblue** [comment]
This issue can be closed as soon as pull request #1480 goes through, pending review by @nikohansen or @brockho.

**Comment by FloopCZ** [comment]
Trick (in case you didn't know already): If your write "Closes #1479" into the commit message, the issue gets closed automatically as soon as the PR is merged to the default branch. (from the [docs](https://help.github.com/articles/closing-issues-using-keywords/))

**Comment by islandblue** [comment]
#1480 is now merged, so this issue can be closed.
