### ISSUE TITLE
Legend in Scaling Figures

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1492]
There has been a legend in the aRT vs dimension figures for the first and the last function in previous versions. I find the figures without a legend, e.g. [here](http://coco.gforge.inria.fr/github/issue00021/ppdata-expensive-refRSportfolio/RANDO_BIPOP_BFGS__SMAC-_lmm-C_HCMA/ppfigs.html) practically unreadable. I cannot remember the color of each algorithm by heart and the caption doesn't make it any easier, because it doesn't display the very same symbol (different size, different thickness). Even if it were the same symbol, scrolling back and forth to find out which is which algorithm is not a useful mode of operation for me. 

I suggest to have a (transparent, e.g. `framealpha=0.2`) legend as before in the first and last function and make it a little better behaved like this:
![image](https://user-images.githubusercontent.com/7316439/29642423-1a830e74-8869-11e7-8a16-86296e76687c.png)

**Comment by brockho** [comment]
I agree with you regarding the names in the last figure.

For [this here](http://coco.gforge.inria.fr/github/issue00021/ppdata-expensive-refRSportfolio/RANDO_BIPOP_BFGS__SMAC-_lmm-C_HCMA/ppfigs.html), the reason that no legend is shown within the figures seems to be that too many algorithms are displayed. We can make the choice to have a legend for 6 algorithms (and maybe even a bit more), but at some point, the plot becomes completely unreadable (if we have for example 30 algorithms displayed) such we have to set a limit from which on we remove the legend for readability.

**Comment by ttusar** [comment]
Maybe the legend can be placed outside the plot

**Comment by nikohansen** [comment]
A legend outside the plot will change the figure size, which is quite problematic. 

I suggest to compute the legend font-size depending on the number of algorithms and see how far we can get (don't we do the same when annotating the ECDF plots?). I reckon that is anyway not very useful (if at all) to display more than 50-or-so algorithms.

**Comment by nikohansen** [comment]
Now it looks like this for 3 and 9 algorithms respectively: 
<img width="189" alt="screen shot 2017-08-25 at 01 13 29" src="https://user-images.githubusercontent.com/7316439/29692896-bd22c8c6-8932-11e7-97bf-ddd129c945fb.png">
<img width="187" alt="screen shot 2017-08-25 at 01 12 29" src="https://user-images.githubusercontent.com/7316439/29692901-c434ee14-8932-11e7-9116-eeab45bcc4bf.png">
