### ISSUE TITLE
post-processing output folder message

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1497]
We see the message 
```
Post-processing (2+): will generate output data in folder ppdata
```
however this isn't too helpful when the `ppdata` folder looks for example like this:
<img width="430" alt="screen shot 2017-08-25 at 17 47 14" src="https://user-images.githubusercontent.com/7316439/29721461-949875fa-89bd-11e7-9188-b79d91f8b786.png">

Hence, information on the written subfolder should be printed as well!

**Comment by nikohansen** [comment]
FTR, this now happens much less often after some changes (not sure what the change was), but it still happens once in awhile (not sure what the precise conditions are). Any hints from anybody?

**Comment by islandblue** [comment]
Confused. I was under the impression that this is not something that happens but just the way output is. Did I get the issue wrong? Don't we just want to add the subfolder to the informative text?

**Comment by nikohansen** [comment]
Sorry, I was too fast, the above comment refers to https://github.com/numbbo/coco/issues/1472

**Comment by nikohansen** [comment]
I still don't see which folder I have to open:
```
import glob
import cocopp
datahome = '/Users/hansen/svn/coco/BBOB/data-archive/data/gecco-bbob-1-24/'
datafiles = glob.glob(datahome + '2009/rawdata/*M*tgz')
dsl = cocopp.main('--runlength-based ' + ' '.join([df for df in datafiles]))

[...]

Loading best algorithm data from refalgs/best2009-bbob.tar.gz ...
    archive extracted to folder cocopp/refalgs/.extracted_best2009-bbob ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: cocopp/refalgs/best2009-bbob.tar.gz
  done (Wed Sep  6 10:19:56 2017).
  done (Wed Sep  6 10:20:19 2017).
Setting changes in `cocopp.genericsettings` compared to default:
    runlength_based_targets: from False to True
    foreground_algorithm_list: from [] to ['/Users/hansen/svn/co...
ALL done (Wed Sep  6 10:20:20 2017).
```

**Comment by islandblue** [comment]
Will add after resolving a conflict in the development branch.
