### ISSUE TITLE
Output of BBOB2009 experiment seems wrong

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#150]
When running the C example of the BBOB2009 demo, the produced output looks wrong. In a file 'bbobexp_f1_i8.info' only results for instance 6 are referenced.

**Comment by oaelhara** [comment]
I tried reproducing the inconsistent output in the new suites (by forcing the creation of dim 5 with different instances instead of dim 20) but the output seems consistent and the post-processing produces the expected result

**Comment by nikohansen** [comment]
What is the current status?

**Comment by brockho** [comment]
Any news about this issue? We should probably close it because I also cannot see a problem with the current code. I tried for example the `instance_idx: 10,11` option when running the `bbob` suite in the 2016 setting and get correctly instances 55 and 56 in the files and `i55` in the filenames.

**Comment by oaelhara** [comment]
I also think it should be closed, I don't see any inconsistent index-file names
