### ISSUE TITLE
CI on Mac

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1504]
The leak-check via valgrind on the Mac currently fails. I tried with an empty main, and it fails also. This leads me to believe that we have the problem described [here](https://stackoverflow.com/questions/16210408/valgrind-shows-memory-leak-on-empty-program-on-mac-osx-10-8). I assume the solution is given [here](http://valgrind.org/docs/manual/manual-core.html#manual-core.suppress), but currently I don't have the time to check this carefully.

**Comment by dtusar** [comment]
I tried the above mentioned solution and added these two errors to the suppression file:

```
# See https://stackoverflow.com/questions/16210408/valgrind-shows-memory-leak-on-empty$
{
   macos-__mach_msg_trap_test1
   Memcheck:Param
   msg->desc.port.name
   fun:mach_msg_trap
   fun:mach_msg
   fun:task_set_special_port
   fun:_os_trace_create_debug_control_port
   fun:_libtrace_init
   fun:libSystem_initializer
}
{
   macos-__mach_msg_trap_test2
   Memcheck:Leak
   match-leak-kinds: possible
   fun:calloc
   fun:map_images_nolock
   fun:map_images
   fun:_ZN4dyldL18notifyBatchPartialE17dyld_image_statesbPFPKcS0_jPK15dyld_image_infoE$
   fun:_ZN4dyld21registerObjCNotifiersEPFvjPKPKcPKPK11mach_headerEPFvS1_S6_ESC_
   fun:_dyld_objc_notify_register
   fun:_objc_init
   fun:_os_object_init
   fun:libdispatch_init
   fun:libSystem_initializer
}
```
Now an empty main goes through but our `leak-check` still has one error. Not sure if I should suppress also this one.

**Comment by dtusar** [comment]
Now the test does not fail any more. @brockho Where can I find the file with the slave installation steps?

**Comment by brockho** [comment]
Great!

@dtusar: so far, we have the slave installation steps in our `numbbo` svn repository in the `administration-infos.txt` file.

**Comment by dtusar** [comment]
I updated the `administration-infos.txt` file.

**Comment by ttusar** [comment]
My commit dc9e82d5ee9471c0b1559aafc57cddcdf73b10ec seems to cause leak check to fail on the development branch on the Mac. However, it worked fine on the devel-test3 branch, so I'm not sure what is the true problem here...
