### ISSUE TITLE
index.hml files for each overview folder?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1513]
When I run the simple example experiment https://github.com/numbbo/coco/issues/1419#issuecomment-309385586, to see the overview over the results I need to open the `ppdata/scipy-optimize-fmin/templateBBOBarticle.html` file. IMHO, this `html` file should be named `index.html` to make it easier accessible to the user. 

This is also related to issue #1497, in that the user needs to be smoothly directed to what to look at after having run the post-processing.

**Comment by islandblue** [comment]
Do we want the link in the top index page to still read `templateBBOBarticle`?

**Comment by islandblue** [comment]
How about `comparison_data.html` for multiple algorithms? Are we going after the principle that there should be an index.html in each folder?

An alternative is to have an index.html wherever we want, that redirects to whichever html file we want. That way, file names remain what they are.

**Comment by nikohansen** [comment]
In this case here, `comparison_data` is somewhat not the right name, because it is only data for a single algorithm, so no comparison (`single_data` seems OK). I would like to always have an `index.html` to make life easier, but I don't mind if it is just redirecting to another file.

**Comment by dtusar** [comment]
I would prefer having only the `index.html` and removing the `comparison_data.html` and `templateBBOBarticle.htm` (in the corresponding folders). It would also make the code cleaner.

**Comment by nikohansen** [comment]
Sounds good to me.

**Comment by brockho** [comment]
see also #1512

**Comment by dtusar** [comment]
Now we have `index.html` file in the multiple algorithm folders and `index1.html` file in the single algorithm folders. The file names are different so it can be determined which folders contain single and which multiple algorithms. I would prefer having `index.html` file in all folders but I don't have a better idea how to distinguish the folders?

**Comment by islandblue** [comment]
For what it's worth, my preference would have been different. Two reasons:

- index.html is the standard filename for the home/entry/main page in any folder of a web site. Multiple files named index.html in different folders is perfectly valid. Maybe I'm a little rigid on this, but to me, index1.html and templateBBOBarticle.html are equally non-standard. index1.html is of course a big hint to a human user, but as long as there is no technical problem with index.html, I don't see any reason to justify deviating from the standard.

- Sole purpose of a filename is to describe the contents of the file itself, not the folder it's in. The folder name is already there to distinguish between folders. After all, if I need to distinguish between two folders, I would prefer to do it looking at the folder that contains the folders, not go inside each of them to see how files inside are named.

Just my opinions, though, and definitely subjective.

**Comment by nikohansen** [comment]
I can live with the current solution.

**Comment by brockho** [comment]
I can also live with the current situation.

**Comment by dtusar** [comment]
So we can close the issue.

**Comment by nikohansen** [comment]
With the latest changes no `index.html` file is written when I process 3 algorithms.

**Comment by dtusar** [comment]
For me it works fine. Which `index.html` is missing in your case? The one in the root folder or the one in the comparison data folder?

**Comment by nikohansen** [comment]
In index file the comparison folder.

**Comment by dtusar** [comment]
Was the file `comparison_data.html` generated?

**Comment by nikohansen** [comment]
Yes.

**Comment by dtusar** [comment]
Then it's not the latest version of `cocopp`.

**Comment by nikohansen** [comment]
I believe I used 2.0.589.

**Comment by nikohansen** [comment]
will try with 2.0.591

**Comment by nikohansen** [comment]
OK, that was it.

**Comment by dtusar** [comment]
Great.
