### ISSUE TITLE
Reset default package install location to system site packages

### ISSUE THREAD

**Issue by islandblue** [numbbo/coco#1514]
After the change targeting issue #1436, the default package install location was temporarily changed back to system site packages to see if that was the reason CI tests were failing. It turned out tests still failed.

Please correct me if I'm wrong:

@brockho thinks the default should remain user site packages, because that's the way it was and only one user had a complaint.

@nikohansen thinks the default should revert to system site packages, because that's the default of setuptools, pip and possibly others, also because whatever you do inside an environment should not affect other environments (and installing in user site packages does).

The reversion is undergoing test. I will merge into development (or discard) as soon as we agree on the course of action. What to do?

**Comment by islandblue** [comment]
Tests are green. Let's take it or leave it. =)

**Comment by nikohansen** [comment]
It turns out that https://github.com/numbbo/coco/pull/1515 breaks the test, as was suspected. Am I wrong? Why didn't we see this beforehand?

**Comment by islandblue** [comment]
Do we know for a fact that access to system site packages is restricted in this environment?

**Comment by nikohansen** [comment]
The tests are back to green, so I assume this was not the reason.
