### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by islandblue** [numbbo/coco#1519]
https://github.com/numbbo/coco/blob/4b1497a0e6d4de4a0dd75e03779d6c5349fa21ae/code-postprocessing/cocopp/compall/pprldmany.py#L567

`...for than...` >>> `...for more than...`

**Comment by brockho** [comment]
The error message is indeed strange. Since the statement is independent of the number of algorithms, I would personally go for `'We never integrate over dimension.'`.

**Comment by nikohansen** [comment]
The message looks a little strange but reflects the tested condition. I believe (86% confidence) the problem here is that we allow either to have different dimensions or to have different algorithms, but not both. When we have both, the above exception is raised.

**Comment by islandblue** [comment]
I'm correcting as I originally proposed. If we want to change the error message to what @brockho suggested, we can open another issue for that.
