### ISSUE TITLE
derivates to construct constraints

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#152]
In order to construct constrained problems in a controlled way, we would like the underlying objective functions to deliver their derivative. 

Proposal: a function like

```coco_get_derivative(coco_problem_t *problem, double *x, double *dx)```

or 

```coco_evaluate_derivative(coco_problem_t *problem, double *x, double *dx)```

is implemented which outputs in `dx` the derivate at point `x`. Each `f_...` file that implements the underlying function used with `coco_evaluate_function` also implements the underlying function used with `coco_evaluate_derivative`, in case it is to be used for a testbed with constraints.

**Comment by brockho** [comment]
This issue seems to be solved with the `development-constraints` branch, or am I wrong?

**Comment by phrsampaio** [comment]
Yes, it is solved there.
