### ISSUE TITLE
Usage of cocopp from the Python shell is broken in several ways

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1532]
The following problems (related to #1523) I see _from within a Python shell_ with the latest development branch 4c68f2f2. These errors happen when using an installed `cocopp` module (though in mysterious ways not always) and always when using the module directly sitting in the repository. None of this shows up in our CI, which also means that our test coverage is insufficient.

1. the calls `cocopp.main("--expensive " + ...)` and `cocopp.main("--runlength-based " + ...)` result in  
```
IOError: [Errno 2] No such file or directory: 'refalgs/best2009-bbob.tar.gz'
```
This error goes away if the latest change to `relative_load=False` in the call of `bestalg.load_reference_algorithm` in `pproc`, [L303](https://github.com/numbbo/coco/blob/4c68f2f26a642ae4b772b818351afe49a4da9b4e/code-postprocessing/cocopp/pproc.py#L303), is reverted (which however breaks the CI).

2.
```python
import os, cocopp
os.chdir('..')
cocopp.main(...)
```
results in
```
--> 466     for file_in_folder in os.listdir(js_folder):
    467         if file_in_folder.endswith(".js"):
    468             shutil.copy(os.path.join(js_folder, file_in_folder), output_dir)

OSError: [Errno 2] No such file or directory: '/Users/hansen/git/coco/cocopp/js'
```
This error also happens in the `master` branch 4b1497a0

I tried quite a few things and the most promising seemed to be using `os.path.dirname(os.path.realpath(os.sys.modules['cocopp'].__file__))`. However none of what I tried fixed _both_ the above errors _and_ the CI tests. [The `pkgutil` module](https://stackoverflow.com/questions/5897666/how-do-i-use-data-in-package-data-from-source-code) ~may be worth a try~ uses ``os.path.dirname(sys.modules[package].__file__)`` as well. 

I suggest that it may be helpful to have a unified way (a helper function) to identify the module path. Then, it may be the case that the tests are part of the problem and need to be changed too.

I suggest also to write a helper function which gives access to the test data which are distributed with the code (or downloaded). Like this, the tests don't need to bother getting the path right. We then also could write the above examples such that they actually work out of the box for everyone. For example, 
```python
import cocopp
cocopp.test_data_files()
["/Users/hansen/git/coco/code-postprocessing/cocopp/data/MCS.tgz", 
 "/Users/hansen/git/coco/code-postprocessing/cocopp/data/IPOP-CMA-ES.tgz"]
```
by default or whatever is there in a controlled way.

As a side remark the files `'data/IPOP-CMA-ES.tgz'` and `'data/MCS.tgz'` are given in the `setup.py.in` under `package_data` but are not in the repository itself.

**Comment by nikohansen** [comment]
My current favorite, which actually seems to give the absolute package path:
```python
def get_package_path():
    egginfo = pkg_resources.require('cocopp')[0]
    return os.path.join(egginfo.location, egginfo.project_name)
```
Alternatives for `egginfo.project_name` are `'cocopp'`, `sys.modules['cocopp'].__path__` and `egginfo._key` (which I guess is the key in the `sys.modules` `dict`).

**Comment by brockho** [comment]
Looks good to me. A quick test to replace the usage of `__file__` in the `copy_js_files` function of `ppfig.py` by the above `get_package_path(...)` solved the previous error during `python -m cocopp.test` both with and without the `cocopp` module being installed.

**Comment by nikohansen** [comment]
This suggests to assign a private attribute in `__init__`, where we use pkg_resources anyways: 
```python
_package_egginfo = pkg_resources.require('cocopp')[0]
_package_path = os.path.join(_package_egginfo.location, _package_egginfo.project_name)

# usage:
from . import _package_path  # or
from .. import _package_path  # depending on in which module we are
```

**Comment by ttusar** [comment]
This does not work from the command line as well.

**Comment by dtusar** [comment]
The errors should be fixed now.
