### ISSUE TITLE
Algorithm information (observer's option algorithm_info) is "cut" in python

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1534]
The `bbob-biobj` logger outputs `algorithm_info` (a string) to a comment in the `.info` files. If this variable contains multiple words (i.e. contains spaces), only the first word is output in the example experiment in python, while this works correctly in C and Java (I haven't checked for Matlab/Octave).  

In C and Java, the algorithm information containing multiple words is formatted as 
`"algorithm_info: \"A simple random search algorithm\""`. 

Changing 
`'algorithm_info': "A SIMPLE RANDOM SEARCH ALGORITHM"` to 
`'algorithm_info': "\"A SIMPLE RANDOM SEARCH ALGORITHM\""` in `example_experiment.py` didn't work.

Additional note: the `bbob` logger does not output `algorithm_info` anywhere.

**Comment by nikohansen** [comment]
In the single-objective case I only see that algorithm_name written to algId in the info file. 

Using the pythonic way: 'algorithm_name: "crazy name with lots of spaces" ' worked fine for me. It didn't work the other way around though, double quotations outside and single quotation inside.

Let me know whether this works for you. I will correct the strings given in the example experiment as examples.

**Comment by nikohansen** [comment]
Fixed with commit 54e6d1e2, please reopen if this didn't do the job.
