### ISSUE TITLE
Overlapping tick labels in pplogabs plots

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1550]
When running postprocessing on two algorithms, the `svg` plots look nice, but the `pdf` plots are "cut". Some examples:

![slika](https://user-images.githubusercontent.com/13745935/30326519-0f98941a-97c9-11e7-9e52-ee7063c930fd.png)

![slika](https://user-images.githubusercontent.com/13745935/30326534-200e687e-97c9-11e7-889d-0606f47de0f7.png)

These kinds of plots also have overlapping ticks:

![slika](https://user-images.githubusercontent.com/13745935/30326560-30fc1406-97c9-11e7-8e21-4c1706b54dea.png)

**Comment by ttusar** [comment]
After updating `matplotlib` the axis labels are fine, but the tick labels on this one should still be fixed:

![slika](https://user-images.githubusercontent.com/13745935/30329350-5599be90-97d2-11e7-894c-8ee46d32d9fb.png)

**Comment by nikohansen** [comment]
most likely to be fixed around line 50 in `comp2/pprldistr2.py`

**Comment by brockho** [comment]
I can reproduce the same problem with the x-axis tick labels (not on all graphs) when comparing DEMO and HMO-CMA-ES in the biobjective case.

**Comment by brockho** [comment]
I guess that this one will be solved together with #1939.

**Comment by brockho** [comment]
Solved now with the latest commit e6736962640db9200c2de21f5ee39a900d259e46.
