### ISSUE TITLE
The bbob-constrained suite is already a known suite

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1560]
as defined in `cocoex.known_suite_names`. Is this supposed to be in for the upcoming release?

**Comment by brockho** [comment]
One result of removing the suite will be that the tests are not running. But I can live with that until we decide to include the suite in one of the next releases.

**Comment by brockho** [comment]
Conclusion from today: remove it in `development`, then merge `development` to `devel-cons-v2` and then change it back in `devel-cons-v2`.

**Comment by nikohansen** [comment]
Done.
