### ISSUE TITLE
example experiment for beginners in python

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1561]
does not use `os.path.join` to open the results of `cocopp` in the browser. Does this yet work under windows?

**Comment by ttusar** [comment]
For me it works on Windows without problems.

**Comment by nikohansen** [comment]
OK, thanks, do you use Internet Explorer?

**Comment by ttusar** [comment]
No, Firefox.

**Comment by brockho** [comment]
FTR: it works like charm also for me (Windows 7 with Firefox).
