### ISSUE TITLE
Random search and constraints

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1574]
In the example experiment, the random search is always evaluating both `f` and `g` when it sees a constrained problem. However, it makes more sense that it actually does not call the objective function when a solution is infeasible.

This change is easy to do, but shall be done simultaneously in all languages, that COCO supports.

**Comment by nikohansen** [comment]
I will check the Python code.

**Comment by brockho** [comment]
Joint decision of today: close (due to above comment by Niko and the fact that the constraints evaluation is called in the example experiment for all supported languages).
