### ISSUE TITLE
y-axis labels wrong in scaling graphs

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1575]
The problem of wrong axis labels coming from the newest changes in matplotlib seems not only restricted to the scatter plots (see #1530): also in the scaling graphs, the y-labels do not look correct:

![image](https://user-images.githubusercontent.com/13706996/30699331-baa33514-9ee4-11e7-8ee6-b42b8dd58ec4.png)

**Comment by nikohansen** [comment]
Should be fixed with commit cf75eb622dc5100a11503c73bf9707f57f24722e, please test again.

**Comment by brockho** [comment]
Thanks @nikohansen, the y-axes in the plots look normal again now. I hence close the issue.
