### ISSUE TITLE
usage of module ntpath

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1577]
The module `ntpath` as used [here](https://github.com/numbbo/coco/blob/development/code-postprocessing/cocopp/findfiles.py#L19) is for "Common pathname manipulations, WindowsNT/95 version.", hence apparently not meant to be used as a cross platform module.

**Comment by brockho** [comment]
The code was there already for quite some time and I just copied it recently. I will take care of changing `ntpath.split` to `os.path.split` and will push it to `development` once the tests run through.

**Comment by brockho** [comment]
This issue is solved now via commit 4b12ce89f64c95dae43bfd0d7a7e9acce49465f4.
