### ISSUE TITLE
ascii encode error in running do.py -run-python

### ISSUE THREAD

**Issue by hplantec** [numbbo/coco#1581]
Trying to install cocoex with python 2.7 in anaconda environment:
```
conda create -n py27 python=2.7 anaconda
activate py27
```

Then I try to install cocoex by:
`(py27) **\coco-master>python do.py run-python`
which yields me the following error:
```
Traceback (most recent call last):
  File "example_experiment.py", line 42, in <module>
    import cocoex
  File "build\bdist.win-amd64\egg\cocoex\__init__.py", line 25, in <module>
  File "build\bdist.win-amd64\egg\cocoex\interface.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\cocoex\interface.py", line 6, in __bootstrap__

UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 11:
 ordinal not in range(128)
```
I am running under Windows 8, using the C compiler recommended by anaconda (Microsoft Visual C++ Compiler for Python 2.7).
I can't file the incriminated file (my folder 

> coco-master\code-experiments\build\python\build\bdist.win-amd64

 is empty), and even if I could, I don't think changing the problematic character really is the solution, is it?

**Comment by nikohansen** [comment]
Please try
```
python do.py run-python
```
instead.

**Comment by nikohansen** [comment]
Are you using the `master` branch?

**Comment by ttusar** [comment]
````
Traceback (most recent call last):
  File "example_experiment.py", line 42, in <module>
    import cocoex
  File "build\bdist.win-amd64\egg\cocex\__init__.py", line 25, in <module>
  File "build\bdist.win-amd64\egg\cocex\interface.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\cocex\interface.py", line 6, in __bootstrap

UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 11: ordinal not in range(128)
````

If this error message is copy-pasted correctly, I find it peculiar that the test tries to use a module named `cocex` instead of `cocoex`.

**Comment by hplantec** [comment]
My bad, I corrected the two typing mistakes by copy-pasting this time. So it's indeed `python do.py run-python` not `python do.py -run-python`, and 'cocex' not 'cocex'.
It's indeed the first installation, I tried before using python 3.4 (and obviously it failed), but I erased the whole code and redownloaded it before recompling with python 2.7. And I am using the master branch.

**Comment by nikohansen** [comment]
>  I tried before using python 3.4 (and obviously it failed)

The `cocoex` module should run under Python 3.4. If it doesn't I would consider this as a bug.

I do not use Windows, so I currently do not have any specific idea. You could try to ``git checkout development`` and run the `do.py` command again. Removing previous installations (which can be tricky in itself) has also been a way to solve strange issues in the past. Otherwise it might be related to the `C` compilation or possibly to `cython`, but I don't see how exactly.

I hope the Windows guys will have more or better ideas.

**Comment by brockho** [comment]
From the output, it is not immediately obvious where the problem comes from directly but the `u'\xeb'` in Hoël might be one reason: can it be that your path to the python installation folder has your name in it?

Trying to avoid this is always a good idea under Windows. (and other operating systems as well).

**Comment by hplantec** [comment]
That indeed seems like a good explanation. Though I tried on another partition of my disk (since I couldn't change the name of the folder, thank you windows...) and I still get the same error (restarting from the github code every time to avoid precompiled-link problems):

```
(py27) D:\Coco\coco-master>python do.py run-python
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.
c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c
', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/python/cyt
hon/coco.c
EXPAND  code-experiments/build/python/cython/coco.c.in to code-experiments/build
/python/cython/coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/python/cython/coco
.h
COPY    code-experiments/src/bbob2009_testcases.txt -> code-experiments/build/py
thon/bbob2009_testcases.txt
COPY    code-experiments/src/bbob2009_testcases2.txt -> code-experiments/build/p
ython/bbob2009_testcases2.txt
COPY    code-experiments/build/python/README.md -> code-experiments/build/python
/README.txt
EXPAND  code-experiments/build/python/setup.py.in to code-experiments/build/pyth
on/setup.py
PYTHON  setup.py install --user in code-experiments\build\python
PYTHON  example_experiment.py in code-experiments\build\python
ERROR: return value=1
Traceback (most recent call last):
  File "example_experiment.py", line 42, in <module>
    import cocoex
  File "build\bdist.win-amd64\egg\cocoex\__init__.py", line 25, in <module>
  File "build\bdist.win-amd64\egg\cocoex\interface.py", line 7, in <module>
  File "build\bdist.win-amd64\egg\cocoex\interface.py", line 6, in __bootstrap__

UnicodeEncodeError: 'ascii' codec can't encode character u'\xeb' in position 11:
 ordinal not in range(128)
```

**Comment by nikohansen** [comment]
I am just wondering where the `interface.py` file comes from, as the repository only has an `interface.pyx` file. I still reckon that the problem is in some way related with the `interface.c` file, either its creation or its compilation.

**Comment by brockho** [comment]
I have the feeling, the problem still lies in the path to where python wants to install the modules which is independent of where you start the `do.py run-python`. Can you try to set your `PYTHONPATH` to a folder where there are only ascii characters inside? Here is a link how to do it:

https://stackoverflow.com/questions/3701646/how-to-add-to-the-pythonpath-in-windows-7#4855685

**Comment by brockho** [comment]
@hplantec : Can we finally close the issue or does the problem still occur?

**Comment by hplantec** [comment]
I found the mistake. It was indeed a path folder problem. My anaconda virtual environment for python 2.7 was located in "Hoël/Documents/[...]", sorry it took me that long to figure this out. And thanks for your help!
