### ISSUE TITLE
open_archive helper function

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1585]
The `cocopp` module now has three data archive attributes

```
bbob
bbob_noisy
bbob_biobj
```
The question now is, whether we should have a helper function
```python
open_archive(...)
```
to open any (known) archive (possibly remote), which could also have been provided by anybody on the www. Assuming that each file in a folder structure represent a complete experiment (zipped `exdata/result_folder`), this should be comparatively simple to do.

**Comment by brockho** [comment]
The new functionality is really nice now. However, I detected some files in the output of `cocopp.bbob.find('')` that are not data sets, for example:
```
'2015-CEC/README'
'2015-GECCO/README.txt'
'2017/origin.txt'
```
I guess that we must take care of them kind of "by hand" or by only allowing `tgz`, `tar.gz` and `zip` files in the archive (=output of `find`).

**Comment by nikohansen** [comment]
We be fixed in the coming days.
