### ISSUE TITLE
overview page has become figureless

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1592]
When post-processing more than one algorithm like ``cocopp.main('ipop-cma ipop-sep smac');``, there is no figures in the root html page anymore. I believe there should be the six summary ECDF figures.

**Comment by dtusar** [comment]
Yes, we lost it with my latest changes of generating the `index` files. But it was only one ECDF figure not six.

**Comment by brockho** [comment]
Even if we never had these figures, it will be important to add them before the next release (all overview figures for all 6 dimensions).

@dtusar: can you let us know where we can find the code that produces the overall `index.html`?

**Comment by dtusar** [comment]
My last comment is not correct. The only figure in the `index` files was and still is in the one in the single algorithm `index` file. We never had figures there for many algorithms. 

Anyway, the `index` files are generated  in `ppfig.py`, function `save_folder_index_file`.

**Comment by brockho** [comment]
Can be closed as #1613 was merged to `development`.
