### ISSUE TITLE
default "focus" in ECDF figures and others

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1593]
When we enter in the browser, for example, `pprldmany.html` (ECDFs), we see (more or less only) the results for dimension 2. Unfortunately, dimension 2 is the most uninteresting result on the entire page, hence the "focus" or entry point puts emphasize where it really does not belong. I do think this is a relevant defect. However it is not immediately clear how this could be easily improved.

**Comment by dtusar** [comment]
What would you like to see when you open the page? The result of another dimension? Which one?

**Comment by nikohansen** [comment]
In the current suites, dimension 10 or 20 is fine. That would be different for the upcoming large-scale testbed.

**Comment by brockho** [comment]
With commit 66c8ae4da3350305ecf84fd11ee4e403afef001e, this is solved now (and the `goto-dimension` became part of the `Testbed` class).
