### ISSUE TITLE
options to rungeneric

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1595]
are defined in `genericsettings.longoptlist` and `.shortoptlist`. This seems to be an odd place, because there seems no way to change these settings without introducing all kind of bugs.

**Comment by brockho** [comment]
I agree. Since `main` of `rungeneric.py` will most likely become the sole entry point for the postprocessing (plus/minus some renaming) where these options play a role, it should go there from my viewpoint.

**Comment by nikohansen** [comment]
I can imagine that the user can or should play with settings in `cocopp.genericsetting` (also plus minus renaming) to adapt the desired behaviour, see e.g. https://github.com/numbbo/coco/issues/1370#issuecomment-332544746 with `cocopp.genericsettings.background`. But they should never change the above definitions of which options exist without changing the respective code.
