### ISSUE TITLE
bbob-new data_format type for best-algorithm data

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1604]
Am I suspecting correctly that we currently can not generate valid best algorithm data with constraints evaluation counts in them?

**Comment by brockho** [comment]
I also suspect that. Not even sure what to expect if we want to generate a reference algorithm from a collection of `bbob-old` and `bbob-new` formatted data sets.

**Comment by nikohansen** [comment]
The `bbob-new` format is 100% backwards compatible with the `bbob-old` format, so there shouldn't be any problem mixing them for unconstrained optimization. In particular, the post-processing may read in new-style format data with an old-style format routine and everything should be working fine.

**Comment by brockho** [comment]
Can be closed now that #1578 links to here.
