### ISSUE TITLE
Weighted sum of f- and g-evaluations: exposure to genericsettings

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1610]
As a follow up of #1367, we should have the weight (0.5 as default) used to sum up the f- and g-evaluations in the constrained case exposed to the user, e.g. into `genericsettings.py`.

**Comment by nikohansen** [comment]
I believe the default weight is supposed to be 1 for both. In any case, this is the value now set in the variable `genericsetting.weight_evaluations_constraints`.
