### ISSUE TITLE
superfluous warning?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1615]
```
Post-processing (1)
/usr/local/lib/python3.6/site-packages/cocopp-2.0.737-py3.6.egg/cocopp/pproc.py:1327: UserWarning: logger is an additional attribute.
warnings.warn('%s is an additional attribute.' % (attrname))
```
I assume `logger` is a new valid attribute and the warning is not valid?

**Comment by brockho** [comment]
Indeed, `logger` should be among the supported entries in the `.info` files. The latest commit to `development` addresses this. I'll close the issue accordingly.
