### ISSUE TITLE
extending archiving functionalities

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1618]
The idea is that we can exchanged created COCO data in a simple and smooth way. Tentative:
EDIT: this is largely outdated, see below.
```python
import cocopp
from cocopp.data_archives import open as open_da  # a better name is `get`
# if a module would allow to define `__call__`, we would alias `__call__` to `open`

bbob = open_da('bbob')  # returns COCOBBOBDataArchive instance
dsl = cocopp.load(open_da('bbob-biobj').get_first('cma'))  # load a data set list

another_da = open_da(local_or_remote_location)  # a folder name or URL

# that is, `open` accepts a known archive name or a folder name or an URL

definition_list = cocopp.data_archives.create(location, overwrite=False, definition_file=None)  # write definition list to `location`, if `location` is local
```
One way to implement this functionality is to place a definition file in or besides the root folder of an archive, thereby defining the archive as COCO data archive. (CAVEAT: as we can have (sub-)archives within an archive, definition files within the archive must be ignored while creating definition files).

If `open` does not find a definition file, it ask the user whether the file should be created (by calling `create`, this may take some time if the location is remote). Like this an archive can be used that does not have the definition file. Q: how to update this archive?

The simplest way to implement `create` for a remote location seems to download the entire archive and create the definition file from the downloaded data. Uploading the created definition file to the remote location "creates" the remote archive to be used with `open`.

`create` should check for a previous definition file and by default extend it with newly found entries given the other entries agree with the previous definitions. There must be an option to overwrite/delete old datasets (for quick online cycles). EDIT: or we have an `update` method to update previous definition files; this can be a method of the class instead of the module.

Whenever the archive changes (grows), not only the data must be added but also a new definition file would need to be created (and uploaded) to make the data visible. This seems to be a little tedious but also unavoidable as uploading usually requires login or superior access rights.

We could allow archives without definition files for quick and dirty access to somewhere uploaded data. Data in these could only be accessed by the exactly correct name and find would not work. For this we probably only need to slightly adapt the `get` method. Most other methods would naturally lead to an exception raised. EDIT: this is basically like create an archive with a single entry from a file instead of a folder.

**Comment by nikohansen** [comment]
Some part of this is now implemented in the `COCOUserDataArchive` class.

The main point is yet to be addressed, as It would still be a big asset to have an `open_da` function, which automatically creates the local path from the remote path and, depending on the user preference, overwrites outdated local data.

**Comment by nikohansen** [comment]
A quick current summary:
- `cocopp.data_archives.get(URL_or_folder_or_file)` (formerly `open`) downloads, if necessary,
  - a definition file, or
  - a single data file and creates a single-entry data archive (under single-data-archives, asks to overwrite if already exist), or
  - a full folder content (asks before to download) and creates a definition file 
  
  and returns the data archive.
- `cocopp.data_archives.create(folder, ...)` creates a definition file in folder according to the data in folder.
- `cocopp.COCODataArchive.update()` updates the definition file of `self`
  - from a remote definition file (and may delete out- or updated data) or
  - from local data.

**Comment by brockho** [comment]
@nikohansen: where do I find the corresponding code? It is not (yet) in the `development` branch.

**Comment by nikohansen** [comment]
The above is interface specification. I have a WIP branch where I implemented some of it. Out of my head I don't know the status in terms of functionality.

**Comment by brockho** [comment]
Thanks for the clarification. The text suggested (in my head at least) that things were already implemented. Otherwise, the planned functionality looks good to me.

**Comment by nikohansen** [comment]
I pushed the WIP to the `dev-archiv` branch. It implements the above ticked bullet points. I did very sparse testing, so I am happy for any alpha-testing and will try to fix any problem ASAP.

**Comment by nikohansen** [comment]
See also issue #1878
