### ISSUE TITLE
Maintaining links to postprocessed data

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1624]
We should provide links to existing postprocessed data that we have lying around here and there. A first list would be
* [entire BBOB 2017 data (`bbob`)](http://coco.gforge.inria.fr/presentation-archive/2017-GECCO/ppdata-bbob2017/)
* [entire BBOB 2017 data (`bbob-biobj`) ](http://coco.gforge.inria.fr/presentation-archive/2017-GECCO/ppdata_bbobbiobj2017/)
* http://coco.gforge.inria.fr/presentation-archive/2017-MascotNum/ppdata-bbob-expensive/
* http://coco.gforge.inria.fr/presentation-archive/2017-MascotNum/ppdata-biobj/
* http://coco.gforge.inria.fr/presentation-archive/2017-SSBSE/ppdata-biobj-all/
* http://coco.gforge.inria.fr/presentation-archive/2017-SSBSE/ppdata-biobj-expensive/

The question remains where to keep this list...

**Comment by brockho** [comment]
Opening/starting the wiki for this reason seems to be one option.

**Comment by nikohansen** [comment]
I added 

* http://coco.gforge.inria.fr/ppdata
* http://coco.gforge.inria.fr/ppdata-archive

as a volatile (`ppdata`) and a less volatile (`ppdata-archive`) place to make post-processed data available.

**Comment by brockho** [comment]
Thanks @nikohansen, I will then try in the next days to finally work on #1372 and put the data to http://coco.gforge.inria.fr/ppdata-archive

**Comment by nikohansen** [comment]
As I was just starting to process data, I also uploaded already quite some. So it seems that #1372 can be considered as addressed.

**Comment by brockho** [comment]
What about the noisy and biobjective data? I can take care of them if you wish (we can discuss this tomorrow also).

**Comment by nikohansen** [comment]
I copied the links [here](https://github.com/numbbo/coco/wiki)

**Comment by brockho** [comment]
Thanks @nikohansen. Now it's time to fill the wiki with additional content :-)

**Comment by brockho** [comment]
I guess that this issue could have been closed for some time now. Any objection to finally do so?
