### ISSUE TITLE
color of background algorithms

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1631]
For keyword `None` a light grey default color should be provided.

Ideally, the interface shouldn't need a value to be passed at all to come up with a default color and linestyle.

**Comment by brockho** [comment]
Since we don't have a default color at the moment, we should rather discuss how to implement this.

**Comment by nikohansen** [comment]
I found `color=3 * [0.9]` to be a pretty good light gray background color, see e.g. http://coco.gforge.inria.fr/ppdata/sel-bbob-2009/

**Comment by nikohansen** [comment]
```python
background_alg_list = cocopp.bbob.get_all("")
cocopp.genericsettings.background = {None: background_alg_list}
```
should work now, where `None` invokes default color and line style.
