### ISSUE TITLE
optimal f-values in the constrained suite

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1637]
The function `bbob-constrained_f07_i03_d03`, for example, has an optimal f-value larger than `1e7`.  This seems to be numerically incompatible with our standard choice of target precisions going down to `1e-8`. That is, the disagreement between the mathematical model and the numerical model becomes relevant, which is a rather undesirable situation.

The preferable solution would be to change the function definition. Offsetting the function value is probably the simplest solution, but it has to be carefully reviewed for loss of precision. Scaling down the function value is another alternative.

**Comment by nikohansen** [comment]
The distribution of `fopt`-values on `bbob-constrained`:
<img width="323" alt="screen shot 2017-10-22 at 14 40 03" src="https://user-images.githubusercontent.com/7316439/31863056-709fa55c-b748-11e7-97fa-fd0e3d9fc3e6.png">
Due to the construction, the minimal `fopt` values are close to -1000.

Scaling down the functions such that `fopt` values before adding the offset are not much larger than 1000 seems advisable.

**Comment by nikohansen** [comment]
We may apply the following transformation:
```
f_opt_raw = f(x_opt)
f(x) -> f(x) / f_opt_raw^0.65 - f_opt_raw^0.35 +  f_bbob2009_compute_fopt(...)
```
with `f_bbob2009_compute_fopt(...)` in [-1000,1000].

**Comment by asmaatamna** [comment]
After implementing the transformation above (changes in ```devel-asma```), the ECDFs of optimal function values are shown in figure below:
![ecdf_fopt_bbob-constrained](https://user-images.githubusercontent.com/14993138/34569834-416adc6e-f16a-11e7-82d2-910016d9f3ef.png)

The ```iPython notebook``` for plotting the ECDFs is available here: [https://drive.google.com/file/d/1xnJzkBAMamD0M-vAa7mxwUY2D1IR50MK/view?usp=sharing](url)
