### ISSUE TITLE
the master branch has become unusable with the latest version of matplotlib

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1638]
see #1636 and https://github.com/numbbo/coco/issues/1481#issuecomment-336171594

**Comment by nikohansen** [comment]
As a fix we may cherrypick the change of commit 7692121decc55f49afa1a1e95d10d9237d901e49 into the master branch.

**Comment by nikohansen** [comment]
I did the cherrypick, but due to our testing logic it seems difficult to push changes to the master branch.

**Comment by brockho** [comment]
It seems that our previous proposal of having a release branch wasn't the worst of all ideas. The master branch should then be protected in a way that tests on this release branch need to pass before the merge and not anymore from development. This will allow the two use cases of quick fixes in the master and larger releases from development. Or am I wrong?

**Comment by nikohansen** [comment]
> It seems that our previous proposal of having a release branch wasn't the worst of all ideas. 

Exactly what I was thinking.

>  This will allow the two use cases of quick fixes in the master and larger releases from development.

I don't think that is yet the ideal solution. I don't want to hurry a release, just because it is "impossible" to push a small fix to the master.

Protecting the master by a test on one or several of the test branches should do the trick either AFAICS.

**Comment by brockho** [comment]
We implemented now the last suggestion of @nikohansen above (protecting the master via `devel-test1` and `test-nightly`. The issue can thus be closed.
