### ISSUE TITLE
comparing each algorithm on the same plot

### ISSUE THREAD

**Issue by 7belrhalmia** [numbbo/coco#1640]
Hello, I want to result to be showing like that where comparing each algorithm on the same plot :

![image](https://user-images.githubusercontent.com/13202562/31862593-c7592c40-b740-11e7-95bc-cb62e797e625.png)

can you give me please the command to do that?

**Comment by brockho** [comment]
```
python -m cocopp NSGA-II.tgz RandomSearch.tgz IBEAe_something.tgz IBEAe_somethingelse.tgz`
```
should do the trick (using the corresponding correct four data sets you want).

**Comment by nikohansen** [comment]
@7belrhalmia, I assume the attempted fix of #1636 worked out for you?

**Comment by brockho** [comment]
@7belrhalmia, can we finally close this issue?

**Comment by 7belrhalmia** [comment]
@brockho  and @nikohansen  Thanks a lot.
