### ISSUE TITLE
text in scaling graphs

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1643]
The scaling graps like [here](http://coco.gforge.inria.fr/ppdata/sel-bbob-2009/ppfigs.html) still list the number of instances of _all_ processed data, instead of writing only the sorted set as the ECDFs [here](http://coco.gforge.inria.fr/ppdata/sel-bbob-2009/pprldmany.html).

**Comment by brockho** [comment]
Yes, clearly a bug. Thanks for detecting this.

**Comment by brockho** [comment]
Addressed with pull request #1649 - hence, can be closed as soon as the merge is done.
