### ISSUE TITLE
Appveyor problem with too long file names?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1651]
Since a few builds, our Appveyor bails out already during cloning the repository. A quick google search gave that it might be related to too long file names under Windows:
```
error: unable to create file code-postprocessing/cocopp/tth/tth (File exists)
Command exited with code 1
```

 I am not aware of any change with this respect. @islandblue: can it be related to the restructuring of the `appveyor.yml` file that now the paths are too long?

**Comment by islandblue** [comment]
@brockho: Just to be clear, I edited the config.yml file for circleci, not the appveyor.yml file. Or did you want me to look into it?

**Comment by brockho** [comment]
Not clear at all to me what caused the problem, but the latest tests run through again.

**Comment by nikohansen** [comment]
The behavior seems rather random. The same commit may fail or succeed:
<img width="960" alt="screen shot 2017-10-26 at 23 12 18" src="https://user-images.githubusercontent.com/7316439/32077364-7451c910-baa3-11e7-857c-a11c33de3318.png">

**Comment by brockho** [comment]
Strange, the very same builds both look green for me right now:
![image](https://user-images.githubusercontent.com/13706996/32077661-7cf483cc-baa4-11e7-8242-4cb34b20fce8.png)

**Comment by islandblue** [comment]
Something's wrong with the interface. They may not be the same builds. Look at the version numbers. First mail has 1.0.615 and 1.0.616, second mail has 1.0.614 and 1.0.615. May be a bug.
