### ISSUE TITLE
rawdata summary archive

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1652]
The folder http://coco.gforge.inria.fr/data-archive/bbob/2013/ has a `BBOB2013rawdata.tgz` entry, which I assume is there by mistake? 

FTR, I would be in favor to not delete any `.txt` files which serve for documentation. The archive definition file creator just can ignore those.

**Comment by brockho** [comment]
No, the file is not there by mistake. It contains all single algorithm data sets from that year for easier download. But with the new functionality of automated downloads via `cocopp.data_archive` that's definitely not needed anymore.

**Comment by nikohansen** [comment]
That's what I meant when writing "by mistake", assuming that the archive was meant to be cleaned up at this point in time (which I am not exactly sure of).

**Comment by brockho** [comment]
The data-archives on the GForge server are now cleaned-up, i.e. there should not be any zip/tar.gz/tgz files lounging around that are not official data files. All text files in the data-archive folders have been checked and updated when needed.

I therefore consider the issue closed.
