### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by islandblue** [numbbo/coco#1655]
I think this is a syntax error.

https://github.com/numbbo/coco/blob/a7a6ed67012e65772be31e64395800eaded3e119/code-postprocessing/cocopp/pproc.py#L1800

Also, the fact that is doesn't come up might suggest insufficient test coverage.

**Comment by nikohansen** [comment]
I see a type error rather than a syntax error. That's a very common bug, happening to me all the time, and here indeed indicating that this code was never reached.

**Comment by dtusar** [comment]
We currently don't have tests that cover irregular data.
