### ISSUE TITLE
Test suites where some problems are not available in all dimensions

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1656]
If we want to provide some truly real-world problems at some point, we must be able to take care of test suites in the postprocessing which are not necessarily available in all dimensions for all problems---an assumption that we currently have build into the postprocessing code. When we rewrite the postprocessing, we should therefore clearly take care of this.

**Comment by nikohansen** [comment]
See #1654

**Comment by islandblue** [comment]
This is now issue 1 in ADT-COCOpost project in Gitlab.
