### ISSUE TITLE
Algorithm names in tables wrong

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1658]
Sometimes, when postprocessing many algorithms, the algorithm names get messed up in the LaTeX tables:

![image](https://user-images.githubusercontent.com/13706996/32553762-0de01b1a-c498-11e7-98ef-47fa7bdd91ff.png)

but I doubt that it comes from wrong algorithm name expansions (I used a call like `python -m cocopp -o ppdata-bbob-5 bbob/2009/BIPOP! bbob/2010/IPOP! bbob/2013/lmm! bbob/2009/bfgs! NEWUOA!`), because in the figures, the algorithm names are displayed correctly:

![image](https://user-images.githubusercontent.com/13706996/32553797-22b241e4-c498-11e7-87bb-aa0318f55288.png)

Looks like the problem is with the `FULLNEWUOA` data set, but by hand, I cannot see something wrong with it (it has for example the right algorithm id in the `.info` files I looked at).

**Comment by nikohansen** [comment]
Could the reason be that the name `FULLNEW` takes more horizontal space than any of the other names?

**Comment by brockho** [comment]
Should be solved with the latest pull request #1678 now.
