### ISSUE TITLE
x-limits in plots to be exposed

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1662]
The x-limits for the ECDF plots are hard-coded to `1e7` for the moment. It should not be too difficult to expose `cocopp.compall.pprldmany.x_limit` to `cocopp.genericsettings` as it is done already for the expensive setting. Note that the already available `cocopp.genericsettings.maxevals_fix_display` has no effect in the non-expensive setting.

**Comment by girotomas** [comment]
I think this issue was solved here https://github.com/numbbo/coco/pull/2045

**Comment by brockho** [comment]
Indeed, the error was not coming from the actual change: the latest commit to the development branch, including the fix for this issue, passes all tests. Hence, we should close this issue.
