### ISSUE TITLE
Estimate feasible volume around bbob-constrained optima

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1665]
It will be important to have a script which estimates the percentage of feasible volume over infeasible volume
* around the optima
* in the whole search space (let us say `[-5...5]^n`)

of the `bbob-constrained` test suite. On the one hand for better understanding about what is going on, on the other hand for testing/finding potential bugs.

Producing the numbers is simple but visualizing is not as simple (heat maps? ECDFs of all values?).

**Comment by paulduf** [comment]
This one is closed as already mentioned in #1469.
