### ISSUE TITLE
Constrained Different Powers simpler than expected

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1666]
Looking at results from the preliminary `bbob-constrained` suite, we realized today with @asmaatamna and @nikohansen that the Different Powers problems are probably too simple (at least simpler than in the unconstrained case). The reason is that the constrained optimum lies typically in a too far distance to the unconstrained optimum such that the conditioning, an algorithm has to cope with, is rather low.

To improve on this, we should use a smaller shift/translation in the construction to choose the new optimum closer to the original one (rather in the order of `1e-5` than a fully random shift).

**Comment by asmaatamna** [comment]
@nikohansen 's suggestion: a possible way to decide what value to choose: run CMA-ES on the function and see what the condition number is for a given distance to the optimum.

**Comment by asmaatamna** [comment]
For the moment, the constrained optimum is generated such that its distance from the unconstrained optimum is ```1e-5``` (code in ```devel-asma```). The link below provides a ```jupyter notebook``` that runs cma on the bbob (unconstrained) different powers (for a given dimension/instance).

[https://drive.google.com/open?id=1rxSr3XLJDWHoby0XdHiJ7g-F3RG8PVQn](url)

**Comment by brockho** [comment]
Do I interpret it correctly from the plots, that the condition number around the constrained optimum will be about `1e6` if we choose a distance of around `1e-5`?

**Comment by asmaatamna** [comment]
@brockho yes.

**Comment by nikohansen** [comment]
Where can I see the distance to the optimum in the plots?

**Comment by asmaatamna** [comment]
@nikohansen sorry I didn't understand your question correctly. You can see the the difference between ```f``` and ```fopt``` on the usual ```cma``` ```f``` graphs (the algorithm is run on the "normalized" different powers). I didn't plot the distance to the optimum...

**Comment by asmaatamna** [comment]
Upon looking at some graphs in ```5D```, it looks like a shift of ```1e-2``` is already sufficient (we may want to test other dimensions/instances however).

**Comment by brockho** [comment]
Unfortunately, I cannot remember what was our reasoning on Jan 23 that 1e-2 as distance is already sufficient. Did we check this in other dimensions than 5? When I run the Jupyter notebook above in 40-D, I get the following:
![40d](https://user-images.githubusercontent.com/13706996/37203051-b6fd1f42-238c-11e8-9348-f004b1124333.png)

Where exactly do I see the 1e-2 now? And, again, why did we change this from 1e-5?

**Comment by asmaatamna** [comment]
We do not see the distance to the optimum on these graphs. So last time, @nikohansen added it to the plots above. I cannot remember whether the code was run on other dimensions than 5. But I remember that from what we observed, the condition number for 1e-2 was already high enough (not sure but maybe around 1e4?).

I can prepare some graphs (I believe it should be easy to add the graphs of the distance to the optimum but I have to remember how Niko did it last time).

**Comment by nikohansen** [comment]
The `CMAEvolutionStrategy.more_to_write.append` method comes handy for this purpose.
