### ISSUE TITLE
Error re: `GLIBC_2.14' in cocoex module

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1667]
With a fresh Anaconda installation on one of our compute servers (`porte-pouchet`, python 2.7.14, cython 0.27.3), I do not get, unfortunately, the `cocoex` installation to work (note that the default python version is 2.6 on this machine which is why I installed Anaconda on top). The installation goes through via ` /home/dimo.brockhoff/anaconda2/bin/python do.py build-python` without displaying any error but I get the following message once I try to import the module:

```
Traceback (most recent call last):
  File "example_experiment_platypus.py", line 2, in <module>
    import cocoex    # experimentation module
  File "/home/dimo.brockhoff/.local/lib/python2.7/site-packages/cocoex-2.0.694-py2.7-linux-x86_64.egg/cocoex/__init__.py", line 25, in <module>
    from . import interface as _interface
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/dimo.brockhoff/.local/lib/python2.7/site-packages/cocoex-2.0.694-py2.7-linux-x86_64.egg/cocoex/interface.so)
```

**Comment by nikohansen** [comment]
This https://github.com/kundajelab/atac_dnase_pipelines/issues/33 may help to find a solution.

**Comment by brockho** [comment]
Finally, `conda install -c asmeurer glibc` went through, although first trying `conda uninstall glibc` gave
```
Fetching package metadata ...........
Solving package specifications: .

PackageNotFoundError: Package(s) is missing from the environment:
            [u'glibc
```
and quite some packages had to be downgraded:
```
The following NEW packages will be INSTALLED:

    glibc:       2.19-0                asmeurer

The following packages will be UPDATED:

    anaconda:    5.0.1-py27hd9359a7_1           --> custom-py27h4a00acb_0

The following packages will be SUPERSEDED by a higher-priority channel:

    conda:       4.3.30-py27h6ae6dc7_0          --> 3.2.0a1-py27_0        asmeurer

The following packages will be DOWNGRADED:

    conda-build: 3.0.27-py27hff9f855_0          --> 1.20.3-py27_0
    pycosat:     0.6.2-py27h1cf261c_1           --> 0.6.0-py27_0
    pyyaml:      3.12-py27h2d70dd7_1            --> 3.10-py27_0
    yaml:        0.1.7-h96e3832_1               --> 0.1.4-0
```

Unfortunately, running COCO now gives me a segmentation fault without any other error message whatsoever:
```
dimo.brockhoff@porte-pouchet:/MYPATH/platypus/NSGA-II-experiments$ /home/dimo.brockhoff/anaconda2/bin/python example_experiment_platypus-NSGA-II.py
Segmentation fault
dimo.brockhoff@porte-pouchet:/MYPATH/platypus/NSGA-II-experiments$
```

**Comment by brockho** [comment]
Neither `python` nor `conda` works anymore, BTW.

**Comment by nikohansen** [comment]
This has been fixed?

**Comment by brockho** [comment]
I suggest to close this issue after we haven't seen this problem for a while. I just checked today: the `porte-pouchet` machine has been updated to python 3.7.4 in the meantime and everything runs smoothly there (with the `cocoex` module installed from the current development branch).
