### ISSUE TITLE
Check whether cross in ECDFs are correctly documented

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1669]
In the constrained case, we have seen already some wrong captions due to the fact that some markers are based on the total number of f-evaluations only (even in the constrained case, see commit constrained). We should check that everything is correct also for the ECDF plots.

**Comment by asmaatamna** [comment]
After checking the postprocessing code where the captions are produced, everything looks fine for me. I still need to check whether everything is fine when more than one algorithm is postprocessed

**Comment by asmaatamna** [comment]
After looking at the graphs from 2 algorithms (fmincon run with 2 different versions of the code), some captions weren't displaying latex code correctly (see #1714). The markers however are documented correctly in the captions. Therefore, this issue can be closed.
