### ISSUE TITLE
Best_parameter not updated for rotated Rosenbrock

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1672]
As the title says: the `best_parameter` value for the rotated Rosenbrock function is still wrong, because it is not updated correctly in the construction of the problem (in `transform_vars_affine`, see #1125). I always get `1^n` as the best parameter (@asmaatamna confirmed this).

This becomes now problematic with the new `bbob-biobj-ext` suite where the rotated Rosenbrock function is used. We see this already in the new plots where the extreme is mis-calculated by the pre-processing (single black point outside the ROI; bottom right in the plot):

![directions-f69-i01-d05-objspace](https://user-images.githubusercontent.com/13706996/33213415-c6368064-d127-11e7-9ba0-b8c96d821d3b.png)

**Comment by asmaatamna** [comment]
I also believe that what is currently done in ```transform_vars_affine.c```, line ```190``` is not correct. It should update ```problem->best_parameter``` instead of ```inner_problem->best_parameter```. For ```inner_problem->best_parameter```, the correct value is ```(1, ..., 1)```.

**Comment by asmaatamna** [comment]
After discussing with @brockho  and @nikohansen : the changes still need to be tested by adding the right test in ```coco/code-experiments/test/regression-test/test_suites.py``` (i.e. compare ```best_parameter``` in the old and the new code for some(?) functions)

**Comment by brockho** [comment]
The issue with the rotated Rosenbrock function is solved now, except for the mentioned test. However, we still have the same issue with the Katsuura function, see #1695.
