### ISSUE TITLE
Jenkins is not triggered

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1685]
when I push to any of the test branches. EDIT: Same when I push to the development branch.

**Comment by dtusar** [comment]
I changed a settings in Jenkins and now the tests should be triggered. I will leave this issue open until you confirm that it works also for you.

**Comment by brockho** [comment]
Things work again now after the change in the Jenkins settings, @dtusar did ("SCMPolling set to 10"), such that we decided today to close the issue.
