### ISSUE TITLE
Plot issue in BBOB postprocessing

### ISSUE THREAD

**Issue by lberti** [numbbo/coco#1691]
After post-processing the data in the sphere function case I get the first plot. Also the other pdf files seem to have few problems, for instance partially cut titles.

[ppfigdim_f001.pdf](https://github.com/numbbo/coco/files/1583524/ppfigdim_f001.pdf)
[ppfigdim_f006.pdf](https://github.com/numbbo/coco/files/1583538/ppfigdim_f006.pdf)

**Comment by brockho** [comment]
Dear @lberti, thanks for reporting the issue. It is very likely the known issue of an outdated `matplotlib` version, see issue #1335 and [here](https://github.com/matplotlib/matplotlib/issues/7937). If you upgrade your `matplotlib` to a version >= v2.0.1, this problem will most likely be solved.

**Comment by brockho** [comment]
Decision of today's meeting: close the issue because it has been already addressed earlier.
