### ISSUE TITLE
cocoex module has no __version__

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1702]
Contrary to the `cocopp` and `cocoprep` modules, the `cocoex` module does not have an accessible `__version__` attribute. In order to check which version is installed, the presence of such an attribute will be much more convenient than trying to uninstall the module via `pip uninstall cocoex` and then looking at the print out (which is what I can do right now). Low priority issue though.

**Comment by nikohansen** [comment]
For `cocopp` it is done like:
```python
import pkg_resources
__version__ = pkg_resources.require('cocopp')[0].version
```
in the module `__init__.py` file.

**Comment by brockho** [comment]
Implemented with latest commit.
