### ISSUE TITLE
Doctests failing due to formatting differences

### ISSUE THREAD

**Issue by islandblue** [numbbo/coco#1703]
I'm getting several doctest failures of the following sort:

Failed example:
    dslist2[2].evals[-1]
Expected:
    array([  1.00000000e-08,   2.14200000e+03,   1.95800000e+03,
             2.31700000e+03,   2.32400000e+03,   2.30500000e+03,
             2.20700000e+03])
Got:
    array([1.000e-08, 2.142e+03, 1.958e+03, 2.317e+03, 2.324e+03, 2.305e+03,
           2.207e+03])

Judging from the fact that these doctests worked until recently, my guess is that numpy went and decided to change the way it prints its arrays out. It's annoying to have tests break down due to such external, random and trivial changes. For this specific problem type, one solution is to not rely on the exact formatting done by the class itself but always compare against the output of strictly formatted print statements. Another might be to drop text comparison altogether and use assert statements. Both solutions make it slightly more tedious to write doctests, but I guess it's better than having to rewrite them every which update of dependencies.

**Comment by brockho** [comment]
We discussed this already a while ago but did not open an issue. I will have a look at it right now in order to be able to do the next release soon.

**Comment by brockho** [comment]
This issue is solved now with the pull-request #1704.
