### ISSUE TITLE
Problems with Table Layout

### ISSUE THREAD

**Issue by mudita11** [numbbo/coco#1712]
Hi!
Tables generated are not structured properly. I got following .tex file after post-processing for function 24 (noiseless continuous suite):

\providecommand{\ntables}{7}\providecommand{\algAtables}{\StrLeft{B-PM-SR(D)}{\ntables}}\providecommand{\algBtables}{\StrLeft{B-PM-SR(I)}{\ntables}}\providecommand{\algCtables}{\StrLeft{B-PM-SR(I1)}{\ntables}}
\begin{tabularx}{1.0\textwidth}{@{}c@{}|*{7}{@{}r@{}X@{}}|@{}r@{}@{}l@{}}
$\Delta f_\mathrm{opt}$ & \multicolumn{2}{@{\,}l@{\,}}{1e1} & \multicolumn{2}{@{\,}l@{\,}}{1e0} & \multicolumn{2}{@{\,}l@{\,}}{1e-1} & \multicolumn{2}{@{\,}l@{\,}}{1e-2} & \multicolumn{2}{@{\,}l@{\,}}{1e-3} & \multicolumn{2}{@{\,}l@{\,}}{1e-5} & \multicolumn{2}{@{\,}l@{\,}}{1e-7} & \multicolumn{2}{|@{}l@{}}{\#succ}\\\hline
\textbf{f24} & \multicolumn{2}{@{}c@{}}{1.3e6 \quad} & \multicolumn{2}{@{}c@{}}{7.5e6 \quad} & \multicolumn{2}{@{}c@{}}{5.2e7 \quad} & \multicolumn{2}{@{}c@{}}{5.2e7 \quad} & \multicolumn{2}{@{}c@{}}{5.2e7 \quad} & \multicolumn{2}{@{}c@{}}{5.2e7 \quad} & \multicolumn{2}{@{}c@{}|}{5.2e7} & 3 & /15\\
\algAtables\hspace*{\fill} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}|}{$\infty$\,\textit{2e6}} & 0 & /15\\
\algBtables\hspace*{\fill} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}|}{$\infty$\,\textit{2e6}} & 0 & /15\\
\algCtables\hspace*{\fill} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}}{\textbf{$\infty$}} & \multicolumn{2}{@{\,}l@{\,}|}{$\infty$\,\textit{2e6}} & 0 & /15
\end{tabularx}

and it generated following table:

[Presentation1.pdf](https://github.com/numbbo/coco/files/1709112/Presentation1.pdf)

I am happy to give more details regarding this (if needed). It would be helpful if this bug is resolved as soon as possible because of a paper deadline. 
You can contact me at ms1938@york.ac.uk. Hope to hear soon from you.
thank you.

**Comment by dtusar** [comment]
Dear @mudita11, thank you for the error report.

This is a bug in the `master` branch which was already fixed in the `development` branch. We will soon have a new release but for the time being please consider using the `development` branch. If this is still a problem in the `development` branch, please let us know.

**Comment by mudita11** [comment]
Hi!
Thank you for your reply. I used development branch but the table is still the same It is still broken.

**Comment by dtusar** [comment]
Thank you for the data. I replaced my data for f24 with yours and for me the table is not broken (see below):
![pptables](https://user-images.githubusercontent.com/13744819/36209922-66de5540-119d-11e8-8c1b-4257545daf69.PNG)

I also noticed that the horizontal lines in the table in your example (pdf file) are not at the same place as in my output. Not sure what output did you get when using the development branch.

**Comment by brockho** [comment]
It looks to me that the issue can be closed. In case that this is not the case, we are happy to reopen it but we would need a bit more information about when this happens then (which version of the code is used? which branch? which python version?).
