### ISSUE TITLE
Understanding of the bbob-constrained functions/constraints

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1717]
Looking at the latest plots, for example this one here:

[contours_f19_1_constraints.pdf](https://github.com/numbbo/coco/files/1744617/contours_f19_1_constraints.pdf)

it is not clear anymore to me how the problems are constructed. I had in mind that the non-linear transformations on the constraints are somehow independent from the underlying objective function. In other words, why do we see (nearly?) the same transformations on the level sets of `f` and of `g` in the above linked figure.

**Comment by anneauger** [comment]
What we have written in the current documentation (or paper draft) says that the same search space transformation is applied to $f$ and $g_i$ [the baseline problems]. Yet according to the plots, it does not fit what is implemented.

One question is whether what is implemented guarantee that we know the global optimum (as the current proof uses that the same bijective transformation is applied to $f$ and $g_i$)

**Comment by asmaatamna** [comment]
I just checked the code and the documentation Phillip wrote and they seem to agree. What we saw yesterday for the separable ellipsoid in the paper draft was a typo of mine: I forgot to add Tosz in the problem definition (section 4.3). However, it's still not clear to me why the objective function and the first constraint don't seem affected by this transformation - see figure below for example. Working on this.

[contours_f8_2_constraints.pdf](https://github.com/numbbo/coco/files/1747326/contours_f8_2_constraints.pdf)

**Comment by asmaatamna** [comment]
Regarding constrained ellipsoid problems where the objective function and one constraint seem unaffected by the nonlinear transformation: when scaling the plots differently, one can see the transformation, for example by setting the x-axis limits to -5e3 and 5e3 instead of -5 and 5, or to -5e6 and 5e6 to see the transformed constraint.

**Comment by brockho** [comment]
Could you please add the plot you talk about here, @asmaatamna? It will be easier to discuss (and I do not need to find and dig into the code).

**Comment by asmaatamna** [comment]
Here are the graphs I had in mind in my previous comment:

[contours_f8_2_constraints_x_axis_5e3.pdf](https://github.com/numbbo/coco/files/1752622/contours_f8_2_constraints_x_axis_5e3.pdf)

[contours_f8_2_constraints_x_axis_5e6.pdf](https://github.com/numbbo/coco/files/1752623/contours_f8_2_constraints_x_axis_5e6.pdf)

**Comment by brockho** [comment]
I am not sure that I understand exactly what we see: are both plots for the same function, dimension (?), and instance as the title suggests? It does not look like, so I am curious to understand.

When you say that we can "see the transformed constraint", I would add that the transformation is *not* visible for the first constraint, or am I wrong?

**Comment by nikohansen** [comment]
If I am not mistaken, the non-linear search space transformations are done coordinate-wise. That is, if I am not mistaken, for axis-parallel lines these search space transformations have no effect on the (linear) shape of the line.

**Comment by brockho** [comment]
After discussing once more all together, we decided that things look correct in documentation and code and that thus the issue can be closed.
