### ISSUE TITLE
Constraints for DiffPowers functions wrong?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1718]
...or do I have a wrong intuition about the function. Looking at other functions, the first constrained is more or less aligned to the level sets of `f` as expected, see for example here:

[contours_f25_1_constraints.pdf](https://github.com/numbbo/coco/files/1744679/contours_f25_1_constraints.pdf)

For the different powers function, however, the first constraint looks perpendicular to the global level sets:

[contours_f37_1_constraints.pdf](https://github.com/numbbo/coco/files/1744680/contours_f37_1_constraints.pdf)

Where is my intuition wrong? Or is there a bug?

**Comment by asmaatamna** [comment]
Here's what I get when I zoom in on the different powers with 1 constraint:

[contours_f37_1_constraints_zoom_in.pdf](https://github.com/numbbo/coco/files/1784204/contours_f37_1_constraints_zoom_in.pdf)

Depending on the axes scaling -- and as we already expected from last week's discussion -- the constraint may look perpendicular while it's not.
