### ISSUE TITLE
49 targets

### ISSUE THREAD

**Issue by mudita11** [numbbo/coco#1723]
Will it be correct to compare an algorithm from a paper that used different number of targets say 50 targets with the one that uses 51 targets? 
If not how can these graphs be compared, probably I can use on my algorithm the coco version that the former algorithm used? 
I have attached a paper with 50 targets in bootstrapped ECDFs:
(https://www.researchgate.net/profile/Mikhail_Zhabitsky/publication/262345508_Asynchronous_differential_evolution_with_adaptive_correlation_matrix/links/5600fe4208aeafc8ac8c7cec/Asynchronous-differential-evolution-with-adaptive-correlation-matrix.pdf)

**Comment by nikohansen** [comment]
A small difference in the _number_ of targets should have no impact on the result, as long as the target range is the same.
