### ISSUE TITLE
Improving font scaling in the legends of comparison plots

### ISSUE THREAD

**Issue by islandblue** [numbbo/coco#1731]
The fontsize of legend labels scales with the number of legend entries, but it becomes very small, very fast. Consequently, around 10-15 entries, half of the legend area is line space while the font could have been larger.

**Comment by islandblue** [comment]
The current scaling is exponential and transitions from the minimum fontsize to the maximum (currently set to 9 and 17, respectively) in about 2-3 entries, as follows.

```
3 : 17.0
4 : 17.0
5 : 17.0
6 : 17.0
7 : 17.0
8 : 17.0
9 : 17.0
10 : 11.9430355294
11 : 10.0826822659
12 : 9.39829654694
13 : 9.14652511111
14 : 9.05390357599
15 : 9.01983001741
16 : 9.00729505572
17 : 9.00268370102
18 : 9.00098727843
19 : 9.00036319944
20 : 9.00013361361
21 : 9.0000491537
22 : 9.00001808264
23 : 9.00000665223
24 : 9.00000244722
25 : 9.00000090028
26 : 9.0000003312
27 : 9.00000012184
28 : 9.00000004482
29 : 9.00000001649
30 : 9.00000000607
```

**Comment by islandblue** [comment]
Since the permissible fontsize actually varies linearly with number of entries, I propose the following modification.

```
3 : 17.0
4 : 17.0
5 : 17.0
6 : 17.0
7 : 17.0
8 : 17.0
9 : 17.0
10 : 17.0
11 : 16.2
12 : 15.4
13 : 14.6
14 : 13.8
15 : 13.0
16 : 12.2
17 : 11.4
18 : 10.6
19 : 9.8
20 : 9.0
21 : 9.0
22 : 9.0
23 : 9.0
24 : 9.0
25 : 9.0
26 : 9.0
27 : 9.0
28 : 9.0
29 : 9.0
30 : 9.0
```

**Comment by islandblue** [comment]
Here are some example plots with the proposed scaling.

![afs05](https://user-images.githubusercontent.com/27438398/38355596-b33cbd7c-38bd-11e8-9567-27bf152c9a33.png)

![afs10](https://user-images.githubusercontent.com/27438398/38355602-b99ad8d4-38bd-11e8-91b7-13e19d1b2cd6.png)

![afs15](https://user-images.githubusercontent.com/27438398/38355610-bdec3964-38bd-11e8-8432-499a4945a835.png)

![afs20](https://user-images.githubusercontent.com/27438398/38355616-c283afca-38bd-11e8-9475-497c483e9ecb.png)

![afs25](https://user-images.githubusercontent.com/27438398/38355621-c642851e-38bd-11e8-9f50-d8aebb37a9db.png)

![afs30](https://user-images.githubusercontent.com/27438398/38355625-c9ed5e82-38bd-11e8-8a37-98fb47bf21d3.png)

**Comment by islandblue** [comment]
For the record, the proposed interpolation factor is as follows.

![formula](http://mathurl.com/y7uazt5w.png)

**Comment by brockho** [comment]
Thanks @islandblue, the above looks fine to me. I suggest that we very quickly discuss your suggestion in the BBOB/COCO meeting later today and then merge the new code to `development` immediately.

FYI, we solved the problem very quick & dirty before for our PPSN paper by setting the minimal font size to 11pt (for 13 algorithms) and it looked already much better than the old 9.something points fontsize. Your suggestion is of course much cleaner and will make the labels even more readable.
