### ISSUE TITLE
Rotated Rosenbrock function definition

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1733]
The rotated Rosenbrock function has its optimum too close to zero, in particular in dimensions larger than 64. The reason is, I think, [this line](https://github.com/numbbo/coco/blob/devel-LS-development/code-experiments/src/f_rosenbrock.c#L202), also implemented in the `bbob` test bed, [here](https://github.com/numbbo/coco/blob/master/code-experiments/src/f_rosenbrock.c#L125), even though in this case
```C
coco_double_max(1.0, sqrt((double) dimension) / 8.0)
``` 
should invariable evaluate to 1. It seem to correctly implement the function defined [here](http://coco.lri.fr/downloads/download15.01/bbobdocfunctions.pdf#page=37).

The reason for the code line is that the rotation matrix, in order to preserve the function property,
should never rotate the `[0, 1]^n` cube of the original definition space outside of the domain [-5, 5] (and the optimum not outside [-4, 4]). The diagonal of the cube has length `sqrt(n)`, the domain has a minimum diameter of 10. Given however that we use block rotation matrices with block size of at most 40, the cube diagonal is smaller than `sqrt(n)` (it should be maximally `sqrt(40)`, i.e. a little over `6.3`).

That is, `dimension` in the above equation could/should read `block_size_dimension` which should address the problem not perfectly but backwards compatible and maybe good enough.

These are some results, suggesting that the above described problem makes the function much easier than it should be:

```python
from scipy.optimize import fmin_l_bfgs_b
import cma
import cocoex
bbob = cocoex.Suite('bbob', '', '')
bbob = cocoex.Suite('bbob-largescale', '', '')
repetitions = 1
for f in [cma.ff.rosen, 'f8', 'f9']:
    print(f)
    for dimension in bbob.dimensions:
        for _ in range(repetitions):
            if f is 'f8' or (hasattr(f, 'name') and 'f8' in f.name):
                f = bbob.get_problem_by_function_dimension_instance(8, dimension, repetitions + 1)
            if f is 'f9' or (hasattr(f, 'name') and 'f9' in f.name):
                f = bbob.get_problem_by_function_dimension_instance(9, dimension, repetitions + 1)
            x, fbest, rest = fmin_l_bfgs_b(f, 0 + 0. * (np.random.rand(dimension) - 0.5),
                                           approx_grad=True, maxfun=1e9)
            print('%3d' % dimension, 
                  '%13.9f' % fbest,
                  '%6d' % rest['funcalls'],
                  np.mean(x**2)**0.5,
                  np.mean(np.abs(x)))
```
```
<bound method FitnessFunctions.rosen of <cma.fitness_functions.FitnessFunctions object at 0x113bb5c18>>
  2   0.000000000     78 0.999995462206 0.999995462205
  3   0.000000000    140 0.999995838764 0.999995838761
  5   0.000000000    276 0.99999614 0.999996139995
 10   0.000000000    836 0.999999095424 0.999999095423
 20   0.000000000   2877 0.999998788265 0.999998788261
 40   0.000000000  10250 0.999999541031 0.999999541029
f8
  2 -999.999999987     69 2.17907174568 2.01237882119
  3 -999.999999985    140 1.98485978738 1.84957164223
  5 -999.999999966    444 1.91847028383 1.82878359693
 10 -999.999999684    979 1.83754865089 1.65972003928
 20 -999.999999785   2394 1.72410560134 1.52606799714
 40 -999.999999745  11029 1.72526048603 1.51159667427
f9
  2  47.510000014     66 0.500117212266 0.384153672774
  3  47.510000000    100 0.500001590408 0.448346949881
  5  47.510000000    216 0.50000067964 0.46459543355
 10  47.510000001    539 0.500001713733 0.411759341698
 20  47.510000013   1365 0.499997411038 0.407490480573
 40  47.510000027   2993 0.499997943782 0.406975725969
```
```
<bound method FitnessFunctions.rosen of <cma.fitness_functions.FitnessFunctions object at 0x113bb5c18>>
 20   0.000000000   2877 0.999998788265 0.999998788261
 40   0.000000000  10250 0.999999541031 0.999999541029
 80   0.000000000  39123 0.999999741587 0.999999741586
160   0.000000000 151984 0.999999750383 0.999999750382
320   0.000000001 591924 0.99999980654 0.999999806538

f8
 20 -999.999999785   2394 1.72410560134 1.52606799714
 40 -999.999999745  11029 1.72526048603 1.51159667427
 80 -999.999998084  42444 1.687954711 1.45313447439
160 -999.999999475 153111 1.63796318244 1.39897920673
320 -999.999998745 312333 1.73378331956 1.50569575003

f9
 20  47.510000016   1386 0.500009303487 0.435601320587
 40  47.510000027   2952 0.499996323869 0.388772664176
 80  47.510000031   5832 0.44721159129 0.357674007565
160  47.510000025  11109 0.316228670818 0.25555595122
320  47.510000081  22149 0.223606448131 0.180193772084
```
Choosing the starting point uniform in [-1, 1] makes L-BFGS 50 times slower in 640-D:
```
<bound method FitnessFunctions.rosen of <cma.fitness_functions.FitnessFunctions object at 0x113bb5c18>>
 20   0.000000000    2940 1.00000040488 1.00000040488
 40   0.000000001   10578 0.999998700997 0.999998700988
 80   0.000000000   39042 0.999999805111 0.99999980511
160   0.000000001  152950 0.999999474093 0.999999474087
320   0.000000001  595776 0.99999977119 0.999999771187
640   0.000000001 2367213 0.999999923906 0.999999923906
f8
 20 149.150000037    4305 1.38331628636 1.05255330363
 40 149.150000107    7462 1.57644488523 1.28552655566
 80 149.150000082   21222 1.68545248532 1.43421935475
160 149.150000265  118979 1.70926725436 1.46403941121
320 149.150012682  272529 1.72472730362 1.5020986532
640 149.150000057 2374905 1.69882749805 1.47249582215
f9
 20 123.830000077    2835 0.499996714959 0.372076177494
 40 123.830000058   10783 0.500004872112 0.399234912224
 80 123.830000018   17658 0.447213907219 0.361489806592
160 123.830000087  155365 0.316225620854 0.255923303612
320 123.830000035  413769 0.223606329535 0.177810878348
640 123.830000016 1177517 0.158114039369 0.12645034421
```

**Comment by nikohansen** [comment]
Making only [the scaling `factor`](https://github.com/numbbo/coco/blob/devel-LS-development/code-experiments/src/f_rosenbrock.c#L136) independent of dimension does not have the desired fixing effect (see below), as I was hoping for. Even in this case, the rotation does not guarantee that the optimum remains in the `[-5,5]` domain in large dimension.

The only solution I can see from here is making the same `x_opt` transformation as in the "original" Rosenbrock function `f8`, in which case we give up the idea that the all-zeros point of the raw function remains with probability one with the `[-5,5]` domain. 

```python
<bound method FitnessFunctions.rosen of <cma.fitness_functions.FitnessFunctions object at 0x1147232e8>>
 20   0.000000000   2877 0.999998788265 0.999998788261
 40   0.000000000  10250 0.999999541031 0.999999541029
 80   0.000000000  39123 0.999999741587 0.999999741586
160   0.000000000 151984 0.999999750383 0.999999750382
320   0.000000001 591924 0.99999980654 0.999999806538
640   0.000000000 2375546 0.999999945662 0.999999945662
f8
 20 -999.999999785   2394 1.72410560134 1.52606799714
 40 -999.999999745  11029 1.72526048603 1.51159667427
 80 -999.999999501  40743 1.68795283704 1.45312837035
160 -999.999999340 108353 1.63795117392 1.39896843461
320 -999.999993783 212823 1.7337712002 1.50567276536
640 -999.999983672 444854 1.72574540544 1.49199345361
f9
 20  47.510000016   1386 0.500009303487 0.435601320587
 40  47.510000027   2952 0.499996323869 0.388772664176
 80  47.510000017   5670 0.500000330398 0.39989340053
160  47.510000015  12236 0.500000193246 0.404068329727
320  47.510000042  23433 0.499997236755 0.402924485012
640  47.510000049  62818 0.499998283547 0.402223082942
```

**Comment by nikohansen** [comment]
In the function `f19` Griewank-Rosenbrock we probably should also use max blocksize instead of dimension.

**Comment by kostasvar** [comment]
I think the problem is that with the current transformation for the rotated Rosenbrock function, the norm of `x_opt` is equal to 4, thus belongs to a hypersphere of radius 4 which is 'much smaller' than [-4,4]^n in high dimension. 

If we use a similar transformation as in the original Rosenbrock but with a different scaling factor, i.e. `z = max(1, sqrt(n)) R (x-x_opt)` and `x_opt` is uniformly chosen in [-4,4]^n , then the point `x_0` corresponding to the all-zeros point of the initial definition remains inside [-5,5]^n . 

Results of L-BFGS with zero initial point: 

`
<bound method FitnessFunctions.rosen of <cma.fitness_functions.FitnessFunctions object at 0x10c7fc890>>
(' 20', '  0.000000000', '  2877', 0.9999987882646557, 0.9999987882607325)
(' 40', '  0.000000000', ' 10250', 0.9999995410310942, 0.999999541029279)
(' 80', '  0.000000000', ' 39123', 0.9999997415869385, 0.9999997415864914)
('160', '  0.000000000', '151984', 0.9999997503827943, 0.9999997503815065)
('320', '  0.000000001', '591924', 0.9999998065397862, 0.9999998065383773)
('640', '  0.000000000', '2375546', 0.9999999456622186, 0.9999999456621133)
f8
(' 20', '-999.999999136', '  3444', 2.2987727031135896, 2.0347281204489898)
(' 40', '-996.013375939', ' 12341', 2.313841889754253, 2.0233239685796036)
(' 80', '-999.999999347', ' 40581', 2.2506053459764366, 1.937509936743396)
('160', '-999.999999564', '207368', 2.1839445330746066, 1.8653001167423469)
('320', '-999.999999813', '607974', 2.311713950638174, 2.0075999979906554)
('640', '-999.999998704', '2374264', 2.300966824873459, 1.9892699506891418)
f9
(' 20', ' 47.510000027', '  3528', 2.5416485487296, 2.3301997688413065)
(' 40', ' 47.510000029', ' 10988', 2.3897677616344257, 2.078280594702481)
(' 80', ' 49.503312020', ' 43983', 2.3214129917766657, 2.0027298882094073)
('160', ' 47.510000046', '153594', 2.4021514650627553, 2.123434998140355)
('320', ' 47.510000007', '613110', 2.3549890222586654, 2.051544994725267)
('640', ' 47.759164020', '2423621', 2.3185609543784915, 2.020580011493417)
`

**Comment by nikohansen** [comment]
I'd like to remain backwards compatible to the `bbob` suite at least for the original Rosenbrock function. I investigated how much the transformation `z = R (x-x_opt) + 1` moves the original all-ones point outside of `[-5, 5]`. It's IMHO acceptable.

```python
"""compute the probability that all-ones gets rotated outside the bound"""
%pylab
from cma.fitness_transformations import Rotation

dims = [2,3,5,10,20,40]
reps = 1000
for dim in dims:
    s = []
    for rep in range(reps):
        x = np.abs(Rotation()(np.ones(dim)) + 8 * np.random.rand(dim) - 4)
        s += [sum((x - 5) * (x > 5))]
    figure(1)
    plot(sorted(s), np.arange(len(s)) / len(s))  # close to empirical distribution function
```
<img width="542" alt="screen shot 2018-04-17 at 17 02 16" src="https://user-images.githubusercontent.com/7316439/38878438-3f6f459c-4261-11e8-80b3-fbefdf023e26.png">

and the `max` instead of the `sum`:
<img width="533" alt="screen shot 2018-04-17 at 16 59 50" src="https://user-images.githubusercontent.com/7316439/38878262-d44ee1f0-4260-11e8-99b2-17f7de78f1c5.png">

**Comment by kostasvar** [comment]
I made a new branch for this issue, implementing the following transformations:
For the Rosenbrock `z = max(1.0, sqrt(s)/8.0)(x-x_opt) + 1`,
for the rotated Rosenbrock `z = max(1.0, sqrt(s)/8.0) R (x-x_opt) + 1`,
for the Griewank-Rosenbrock `z = max(1.0, sqrt(s)/8.0) R x + 1/2` , where `s` is the (maximum) block size of `R`. 

Some results for the first two, as above, are in the following. 

LBFGS with zero initial point:
```python
<bound method FitnessFunctions.rosen of <cma.fitness_functions.FitnessFunctions object at 0x10d927990>>
(' 20', '  0.000000000', '  2877', 0.9999987882646557, 0.9999987882607325)
(' 40', '  0.000000000', ' 10250', 0.9999995410310942, 0.999999541029279)
(' 80', '  0.000000000', ' 39123', 0.9999997415869385, 0.9999997415864914)
('160', '  0.000000000', '151984', 0.9999997503827943, 0.9999997503815065)
('320', '  0.000000001', '591924', 0.9999998065397862, 0.9999998065383773)
('640', '  0.000000000', '2375546', 0.9999999456622186, 0.9999999456621133)
f8
(' 20', '-999.999999785', '  2394', 1.7241056013436329, 1.526067997140037)
(' 40', '-999.999999745', ' 11029', 1.725260486031523, 1.511596674266779)
(' 80', '-999.999999501', ' 40743', 1.6879528370438224, 1.453128370351779)
('160', '-999.999999340', '108353', 1.6379511739184094, 1.3989684346053388)
('320', '-999.999993783', '212823', 1.7337712001957588, 1.505672765359118)
('640', '-999.999983672', '444854', 1.7257454054392722, 1.491993453609984)
f9
(' 20', ' 51.496623891', '  2751', 2.534410896904476, 2.231937235724592)
(' 40', ' 47.510000022', '  6314', 2.3897696710653653, 2.078283227777412)
(' 80', ' 47.510000025', ' 40176', 2.322049303136847, 2.002740902313994)
('160', ' 47.510000119', ' 78890', 2.402148906618151, 2.123432481775135)
('320', ' 48.008328024', '559824', 2.354921365599481, 2.0495867326085)
('640', ' 47.510000075', '1717239', 2.3185412858526364, 2.0205327206120907)
```
and with initial point uniformly chosen in `[-1,1]^n`:
```python
<bound method FitnessFunctions.rosen of <cma.fitness_functions.FitnessFunctions object at 0x10d927990>>
(' 20', '  0.000000000', '  3171', 0.9999979297131076, 0.9999979297016823)
(' 40', '  0.000000001', ' 10455', 0.9999992642126644, 0.9999992642085708)
(' 80', '  0.000000001', ' 38394', 0.9999995977886027, 0.9999995977865812)
('160', '  0.000000000', '152467', 0.9999999328810144, 0.9999999328809096)
('320', '  0.000000001', '598986', 0.9999998457088901, 0.9999998457076759)
('640', '  0.000000000', '2367854', 0.9999999477473832, 0.9999999477472808)
f8
(' 20', '-999.999999784', '  1848', 1.7240806380469138, 1.5260463551676964)
(' 40', '-999.999999313', ' 11111', 1.72525792289869, 1.511595575900579)
(' 80', '-999.999999465', ' 42282', 1.687955951807573, 1.4531378864873403)
('160', '-999.999999711', '100786', 1.6379570528264658, 1.398973668973723)
('320', '-999.999994496', '316506', 1.7337793957917265, 1.5056874897067378)
('640', '-999.999999305', '685229', 1.725725397834334, 1.4919537910922962)
f9
(' 20', ' 51.496623867', '  2919', 2.5344129348521585, 2.2319382007245925)
(' 40', ' 47.510000011', '  6027', 2.3897672115865576, 2.0782797019462462)
(' 80', ' 47.510000041', ' 39771', 2.322048519866012, 2.0027400766487733)
('160', ' 47.510000011', ' 77924', 2.4021517927270843, 2.123435342818033)
('320', ' 47.510000033', '431745', 2.354988964920559, 2.051544967569921)
('640', ' 47.510000039', '940988', 2.3185422602534045, 2.0205338836633002)
```

Note that now the Rosenbrock becomes easier than the rotated Rosenbrock in large dimensions (even by a larger factor when the initial point is zero). This could be related to the fact that for the Rosenbrock, `x_opt` is chosen in `[-3, 3]^n`, as can be seen in [this](https://github.com/numbbo/coco/blob/caeec76b9d5067cbc9cd176b6172d1c9d41f72d8/code-experiments/src/f_rosenbrock.c#L88) line  which is not the case for the Rotated (it is in `[-4, 4]^n`).

If we also choose for the Rotated Rosenbrock `x_opt` to be in `[-3, 3]^n`, then the results are:

Zero initial point:
```python
f9
(' 20', ' 47.510000030', '  2604', 1.9062403607339136, 1.747650683325891)
(' 40', ' 47.510000013', '  6191', 1.7923254277100593, 1.5587096764105148)
(' 80', ' 47.510000005', ' 39771', 1.7415365980708346, 1.5020552078759837)
('160', ' 47.510000015', ' 78890', 1.8016127312193966, 1.592575288728619)
('320', ' 47.510000026', '212181', 1.766241316311614, 1.538658512365732)
('640', ' 47.510000013', '741637', 1.738906517346576, 1.5154002189159685)
```
Initial point uniformly chosen in `[-1,1]^n`:
```python
f9
(' 20', ' 47.510000036', '  3360', 1.90623401956332, 1.747649423755351)
(' 40', ' 47.510000022', '  6150', 1.7923249356742896, 1.5587092370676128)
(' 80', ' 47.510000041', ' 41229', 1.741535514019213, 1.5020539006828266)
('160', ' 47.510000035', ' 75992', 1.8016133709035604, 1.5925760374652576)
('320', ' 48.008327998', '508464', 1.7670517712428433, 1.537019976354657)
('640', ' 47.510000060', '511518', 1.7389041085937962, 1.5153977049143446)
```

Choosing `x_opt` in `[-4, 4]^n` for Rosenbrock is also an option, but then we are not anymore consistent with the `bbob` Rosenbrock.

**Comment by nikohansen** [comment]
AFAICS, it would be most consistent to have `xopt` in `[-3,3]^n` also for `f9`, because we have chosen to change `f9` anyways and to make the definition as close as possible to `f8`. It also reduces the risk to move things out-of-domain (almost to zero). 

Are the last two lines on `f9`:
```
('320', ' 48.008327998', '508464', 1.7670517712428433, 1.537019976354657)
('640', ' 47.510000060', '511518', 1.7389041085937962, 1.5153977049143446)
```
reproducible?

**Comment by kostasvar** [comment]
Yes, if you change the source code: add `xopt[i] *= 0.75;` inside the `for` loop [here](https://github.com/numbbo/coco/blob/caeec76b9d5067cbc9cd176b6172d1c9d41f72d8/code-experiments/src/f_rosenbrock.c#L209) .

**Comment by nikohansen** [comment]
What I mean: can you reproduce the result when you rerun it? In 320-D it seems that the optimum has not been reached, so I assume that this is a random effect and should go away in another try.

**Comment by kostasvar** [comment]
It happens with some (low) frequency. For 20 runs with random initial point and for the same instance, I get: 
```python
('320', ' 47.510000031', '293073', 1.766241611480149, 1.5386587569376775)
('320', ' 48.008328023', '228873', 1.767051824016005, 1.537019954583202)
('320', ' 47.510000012', '374928', 1.766241849160137, 1.5386587428972234)
('320', ' 47.510000010', '255195', 1.7662416781040884, 1.5386587151690363)
('320', ' 47.510020770', '294678', 1.766202530438247, 1.538635129143674)
('320', ' 47.510000518', '184896', 1.7662356516798101, 1.5386551572446374)
('320', ' 47.510001334', '180402', 1.7662317997177859, 1.5386528325260016)
('320', ' 47.510000010', '378459', 1.7662416422950313, 1.5386586667892828)
('320', ' 47.510000056', '224700', 1.766241652693536, 1.5386586494674124)
('320', ' 47.510000093', '297888', 1.7662416530758165, 1.538658608578722)
('320', ' 47.510000030', '274134', 1.7662419272943297, 1.5386588769738527)
('320', ' 47.510000063', '390978', 1.7662418095747412, 1.538658859102119)
('320', ' 47.510000011', '387768', 1.766241762915362, 1.5386587654208863)
('320', ' 47.510000012', '420831', 1.7662416923375555, 1.538658655358002)
('320', ' 47.510001685', '175587', 1.7662307081023554, 1.538652192828371)
('320', ' 48.008328019', '356952', 1.767051884361517, 1.5370200405088377)
('320', ' 47.510000022', '427893', 1.7662419522629933, 1.538658839602307)
('320', ' 47.510000012', '185217', 1.7662411982279322, 1.5386583980720396)
('320', ' 47.510000021', '407670', 1.7662416419522404, 1.5386586293463727)
('320', ' 47.510000033', '373002', 1.7662422110178349, 1.5386590026585516)
```
What seems strange is that this happens more often in dimension 20:
```python
(' 20', ' 47.510000006', '  2709', 1.9062336617448257, 1.7476492775287995)
(' 20', ' 47.510000307', '  2919', 1.9062505317172647, 1.7476535484287612)
(' 20', ' 51.496623870', '  2247', 1.9120291333393638, 1.6493882957553567)
(' 20', ' 47.510000023', '  2520', 1.906239623627335, 1.7476502856949696)
(' 20', ' 51.496623930', '  2268', 1.912033626205602, 1.649389364602993)
(' 20', ' 51.496623856', '  2331', 1.9120291776013645, 1.6493888280572881)
(' 20', ' 47.510000005', '  3003', 1.9062359130527593, 1.7476496795446081)
(' 20', ' 47.510000018', '  3171', 1.906237168354062, 1.7476503406201516)
(' 20', ' 51.496623901', '  2520', 1.9120288688373293, 1.6493887115043417)
(' 20', ' 47.510000002', '  2457', 1.9062379240066827, 1.7476503056103756)
(' 20', ' 47.510000019', '  2835', 1.9062368283200555, 1.747650066750964)
(' 20', ' 47.510000011', '  2415', 1.906233602632566, 1.7476491223402402)
(' 20', ' 51.496623863', '  1953', 1.9120317811133045, 1.6493893129050599)
(' 20', ' 47.510000019', '  2793', 1.9062379787253605, 1.7476499943359396)
(' 20', ' 51.496623869', '  2751', 1.9120269503944272, 1.6493883306438033)
(' 20', ' 51.496623875', '  2037', 1.91202687156868, 1.6493885615715431)
(' 20', ' 47.510000085', '  2457', 1.906236340579678, 1.7476496509414072)
(' 20', ' 51.496623877', '  2499', 1.91202815079065, 1.6493884389707858)
(' 20', ' 47.510000015', '  2625', 1.906241639744778, 1.7476513165256733)
(' 20', ' 47.510000003', '  2919', 1.9062372448179719, 1.7476501010213958)
```

**Comment by nikohansen** [comment]
So the `508464` in 320-D you got first I would call "not reproducible", as all 20 runs you did afterwards are below `427893`.

I see nothing particular strange that we could end up more often in a local optimum in lower dimension than in higher dimension. It's interesting though as I wasn't aware of it, and the rate in 20-D is higher than the one we get with CMA-ES, again also not necessarily a surprise.

**Comment by kostasvar** [comment]
The definition is decided above so the issue is closed.
