### ISSUE TITLE
Replace axes grid under legend with white space in ECDF plots

### ISSUE THREAD

**Issue by islandblue** [numbbo/coco#1747]
The present layout of the legend in ECDF plots can be improved. First few suggestions:

* Have the axes box end at the vertical line indicating maximum evaluations, thus leaving blank space underneath the legend labels and leader lines
* Slightly detach leader lines from the plot lines to make them more distinct

**Comment by islandblue** [comment]
The method of drawing a white span underneath the legend has the following disadvantages:

* It will crop part of the horizontal axis label
* The horizontal axis label will not appear centered

The first can be addressed by using a patch instead of a span, but at the cost of introducing another potential problem. The vertical coordinates have to be adjusted so that on the horizontal axis the tick labels are covered, but the axis label is not. This may come back to haunt us since changing font sizes or  having multiline axis label etc. could easily invalidate the precarious setting.

Besides, to paint the patch above the axes grid and borders and below all plot lines and legend labels, zorder needs to be correctly specified for each plotting operation. A simple attempt resulted in the best line to move up and obscure both the annotation text and the other plot lines (see below). So the only merit of this approach, which is being practical and minimally invasive, is rendered moot.

![zorder](https://user-images.githubusercontent.com/27438398/39240884-6c07afa2-4885-11e8-92ec-2d8f7e384b36.png)

**Comment by islandblue** [comment]
Below is another result, by actually ending the axes where the black line is and adjusting axes width to approximate the earlier look.

![old](https://user-images.githubusercontent.com/27438398/39245649-a7b718c6-4894-11e8-8d52-70a0ad11ab27.png)

![new](https://user-images.githubusercontent.com/27438398/39245657-ab203966-4894-11e8-89e5-69d1238f8f7e.png)

**Comment by brockho** [comment]
Thanks for trying out all those options. I like very much the last one where everything after the black vertical line is gone except for the labels. 

Would you mind to add the `ONEFIFTH` algorithm and redo the plot? I just want to see whether the dot, indicating the longest data point from the simulated runlengths after which the graph is flat, appears outside the actual plot region (as here):

[pprldmany_f018_03D.pdf](https://github.com/numbbo/coco/files/1946991/pprldmany_f018_03D.pdf)

**Comment by islandblue** [comment]
Sure. Working on detaching the lines right now. I'll produce its examples with ONEFIFTH added.

**Comment by islandblue** [comment]
Not that you haven't explained it already, but I'm having difficulty associating the code with the function you described.

**Comment by islandblue** [comment]
Oh I think I get it. It's plotting the last data point outside of the "normal" plotting area, *yet still inside of the axes limit*. If this is correct, even though we've shortened the axes, the figure limits and the positioning of the axes within the figure remain similar, so I guess it's not absurd to keep the old calculation here.

**Comment by nikohansen** [comment]
+1 for fully white space without frame.

I think the idea of using `x_limit ** annotation_space_end_relative` to compute also the index for the `y`-value is to plot the most extreme point _which lies on the true graph_ and which would still be visible (and/or not screw up the page width formatting). However it means that we do not know whether to the right of this point there could be yet a point with higher y-value (that is, our information interpretation was not quite precise).

**Comment by islandblue** [comment]
I've produced some sample output with different amounts of detachment. Can't really say one looks better than the other. Posting here for your opinion.

development branch:
![dev](https://user-images.githubusercontent.com/27438398/39252539-30a68f3e-48a6-11e8-9e4c-0f41cd3d94b1.png)

detached graphs
![det101](https://user-images.githubusercontent.com/27438398/39252570-40b28798-48a6-11e8-8322-7bce68d963b8.png)
![det102](https://user-images.githubusercontent.com/27438398/39252571-40e3d712-48a6-11e8-9c06-eaee346dd004.png)
![det103](https://user-images.githubusercontent.com/27438398/39252575-416198d2-48a6-11e8-8bdf-31c473eb967b.png)
![det104](https://user-images.githubusercontent.com/27438398/39252576-4186d25a-48a6-11e8-8af7-258f1823d0f9.png)

**Comment by brockho** [comment]
Hmm, for me it is even more confusing when the lines are not connected. Hence, I vote for keeping it as is.

**Comment by nikohansen** [comment]
+1 for keeping the lines connected. I also like the third version when the line end taches the symbol, but I don't think this can be (easily) guaranteed.

**Comment by ttusar** [comment]
What about keeping the lines "together" (as is now), but making the part of the line from the end of the graph to the label dashed?

This is actually an idea of my colleague. I didn't like it at first, but I'm now wondering how this would look like... Maybe it would be clearer that it's a "label line"...

**Comment by nikohansen** [comment]
That would remove dashed lines as optional line style for the original data (as we had it for some later styles). I also don't like to have all lines dashed, it usually looks terrible.

**Comment by nikohansen** [comment]
example with many data: http://coco.gforge.inria.fr/ppdata-archive/bbob/2009-all/

**Comment by islandblue** [comment]
After a two-day long struggle with matplotlib's bizarre handling of minor ticks in logarithmic plots, here is the final result. Hope this helps to establish that the right edge of the plot is actually 10⁸.

![prop](https://user-images.githubusercontent.com/27438398/39588909-0fbc6066-4efd-11e8-9245-755814691f44.png)

**Comment by nikohansen** [comment]
Is it going to be merged?

**Comment by islandblue** [comment]
The pull request is up.
