### ISSUE TITLE
Recording constraint values

### ISSUE THREAD

**Issue by asmaatamna** [numbbo/coco#1756]
As discussed with @anneauger, @nikohansen and @brockho, it would be useful to have a column (last column) in the logger that contains the discretized constraint values (case of ```bbob-constrained```). Instead of the actual constraint value of each constraint, we would have for each constraint value ```gi(x)``` a value from ```0``` to ```9```, where for example:
- ```0```: ```gi(x) <= 0```
- ```1```: ```0 < gi(x) <= 1e-8```
- ```...```
- ```9```: ```1e-1 < gi(x) <= 1```

For this, we would need a function that given a g-value returns a number between ```0``` and ```9```.

**Comment by nikohansen** [comment]
It should probably the 5-th column (replace best measured noisy fitness), see also #1755
