### ISSUE TITLE
Being careful with `bbob` and `bbob-new` data

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1758]
The new logger output that writes both `f`- and `g`-evaluation counter values is not directly compatible with the old data (the new one has 6 columns plus the `x`-values while the old one had only 5 columns plus `x`-values).

Since we received for BBOB-2018 data with the new format already, we have to make sure in the postprocessing that both old and new data can be read in and compared correctly side-by-side.

**Comment by nikohansen** [comment]
See also #1755

**Comment by brockho** [comment]
This seems to be an outdated issue that can be closed.
