### ISSUE TITLE
how to crash the python kernel

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1767]
This crashes my Jupyter Python 2 and Python 3 notebook kernel:
```python
import cocoex
f4 = cocoex.Suite('bbob', '', '').get_problem_by_function_dimension_instance(4, 5, 2)
f4.observe_with(cocoex.Observer('bbob', 'test-folder'))  # necessary
for i in range(9):
    f4(5 * [1])
f4.free()
```
The reason seems to be that ``cocoex.Suite('bbob', '', '')`` is not assigned to a variable, as the following works reliably:
```python
import cocoex
bbob = cocoex.Suite('bbob', '', '')
f4 = bbob.get_problem_by_function_dimension_instance(4, 5, 2)
f4.observe_with(cocoex.Observer('bbob', 'test-folder'))
for i in range(9):
    f4(5 * [1])
f4.free()
```
Assigning the observer to a variable does not help, but having no observer at all "fixes" the problem as well. I suspect that this is a `Cython` problem and that it is a won't fix. Any specific ideas to the reason?

**Comment by brockho** [comment]
I confirm that the same happens with my Jupyter notebook (setup: Windows 7, Anaconda with Python 2.7, Firefox).
