### ISSUE TITLE
Inconsistencies between current documentation and implementation in large-scale

### ISSUE THREAD

**Issue by kostasvar** [numbbo/coco#1770]
There seem to be many inconsistencies between the current documentation and the implementation of the `large-scale` suite. Some functions are not normalised by dimension as the documentation describes, e.g. the Gallagher, Weierstrass, Katsuura functions. In most of the times these inconsistencies concern this lack of normalisation (which btw could be reasonable in some problems), but not always:  in the Attractive sector function, the normalisation is performed before the oscillation and the power transformations.

**Comment by brockho** [comment]
Decided today that it is indeed the documentation that is wrong.
