### ISSUE TITLE
Unclear table captions

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1789]
After running the `example_experiment_for_beginners.py`, this table is produced (the table goes on, I'm pasting here just the first lines):

<img width="517" alt="screen shot 2018-05-24 at 13 25 51" src="https://user-images.githubusercontent.com/13745935/40482930-9dd080ee-5f56-11e8-933b-a7e7e39b2f8b.png">

The caption reads

> Average running time (aRT in number of function evaluations) divided by the aRT of the best algorithm from BBOB 2009 in different dimensions. The aRT  and in braces, as dispersion measure, the half difference between 90 and 10%-tile of bootstrapped run lengths appear in the second row of each cell, the best aRT  (preceded by the target ∆f-value in italics) in the first. #succ is the number of trials that reached the target value of the last column. The median number of conducted function evaluations is additionally given in italics, if the target in the last column was never reached. Bold entries are statistically significantly better (according to the rank-sum test) compared to the best algorithm from BBOB 2009, with p = 0.05 or p = 10−k when the number k > 1 is following the ↓ symbol, with Bonferroni correction by the number of functions (24).

From the caption it seems as if the aRT of the algorithm, the aRT of "best 2009" and the ratio between the two are all shown in the table. Which line contains which aRT (ratio)?

**Comment by brockho** [comment]
Actually, all three numbers are given in the table, or at least can be inferred from it: The first line always gives the (absolute) aRT of the best-2009 (or the reference algorithm that is chosen in the postprocessing) and the corresponding second, third, etc. lines (in your example only one) are the ratios for the postprocessed algorithms.

The entry `21` in the above example for the sphere function (`f_1`) corresponds then to an aRT of `21*2.0=42` function evaluations for the displayed algorithm.

**Comment by ttusar** [comment]
Thanks for the quick response. I think it would be clearer, if the caption said 

> The aRT ratio and in braces,

Instead of

> The  aRT and in braces,

**Comment by brockho** [comment]
The caption actually says "Average running time divided by the aRT of the best algorithm from BBOB 2009" which is more informative from my point of view than just "aRT ratio".

**Comment by ttusar** [comment]
I agree, but then in the next sentence "the aRT and in braces" is confusing, because it does not refer to the aRT, but the ratios of aRTs.

**Comment by nikohansen** [comment]
Fixed in the development branch, where "_the aRT and in braces,_" now reads "_this aRT ratio and, in braces_".
