### ISSUE TITLE
Creating data archive results in suboptimal paths

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1791]
When I run `cocopp.archiving.create('./')` within my '~/.cocopp/data_archive/' folder (under Windows, python 2.7), I get other path names than expected:
```
[(u'Users/dimo/.cocopp/data-archive/bbob/2009/ALPS_hornby_noiseless.tgz', '98810d28d879eb25d87949f3d7666b36f524a591e3c7d16ef89eb2caec02613b', 19150L), 
(u'Users/dimo/.cocopp/data-archive/bbob/2009/AMALGAM_bosman_noiseless.tgz', 'e92951f11f8d56e0d1bdea7026bb1087142c3ea054d9e7be44fea2b063c6f394', 17020L), 
(u'Users/dimo/.cocopp/data-archive/bbob/2009/BAYEDA_gallagher_noiseless.tgz', 'ed674ff71237cc020c9526b332e2d817d5cd82579920c7ff2d25ff064a57ed33', 12872L), 
(u'Users/dimo/.cocopp/data-archive/bbob/2009/BFGS_ros_noiseless.tgz', 'ca9dbeab9f7ecd7d3bb39596a6835a01f832178f57add98d95592143f0095c7a', 15026L), 
(u'Users/dimo/.cocopp/data-archive/bbob/2009/BIPOP-CMA-ES_hansen_noiseless.tgz', '6b1276dc15988dc71db0d48525ae8c41781aba8a171079159cdc845cc0f1932d', 16476L),
[...]
```
I would either expect the absolute paths (`C:/Users/dimo/.cocopp/...`) or the relative paths (preferred, `bbob/2009/...` etc.). The latter is definitely better because this is platform independent and also the format, we have in the `archiving.py` itself for the COCO-supported data archive.

**Comment by nikohansen** [comment]
This was very purely tested in the first place, as it also doesn't give the right paths under MacOS.
