### ISSUE TITLE
coco_random_new() returns the same first random number for different seeds

### ISSUE THREAD

**Issue by asmaatamna** [numbbo/coco#1796]
This bug showed up while I was writing a new function for ```f_rastrigin_constrained``` in order to have the unconstrained optimum of the function on the grid. I get the following output when I print the seed passed to ```coco_random_new()``` and first random number it computes:

```
In [6]: problem = suite.get_problem_by_function_dimension_instance(43, 2, 1)
-------
coco_random_new(): 20043
f_rastrigin_cons_compute_xopt(): first random number: 0.000005
f_rastrigin_cons_compute_xopt(): xopt[0] = -4.00
-------
coco_random_new(): 10043
coco_random_new(): 60043

In [7]: problem = suite.get_problem_by_function_dimension_instance(44, 2, 1)
-------
coco_random_new(): 20044
f_rastrigin_cons_compute_xopt(): first random number: 0.000005
f_rastrigin_cons_compute_xopt(): xopt[0] = -4.00
-------
coco_random_new(): 10044
coco_random_new(): 60044
coco_random_new(): 110044

In [8]: problem = suite.get_problem_by_function_dimension_instance(45, 2, 1)
-------
coco_random_new(): 20045
f_rastrigin_cons_compute_xopt(): first random number: 0.000005
f_rastrigin_cons_compute_xopt(): xopt[0] = -4.00
-------
coco_random_new(): 10045
coco_random_new(): 60045
coco_random_new(): 110045
coco_random_new(): 160045
coco_random_new(): 210045
coco_random_new(): 260045
coco_random_new(): 310045

In [9]: problem = suite.get_problem_by_function_dimension_instance(46, 2, 1)
-------
coco_random_new(): 20046
f_rastrigin_cons_compute_xopt(): first random number: 0.000005
f_rastrigin_cons_compute_xopt(): xopt[0] = -4.00
-------
coco_random_new(): 10046
coco_random_new(): 60046
coco_random_new(): 110046
coco_random_new(): 160046
coco_random_new(): 210046
coco_random_new(): 260046
coco_random_new(): 310046
coco_random_new(): 360046

In [10]: problem = suite.get_problem_by_function_dimension_instance(47, 2, 1)
-------
coco_random_new(): 20047
f_rastrigin_cons_compute_xopt(): first random number: 0.000005
f_rastrigin_cons_compute_xopt(): xopt[0] = -4.00
-------
coco_random_new(): 10047
coco_random_new(): 60047
coco_random_new(): 110047
coco_random_new(): 160047
coco_random_new(): 210047
coco_random_new(): 260047
coco_random_new(): 310047
coco_random_new(): 360047
coco_random_new(): 410047

In [11]: problem = suite.get_problem_by_function_dimension_instance(48, 2, 1)
-------
coco_random_new(): 20048
f_rastrigin_cons_compute_xopt(): first random number: 0.000005
f_rastrigin_cons_compute_xopt(): xopt[0] = -4.00
-------
coco_random_new(): 10048
coco_random_new(): 60048
coco_random_new(): 110048
coco_random_new(): 160048
coco_random_new(): 210048
coco_random_new(): 260048
coco_random_new(): 310048
coco_random_new(): 360048
coco_random_new(): 410048
coco_random_new(): 460048
coco_random_new(): 510048
coco_random_new(): 560048
coco_random_new(): 610048
```

What is between ```-------``` is printed when the new function ```f_rastrigin_cons_compute_xopt()``` is called (code currently in the branch ```asma-bug-cons-rastrigin```). As discussed with @nikohansen , skipping the first random number returned by ```coco_random_new()```, or calling ```coco_random_generate()``` before ```return``` statement fixes the problem (lines ```61``` and ```62``` in ```coco_random.c```).

I include two ```.txt``` files where we can compare ```xopt``` values before and after the fix.

[uncons_xopt_f_rastrigin_original_coco_random_new.txt](https://github.com/numbbo/coco/files/2065930/uncons_xopt_f_rastrigin_original_coco_random_new.txt)
[uncons_xopt_f_rastrigin_updated_coco_random_new.txt](https://github.com/numbbo/coco/files/2065931/uncons_xopt_f_rastrigin_updated_coco_random_new.txt)

EDIT: the number we see in ```coco_random_new(): XXX``` is the seed.

**Comment by asmaatamna** [comment]
The code in ```coco_random.c``` hasn't been tested before and should not be used for the moment. Besides the constrained test suite, it is also used in:
- ```example_experiment.c```
- ```large_scale_transformations.c```
- test files for ```bbob-constrained``` and ```bbob-biobj```

**Comment by nikohansen** [comment]
We should replace using the above `coco_random*` code with `bbob2009_unif`, in particular everywhere where we generate instances with pseudo-random numbers.

**Comment by nikohansen** [comment]
The effect on sampling the first normal variate:
<img width="741" alt="screen shot 2018-06-05 at 16 38 12" src="https://user-images.githubusercontent.com/7316439/40983030-f9cfc97c-68de-11e8-9311-4c8b0823d73c.png">

**Comment by nikohansen** [comment]
Like see e.g. [here](https://github.com/numbbo/coco/commit/e05bc27bb867dd0dc1ca3954e51510f8c53daade).
