### ISSUE TITLE
Bug in postprocessing with bbob-new2 format

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1800]
When postprocessing a `bbob-new2`-formatted data set (for example from a newly generated random search data set via our example experiments, we get wrong ECDF plots:

![image](https://user-images.githubusercontent.com/13706996/41067042-67c2f0ca-69e4-11e8-9073-5a07e435bf69.png)

For those who don't see immediately the error: the plots start at function evaluation 2 instead of 1 (and thus everything is shifted to the right). Most likely due to a wrong interpretation of the loaded data (the factor 2 would not be too unexpected for `bbob-constrained` data). 

Note that this bug only happens if the `RS_on_bbob` data set is the first argument in the postprocessing (which decided with respect to which data format all algorithms are read in). When changing the order and the `RS_on_bbob` data set is put last, for example, the ECDF plots are correct.

Happens with the current `development` branch.

**Comment by brockho** [comment]
In order to find the bug, we decided today to try to reduce the bug with the logger which writes the `bbob-new` data format. Maybe this bug was there for a long time and we just did not see it.

**Comment by nikohansen** [comment]
Line 65 in `dataformatsettings.py`
```python
        dataset.evals_constraints, maxevals_cons, finalfunvals_cons = aligner(data,
                self.evaluation_constraints_idx,
                self.function_value_idx, rewind_reader=True)
```
seems to assign the function evaluations also into `dataset.evals_constraints`, whereas `maxevals_cons` is correctly set to zeros. `aligner` here is `readalign.align_data`, where the culprit may be.

**Comment by nikohansen** [comment]
The reason is that the `idxData` attribute of the `data: XMultiReader` is never set to the right value `self.evaluation_constraints_idx`.
