### ISSUE TITLE
Warnings in the C code

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1801]
The C code in the development branch has some warnings that should probably be addressed...

````
MAKE	all in code-experiments/build/c
CHDIR	/builds/disk/builds/workspace/Coco-devel-linux/dotype/test-c-unit/label/numbbo-ubuntu-12p04-i386/pyversion/python/code-experiments/build/c
COPY	Makefile.in -> Makefile
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment.o example_experiment.c
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o coco.o coco.c
code-experiments/src/c_linear.c: In function ‘c_linear_cons_bbob_problem_allocate’:
code-experiments/src/c_linear.c:305:29: warning: variable ‘data_c1’ set but not used [-Wunused-but-set-variable]
code-experiments/src/suite_cons_bbob_problems.c: In function ‘feasible_direction_set_length’:
code-experiments/src/suite_cons_bbob_problems.c:154:3: warning: conversion to ‘long unsigned int’ from ‘long int’ may change the sign of the result [-Wsign-conversion]
code-experiments/src/suite_cons_bbob_problems.c:154:29: warning: conversion to ‘long int’ from ‘long unsigned int’ may change the sign of the result [-Wsign-conversion]
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment coco.o example_experiment.o -lm  
````

**Comment by nikohansen** [comment]
@asmaatamna , you may want to have a look at this.

**Comment by asmaatamna** [comment]
I made the changes that I think will get rid of the warnings; they are in the branch ```issue-1801```. However, I can't be sure since I didn't get any warnings to begin with. @ttusar could you please check again and let me know is the problem is fixed?

**Comment by nikohansen** [comment]
@asmaatamna if you run `make clean` and `make` in the `C` folder you should see the warnings as well.

**Comment by asmaatamna** [comment]
@nikohansen that's what I did, but that was after addressing one warning (the unused variable). I just undid the changes I make and I can only see the first warning...

**Comment by ttusar** [comment]
@asmaatamna If you push your changes to one of the `devel-test` branches, the CI will get triggered and you can check if there are any warnings on all CI machines (you have to log in to Jenkins). I found this to be a good thing to do once in a while because the warnings depend on the compiler and very often the compiler on the linux machine shows more warnings than any of my compilers.

**Comment by brockho** [comment]
see also #1696

**Comment by ttusar** [comment]
I had a quick look at all the c-related builds on Jenkins. It seems that other than the missing end of line (being taken care of in #1803) there are no compiler warnings left. So this issue and #1696 can eventually be closed.
