### ISSUE TITLE
max"evals" in the constrained case

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1806]
What do we display/use as "maxevals" in the constrained case? As runtime we use currently

```python
genericsettings.weight_evaluations_constraints[0] * evals
   + genericsettings.weight_evaluations_constraints[1] * con_evals
```

**Comment by brockho** [comment]
Seems related to #1669.

**Comment by paulduf** [comment]
Adressed in [the PR](https://github.com/numbbo/coco/pull/2068).
