### ISSUE TITLE
Captions in the bbob-constrained case wrong

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1810]
Several (if not all) captions in the case of ``bbob-constrained`` data are wrong, mostly in the way the aRT is defined. Very often, we still see "number of f-evaluations" or something similar. This must be carefully checked and corrected for all plots.

**Comment by paulduf** [comment]
As mentioned, the tables are not up to date. Maybe keep only "number of evaluations" to avoid code duplication. It is anyway mentioned in the caption.

**Comment by brockho** [comment]
TODOs on my side:
* replace html text, hard-coded in `ppfig.py`
* make sure that all captions depend on `genericsettings.weight_evaluations_constraints` in some way

**Comment by paulduf** [comment]
NB: the caption in the scaling with dimension plots says `f_1 and f_48` which is not true anymore, as we have now 54 functions in the constrained testbed

**Comment by paulduf** [comment]
Note: in the `ppfigdim.py` there was already some code to handle the caption in the constrained case, see [this line](https://github.com/numbbo/coco/blob/11ce3ccdf3e19ddbd56b3f9f56dc0829fc47817b/code-postprocessing/cocopp/ppfigdim.py#L537). However, doing this in each script is not a good idea, as it is error-prone and makes any change painful to apply.

**Comment by paulduf** [comment]
Can't we have something like this:

```python

    @property
    def evals_string(self):
        if self.has_constraints:
            return "evaluations"
        else:
            return "$f$-evaluations"
```

at the `Testbed` level so in any caption we just call `testbedsettings.current_testbed.evals_string` to use  the right wording.
There are still some things to be discussed, like having something case-sensitive; and as of today, I find sometimes "$f$-evaluations" and sometimes "objective function evaluations", I don't know if this is for a particular purpose. The latex dollars should be converted to something in the HTML as well.

**Comment by paulduf** [comment]
Done for [the release](https://github.com/numbbo/coco/pull/2068).
