### ISSUE TITLE
random search parameter testing

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1813]
I suggest to get a few more versions of uniform random search benchmarked, which would give a little more insight into the `bbob` test suite.

Specifically, sampling uniformly in `[-b, b]**n` for `b` in `[1/2, 1, 2, 3, 4, 5, 6]`. This should be done with and w/o evaluating the origin first.

I suspect that the optimal overall random search parameter `b` is `2`, but it most likely also depends on the function. It seems in particular interesting to see how large the difference in performance is, as the volume difference covered by this parameter sweep is quite large, in particular with larger dimension.

**Comment by brockho** [comment]
Unfortunately, I forgot about this issue for quite some time, but here are the results:

![image](https://user-images.githubusercontent.com/13706996/53559327-296ae200-3b4a-11e9-8e03-d0ae880ce511.png)
![image](https://user-images.githubusercontent.com/13706996/53559374-3ee00c00-3b4a-11e9-8dcc-61fc85d235a7.png)
![image](https://user-images.githubusercontent.com/13706996/53559425-5a4b1700-3b4a-11e9-85ec-df57e38bd169.png)

The differences become less visible in larger dimensions but the main order stays the same. Note that RS-X is the RandomSearch uniformly at random in `[-X, +X]` with `0p5` meaning `0.5`  - hence, your guess that RS-2 is the best choice is certainly not true over all functions.

*As to the single functions:*
We see on the sphere that RS-4 is the best setup, for the linear function it is (obviously) RS-6 that is best while for the Griewank-Rosenbrock function (also not surprisingly from our experience) it is RS-0p5 which is the best strategy. For the rotated Rosenbrock function, it is first RS-0p5 and then in a later stage RS-1 which is best. For most other functions, there is no clear winner and multiple search ranges are very similar with RS-4 often among the top variants. For more details, please see the full data here: http://coco.gforge.inria.fr/playground/ppdata-RS/

Stay tuned for the runs that evaluate the search space origin first...

**Comment by nikohansen** [comment]
> The differences become less visible in larger dimensions but the main order stays the same.

Not really the same. RS-3 is best in 10- and 20-D and RS-2 is best in 40-D. The differences look small but they also look stable. It is also very conceivable that the true order could change with the budget. Or it might not.

**Comment by nikohansen** [comment]
The superior performance of RS-6 is weird.

**Comment by brockho** [comment]
I agree with the weird performance of RS-6 that I cannot directly attribute to a single function. Regarding the higher dimensions, I still have difficulties to see that 

> RS-3 is best in 10- and 20-D and RS-2 is best in 40-D.

except for the fact that the algorithms show up on top in the sorted legend. The differences are so small that I wrote above that they behave similar in higher dimensions.

**Comment by nikohansen** [comment]
There is a difference between _looking small_ and _being small_ though. The looks depend to a large extend on the presentation. If we zoomed into the y-axis by a factor of 20 and adjusted the line widths accordingly, the conclusion about the looks would be quite different, I think.

**Comment by brockho** [comment]
I tried to zoom in by removing the most difficult targets, so here we are:

![image](https://user-images.githubusercontent.com/13706996/53643289-f9980900-3c33-11e9-9aa5-9aed86b54c66.png)
![image](https://user-images.githubusercontent.com/13706996/53643331-12a0ba00-3c34-11e9-95b2-a7d400ea9117.png)

What I see is first, RS-1 is best, then RS-2, then RS-3, then again RS-2, then once more RS-3 and finally RS-2. But the differences are, again, rather small.

Very similar in 20-D, with the same 11 targets from 100 till 1:

![image](https://user-images.githubusercontent.com/13706996/53643477-70cd9d00-3c34-11e9-946e-6e7e00aa202a.png)

**Comment by brockho** [comment]
As promised, here is the data for the same random search variants as above but now with the origin evaluated in the first place: http://coco.gforge.inria.fr/playground/ppdata-RS-initIn0/

In addition, you see the random search also in `[-10, +10]` and `[-20, +20]`.

**Comment by nikohansen** [comment]
Just FTR, cutting away parts of the figures is not what I mean when I wrote zoom into the y-axis by a factor of 20.

**Comment by brockho** [comment]
A BBOB-2019 paper on this issue will be published in July at GECCO.
