### ISSUE TITLE
Querying the optimal value and optimal position

### ISSUE THREAD

**Issue by Yunaik** [numbbo/coco#1818]
Hello,

Thank you very much for this comprehensive tool to benchmark optimization algorithms. While using this  platform, I was wondering whether it is possible to obtain both the optimal parameter x_opt and the optimal function value f_opt. I am using the python version of coco cloned from the master branch.

Regarding the value I only found the description in [bbobdocfunctions.pdf](http://coco.lri.fr/downloads/download15.01/bbobdocfunctions.pdf)
stating that x_opt is in [-5,5]^D, and f_opt is drawn from a Cauchy distribution. However, I was not able to find a corresponding method or attribute in the class `cocoex.Problem(_interface.Problem)` from this API: [APIdocs-cocoex](http://coco.gforge.inria.fr/apidocs-cocoex/cocoex.Problem.html).

The methods `final_target_fvalue1` and `best_observed_fvalue1` are undocumented in the APIdoc, and `final_target_fvalue1`, which I assumed to be f_opt, is not implemented. Online I found earlier versions which are using `final_target_fvalue1` to determine the termination condition, however, this seemed to be have been replaced with `final_target_hit`. 

Thank you very much for your help.

**Comment by nikohansen** [comment]
Hello, and sorry for the late reply. It is on purpose that the x_opt and f_opt values are difficult to access, such that they may not be used unintentionally during the benchmarking process...

**Comment by maxhuettenrauch** [comment]
Would it be possible to make them available only in case a debug flag is set, for example?

**Comment by nikohansen** [comment]
I think it depends on the used language, whether and how it is possible to access these values. Given that the code is open source, it should always be possible though, the question is rather how much additional coding is involved.

**Comment by mudita11** [comment]
> Hello,
> 
> Thank you very much for this comprehensive tool to benchmark optimization algorithms. While using this platform, I was wondering whether it is possible to obtain both the optimal parameter x_opt and the optimal function value f_opt. I am using the python version of coco cloned from the master branch.
> 
> Regarding the value I only found the description in [bbobdocfunctions.pdf](http://coco.lri.fr/downloads/download15.01/bbobdocfunctions.pdf)
> stating that x_opt is in [-5,5]^D, and f_opt is drawn from a Cauchy distribution. However, I was not able to find a corresponding method or attribute in the class `cocoex.Problem(_interface.Problem)` from this API: [APIdocs-cocoex](http://coco.gforge.inria.fr/apidocs-cocoex/cocoex.Problem.html).
> 
> The methods `final_target_fvalue1` and `best_observed_fvalue1` are undocumented in the APIdoc, and `final_target_fvalue1`, which I assumed to be f_opt, is not implemented. Online I found earlier versions which are using `final_target_fvalue1` to determine the termination condition, however, this seemed to be have been replaced with `final_target_hit`.
> 
> Thank you very much for your help.

Hi max, I have the same question you asked. I am trying to access the optimal fitness values for each instance and dimension of the problem. Which part of the code did you amend to gain access to F_opt values?
Thanks.

**Comment by maxhuettenrauch** [comment]
Hi, I literally started implementing the functions myself using numpy in python from the equations in the documentation. If the authors of the suite allow it, I can upload it on my github.

**Comment by mudita11** [comment]
It would be great if you can share. Do you mind sharing it personally if you don't want to share publically?

**Comment by maxhuettenrauch** [comment]
You can find it here

https://github.com/maxhuettenrauch/bbob_numpy

**Comment by mudita11** [comment]
Thanks.
