### ISSUE TITLE
Rastrigin v. Bueche-Rastrigin

### ISSUE THREAD

**Issue by karroje** [numbbo/coco#1819]
I cannot see any effective difference between the implementation of these two functions (f_rastrigin and f_bueche_rastrigin) -- they appear to be identical.

**Comment by karroje** [comment]
Note also that the only documentation on this Bueche-Rastrigin doesn't make sense.  Looking at the definition [here](https://learning.projects.x20web.corp.google.com/vizier/static/bbobdocfunctions.pdf), there seems to be a circular dependency.  (s_i is dependent on z_i, and z_i is dependent on s_i.)

**Comment by nikohansen** [comment]
> I cannot see any effective difference between the implementation of these two functions (f_rastrigin and f_bueche_rastrigin) -- they appear to be identical.

To me they look different. In particular only one of them calls the line 
```C
problem = transform_vars_brs(problem);
```
> Note also that the only documentation on this Bueche-Rastrigin doesn't make sense. Looking at the definition here, there seems to be a circular dependency. (s_i is dependent on z_i, and z_i is dependent on s_i.)

Thanks for pointing outing out this notational glitch. It seems easy to resolve by noting that `s` uses only the sign of `z` in its definition, and this sign does not depend on `s`.

**Comment by nikohansen** [comment]
There is a comment in the code: ``Documentation: the condition should be Tosz(x_i - x_i^opt) > 0 in stead of z_i > 0`` which we should also check, see also #837, #1819.
