### ISSUE TITLE
Postprocessing failing with matplotlib 3.0.0

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#1825]
Simply running `python -m cocopp exdata/scipy-optimize-fmin` gives me this warning:

```ECDF graphs per function...
/home/pol/.pyenv/versions/cma/lib/python3.6/site-packages/matplotlib/tight_layout.py:177: UserWarning: The left and right margins cannot be made large enough to accommodate all axes decorations. 
  warnings.warn('The left and right margins cannot be made large '
  done (Tue Nov 27 10:59:29 2018).
```

This more of an errof. Find below a screenshot on the resulting graphs processed.

I could solve the issue downgrading matploblib to 2.2.3. Maybe this should be put in the requirements?

![screenshot from 2018-11-26 18-26-52](https://user-images.githubusercontent.com/27226228/49074614-4c2ce800-f235-11e8-8115-e03cdd3ded6f.png)

**Comment by nikohansen** [comment]
The call of `tight_layout` is in `ppfig.save_figure`. The first thing to try would be to call this function only if ``plt.matplotlib.__version__[0] < '3'``.

**Comment by nikohansen** [comment]
A preliminary fix is in the `development` branch. I assume that there are now a few more (hopefully smaller) adjustments which need to be done for this new major `matplotlib` version.

**Comment by ttusar** [comment]
Post-processing random search results on the `bbob` suite using `matplotlib v3.0.2` now works (as in, it does not fail and produces results), but is not perfect:

<img width="703" alt="image" src="https://user-images.githubusercontent.com/13745935/50346260-188e6680-0532-11e9-9269-515fa8205259.png">

See how the `xlabels` are cut? The same happens in all plots, see for example these:

<img width="426" alt="image" src="https://user-images.githubusercontent.com/13745935/50346442-a8ccab80-0532-11e9-8133-d7db2b5432cf.png">

Additionally, the following deprecation warnings are output:

````
/Users/tea/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py:3221: MatplotlibDeprecationWarning: The `xmax` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use `right` instead.
  alternative='`right`', obj_type='argument')
/Users/tea/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py:3215: MatplotlibDeprecationWarning: The `xmin` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use `left` instead.
  alternative='`left`', obj_type='argument') 
/Users/tea/anaconda3/lib/python3.6/site-packages/cocopp-2.2.1.236-py3.6.egg/cocopp/pplogloss.py:339: MatplotlibDeprecationWarning: numpy.percentile
  wisk_lo, q1, med, q3, wisk_hi = mlab.prctile(d, [10, 25, 50, 75, 90])
/Users/tea/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py:3604: MatplotlibDeprecationWarning: The `ymin` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use `bottom` instead.
  alternative='`bottom`', obj_type='argument')
/Users/tea/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py:3610: MatplotlibDeprecationWarning: The `ymax` argument was deprecated in Matplotlib 3.0 and will be removed in 3.2. Use `top` instead.
  alternative='`top`', obj_type='argument')
````

At least four of those should be rather easy to fix...

**Comment by nikohansen** [comment]
I hope all problems are fixed now in the `development` branch. Feel free to prove me wrong ;-)
