### ISSUE TITLE
Sub-optimal automatical placement of legends

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1827]
Here is the example (when postprocessing BFGS-P-StPt):

![image](https://user-images.githubusercontent.com/13706996/49640524-1a263d80-fa0e-11e8-9ea8-ce0c2e3cef57.png)

The legend should be optimally placed on the top left, a bit smaller and transparent.

**Comment by nikohansen** [comment]
This seems to be OK in the `pdf` and `svg`. It may be a problem with the `eps` only?

**Comment by nikohansen** [comment]
As a side note, I also do not understand where in the code the notched bars are plotted. `ppfigdim.plot_a_bar` seems to be able to do this but it seems never to be called.

**Comment by brockho** [comment]
The above also happens in the pdf. Here the old version (from the coco-docs paper):
![image](https://user-images.githubusercontent.com/13706996/72217474-838c5000-352e-11ea-9a70-b4dfc02dc5e4.png)

And here the newly created plot:

![image](https://user-images.githubusercontent.com/13706996/72217477-92730280-352e-11ea-8cd2-5e9509d10fba.png)

[I guess that the axes labels have been added manually by @ttusar]

**Comment by brockho** [comment]
TODO for myself: add the axis labels automatically (via a switch) for the coco-docs paper.

**Comment by brockho** [comment]
The most recent commit in the development branch produces this:

![image](https://user-images.githubusercontent.com/13706996/72806671-f182f680-3c55-11ea-8b34-edc83d2e9fb5.png)

It looks better and much closer to the original plot above. Shall we close the issue?

**Comment by brockho** [comment]
Closed in agreement with @ttusar and @nikohansen.
