### ISSUE TITLE
Annotation of scatter plots

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1837]
The x- and y-labels of the scatter plots should give the algorithm name instead of "log10(# evaluations)".

Rationale: without knowing the annotation we gain (almost) zero information from the plots. Even with lots of experience, I always have to check the caption several times to be certain which algorithms is on which axis.

**Comment by ttusar** [comment]
Why not have both?

**Comment by brockho** [comment]
Are we happy with the current output?
![image](https://user-images.githubusercontent.com/13706996/81058275-65c46b80-8ece-11ea-8a72-2d836fb5c458.png)

I remember that we said at some time to decrease the font size in the axis labels.

**Comment by ttusar** [comment]
I think we came to the conclusion that it depends on whether you are looking at (1) separate plots (or at plots via the html page) or (2) a table of small plots in the paper. Since we want to support (2), we decided on keeping the large fonts.

**Comment by nikohansen** [comment]
The fontsize of the labels must IMHO be slightly smaller: they should not visually dominate the title.

**Comment by brockho** [comment]
The latest code in the development branch addresses the above. A new issue to adapt the LaTeX templates---if needed---has been added (#1962).
