### ISSUE TITLE
Failed verify-postprocessing test

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#1847]
The verify-postprocessing test fails with the following information. Any help would be appreciated...
````
Validation failed! File latex_commands_for_html.html should be regenerated!
Original line:         in number of function evaluations. For each function, the <span class="roman">aRT</span>&nbsp;
Generated line:         in number of function evaluations in different dimensions. For each function, the <span class="roman">aRT</span>&nbsp;
````

**Comment by nikohansen** [comment]
Looks like the cause is some changed captions. I assume that using the`preparetexforhtml.py` script to regenerated the `latex_commands_for_html.html` should fix this, but I am not 100% sure.

**Comment by ttusar** [comment]
`preparetexforhtml.py` worked, thanks.
