### ISSUE TITLE
Wrong implementation of large-scale Griewank-Rosenbrock 

### ISSUE THREAD

**Issue by kostasvar** [numbbo/coco#1851]
The following were observed in the (tested) instances of the `bbob-largescale` suite:

- The optimum in the current implementation appears to be almost equal to zero in all coordinates except one. This coordinate is always the same for a specific instance, and the distance the origin is the same for all instances in a given dimension. The latter distance increases with the dimension (observed for 20 and 40D). 

- The level sets show a higher conditioning close to the origin along this coordinate and a regularity in valley locations, as in the figure below for `x_3` (the black dot is the optimum location). 

- In [this](https://github.com/numbbo/coco/blob/5936a47a1a5f36833e30bf6fb4e1628cdff43048/code-experiments/src/f_griewank_rosenbrock.c#L194) line, during the loop the variable `tmp` initially has zero value, then increases and at the end of the loop again decreases to zero. 

<img width="645" alt="screenshot 2019-02-19 at 18 49 32" src="https://user-images.githubusercontent.com/32420824/53036039-26e7f880-3477-11e9-9820-e60d80d2198b.png">

Even though this is probably not related, a difference in the definition of the `bbob` and `bbob-largescale` rotated Rosenbrock functions is described in https://github.com/numbbo/coco/issues/1733 . This transformation difference was not implemented in the `bbob-largescale` Griewank-Rosenbrock function.

**Comment by ttusar** [comment]
> * In [this](https://github.com/numbbo/coco/blob/5936a47a1a5f36833e30bf6fb4e1628cdff43048/code-experiments/src/f_griewank_rosenbrock.c#L194) line, during the loop the variable `tmp` initially has zero value, then increases and at the end of the loop again decreases to zero.

Just to clarify, between being initialized at zero and then falling back to zero, the value of `tmp` increases and decreases non-monotonously.

**Comment by nikohansen** [comment]
FTR, @ttusar computed the `best_parameter` for f19, dimension 80, instance 14. The two values which are not close to zero assume `3.16227766016837641416` which is essentially `sqrt(10)`. This might give a debugging hint.

**Comment by ttusar** [comment]
Some additional details that could be helpful for debugging can be found here: https://gitlab.inria.fr/randopt/tea/issues/15

**Comment by nikohansen** [comment]
May now be fixed, thanks to @ttusar
