### ISSUE TITLE
Error when running matlab setup file for bbob-biobj-matlab-smsemoa example

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#1853]
When I run the "setup.m" file in the example folder I have compilation errors (with g++):

> For online documentation, see https://www.mathworks.com/support
> For product information, visit www.mathworks.com.
>  
> compiling Hypervolume.cpp...Building with 'g++'.
> Error using mex
> /home/pol/workspace/1+1_mo_cma_es/hv.cpp: In function ‘void mexFunction(int, mxArray**, int, const mxArray**)’:
> /home/pol/workspace/1+1_mo_cma_es/hv.cpp:31:32: error: cannot convert ‘const mwSize* {aka const long unsigned int*}’ to ‘const int*’ in assignment
>   dims = mxGetDimensions(prhs[0]);
>                                 ^
> /home/pol/workspace/1+1_mo_cma_es/hv.cpp:37:34: error: cannot convert ‘const mwSize* {aka const long unsigned int*}’ to ‘const int*’ in assignment
>   dims_r = mxGetDimensions(prhs[1]);
>                                   ^
> 
> 
> Error in setup (line 8)
> mex -I. hv.cpp Hypervolume.cpp

I use Debian 9 and g++ (Debian 6.3.0-18+deb9u1) 6.3.0 20170516.

**Comment by ttusar** [comment]
I can duplicate the problem

**Comment by nikohansen** [comment]
I am slightly lost which step of the installation we are talking about. Is it that 

```
python do.py run-matlab
```

calls `setup.m` which then fails?

**Comment by brockho** [comment]
The problem seems to lie in the hypervolume code that is borrowed from the Shark library and has nothing to do directly with COCO.

**Comment by paulduf** [comment]
In the do.py file this refers to the run-matlab-sms method. but when I run this, the program is stuck after prnting: 

> RUN	matlab -nodisplay -nosplash -r setup, exit in code-experiments/examples/bbob-biobj-matlab-smsemoa

The error I show comes from a direct call `matlab -nodisplay -nosplash -r setup`

**Comment by ttusar** [comment]
The SMS-EMOA example fails. I already have a fix.

**Comment by paulduf** [comment]
> The problem seems to lie in the hypervolume code that is borrowed from the Shark library and has nothing to do directly with COCO.

I agree but then it should be either solved or removed from the examples ?

**Comment by brockho** [comment]
If @ttusar has a fix, that's the best thing to proceed. We had never tested the Matlab code under a non-Windows non-MacOS operating system (and therefore also never claimed that it should work :-), see [here](https://github.com/numbbo/coco/blob/master/code-experiments/build/matlab/README.md))

**Comment by ttusar** [comment]
I have just created a pull request with the fix (https://github.com/numbbo/coco/pull/1854). When the tests pass, we need to merge it into the development branch.

**Comment by ttusar** [comment]
Merged
