### ISSUE TITLE
ModuleNotFoundError: No module named 'cocoex'

### ISSUE THREAD

**Issue by idodan1** [numbbo/coco#1858]
I followed the instructiones for "Getting Started" with coco https://github.com/numbbo/coco#getting-started- but when I run on the cmd the command:
` python do.py run-python`
I keep getting this exception:

```
PYTHON  example_experiment.py bbob in code-experiments\build\python
ERROR: return value=1
Traceback (most recent call last):
  File "example_experiment.py", line 42, in <module>
    import cocoex
ModuleNotFoundError: No module named 'cocoex'`

```
Not sure what I did wrong, hope someone could help

**Comment by nikohansen** [comment]
Maybe you could paste the full output? `python do.py run-python` is supposed to install `cocoex` before the example experiment is executed, so maybe something went wrong during the installation.

**Comment by idodan1** [comment]
deleting and redownloading coco-master did the trick I guess somthing went wrong with the first insallation. thanks
