### ISSUE TITLE
rungeneric.py line 25 Attempted relative import in non-package

### ISSUE THREAD

**Issue by jorgecervanteso** [numbbo/coco#1865]
when I run rungeneric.py I get 

  File "c:\users\usuario\downloads\coco-2.3\code-postprocessing\cocopp\rungeneric.py", line 25, in <module>    from . import genericsettings, testbedsettings, rungeneric1, rungenericmany, toolsdivers, bestalg, archiving
ValueError: Attempted relative import in non-package

What does it mean?

Thanks

**Comment by brockho** [comment]
`rungeneric.py` is not supposed to be called directly. Try 
```
python -m cocopp ALG1 ALG2 ALG3 ...
```
instead (after installing the `cocopp` module via `python do.py install-postprocessing`). See the [Getting Started](https://github.com/numbbo/coco#getting-started-) section of the [README.md](https://github.com/numbbo/coco/blob/master/README.md) for further details.

**Comment by jorgecervanteso** [comment]
Thanks a lot. It worked. I was following an outdated document. 
:)
