### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1874]
The first link of http://bbobbiobj.gforge.inria.fr to this repository is broken http://bbobbiobj.gforge.inria.fr/github.com/numbbo/coco and I can't fix it myself, because I don't have access to this project.

**Comment by brockho** [comment]
I just did the change.

FYI, you should also have the access (with your GForge account). You have to access the `scm.gforge.inria.fr` server and then go to the `/home/groups/bbobbiobj/htdocs` folder.

**Comment by nikohansen** [comment]
That's what I tried, I cannot edit files in this folder. The project is also not listed in my projects.
