### ISSUE TITLE
Simulated restarts on the biobjective suites

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1877]
We should consider to turn off simulated restarts for the biobjective suites, unless we are convinced that the instances and targets of the instances are in effect similar/comparable.

**Comment by nikohansen** [comment]
Now implemented in the development branch via attribute `testbedsettings.Testbed.instances_are_uniform` which is set to `False` for the subclass `GECCOBiObjBBOBTestbed`.

Needs to get some manual/visual testing.

**Comment by brockho** [comment]
Overall, the change looks okay. I found, however, some plots where turning off the simulated restarts also changes the graphs "before the cross":
[pprldmany_f019_20D.pdf](https://github.com/numbbo/coco/files/3111319/pprldmany_f019_20D.pdf)
[pprldmany_f019_20D.pdf](https://github.com/numbbo/coco/files/3111324/pprldmany_f019_20D.pdf)
compare for example the blue N-II-11.

**Comment by nikohansen** [comment]
This would be consistent if the budget is not the only termination condition of N-III-11 and some runs stop early. Otherwise it could also be just by chance, though it doesn't exactly look like chance (somewhat easy to check).

**Comment by brockho** [comment]
As much as I know, there is only the budget that determines the termination of NSGA-III (and all the other algorithms) in [platypus](https://platypus.readthedocs.io/en/latest/). At least you cannot set any other criterion from the outside.

I rerun the postprocessing a few times to see the effect (and variance) of the simulated restarts, so here are three additional instances of the above ECDF:

[pprldmany_f019_02D-run1.pdf](https://github.com/numbbo/coco/files/3116422/pprldmany_f019_02D.pdf)
[pprldmany_f019_20D-run2.pdf](https://github.com/numbbo/coco/files/3116423/pprldmany_f019_20D.pdf)
[pprldmany_f019_20D-run3.pdf](https://github.com/numbbo/coco/files/3116708/pprldmany_f019_20D.pdf)


The variance of the simulated restarts is rather large for all displayed algorithms which tells us that turning off the simulated restarts is indeed a good idea.

**Comment by nikohansen** [comment]
The variance before the restarts is in principle unnecessary and related to [this issue](https://github.com/numbbo/coco/issues/735#issue-138201919) which isn't fixed (yet). For the `instances_are_uniform == False` case the variance is entirely removed if and only if `nbsamples % nbtrials == 0`.

**Comment by brockho** [comment]
I moved up the priority of the related issue #735 such that this one here can be closed.
