### ISSUE TITLE
logger implementation

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1880]
Ideally, the logger / observer implementation should write nothing _before_ the observed problem is evaluated for the first time. This prevents empty trials and/or files and [this error](https://github.com/numbbo/coco/issues/1879) when a problem is instantiated, but for some reason never used.

**Comment by ttusar** [comment]
I don't think I understand the problem. If the code below is executed, an empty result folder is created, but nothing is written into it (no files are made). Is that already an issue?

```Python
import cocoex
suite = cocoex.Suite("bbob", "", "")
observer = cocoex.Observer("bbob", "")
for p in suite:
    p.observe_with(observer)
    print(p.name)
```

**Comment by brockho** [comment]
Is it difficult to create the folder only at the very first evaluation? In principle, one and the same observer should write only into a single folder and data from different functions are written to separate files or am I wrong?

**Comment by ttusar** [comment]
Sorry, I wasn't detailed enough in my response. Only the `exdata` folder is created in the case above. I can have a look to see how much "work" it would entail to change this...

**Comment by nikohansen** [comment]
This looks like the correct behavior to me. As long as no evaluation was done, it is better to write no file than to write a file with nothing useful in it.
