### ISSUE TITLE
Observer unknown for bbob-mixint on a distant machine

### ISSUE THREAD

**Issue by DahitoMA** [numbbo/coco#1894]
I try to use the cocoex.Observer on the bbob-mixint suite on a distant machine using linux. It is saying 'COCO WARNING: Unknown observer!'
I am using python 2.7.16 from Anaconda and to this day the coco version is up-to-date with the master branch. Here is the code: 

```python
import cocoex
suite = cocoex.Suite('bbob-mixint', 'instances: 1-5', 'dimensions: 5, 10, 20')
observer = cocoex.Observer('bbob-mixint', 'result_folder')
```

**Comment by nikohansen** [comment]
How about using the (default) `'bbob'` observer? Isn't that supposed to work, @ttusar ?

**Comment by ttusar** [comment]
Yes, there's no `'bbob-mixint'` obsever, just the `'bbob'` one. 

I think the confusion might come from some examples where the suite name is automatically used also as the observer name (I'm saying this on the top of my head - I think I saw it somewhere).

**Comment by brockho** [comment]
I found the problem. We did not implement the automatic map from the new observer names to the old observers. Fix is on the way.

**Comment by ttusar** [comment]
What new observers?

**Comment by ttusar** [comment]
Oh, I see now what you did...

**Comment by brockho** [comment]
"Observer names": 'bbob-mixint' and 'bbob-biobj-mixint', see https://github.com/numbbo/coco/commit/5666592b3af1f2ea293309afae564fde6f06c190

**Comment by ttusar** [comment]
I never thought we would be giving new names to old observers. I guess it's practical, but it just never occurred to me...
