### ISSUE TITLE
Wrong sorting of data archive entries and missing warning/error

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1900]
```python
cocopp.archives.all('bfgs')
['bbob-noisy/2009/BFGS_ros_noisy.tgz',
 'bbob/2009/BFGS_ros_noiseless.tgz',
 'bbob/2012/DE-BFGS_voglis_noiseless.tgz',
 'bbob/2012/PSO-BFGS_voglis_noiseless.tgz',
 'bbob/2014-others/BFGS-scipy-Baudis.tgz',
 'bbob/2014-others/L-BFGS-B-scipy-Baudis.tgz',
 'bbob/2018/BFGS-M-17.tgz',
 'bbob/2018/BFGS-P-09.tgz',
 'bbob/2018/BFGS-P-Instances.tgz',
 'bbob/2018/BFGS-P-StPt.tgz',
 'bbob/2018/BFGS-P-range.tgz']
```
sorts the noisy entry first, hence `"bfgs!"` does not give the data it used to.

The main routine then also processes the data from different suites with warnings like `cocopp/pproc.py:2825: UserWarning: No data for algorithm exdata/random_search_on_bbob_budget0002xD in 2-D`. Then only the data from the first suite show up.

**Comment by nikohansen** [comment]
The user oriented fix for the sorting problem: rather use `"bbob/.*bfgs!` instead of "bfgs!".

**Comment by brockho** [comment]
I have the feeling that the problem appeared when we replaced the usage of the old internal list (within the code) with the usage of the archive definition file.

While the new algorithm list from the archive definition file seems sorted (`bbob-noisy/...` comes before any `bbob/...`), the old list was not sorted but had the `bbob/` entries first (probably for historic reasons).

**Comment by nikohansen** [comment]
Maybe a solution is to sort first for `s.split('/')[0]`. As the sorting comes from the archive creation, I will change the creation code at line 401 of `cocopp.archiving` from

```python
file_.write(repr(sorted(res)).replace('L)', ')').replace('(', '\n('))
```

to  

```python
file_.write(repr(sorted(res, key=lambda s: (s.split('/')[0], s))).replace('L)', ')').replace('(', '\n('))
```

**Comment by nikohansen** [comment]
See #1907.
