### ISSUE TITLE
Archive path-name length under Windows

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1903]
To long paths are bailing out under Windows, see e.g. https://github.com/numbbo/coco/issues/1901.

I still really like the way how the path is chosen now, in that the URL of the archive can be easily retrieved from the path and vice versa. What could be a possible solution then?

**Comment by brockho** [comment]
I solved the issue for me by removing any available (subfolder) structure within the `.tgz` that we officially provide. The maximal Windows path length is 260 characters which should now be okay for most people. 

The problem occurred from submissions that had quite long folder names (and then a few of them nested). Maybe moving to `.zip` in the future might help as well (then, the `.tar` folder is not created anymore under Windows. Probably, we should add a corresponding comment in the data archive's `create` docstring?
