### ISSUE TITLE
doctest not executed?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1905]
It seems that the `cocopp.archiving` doctests [are not executed](https://github.com/numbbo/coco/issues/1904#issuecomment-510863993)?

**Comment by brockho** [comment]
For my latest change (which was independent of the archiving module), the tests were executed, I guess, and unfortunately gave quite some errors :-(

See https://ci.appveyor.com/project/brockho/coco/builds/26237670/job/iy1abjs5bneoiif6

**Comment by nikohansen** [comment]
The above link doesn't work for me.

```python
import doctest
import cocopp
doctest.testmod(cocopp.archiving)
```
gives for me a user warning due to an inconsistent archive and
```
TestResults(failed=0, attempted=88)
```

**Comment by brockho** [comment]
Does the user warning go away after you run the `cocopp.archives.update_all()`? I also got initially a warning about an outdated archive definition file when I uploaded the newly created one to gforge.

**Comment by nikohansen** [comment]
No user warning currently, and I also see that the doctests seem to work on circleci and appveyor.
