### ISSUE TITLE
Automatically creating new function suites

### ISSUE THREAD

**Issue by CIGbalance** [numbbo/coco#1915]
I don't know if something like this already exists, but I wrote a script that automatically creates the files required to create a new function suite using the interface Tea implemented for GBEA. It's pretty simply just uses templates for all files and required code. Thought I'd leave it here in case it helps. Still need to do the same for post-processing.

You can find the scripts in the GBEA CodeOcean capsule: https://codeocean.com/capsule/2600355/tree/v1

- code/utils/create-suite.sh
- code/utils/build-local.sh

**Comment by Yash-Pisat** [comment]
@CIGbalance  Hello, I am trying to create a new suite and I am facing some issues. Can you tell me, how do I use your scripts to create a custom suite which include a single polynomial function.

**Comment by CIGbalance** [comment]
Sorry, I am not actively maintaining the linked code anymore and lots of the interfaces here have changed. So I assume that is why it is not working anymore. I will close this issue now. Might be best to contact one of the maintainers of this repo to figure out how to add new suites.
