### ISSUE TITLE
Cannot find `mlab.prctile`

### ISSUE THREAD

**Issue by giuse** [numbbo/coco#1917]
https://github.com/numbbo/coco/blob/9f117c4b6e3520e349c88c30690c4c0c0a1f34c3/code-postprocessing/cocopp/pplogloss.py#L340 uses `mlab.prctile`, which is not available in recent versions of `matplotlib`. The [deprecation notice](https://matplotlib.org/3.1.1/api/api_changes.html) suggests to use `numpy.percentile` instead.

**Comment by brockho** [comment]
fixed with recent pull request by @giuse
