### ISSUE TITLE
Open TODOs for problems with unknown optima

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1921]
Here, we should collect the open TODOs towards supporting (well) test suites with unknown optima.

**Comment by brockho** [comment]
* [ ] "equidistant targets" logger implemented/tested
* [ ] JASON file (either in cocopp or cocoex) that contains all best-so-far/estimations of optimal f-values (similar to the current values in C for the logger)
   * using all known algorithms or also simply random search as reference should work (nice-to-have: code to extract these best values)
   * [ ] needs to be read in by the postprocessing to adjust the read-in target values (probably the most time-consuming part because of the postprocessing)

**Comment by nikohansen** [comment]
File format for target precision reference value and usage suggestion:
`bbob_target_precision_references.py` file:
```
# -*- coding: utf-8 -*-
"""Target reference values for the bbob testbed (they are all zero ;-)"""
# dictionary keys are function nb, dimension, instance number
target_range_hint = [1e-8, 100]
values = {1: {2: {1: 0.0, 2: 0.0, ...
```
Usage in Python:
```python
from bbob_target_precision_references import values 
values[1][20][0]  # function, dimension, instance
0.0
```

**Comment by brockho** [comment]
After today's discussion with @ttusar and @nikohansen, we agree that the above open issues are not needed anymore right now. We therefore close the issue.
