### ISSUE TITLE
Document how to interface to another language

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1925]
It will be nice to have a clear documentation of what has to be done when somebody wants to interface COCO to a new (algorithm) language:
* interface kind of everything in coco.h
* write an example experiment

With @ttusar and @nikohansen, we agreed today that the best way seems to be the C documentation here: http://numbbo.github.io/coco-doc/C/ with a link to it from the `howtos/` folder.

**Comment by ttusar** [comment]
I have just updated the file https://github.com/numbbo/coco-doc/blob/gh-pages/docs/coco-doc/C/README.md with this information. However, running `doxygen` on my computer does not produce nice results as the file headers seem to be broken. Can someone else run `doxygen` and publish the resulting files?

**Comment by brockho** [comment]
done
