### ISSUE TITLE
Solve Appveyor Issue

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1930]
Since some time, the python 2.7 tests do not run through any more on Appveyor: https://ci.appveyor.com/project/nikohansen/coco-28e3ab1txqzfiw9/builds/29922841/job/ek6f2mk3k8l7l28r ("DLL fails to load"). Shall we simply get rid of these tests as Python 2 will not be maintained anymore?

**Comment by nikohansen** [comment]
It seems to be a `numpy` related problem under Python 2.7 and I have no idea how to fix this. Consider to drop the Python 2 test makes sense to me.

**Comment by nikohansen** [comment]
Fixed with df7d7d29, the culprit was installing `numpy` with `conda`.
