### ISSUE TITLE
Double Testing on Appveyor

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1932]
There seem to be two Appveyor projects linked to COCO

https://ci.appveyor.com/project/nikohansen/coco-j53aywshl8udzvb
https://ci.appveyor.com/project/nikohansen/coco-28e3ab1txqzfiw9

for no apparent reason to me. Does anyone have an insight as to why this is so and whether/how we should/could remove one of them?

**Comment by ttusar** [comment]
No idea

**Comment by nikohansen** [comment]
We changed the trigger, such that we still have several projects but triggered on different events.
