### ISSUE TITLE
DataSet: get_suite vs. testbed_name

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1933]
The `DataSet` class has both `get_suite()` (which returns a string!) and `testbed_name` (which also returns a string). This is (i) highly confusing, (ii) not really maintainable and (ii) not needed. Better would be, from my point-of-view, to have only the `get_suite()` but which actually returns the corresponding suite instance (like `testbedsettings.current_testbed`). With the return value, one can get easily the test suite's name.

This issue will affect a lot of code and thus has to be done with care, but in terms of maintainability, it will help us a lot, I suppose.

Background: so far, every `DataSet` instance kept both `get_suite()` and `testbed_name` constant throughout its life. With the filter functionality, however, it is needed to change those after loading, which is why it gets almost unmaintainable.

**Comment by nikohansen** [comment]
`get_suite()` is a very Javaesk (and misleading) interface for returning a name.

The decision should depend on what a suite actually "is" or meant to be. `suite` could be a property which "links to" the suite instance (or type/class?).

**Comment by brockho** [comment]
The latest PR (#1963) has a fix to this, making things clearer and hopefully easier to use. A DataSet has now solely a property `suite_name`, returning a string with the suite name such as `"bbob"` or `"bbob-largescale"`. The already existing `testbedsettings.get_testbed_from_suite` can be used to map a `suite_name` string into the corresponding `Testbed` class (currently only used in `testbedsettings.py` itself). The former `get_suite` and `testbed_name` have been removed.

**Comment by brockho** [comment]
Fixed now in `development` branch.
