### ISSUE TITLE
Scatter plot tick labels too large for bbob and bbob-largescale data?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1934]
I thought that the axis labels in our scatter plots show the exponent of the `log10(#f-evals)`, however, when comparing for example BIPOP-CMA-ES (on `bbob`) with LBFGS (on `bbob-largescale`), the scatter plots show for some functions surprisingly high values on the axes:

![image](https://user-images.githubusercontent.com/13706996/72205779-30ab8d80-3487-11ea-9c13-1e4e944ca51d.png)

Is this to be considered a bug or are these values really that high (I imagine it is the former)? It almost looks to me as if the dimensions (from 2 to 640) play a role here for the axes labels, but that would be even weirder.

**Comment by nikohansen** [comment]
This doesn't look like the scatter plots that I have in mind. The above plot looks like generated with `loglog(data)`, while the original scatter plots are generated like `plot(log10(data))` and use `log10(data)` as tick annotations.

**Comment by nikohansen** [comment]
OK, I think the problem is that we see the automatically generated minor ticks, because the overall scale of the data is small.

**Comment by brockho** [comment]
Just checked, the problem still appears in the current version (development branch):
![image](https://user-images.githubusercontent.com/13706996/81057712-3fea9700-8ecd-11ea-8096-b1875b3596a6.png)

**Comment by nikohansen** [comment]
```python
    l = matplotlib.ticker.FixedLocator([])
    gca().xaxis.set_minor_locator(l)
```

**Comment by nikohansen** [comment]
We added a marker at log `1, 1` (by adding a target), which fixes both problem.

**Comment by brockho** [comment]
Actually, the current version has the marker at `(2,2)` but nevertheless, the issue can be closed. Note that a new issue to adapt the LaTeX templates---if needed---has been added (#1962).
