### ISSUE TITLE
Error while using COCO problem in python: ValueError: Buffer has wrong number of dimensions (expected 1, got 2)

### ISSUE THREAD

**Issue by jillianlee** [numbbo/coco#1941]
I'm using the current version in Python 3.7 and I'm trying to experiment with Bayesian Optimization (packaged GPyOpt).

I keep getting `ValueError: Buffer has wrong number of dimensions (expected 1, got 2)` coming from the cython Interface.pxy and I've been working at it for a while and I can't figure out why. I'm not an experienced python programmer and I'm not sure how to debug this.

The error is coming up before the optimization is supposed to have run. The error is coming up at the creation of the Bayesian Optimization class, yet the run_optimization()  function has not been run on that class yet so I cant figure out how to stop that, or why the buffer error is happening.
`def bayesianOpt (problem):` 
`    ` `domain = [{'name': 'var_1', 'type': 'continuous', 'domain': 
               (problem.dimension*(-5), problem.dimension*(5)), 'dimensionality': problem.dimension}]`
`    ` `model=BayesianOptimization(problem, domain=domain, acquisition_optimizer_type='CMA')`
`    ` `model.run_optimization(max_iter=15)`
`    ` ` xopt=model.x_opt`
`    ` `return xopt`
...

`fmin=bayesianOpt`
...
`elif fmin is bayesianOpt:`
`    ` `xopt=fmin(problem)`

I would really appreciate any insight. Thanks, and sorry for my inexperience.

![Screenshot (99)](https://user-images.githubusercontent.com/56376166/73804954-56306c00-4793-11ea-859d-4cf5f2c09134.png)

**Comment by brockho** [comment]
Thanks for reporting this. It looks, though, that the problem is more likely on the algorithmic side and not in COCO. 

What does your algorithm expect as return value from the objective function? COCO returns (in the single-objective case, a single value and in the bi-objective case a list of two objective vectors, but it cannot be directly used to return `f_evals` and `cost_evals` as in the `f_evals, cost_evals = self._eval_func(x)` line in the above error message. For more information, please check the [COCO Python API](https://coco.gforge.inria.fr/apidocs-cocoex/cocoex.html) and in particular the [documentation of the Python `cocoex.Problem` class](https://coco.gforge.inria.fr/apidocs-cocoex/cocoex.Problem.html).  

If you need further help, please provide us with more details, in particular on how you call the COCO objective function within your `BayesianOptimization` code.

**Comment by jillianlee** [comment]
Ah I see, thank you for that clarification.

Yes the `BayesianOptimization` module I'm currently using actually needs the function definition. Previously I was passing `problem`. 

I have looked through the `cocoex.Problem` class documentation. Is there a way I can use the problem ID to obtain the problem function definition to pass to the optimizer? Or could I use the `Suite` class to obtain the problem function definition?

Thank you!

For clarification, here is a toy example of the functioning Bayesian Optimization class:
`def f(x): `
`    ` `return (6*x*-2)**2*np.sin(12*x-4)`
` `
`domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (0,1), 'dimension':2}]`
`prob = BayesianOptimization(f=f, domain=domain)`
`prob.run_optimization(max_iter=15)`

**Comment by brockho** [comment]
I see as well :-)

In principle, running on a `bbob` function should be as simple as 
```
import cocoex
mysuite = cocoex.Suite('bbob', '', '')
myproblem = mysuite.get_problem by_function_dimension_instance(2, 10, 1) # get instance 1 of f_2 in dimension 10

domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (myproblem.lower_bounds[0], myproblem.upeer_bounds[0]), 'dimension':myproblem.dimension}]
prob = BayesianOptimization(f=myproblem, domain=domain)
prob.run_optimization(max_iter=15)
```

because a COCO problem behaves exactly like the above `f(x)` - it returns the function value `f(x)` when called with `x`.

**Comment by jillianlee** [comment]
This code script actually gives a new error, earlier in the `interface.pyx` script now:
![Screenshot (101)](https://user-images.githubusercontent.com/56376166/73902480-ffdf2e00-4863-11ea-9bac-7e5bacc51638.png)


Is there a specific function format that COCO expects that this GPyOpt module does not align with? I have had success with the CMA module which returns the xopt, which I can get from the BayesianOptimization module after having created the problem instance, but the code gets stopped due to error before the xopt can be returned:
`domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (myproblem.lower_bounds[0], myproblem.upeer_bounds[0]), 'dimension':myproblem.dimension}]`
`prob = BayesianOptimization(f=myproblem, domain=domain)` <-- ERROR
`prob.run_optimization(max_iter=15)`
`xopt=prob.x_opt`

Sorry for all the questions, thank you for your help!

**Comment by brockho** [comment]
Hi again,

The `ValueError` you get now suggests that there is something going wrong with the dimension of the `x`, you put into the objective function. Can you check that what you put into the COCO problem is actually a vector of length `dimension`?

I get the very same error when I try to put an `x` of wrong (i.e. here too high) dimension into a COCO problem:
```
ValueError: Dimension, `np.size(x)==20`, of input `x` does not match the problem dimension `number_of_variables==10`.
```

**Comment by jillianlee** [comment]
Hi Again,

I have fixed that now, you were correct, I fed in a new X input and got rid of that error. The original error I posted about though is now back again. I'm still getting `ValueError: Buffer has wrong number of dimensions (expected 1, got 2)` with the same traceback as from before, using the code you provided.

`mysuite = cocoex.Suite('bbob', '', '')`
`myproblem = mysuite.get_problem_by_function_dimension_instance(2, 10, 1)`
`domain = [{'name': 'var_1', 'type': 'continuous', 'domain': (myproblem.lower_bounds[0], myproblem.upper_bounds[0]), 'dimension':myproblem.dimension}]`
`prob = BayesianOptimization(f=myproblem, domain=domain, X=np.ndarray(shape=(2, 10)))` <- ERROR 
`prob.run_optimization(max_iter=15)`

**Comment by brockho** [comment]
What exactly is this `X=np.ndarray(shape=(2, 10))` in the line, marked with "ERROR"? It not so clear how this two-dimensional array can work well with the COCO problem, because a COCO problem assumes as `x` a 1-dimensional array or a 1-dimensional list as input.

**Comment by jillianlee** [comment]
The documentation for GPyOpt states that a parameter `X – 2d numpy array containing the initial inputs (one per row) of the model` can be defined. Not sure why it wants a 2D array but it is a `2xDimension` array of random numbers as initial X inputs. It is not a mandatory parameter though, but when run without it, I get the aforementioned error `ValueError: Dimension, np.size(x)==20, of input x does not match the problem dimension `number_of_variables==10`.

If not done in this method, how else can I give a vector of length `dimension` to the COCO objective problem to get rid of that value error?

**Comment by nikohansen** [comment]
Chiming in late and I might not got everything right at first glance, but the easiest way to negotiate between the `BayesianOptimization` class and the `cocoex` module may be to write  a small function wrapper that transforms the solution proposed by `BayesianOptimization` before to call the `cocoex` function. Like
```python
class BOCOCOWrapper:
    """A coco function that can deal with solutions proposed by the
    `BayesianOptimization` class
    """
    def __init__(self, coco_function):
        self.f = coco_function
    def __call__(self, x):
        # change x here to obey by what `coco_function` expects
        x = ...
        f = self.f(x)
        # possibly change here the value to what `BayesianOptimization` expects
        return f

**Comment by jillianlee** [comment]
This wrapper solution worked!! Thank you both so much for your help!

**Comment by Yash-Pisat** [comment]
> This wrapper solution worked!! Thank you both so much for your help!

I implemented Bayesian Optmization with the COCO framework and compared it with randomsearch results. It does not show much difference in results. Where as I was expecting much better results from bayesian optimization. I would like to know about your results.

**Comment by brockho** [comment]
> > This wrapper solution worked!! Thank you both so much for your help!
> 
> I implemented Bayesian Optmization with the COCO framework and compared it with randomsearch results. It does not show much difference in results. Where as I was expecting much better results from bayesian optimization. I would like to know about your results.

Hello. First of all, many thanks for using COCO. Bayesian Optimization is not a single algorithm, but rather a framework and, in addition, we compare implementations of algorithms, not abstract concepts. Therefore, I cannot really say what I would expect from your implementation, but in general, Bayesian Optimization algorithms should perform better in lower dimension and worse in higher  - so at least in higher dimensions, your result is not totally unexpected, I would say. However, depending on the implementation, Bayesian Optimization can also work well, see for example SMAC-BBOB by Hutter et al. from 2013.

**Comment by Yash-Pisat** [comment]
> SMAC-BBOB by Hutter et al. from 2013

Thank you for the quick response. I am doing masters thesis in the benchmarking area and COCO has been really great work to look forward to! Regarding the implementation , I am just attaching the reference code for bayesian optimization so that you can have a look also I will go through the documentation that you have mentioned to me.

def bayesian_optimization(f, lbounds, ubounds, num_init_points, num_evaluations):
    # Convert bounds to tensor
    bounds = torch.tensor([lbounds, ubounds], dtype=torch.float32)

    # Initialize training data
    train_x = torch.rand((num_init_points, len(lbounds)))  # Initial random points
    train_x = bounds[0] + (bounds[1] - bounds[0]) * train_x  # Scale to bounds
    train_y = torch.tensor([f(x.numpy()) for x in train_x], dtype=torch.float32).unsqueeze(-1)

    # Gaussian Process Model
    model = SingleTaskGP(train_x, train_y)
    mll = ExactMarginalLogLikelihood(model.likelihood, model)
    fit_gpytorch_model(mll)


    # Main optimization loop
    for _ in range(num_evaluations - num_init_points):
        # Define the acquisition function
        EI = ExpectedImprovement(model, best_f=train_y.max())

        # Find the next point to evaluate
        new_x, _ = optimize_acqf(
            EI, bounds=bounds, q=1, num_restarts=5, raw_samples=20,
        )
        # Evaluate the new point and update training data
        new_y = torch.tensor([f(new_x.numpy()[0])], dtype=torch.float32).unsqueeze(-1)

        train_x = torch.cat([train_x, new_x])
        train_y = torch.cat([train_y, new_y])

        # Update the model
        model = SingleTaskGP(train_x, train_y)
        mll = ExactMarginalLogLikelihood(model.likelihood, model)
        fit_gpytorch_model(mll)

    return train_x

![image](https://github.com/numbbo/coco/assets/111347181/3d030bce-49d6-49fb-aff6-299d3466f02d)

    
![image](https://github.com/numbbo/coco/assets/111347181/44189dd8-89ee-4cb4-9a95-d877b82e05a4)


Any suggestions or something that I am try?

**Comment by nikohansen** [comment]
You have only conducted 5 function evaluations. That's not enough to draw any conclusions about the performance even on the (simple) sphere function.

**Comment by Yash-Pisat** [comment]
> You have only conducted 5 function evaluations. That's not enough to draw any conclusions about the performance even on the (simple) sphere function.

Oh okay. Understood. I will increase the budget maybe to 10 and see the results.
