### ISSUE TITLE
reduce figure file size

### ISSUE THREAD

**Issue by TGlas** [numbbo/coco#1950]
I just submitted a paper containing 28 COCO figures to arXiv, and it turns out that the paper is oversized by their standards (10MB limit). The PDF figures are all between 300K and 500K in size, with four curves per plot (four algorithms). That's a huge file size for a few curves plus coordinate system and decoration. The SVG-Files are 4 to 5 times smaller than the PDFs, although they are uncompressed. That's a huge mismatch. There must be some inefficiency in the PDF generation procedure.

**Comment by nikohansen** [comment]
One way to go about this may be to use ```rasterized=True``` when _plotting_. This would need some investigation how easily this can be done and how effective it is.

**Comment by nikohansen** [comment]
Meanwhile, @ttusar and @brockho figured out the reason: fonts are included in the pdfs (as it seemed to be necessary for GECCO submissions). This will be fixed in the coming days.

**Comment by TGlas** [comment]
Thanks for looking into this. It seems safe to use only Helvetica in the plots, or one of the other four standard postscript fonts. As far as I know there is no need to embed these. To make GECCO happy, embedding only the characters that are actually needed should solve it, too.In any case, embedding the same font 28 times is far from ideal :)

**Comment by nikohansen** [comment]
> In any case, embedding the same font 28 times is far from ideal

Right, and now I also understand how pdf down-sizing can be so amazingly effective and loss less: just remove 27 of the 28 copies :-)

**Comment by brockho** [comment]
Eventually, we solved all "problems" with the continuous integration tests such that the suggested default removal of the fonts to reduce the pdf file size is now effective in the development branch (and soon in a new release).

The new `--include-fonts` option of the postprocessing allows now to include the fonts into the generated PDFs such that the COCO/BBOB LaTeX submissions are ACM compatible (for example as needed for the BBOB workshop submissions).
