### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#1956]
With the latest changes in CircleCI and the non-support of Python2 as a language brings us to the point where a single (simple) code breaks some of our code somewhere. As a workaround, we should switch on import between `time.clock` and `time.process_time`.

I'll take care of that.

**Comment by nikohansen** [comment]
For `cocopp` I think we can drop the support. For `cocoex` I would try to keep it as long as it is practical to do without painful additional efforts.

**Comment by brockho** [comment]
With the latest change in the development branch, as discussed today, all current tests run through again. On CircleCI, I removed the python 2 test because it is not anymore supported, but on AppVeyor and Jenkins, we will still have the previous python 2.7 tests for the time being.
