### ISSUE TITLE
tests failing due to installation requirements

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1957]
The tests on this branch seem to fail due to the installation requirement `'matplotlib>=3.1'` see [here](https://ci.inria.fr/numbbo/job/Coco-test2-linux/499/dotype=test-postprocessing,label=numbbo-ubuntu-12p04-i386,pyversion=python/console) or [here](https://ci.appveyor.com/project/nikohansen/coco-j53aywshl8udzvb/builds/32536178/job/iobhhju4ce445cs4)

**Comment by nikohansen** [comment]
The reason is not the test branch, but the setup file used when testing the post-processing. The requirement is not mentioned in `'setup.py.in'` which is used for testing, while it is given in the `setup.py` which is used for the distribution.

**Comment by nikohansen** [comment]
Why are all dependencies are outcommented in https://github.com/numbbo/coco/blob/master/code-postprocessing/setup.py.in ?

**Comment by brockho** [comment]
A good question. The outcommented dependencies are there since the beginning, see the original commit of the file: https://github.com/numbbo/coco/commit/0e462e2c44124c647106c9dc465358440b39971e

**Comment by nikohansen** [comment]
I outcommented the dependencies in the `setup.py` file for the time being to not break the tests. To create a distribution they should be put back, as described in the file.

The better long term solution would be that tests do not break on required dependencies.
