### ISSUE TITLE
Matplotlib future error

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1958]
This will fail to work with future versions of matplotlib, hence should be fixed, also because it floods the screen with tons of annoying warnings.
```
/anaconda3/lib/python3.7/site-packages/cocopp-2.3.3.18.11-py3.7.egg/cocopp/ppfig.py:574: MatplotlibDeprecationWarning: Saw kwargs ['ls', 'linestyle'] which are all aliases for 'linestyle'.  Kept value from 'linestyle'.  Passing multiple aliases for the same property will raise a TypeError in 3.3.
  res2 = plt.plot(x2, y2, **marker_args)
```
It's kind-of tricky to understand where this comes from though.

**Comment by georgedeath** [comment]
**[Here](https://github.com/numbbo/coco/commit/4b6adb9b911568a40d713b8d6c538f4b9043d6e8)** is the commit that fixes it, in case people were struggling to find the code.
