### ISSUE TITLE
Testing two calls of `cocopp.main` without quitting Python between

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1965]
Currently it seems that there is no test that executes the post-processing twice from the same Python shell, that is, a test that does something like

```python
import cocopp
cocopp.main('slsqp*')
cocopp.main('bfgs*')
```

Currently, the above code breaks, see #1964.

**Comment by brockho** [comment]
After solving #1964, the new error is
```ValueError: Data from more than two suites {'bbob-largescale', 'bbob-noisy', 'bbob'} cannot be post-processed together```
which is not surprising because data from more than one incompatible test suite fits `bfgs*`:
```
In [3]: cocopp.main('bfgs*')
Post-processing (1)
  Using:
    [path]\data-archive\bbob\2009\BFGS_ros_noiseless.tgz
    [path]\data-archive\bbob\2012\DE-BFGS_voglis_noiseless.tgz
    [path]\data-archive\bbob\2012\PSO-BFGS_voglis_noiseless.tgz
    [path]\data-archive\bbob\2014-others\BFGS-scipy-Baudis.tgz
    [path]\data-archive\bbob\2014-others\L-BFGS-B-scipy-Baudis.tgz
    [path]\data-archive\bbob\2018\BFGS-M-17.tgz
    [path]\data-archive\bbob\2018\BFGS-P-09.tgz
    [path]\data-archive\bbob\2018\BFGS-P-Instances.tgz
    [path]\data-archive\bbob\2018\BFGS-P-StPt.tgz
    [path]\data-archive\bbob\2018\BFGS-P-range.tgz
    [path]\data-archive\bbob\2019\BFGS-scipy-2019_bbob_Varelas_Dahito.tgz
    [path]\data-archive\bbob\2019\L-BFGS-B-scipy-2019_bbob_Varelas_Dahito.tgz
    [path]\data-archive\bbob-largescale\2019\LBFGS_largescale_Varelas.tgz
    [path]\data-archive\bbob-largescale\2019\m2DLBFGS_largescale_Varelas.tgz
    [path]\data-archive\bbob-noisy\2009\BFGS_ros_noisy.tgz
```

Because
```
import cocopp
cocopp.main('slsqp*')
cocopp.main(cocopp.archives.bbob.find('bfgs'))
```
works, I would not consider the issue a true issue anymore.

**Comment by nikohansen** [comment]
A implemented test though should chose a string that selects fewer algorithms than `'bfgs'` to not add another 2 minutes to the test time for no good reason.

**Comment by brockho** [comment]
First suggestions: 
* `'abc'` results in 2 `bbob` data sets
* `'nelder'` results in 5 `bbob` data sets
* `'nelder-mead'` results in 3 `bbob` data sets
* [`'nsga'` results in 3 `bbob-biobj` data sets]

**Comment by brockho** [comment]
The test has been added a while ago and runs through now. Hence, I close the issue.
