### ISSUE TITLE
Scatter plot annotation

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#1967]
Using `cocopp` version `'2.3.3.18.27'` installed from the current development branch, I got this figure
<img width="224" alt="Screen Shot 2020-05-18 at 23 53 38" src="https://user-images.githubusercontent.com/7316439/82263370-0604a080-9963-11ea-9b2f-4e73efd991bd.png">
When did we lose the name-annotation in the scatter plots?

**Comment by brockho** [comment]
Hmm. I tried myself with the newest `development` branch and I see the correct annotations (tested with `cocopp.main('bipop! lmm')`). Can it be that, by accident, you did not use the latest version when installing? My version is `'2.3.3.46'` by the way.

**Comment by nikohansen** [comment]
We found that it does not happen with archive data.

**Comment by nikohansen** [comment]
Line 383 in `ppscatter.py` is probably the culprit:
```python
   a.set_xlabel('log10(ERT of %s)' % dsList0[0].algId,
                     fontsize=0.85*genericsettings.rcfont["size"])
        a.set_ylabel('log10(ERT of %s)' % dsList1[0].algId,
                     fontsize=0.85*genericsettings.rcfont["size"])

```

**Comment by brockho** [comment]
What we found out is that the `algId` is typically the actual name of the algorithm as given within the info files' `ALG` property (set to `"ALG"` by default and is set correctly for (most) algorithms in the COCO data archive).

We should change this `algId` property when reading in the data in the DataSet's `__init__` method.

**Comment by nikohansen** [comment]
Algorithm names are now set from the folder or tar/zip filename in `pproc.processIndexFile` and not from data attributes, unless the file to process is an `.info` file. This means also that at least some names from the official archive will now show up differently, we have to see whether some fixes are necessary.

On the positive side, name are they are now reliably searchable in the archive like

```python
if cocopp.archives.bbob.find(ds.algId):
    print(ds.algId, 'is an official data set from the bbob test suite')
```

`'noiseless'` is removed from names of the bbob testbed.
