### ISSUE TITLE
[COCO SUBMISSION] Hessian Estimation Evolution Strategy

### ISSUE THREAD

**Issue by TGlas** [numbbo/coco#1996]
Hello COCO user!
Hello COCO team!

Here is the right place to submit one or several COCO data sets to the official COCO archive (https://coco.gforge.inria.fr/doku.php?id=algorithms). Please provide the information requested below and submit the issue. Before, we kindly ask you to read about the details in our [How to publish a dataset documentation](https://github.com/numbbo/coco/blob/development/howtos/publish-a-dataset-howto.md).

#### Reference
https://arxiv.org/abs/2003.13256
https://arxiv.org/pdf/2003.13256

#### Description of the Algorithm(s)
Hessian Estimation Evolution Strategy (HE-ES)

#### Link to Data
https://tglas.2fine.de/HE-ES.zip
NOTE: Please copy, I cannot host the file on the server as a permanent solution.

#### Potentially: Source Code of Experiment
https://www.ini.rub.de/upload/editor/file/1585464419_306c059ec73a243dd05b/HE-ES.py

#### Information About the Authors
Tobias Glasmachers and Oswin Krause

**Comment by brockho** [comment]
Dear @TGlas, many thanks for your data submission!

I have now made everything available via the postprocessing through
```
import cocopp
cocopp.bbob.update()   # potentially needed to update your local copy of the archive definition file
cocopp.main('HE-ES')
```
and I also added an entry to the official list of supported data sets here: https://coco.gforge.inria.fr/doku.php?id=algorithms-bbob

**Comment by brockho** [comment]
These data are available for some time now, hence, I close the issue.
