### ISSUE TITLE
Manage where the ECDFs start in the x-axis

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#2]
```
Manage where the ECDFs start in the x-axis (see also mail by Arnold Neumaier). 
log(fevals)=0 seems not advisable in particular for much larger dimension. 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 8:43

**Comment by brockho** [comment]
@nikohansen: I guess that this issue can also be closed or is there something that I miss?
