### ISSUE TITLE
Move to Python 3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#20]
```
move to Python 3
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 4:42
- Blocked on: #45

**Comment by nikohansen** [comment]
See also #19 #45 #46 #56

**Comment by nikohansen** [comment]
One possible solution is a 2/3 compatible entire new (re-)implementation, which would have additional benefits, like cleaning up of interfaces and getting rid of quite some difficult-to-understand code. It could start as a light-weight version with only limited functionality...

**Comment by nikohansen** [comment]
this, https://plot.ly/external, should be evaluated as a way to generate the plots in a new implementation, trying out

```python
import plotly
from plotly.graph_objs import Scatter, Layout

plotly.offline.plot({
    "data": [Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])],
    "layout": Layout(title="hello world")
})
```
gives a nice interactive html page. 

See also https://wiki.python.org/moin/NumericAndScientific/Plotting

**Comment by nikohansen** [comment]
http://python-future.org/ looks like a good resource for Python 2/3 questions.

**Comment by nikohansen** [comment]
This may be a good time to attempt an automated code conversion of our post-processing code to Python 3 soon. Due to the division change, the current code in unlikely to ever become Python 3 on its own. Therefore we should try to figure out what we need to change/adapt to make smooth automated code conversions once in a while.

**Comment by nikohansen** [comment]
This is a random wish list for improvements over `cocopp` by a Python 3 reimplementation.

- unified coding style (also: use `@property` in case) 
- simplified way to configure and set options (`config.py` and `genericsettings.py`)

**Comment by nikohansen** [comment]
Another useful test: we may include the `from __future__ import division` line in one or several files and check whether the output changes in Python 2.

**Comment by gillhofer** [comment]
Is there an update or a timetable to this issue?

**Comment by nikohansen** [comment]
@gillhofer , the module can be used under Python 3 since some time. We don't however have a way to verify that we see the very same output each and every time.
