### ISSUE TITLE
Instance-wise optimum stays the same over different functions for bbob

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2000]
When investigating the `bbob-biobj` and `bbob-biobj-ext` functions here https://numbbo.github.io/bbob-biobj/vis/, I realized today that some instances looked very similar for different functions. More concretely, the Pareto set approximations for F56 (=(f1,f3) of `bbob`) and F57 (=(f1,f4) of `bbob`) look visually the same for instances 1 and 5:

|          | instance 1  | instance 5   |
| -------- | ------------- |:-------------:| 
| f56 | ![image](https://user-images.githubusercontent.com/13706996/100615281-aa569f00-3317-11eb-9834-16fe934aeb5b.png )      | ![image](https://user-images.githubusercontent.com/13706996/100615300-b2164380-3317-11eb-854c-a5375182f654.png) |
| f57 | ![image](https://user-images.githubusercontent.com/13706996/100615251-a0cd3700-3317-11eb-8259-da939b9bfaf7.png) | ![image](https://user-images.githubusercontent.com/13706996/100615315-b93d5180-3317-11eb-94c6-55df23f2917c.png) |

When investigating this further, I saw that the optima for the single-objective functions f3 and f4 have the same behavior for instances 1 and 5:
```python

In [1]: import cocoex

In [2]: mysuite = cocoex.Suite('bbob', '', '')

In [3]: f3 = mysuite.get_problem_by_function_dimension_instance(3, 2, 1)

In [4]: f4 = mysuite.get_problem_by_function_dimension_instance(4, 2, 1)

In [5]: f3._best_parame...   # exact call hidden here
   ...: with open('._bbob_problem_best_parameter.txt', 'rt') as file_:
   ...:     print([float(s) for s in file_.read().split()])
   ...:
[-2.3407999999999998, 2.3]

In [6]: f4._best_parame...   # exact call hidden here
    ...: with open('._bbob_problem_best_parameter.txt', 'rt') as file_:
    ...:     print([float(s) for s in file_.read().split()])
    ...:
[-2.3407999999999998, 2.3]
```

I can imagine we have never observed this before and it is definitely worth to investigate further whether this is a bug or a feature.

**Comment by nikohansen** [comment]
It turns out this is indeed done on purpose for pairing the functions 3 and 4 in [this code](https://github.com/numbbo/coco/blob/997940bb478a7be1dd1973af30cb29428c8dbd07/code-experiments/src/suite_bbob.c#L100):

```C
  const long rseed = (long) (function + 10000 * instance);
  const long rseed_3 = (long) (3 + 10000 * instance);
  const long rseed_17 = (long) (17 + 10000 * instance);

  if (function == 1) {
    problem = f_sphere_bbob_problem_allocate(function, dimension, instance, rseed,
        problem_id_template, problem_name_template);
  } else if (function == 2) {
    problem = f_ellipsoid_bbob_problem_allocate(function, dimension, instance, rseed,
        problem_id_template, problem_name_template);
  } else if (function == 3) {
    problem = f_rastrigin_bbob_problem_allocate(function, dimension, instance, rseed,
        problem_id_template, problem_name_template);
  } else if (function == 4) {
    problem = f_bueche_rastrigin_bbob_problem_allocate(function, dimension, instance, rseed_3,
        problem_id_template, problem_name_template);
  } else if (function == 5) {
```
