### ISSUE TITLE
[Bug report] observer stores in wrong file

### ISSUE THREAD

**Issue by Ulfgard** [numbbo/coco#2008]
**Describe the bug**
I am 80% sure this is still user error, but i have ruled our everything i could.
I ran an optimizer using 72 batches based on example_experiment2.py. Here is the reduced code with everything except the optimizer loop:
```
import sys
import numpy  as np
import cocoex  # experimentation module


suite_name = "bbob"  # see cocoex.known_suite_names
suite_filter_options = ("dimensions: 2,3,5")
batches = 72
current_batch = int(sys.argv[1])  # only current_batch modulo batches is relevant

#define output location
output_folder = 'HEBO_batch%03dof%d' % (current_batch, batches)

### prepare
suite = cocoex.Suite(suite_name, "", suite_filter_options)
observer = cocoex.Observer(suite_name, "result_folder: " + output_folder)

### go
for batch_counter, problem in enumerate(suite):  # this loop may take hours or days...
    if batch_counter % batches != current_batch % batches:
        continue
    problem.observe_with(observer)  # generate the data for cocopp post-processing
    problem(np.zeros(problem.dimension))  # making algorithms more comparable
    print(problem.name)
```
When i run the code, i print the problem name, which returns exactly the problem id and instances. When i compare my print out ids/instances with the files actually stored, i obtain:

![Screenshot (22)](https://user-images.githubusercontent.com/15045382/108622191-61564880-7437-11eb-93f7-524514169d4e.png)

so while i evaluate on different instances only files with _i2.dat are saved. The issue lies not in the log files, because according to the printout some function/instance combinations are missing and some double (and the total are the requested 1080).
The experiments are pretty resource intensive. Can i just rename all 1080 files to the correct scheme?

**Your System (please complete the following information when it seems relevant):**
 - Operating system: RHEL 7.9
 - COCO version: 2.4, master branch

**Comment by Ulfgard** [comment]
The issue extends also to the info files. they are also named with the wrong ids.

**Comment by nikohansen** [comment]
FTR, files names have no meaning or relevance for the post-processing `cocopp` other than the `.info` extension, which indicates the entry files that `cocopp` is looking for. Then, the data-file names are given in the `.info` files. Renaming data file is for this reason unlikely to get a desired result.

**Comment by nikohansen** [comment]
Data files can contain data from several instances, you may want to check this.

**Comment by nikohansen** [comment]
It may help if you post the content of an `.info` file here.
