### ISSUE TITLE
[Feature request] Add 2020 bbob as well as 2019 bbob-mixint data to ppdata-archive

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2013]
We should prepare and put online the postprocessed data from the continuous submissions in 2020 as well as from the 2019 bbob-mixint paper here: https://numbbo.github.io/ppdata-archive/

**Comment by brockho** [comment]
While starting to look into the data archive again, I realized that the SNES data set of 2012 has 40-D data only for f1 till f11. This causes an error in particular when calling the ```bestalg.extractBestAlgorithms(...)```. Shall I remove this incomplete 40-D data from the official data set because? FYI, the originally submitted data has already this "missing" data for f12-f24.

**Comment by nikohansen** [comment]
@ttusar , you could submit the data from the 2019 paper here with the data submission label?

**Comment by nikohansen** [comment]
Re. SNES 2012 data: If the 40-D data can be removed cleanly, it sounds like a good option.

**Comment by brockho** [comment]
The 2019--2021 datasets are now postprocessed and available in the [ppdata archive](https://numbbo.github.io/ppdata-archive/). Because the SNES 2012 data has been cleaned up as well in the meantime, I close this issue.
