### ISSUE TITLE
Path to matlab problem described in troubleshooting persists after editing /etc/paths

### ISSUE THREAD

**Issue by SteveHuntsman** [numbbo/coco#2015]
After editing /etc/paths to

> /usr/local/bin
> /usr/bin
> /bin
> /usr/sbin
> /sbin
> /Applications/MATLAB_R2020a.app/bin/

I still got the same error messages as initially, viz.

> CLEAN	mex files from code-experiments/build/matlab/
> AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_matlab.c'] -> code-experiments/build/matlab/coco.c
> EXPAND	code-experiments/build/matlab/coco.c.in to code-experiments/build/matlab/coco.c
> EXPAND	code-experiments/src/coco.h to code-experiments/build/matlab/coco.h
> WRITE	code-experiments/build/matlab/REVISION
> WRITE	code-experiments/build/matlab/VERSION
> RUN	matlab -nodisplay -nosplash -r setup, exit in code-experiments/build/matlab
> Traceback (most recent call last):
>   File "do.py", line 1032, in <module>
>     main(sys.argv[1:])
>   File "do.py", line 1005, in main
>     elif cmd == 'run-matlab': run_matlab()
>   File "do.py", line 435, in run_matlab
>     build_matlab()
>   File "do.py", line 423, in build_matlab
>     run('code-experiments/build/matlab',
>   File "/Users/sha0639/Documents/coco-master/code-experiments/tools/cocoutils.py", line 120, in run
>     output = check_output_with_print(verbose, args, stderr=STDOUT, env=os.environ,
>   File "/Users/sha0639/Documents/coco-master/code-experiments/tools/cocoutils.py", line 43, in check_output_with_print
>     output = check_output(*popenargs, **kwargs)
>   File "/Users/sha0639/opt/anaconda3/lib/python3.8/subprocess.py", line 411, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/Users/sha0639/opt/anaconda3/lib/python3.8/subprocess.py", line 489, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/Users/sha0639/opt/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Users/sha0639/opt/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'matlab'

I am running Mac OS Catalina 10.15.7 and am utterly incompetent at working with software and/or the guts of OSes in any meaningful way, so please explain any fixes as you would to a small child, or a golden retriever. Thanks- SH

**Comment by nikohansen** [comment]
You probably need to open a new shell window such that the editing of `/etc/paths` takes effect (the previous windows will still only have the old path).

Then, for a start, you could check in a system shell

- `echo $path` # see whether the path is in effect and
- `matlab`  # see whether you can call matlab from the shell

I have no other clues either.

**Comment by SteveHuntsman** [comment]
@nikohansen This does seem to help (thanks!), but now `python do.py run-matlab` seems to hang versus completing. I let it run for well over two hours. I've confirmed that MATLAB starts from the shell and `echo $PATH` shows
> /Users/sha0639/opt/anaconda3/bin:/Users/sha0639/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/MATLAB_R2020a.app/bin:/Library/TeX/texbin

FWIW, I did an Octave install and initial test on Ubuntu without problems (so I know that two hours is not to be expected!). This will be my fallback, and I don't think I have any critical need for MATLAB per se.

**Comment by brockho** [comment]
By default, the ```do.py``` swallows a lot of output such that you might not see what is actually going on. You can run ```python do.py verbose run-matlab``` to see more output. For me, the default experiment is running within a few seconds:

```
(base) [...]/coco-repo$ python do.py verbose run-matlab
CLEAN   mex files from code-experiments/build/matlab/
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.                                                                                                       c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c                                                                                                       ', 'code-experiments/src/coco_runtime_matlab.c'] -> code-experiments/build/matla                                                                                                       b/coco.c
EXPAND  code-experiments/build/matlab/coco.c.in to code-experiments/build/matlab                                                                                                       /coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/matlab/coco.h
WRITE   code-experiments/build/matlab/REVISION
WRITE   code-experiments/build/matlab/VERSION
RUN     matlab -nodisplay -nosplash -r setup, exit in code-experiments/build/mat                                                                                                       lab
/usr/local/bin/matlab: line 1335: lsb_release: command not found

                            < M A T L A B (R) >
                  Copyright 1984-2019 The MathWorks, Inc.
                  R2019a (9.6.0.1072779) 64-bit (glnxa64)
                               March 8, 2019


To get started, type doc.
For product information, visit www.mathworks.com.

compiling cocoCall.c...Building with 'gcc'.
Warning: You are using gcc version '4.8.5-36)'. The version of gcc is not supported. The version currently supported with MEX is '6.3.x'. For a list of currently
supported compilers see: https://www.mathworks.com/support/compilers/current_release.
> In setup (line 8)
MEX completed successfully.
Done
Preparation of all mex files finished.

Wait for compilation to finish
RUN     matlab -nodisplay -nosplash -r exampleexperiment, exit in code-experiments/build/matlab
/usr/local/bin/matlab: line 1335: lsb_release: command not found

                                                                      < M A T L A B (R) >
                                                            Copyright 1984-2019 The MathWorks, Inc.
                                                            R2019a (9.6.0.1072779) 64-bit (glnxa64)
                                                                         March 8, 2019


To get started, type doc.
For product information, visit www.mathworks.com.

COCO INFO: Results will be output to folder exdata/RS_on_bbob

COCO INFO: 19.05.21 20:50:38, d=2, running: f01...............f02...............f03...............f04...............f05...............f06...............f07........                    .......f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16.........                    ......f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
COCO INFO: 19.05.21 20:50:40, d=3, running: f01...............f02...............f03...............f04...............f05...............f06...............f07........                    .......f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16.........                    ......f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
COCO INFO: 19.05.21 20:50:41, d=5, running: f01...............f02...............f03...............f04...............f05...............f06...............f07........                    .......f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16.........                    ......f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
COCO INFO: 19.05.21 20:50:42, d=10, running: f01...............f02...............f03...............f04...............f05...............f06...............f07.......                    ........f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16........                    .......f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
COCO INFO: 19.05.21 20:50:44, d=20, running: f01...............f02...............f03...............f04...............f05...............f06...............f07.......                    ........f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16........                    .......f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
COCO INFO: 19.05.21 20:50:46, d=40, running: f01...............f02...............f03...............f04...............f05...............f06...............f07.......                    ........f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16........                    .......f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done

   COCO TIMING: dimension 2 finished in 9.252937e-04 seconds/evaluation   COCO TIMING: dimension 3 finished in 5.796880e-04 seconds/evaluation   COCO TIMING: dimen                    sion 5 finished in 3.714772e-04 seconds/evaluation   COCO TIMING: dimension 10 finished in 2.222142e-04 seconds/evaluation   COCO TIMING: dimension 20 finished in                     1.459977e-04 seconds/evaluation   COCO TIMING: dimension 40 finished in 9.400753e-05 seconds/evaluation

```

If you see the
```
MEX completed successfully.
Done
Preparation of all mex files finished.
```
appearing, everything should be fine and then it might be the actual experiment which takes the time. But keep in mind that it is always advisable to start with a very short experiment and then increase the number of function evaluations by factors of 2-10 to get a feeling of how the algorithm scales. Waiting 2+ hours for the very first experiment to finish seems definitely too long :-)

**Comment by SteveHuntsman** [comment]
@brockho Using the `verbose` option shows no difference versus not using it on stdout. Running `matlab -nodisplay -nosplash` works fine.

**Comment by brockho** [comment]
Interesting. For me, it makes a difference. At least on our linux machine, I do not see any output from the actual experiment without the ```verbose``` option:
```
(base) [...]/coco-repo$ python do.py run-matlab
CLEAN   mex files from code-experiments/build/matlab/
AML     ['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_matlab.c'] -> code-experiments/build/matlab/coco.c
EXPAND  code-experiments/build/matlab/coco.c.in to code-experiments/build/matlab/coco.c
EXPAND  code-experiments/src/coco.h to code-experiments/build/matlab/coco.h
WRITE   code-experiments/build/matlab/REVISION
WRITE   code-experiments/build/matlab/VERSION
RUN     matlab -nodisplay -nosplash -r setup, exit in code-experiments/build/matlab
Wait for compilation to finish
RUN     matlab -nodisplay -nosplash -r exampleexperiment, exit in code-experiments/build/matlab
(base) [...]/coco-repo$
```

But I am happy that it finally works with the mentioned Matlab options.

**Comment by SteveHuntsman** [comment]
@brockho - I think I gave the wrong impression. Neither the verbose nor the standard option works; both hang, and both produce the same output on stdout, _suggesting that the setup never completes_. I have just confirmed this again today.

Meanwhile I've found that my own optimizer behaves very differently on Octave vs Matlab, for reasons which are also mystifying but that I suspect are due to calls to fmincon on a surrogate. I had been hoping that this would be a decent workaround but the behavior discrepancy is subtle--I did not have to meaningfully change my code to get it to run in Octave.

So if you have any guidance on what I might be doing wrong I would be very glad. Octave on Ubuntu seems to have its own pitfalls that prevent me characterizing my optimizer, though I did get COCO to work in that context.

**Comment by brockho** [comment]
Dear Steve,

Would you be so kind and paste the output that you see with ```python do.py build-matlab``` here? What you can also try is to go to the ```code-experiments/build/matlab/``` folder. There, you should find a ```setup.m``` file that you can run "by hand" within matlab (by typing ```run setup.m``` within the matlab shell when you are in this folder). What do you see? I get 
```
>> run setup.m
compiling cocoCall.c...Building with 'gcc'.
Warning: You are using gcc version '4.8.5-36)'. The version of gcc is not supported. The version currently supported with MEX is '6.3.x'.
For a list of currently supported compilers see: https://www.mathworks.com/support/compilers/current_release.
> In setup (line 8)
  In run (line 91)
MEX completed successfully.
Done
Preparation of all mex files finished.
```
[We seem to have a very outdated Matlab on the linux machine...]

After this, I have a ```cocoCall.mexa64``` file in this folder (the file ending might depend on your system) which is what the example experiment is using to connect to COCO. Or does the ```python do.py run-matlab``` already stops before moving the `.m` and the `coco.c` and `coco.h` files to this folder?

**Comment by SteveHuntsman** [comment]
build script output:

> (base) str-mac-2613:coco-master sha0639$ python do.py build-matlab
> AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_matlab.c'] -> code-experiments/build/matlab/coco.c
> EXPAND	code-experiments/build/matlab/coco.c.in to code-experiments/build/matlab/coco.c
> EXPAND	code-experiments/src/coco.h to code-experiments/build/matlab/coco.h
> WRITE	code-experiments/build/matlab/REVISION
> WRITE	code-experiments/build/matlab/VERSION
> RUN	matlab -nodisplay -nosplash -r setup, exit in code-experiments/build/matlab

then nothing. The setup is giving me a hard time:

> compiling cocoCall.c...Warning: Xcode is installed, but its license has not been accepted. Run Xcode and accept its
> license agreement.
>  
> > In setup (line 8) 
> Error using mex
> No supported compiler was found. For options, visit
> https://www.mathworks.com/support/compilers.
> 
> Error in setup (line 8)
> mex('-Dchar16_t=uint16_t', 'cocoCall.c');

and I'll try to figure this out tomorrow. Thanks for your patience and help

**Comment by SteveHuntsman** [comment]
@brockho **SUCCESS! Many thanks.** 

Details: after actually installing Xcode (which was not actually installed, much less its license accepted) today and running setup in Matlab, I got

> >> setup
> compiling cocoCall.c...Building with 'Xcode with Clang'.
> MEX completed successfully.
> Done
> Preparation of all mex files finished.

Then I did 

> (base) str-mac-2613:coco-master sha0639$ python do.py verbose run-matlab
> CLEAN	mex files from code-experiments/build/matlab/
> AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_archive.c', 'code-experiments/src/coco_runtime_matlab.c'] -> code-experiments/build/matlab/coco.c
> EXPAND	code-experiments/build/matlab/coco.c.in to code-experiments/build/matlab/coco.c
> EXPAND	code-experiments/src/coco.h to code-experiments/build/matlab/coco.h
> WRITE	code-experiments/build/matlab/REVISION
> WRITE	code-experiments/build/matlab/VERSION
> RUN	matlab -nodisplay -nosplash -r setup, exit in code-experiments/build/matlab
> 
>                             < M A T L A B (R) >
>                   Copyright 1984-2020 The MathWorks, Inc.
>               R2020a Update 5 (9.8.0.1451342) 64-bit (maci64)
>                                August 6, 2020
> 
>  
> To get started, type doc.
> For product information, visit www.mathworks.com.
>  
> compiling cocoCall.c...Building with 'Xcode with Clang'.
> MEX completed successfully.
> Done
> Preparation of all mex files finished.
> 
> Wait for compilation to finish 
> RUN	matlab -nodisplay -nosplash -r exampleexperiment, exit in code-experiments/build/matlab
> 
>                             < M A T L A B (R) >
>                   Copyright 1984-2020 The MathWorks, Inc.
>               R2020a Update 5 (9.8.0.1451342) 64-bit (maci64)
>                                August 6, 2020
> 
>  
> To get started, type doc.
> For product information, visit www.mathworks.com.
>  
> COCO INFO: Results will be output to folder exdata/RS_on_bbob
> 
> COCO INFO: 02.06.21 09:41:29, d=2, running: f01...............f02...............f03...............f04...............f05...............f06...............f07...............f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16...............f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
> COCO INFO: 02.06.21 09:41:32, d=3, running: f01...............f02...............f03...............f04...............f05...............f06...............f07...............f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16...............f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
> COCO INFO: 02.06.21 09:41:34, d=5, running: f01...............f02...............f03...............f04...............f05...............f06...............f07...............f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16...............f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
> COCO INFO: 02.06.21 09:41:38, d=10, running: f01...............f02...............f03...............f04...............f05...............f06...............f07...............f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16...............f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
> COCO INFO: 02.06.21 09:41:42, d=20, running: f01...............f02...............f03...............f04...............f05...............f06...............f07...............f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16...............f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
> COCO INFO: 02.06.21 09:41:48, d=40, running: f01...............f02...............f03...............f04...............f05...............f06...............f07...............f08...............f09...............f10...............f11...............f12...............f13...............f14...............f15...............f16...............f17...............f18...............f19...............f20...............f21...............f22...............f23...............f24...............done
> 
>    COCO TIMING: dimension 2 finished in 1.750014e-03 seconds/evaluation   COCO TIMING: dimension 3 finished in 1.278761e-03 seconds/evaluation   COCO TIMING: dimension 5 finished in 8.997555e-04 seconds/evaluation   COCO TIMING: dimension 10 finished in 5.913885e-04 seconds/evaluation   COCO TIMING: dimension 20 finished in 4.429540e-04 seconds/evaluation   COCO TIMING: dimension 40 finished in 1.551662e-04 seconds/evaluation

**Comment by brockho** [comment]
Nice! Happy that it worked.
