### ISSUE TITLE
[Bug report] Missing "runtime distributions (ECDFs) over all targets" for comparison data on "bbob-biobj-mixint"

### ISSUE THREAD

**Issue by jyyang5** [numbbo/coco#2016]
The "runtime distributions (ECDFs) over all targets" is missing after post-processing for comparison data
on `bbob-biobj-mixint` test suite, for single algorithm data, everything is good. 
COCO version 2.4.

**Comment by ttusar** [comment]
Thanks for the bug report. 

I can confirm that this is the case also for the latest development version (2.4.18). That is, when comparing two algorithms on the `bbob-biobj-mixint` suite, the `html` with the post-processed results is missing the title "Runtime distributions (ECDFs) over all targets" as well as the plots `pprldmany_xxD_noiselessall` that should appear below it. The plots are created by the post-processing, they are just not included in the `html` output, so this should be relatively easy to fix.

**Comment by ttusar** [comment]
This is now fixed on the development branch.
