### ISSUE TITLE
[Bug report] python3.9.7

### ISSUE THREAD

**Issue by cola-gwei** [numbbo/coco#2033]
**Describe the bug**
I meet the error ["/usr/bin/gcc" is fatal] when python=3.9.7, while changing to python=3.8.0 the bug disappear.  

**Your System (please complete the following information when it seems relevant):**
 - Operating system: [Ubuntu 20.0.1]
 - COCO version: [e.g. 2.2.1 (according to `cocopp.__version__`), from the `development` branch, ...]
 - Browser (if relevant): [e.g. chrome, safari]

**Comment by nikohansen** [comment]
FTR
```
export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
./do.py run-python
```
works for me with Python 3.9 (with `numpy` installed, and in case `cython`) on macOS Catalina.
