### ISSUE TITLE
[Bug report] cocopp.ppfig.write_tables writes BBOB-2009 when a reference is shown

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2038]
while there can be other reference sets in which case the text is wrong.

**Comment by brockho** [comment]
I went through all appearances of the string "BBOB-2009" (and the text around it) and replaced it (where applicable) by something like "of the best reference algorithm".

**Comment by nikohansen** [comment]
Why "best"? Could random search not be used as reference algorithm too?
