### ISSUE TITLE
[Feature request] cocopp.pproc.DataSet should have a number_of_constraints property

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2040]
We need the number of constraints in `cocopp.pproc.DataSet` to make aggregation decisions, see for example #1360 and #1369.

Functions in the `cocoex` module have this property as well, which is coded in C.

In `cocopp`, we need to infer the number of constraints from the testbed and the function ID. This suggests that the value computation should best be coded in the respective testbed class?

The most obvious approach seems to implement the method `Testbed.number_of_constraints(dimension, funcId)` by default as

```python
def number_of_constraints(self, dimension, funcId):
    return 0
```

and overwrite the definition in any suite with constraints.

To get the number of constraints one needs to call something like

```python
testbedsettings.current_testbed.number_of_constraints(ds: cocopp.pproc.DataSet)
```

or, maybe even better, the call is independent of the value of `current_testbed`, as `DataSet` contains the necessary suite information, like

```python
def number_of_constraints(ds: cocopp.pproc.DataSet):
    return testbedsettings.SuiteClass(ds.suite_name).number_of_constraints(ds.dim, ds.funcId)
```
as a property method of `DataSet`?

**Comment by paulduf** [comment]
The number of constraints is also a function of the dimension, so the function ID is not enough, we should add the dimension in the arguments or do you see another solution ?

**Comment by nikohansen** [comment]
Maybe `number_of_constraints` should be a class method?

Rationales:
- The use case I have now suggest this, as instantiation of the class requires an argument `target_values` which is entirely superfluous in this case.
- the class instantiation seems not needed to determine the number of constraints for the functions of the suite, as they should not (never?) depend on the instance.

**Comment by paulduf** [comment]
Done in the release, see [the PR](https://github.com/numbbo/coco/pull/2068)
