### ISSUE TITLE
Runtime distribution figure polishing

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2047]
left: old, right: new
<img width="1788" alt="Screen Shot 2021-11-24 at 13 32 25" src="https://user-images.githubusercontent.com/7316439/143239040-659061cf-9011-4c09-b120-1f996e942cbb.png">

Changes:
- increased frame width from 0.735 to 0.783
- removed frame (which makes the y-space ever so slightly larger)
- smaller legend font and fewer space between xlimit and legend

Are there any (potential) problems with, or objections to, this polishing?

**Comment by ttusar** [comment]
I don't understand why only some of the borders were removed. Wouldn't it look nicer if the bottom and right border were also removed?

Although the need to diminish the spaces is understandable, I'm not a big fan - the plots look even more crowded now (there is hardly any space between the legend of one plot and the y-label of its right neighbor). 

The smaller space between the x-limit and the legend looks okay in this example, but might not when there's 20 algorithms in the comparison. 

Additional polishing ideas:
- add a space in "function,target" (it should say "function, target")
- diminish the size of the x-axis tick labels (they should be the same size as the y-axis ones)

**Comment by brockho** [comment]
I agree with @ttusar about the two last points as well as about the space between the figures which might be too small when many algorithms are involved. Is the code available in your fork? I would like to try it out with, say 10 or 20 algorithms, to see whether things are still as readable as with the four algorithms above.

**Comment by nikohansen** [comment]
- making the plot more crowded, or in other words removing useless white space, was the original point of this polishing, to me it's all about form (esthetics) following function
- the font size of the x-tick labels is now set to the same font size as the x-label, I could not find out why they have a different font size to begin with and I also don't know how to get the tick label font size
- the right border should not be removed: without this border, people often misinterpret the connecting line as data
- I put the upper border back at the value 1.0, because this makes it simpler to see whether 1.0 was reached
- the connecting line is IMHO not even really needed anyway (it only gives a hint of the approximate final value of runtime distribution graph) and I start wondering whether it would be better to remove it
- depending on the font size, we still have too much white space to the figure right

<img width="872" alt="Screen Shot 2021-11-30 at 12 31 11" src="https://user-images.githubusercontent.com/7316439/144040219-f2565fe5-d626-426a-b1f1-cb8f1d760714.png">

<img width="884" alt="Screen Shot 2021-11-30 at 12 09 09" src="https://user-images.githubusercontent.com/7316439/144036702-2550b409-8f8d-42eb-84f5-10ceadf4ff0b.png">

**Comment by nikohansen** [comment]
Done with commit c2803b6e3ad5ef08975881827b37d96d6d8f7f6b.
