### ISSUE TITLE
`coco-doc` repository home

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2051]
see https://numbbo.github.io/coco-doc, points to a rather outdated version of the paper and and outdated reference. It seems we should remove this html version all together and just point to the final pdf?

**Comment by ttusar** [comment]
We should structure the many pages with documentation, data and everything else about COCO. 

Start from Links and Documentation and Comprehensive List of Documentations at the bottom of the file [README.md](https://github.com/numbbo/coco#readme).

**Comment by nikohansen** [comment]
- [ ] we also have an almost forgotten [Wiki page](https://github.com/numbbo/coco/wiki) which we probably do not want to keep maintaining.

**Comment by nikohansen** [comment]
The tentative home would be https://numbbo.github.io/coco

**Comment by nikohansen** [comment]
FTR, the home now points to the final paper pdf.
