### ISSUE TITLE
Remove all links to gforge.inria.fr

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#2057]
In all `numbbo` repositories, not just `coco`

**Comment by brockho** [comment]
* [x] numbbo/coco
* [ ] numbbo/coco-doc
* [ ] numbbo/regression-tests
* [ ] numbbo/ppdata-archive
* [x] numbbo/coco-next 
* [ ] numbbo/workshops
* [ ] numbbo/data-archive
* [ ] numbbo/numbbo.github.io
* [ ] numbbo/bbob-biobj
* [ ] numbbo/cocopp-playground

**Comment by brockho** [comment]
Looks like we forgot to close this issue during our COCO sprint in November.
