### ISSUE TITLE
[Feature request] Plot maxevals even when there is no data

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#2062]
It is desirable to plot the cross at the max-evals location even if not a single target has been reached by the algorithm.

Without this, there is no way to know the algorithm's budget from the graphics.

The current behaviour in `compall.pprldmany.plot_data` ([see here](https://github.com/numbbo/coco/blob/11ce3ccdf3e19ddbd56b3f9f56dc0829fc47817b/code-postprocessing/cocopp/compall/pprldmany.py#L214)) is to plot the max evals in the `if n > 0` block. 
This could be under-indented to plot the max evals in all cases. But then there may be some undefined variables, like the `maxval` and `y2` (but we want y to be 0 in this case). Or we can add a cross plot in the first `if n==0` block.

Do you agree ? If yes, I can add this feature in the *coming soon* pull request about the postprocessing for constraints

**Comment by paulduf** [comment]
I have a working version, see [this commit](https://github.com/numbbo/coco/commit/3c173fdc2f95c236cdb546bcc0d6fb69c60c33c4).
I just had to under indent the code and put `maxval` to `np.inf` to escape the if condition in this case.

**Comment by nikohansen** [comment]
Looks good to me.

**Comment by paulduf** [comment]
Closed as adressed in [the PR](https://github.com/numbbo/coco/pull/2068).
