### ISSUE TITLE
[DATA SUBMISSION] Variants of ORTHOMADS on bbob and bbob-mixint

### ISSUE THREAD

**Issue by DahitoMA** [numbbo/coco#2063]
#### Reference
[Dahito MA., Genest L., Maddaloni A., Neto J. (2021) On the Performance of the ORTHOMADS Algorithm on Continuous and Mixed-Integer Optimization Problems. In: Pereira A.I. et al. (eds) Optimization, Learning Algorithms and Applications. OL2A 2021. Communications in Computer and Information Science, vol 1488. Springer, Cham. [https://doi.org/10.1007/978-3-030-91885-9_3](https://doi.org/10.1007/978-3-030-91885-9_3)]

#### Description of the Algorithm(s)
[Six variants of ORTHOMADS are tested with and without use of the search phase on the bbob and bbob-mixint testbeds. The dimensions of the problems used are 2, 3, 5, 10 and 20. All variants are tested with the budget 2e3xdim on the first 5 instances of each function. Some variants are also tested with the budget 1e5xdim on the 15 instances: Neg and 2N on bbob, and Neg and Quad on bbob-mixint.]

#### Link to Data
[[https://www.dropbox.com/s/0h1cx28j8kour3i/DataORTHOMADS.zip?dl=0](https://www.dropbox.com/s/0h1cx28j8kour3i/DataORTHOMADS.zip?dl=0)
The corresponding ORTHOMADS variants for each folder name are as follows:
1: ORTHO 1
2: ORTHO 2
2N: ORTHO 2N
Neg: ORTHO N+1 NEG
Quad: ORTHO N+1 QUAD
Uni: ORTHO N+1 UNI
The presence of NoSrch in the name of a folder means that the search phase of the algorithm was deactivated.]

**Comment by brockho** [comment]
Dear @DahitoMA,

Many thanks for your submission. I could download the data without problems, so I will take care of putting everything online.

**Comment by brockho** [comment]
Many thanks again for your data submission, @DahitoMA. I had a closer look now into the data sets for the `bbob` suite. Except for the variants `2N` and `Neg`, indeed, only data for the first five instances were submitted. I will therefore, for now, put only the `2N` and `Neg` data sets into our official archive and make those ones with only 5 instances available in the list of "inofficial/incomplete" data sets [here](https://numbbo.github.io/data-archive/bbob/#inofficialincomplete-data-sets). As soon as you can submit data from 10 additional instances, I will move them to the official archive of course.

**Comment by brockho** [comment]
Eventually, the data for the `2N` and `Neg` versions of Ortho-MADS are now available online via our [online data archive](https://numbbo.github.io/data-archive/bbob/) as well as via the postprocessing:

```
import cocopp
cocopp.archives.update_all()
cocopp.main('Mads*')
```

Sorry for the delay with putting this online.

Note to self: Github pages do not deploy when some `.md` files are missing in the repository :-)

**Comment by DahitoMA** [comment]
Thanks for the update!
