### ISSUE TITLE
Display evaluation count weights in figures

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2064]
The value of ```cocopp.genericsettings.weight_evaluations_constraints``` could be displayed as "meta-information", for example, alongside the Df values in the figures. This is only necessary or useful if there are any constraints evaluations which should be (approximately) testable via ```cocopp.testbedsettings.current_testbed.has_constraints```.

**Comment by paulduf** [comment]
Implemented in [this commit](https://github.com/numbbo/coco/commit/a80b24df30eba21e82200b5b64d1b223b996e9d1). It may change as the line is a bit too long.

**Comment by nikohansen** [comment]
IMHO, the three lines below the indication of the function should be displayed in a smaller font. It's probably also just fine to display

```
2xf-evals + 3xg-evals
```
instead of
```
2 x #f-evals + 3 x #g-evals
```
