### ISSUE TITLE
[DATA SUBMISSION] EXPLO2

### ISSUE THREAD

**Issue by SteveHuntsman** [numbbo/coco#2065]
Hello COCO user!

Here is the right place to submit one or several COCO data sets to the official COCO archive (https://coco.gforge.inria.fr/doku.php?id=algorithms). Please provide the information requested below and submit the issue. Do not hesitate to read about the details in our [How to publish a dataset documentation](https://github.com/numbbo/coco/blob/development/howtos/publish-a-dataset-howto.md).

#### Reference
[[Put the full reference (for citations) and a link to the pdf here.]](https://arxiv.org/abs/2201.11677)

#### Description of the Algorithm(s)
[Please provide a short description for each algorithm in the data.](EXPLO2 uses differential magnitude and radial basis function interpolation to provide a surrogate which is optimized with an inner algorithm, here MATLAB's fmincon.)

#### Link to Data
[Please prepare and upload your COCO data (see [how to](https://github.com/numbbo/coco/blob/development/howtos/publish-a-dataset-howto.md)) and provide the link here. If you want to submit more than one data set at the same time, please indicate which file corresponds to which algorithm.]
https://drive.google.com/file/d/1ks9jio7ts6oOOkphRKMTHBT0blIJeVzA/view?usp=sharing
https://drive.google.com/file/d/1pJAVHp4fCOeYyzTZ77WwtTdkkOgnoIEx/view?usp=sharing
https://drive.google.com/file/d/1cHVq1rCrK1FFcZ1VtLFChIaP4nTU11U3/view?usp=sharing

(I am pretty sure these are correct, but could not swear to it. I had to do lots of trials and the big file took a week to produce, so if this is wrong then it's probably best to just throw it out--I won't have a spare machine-week to run this on again for the foreseeable future)

#### Optional: Source Code of Experiment
[We are happy to also share any source code of the algorithm and the COCO experiment, you were running. Please provide, if you wish, any code, links, etc. here]

**Comment by brockho** [comment]
Many thanks, @SteveHuntsman, for your submission. I downloaded the data and at first sight, things look okay to me. I will separate actual and postprocessed data before to test and then put things up for automated access via the `cocopp` module as soon as I find the time :-)

**Comment by brockho** [comment]
Finally, the data is available online and via the `cocopp` module:

```
import cocopp
cocopp.archives.update_all() # only needed if you have used the module before
cocopp.main('explo')
```
