### ISSUE TITLE
Weird comparison in test case.

### ISSUE THREAD

**Issue by olafmersmann** [numbbo/coco#2072]
The use of `coco_double_almost_equal` [here](https://github.com/numbbo/coco/blob/11ce3ccdf3e19ddbd56b3f9f56dc0829fc47817b/code-experiments/src/transform_vars_blockrotation.c#L107) here seems weird, given that the second argument is a bool/int.

**Comment by nikohansen** [comment]
This seems to make sense to me, as the first argument `y[j]` may suffer from numerical imprecision as a result of multiplication with a orthogonal matrix (that's my hunch).
