### ISSUE TITLE
Search domain of constraint testbed

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2083]
The current documentation described the search domain to be restricted to `[-5, 5]^n`, while this is not the case for other test suites. This should be clarified.

**Comment by nikohansen** [comment]
@paulduf , is there a reason that we need unconditional domain bounds for the constrained testbed?

**Comment by paulduf** [comment]
Why do you say it is not the case for other test suites ? For the BBOB test suite I read this

> All functions are defined and can be evaluated over R D , while the actual search
domain is given as [−5, 5] D .

And it is the same situationfor BBOB-constrained. Maybe in the documentation it is not clear than the functions can be evaluated everywhere ?

**Comment by nikohansen** [comment]
There are several charitable ways to read the above sentence (it is at least clear that the functions are defined over the entire R^D) and there are, I am sure, other places where this is explained more concisely. None of the testbeds was designed only for bound constrained solvers and I think it should stay that way for the constrained testbed. If this is described differently anywhere, I would consider this to be the bug. In the MO case, we are also not sure that the Pareto set is in the [-5, 5] bound.

I assume there is no specific reason why we need the bounds for the constrained testbed, right?

**Comment by paulduf** [comment]
> I assume there is no specific reason why we need the bounds for the constrained testbed, right?

Indeed, since the solution is almost surely never at any bound

**Comment by nikohansen** [comment]
@paulduf could you give a link to the above cited document?

**Comment by paulduf** [comment]
@nikohansen Here you go: https://hal.inria.fr/inria-00362633v2/document
