### ISSUE TITLE
[Bug report] year option fails

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2089]
With the `cocoex` installed from the current master branch
```python
import cocoex
for sname in cocoex.known_suite_names:
    print(sname, flush=True)
    try:
        suite = cocoex.Suite(sname, "year: 2022", "")
    except e:
        print("{} raised exception {}".format(sname, e))
```
crashes the Python kernel already for the first `bbob` suite. Namely, it also fails on the `bbob-largescale` suite and works on the others.

Expected: the above code runs smoothly.

**Comment by brockho** [comment]
I pushed a small change in the code to `development` which addresses the above  and passes the test for all years from 2009 onwards.
