### ISSUE TITLE
x-axis setup wrong in expensive setting

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2097]
**Describe the bug**
In the expensive setting, the x-axis is wrongly scaled in the latest `cocopp` version:

![image](https://user-images.githubusercontent.com/13706996/162749524-d8e164bc-65bd-435c-a32e-8eb2fe5a77eb.png)

Before, we had way shorter runtimes (up to `10^3` times dimension only) displayed such that most of the plot wasn't just white. Many thanks to @rleriche  for actually reporting this issue in a call earlier today.

**Your System (please complete the following information when it seems relevant):**
 - Operating system: shouldn't matter
 - COCO version: latest 2.6.2

**Comment by nikohansen** [comment]
We identified commit f5289e3 as a potential reason (though we don't understand how) and decided, due to lack of other ideas, to test whether the error remains before/after this commit specifically.

**Comment by nikohansen** [comment]
Now I actually understand the problem, will provide a fix.

**Comment by nikohansen** [comment]
Should be fixed with the latest update of the development branch (though I didn't cross-check the output).

**Comment by rleriche** [comment]
Thank you Niko!

**Comment by nikohansen** [comment]
The fix 4a6cc23fbd is now in the development branch.
