### ISSUE TITLE
[Bug report] Optimal solution is slightly infeasible

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#2098]
**Describe the bug**

The optima solution obtained with the (hidden) method `problem._best_parameter` for problem `f18` in 20-D has some very small positive value for some constraints. This prevents the triggering of the final target (and maybe some others) when evaluating what is supposed to be a reference for the global optimum.

**Your System (please complete the following information when it seems relevant):**
 - Operating system: Ubuntu 18.04
 - COCO version: 2.6.2

**Minimal Reproducible Example**

```python
import cocoex
import numpy as np
suite = cocoex.Suite("bbob-constrained", "", "")
problem = suite.get_problem_by_function_dimension_instance(18, 20, 1)
problem._best_parameter('print')
_xopt = np.loadtxt('._bbob_problem_best_parameter.txt')
problem(_xopt)
problem.final_target_hit
max(problem.constraint(_xopt))
```

Outputs:
```
0
1.5969018398508795e-13
```

**Comment by nikohansen** [comment]
It looks like subtracting `1e-12` from the constraint values solves the issue on all (first) 15 function instances in all dimensions. This should have practically no influence on the performance evaluation. In the construction, constraints are multiplied by up to about `1e5`.

**Comment by paulduf** [comment]
Related plot: CDF of max(g-values) over the first 100 instances of all problems in all dimensions (on a symlog scale).

![CDF of max g values](https://user-images.githubusercontent.com/27226228/164012080-5a78933a-1473-41e6-8823-af01dacf42e6.png)

**Comment by nikohansen** [comment]
I implemented a different solution https://github.com/numbbo/coco/commit/92946781fa17123ba82c140bd9f862477b9204a9 which returns exactly zero in the above example. The distribution of the maximal constraint in the optimum over all instances looks like
<img width="770" alt="Screen Shot 2022-04-21 at 20 47 49" src="https://user-images.githubusercontent.com/7316439/164532483-7fe4bf43-b88a-4fc3-9915-78f876843b95.png">

**Comment by nikohansen** [comment]
@paulduf, @brockho how do we check that https://github.com/numbbo/coco/commit/92946781fa17123ba82c140bd9f862477b9204a9 doesn't break the regression test for the testbed?

**Comment by brockho** [comment]
`python do.py test-suites` should do what you want, shouldn't it? The documentation says "Runs regression test on all benchmark suites".

**Comment by nikohansen** [comment]
The regression test passes. It tests like `np.abs(x - y) < 1e-9)`, so `1e-11` should not matter even when we test this very position.
