### ISSUE TITLE
[DATA SUBMISSION] Data for benchmarked algorithms

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#2099]
Dear Organizers of BBOB 2022,

Please find below the link to data of the algorithms (benchmarked on the BBOB Noiseless Testbed) in my paper which has been submitted to your workshop.

With kind regards,

Duc Manh Nguyen
#### Reference
[Put the full reference (for citations) and a link to the pdf here.]

#### Description of the Algorithm(s)
[Please provide a short description for each algorithm in the data.]

CMAES-APOP-MA: on the BBOB Noiseless Testbed
CMAES-APOP-KP: on the BBOB Noiseless Testbed
CMAES-APOP-KMA: on the BBOB Noiseless Testbed

#### Link to Data

https://drive.google.com/drive/folders/1rW7RjqnrnV-Gy4e_VKosFx5I0vacPGH0?usp=sharing

#### Optional: Source Code of Experiment
[We are happy to also share any source code of the algorithm and the COCO experiment, you were running. Please provide, if you wish, any code, links, etc. here]

**Comment by brockho** [comment]
Dear @NDManh,

Many thanks for your submission. I had a look at it and all looks clean and complete. I will make the data available on our https://numbbo.github.io/data-archive/ page if your BBOB-2022 paper gets accepted (notification deadline is April 25, 2022).

**Comment by brockho** [comment]
The data is now available via the postprocessing (at least after typing `import cocopp; cocopp.archives.update_all()` in your favorite python shell/notebook.
