### ISSUE TITLE
Transformations don't update the best values of the problem

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#210]
The basic problems (implemented in files `f_*.c`) define `best_parameter` and `best_value`. The transformed problems (implemented in files `transform_*.c`) should update them, but they don't. 

This creates a bug in the bi-objective code - the ideal and nadir points are not computed correctly.

**Comment by brockho** [comment]
kind of the same as #224 and linked with #225

**Comment by asmaatamna** [comment]
Now transform_obj_*.c files update the best value (except for the penalization since the best parameter is feasible) (dcf7016d98b095c8f1a617ed10b02be170af4889).

**Comment by asmaatamna** [comment]
If everyone agrees with the proposed solution, I think we can close this issue.

**Comment by asmaatamna** [comment]
If everyone agrees with the proposed solution, I think we can close this issue.
