### ISSUE TITLE
[DATA SUBMISSION] CMA-ES with Margin (CMA-ESwM) results on the bbob-mixint testbed

### ISSUE THREAD

**Issue by satuma777** [numbbo/coco#2101]
Dear Organizers,

Please find below the link to dataset for the CMA-ES variant (benchmarked on the bbob-mixint testbed) which has been submitted to your workshop.

Best regards,
Shota Saito

===================

#### Reference
[Put the full reference (for citations) and a link to the pdf here.]
- Ryoki Hamano, Shota Saito, Masahiro Nomura, and Shinichi Shirakawa, "CMA-ES with Margin: Lower-Bounding Marginal Probability for Mixed-Integer Black-Box Optimization." In Genetic and Evolutionary Computation Conference (GECCO ’22). ACM. ~~(Conditionally Accepted)~~ 
  - The status of this paper has been changed from `Conditionally Accepted` to `Accepted`.

#### Description of the Algorithm(s)
[Please provide a short description for each algorithm in the data.]

The CMA-ES with Margin (CMA-ESwM)  is a CMA-ES variant which introduces a lower bound on the marginal probability associated with integer variables. A dataset evaluating the performance of the CMA-ESwM in the bbob-mixint testbed is included in "CMA-ESwM.zip". This zip-file is available via the link below.

#### Link to Data
[Please prepare and upload your COCO data (see [how to](https://github.com/numbbo/coco/blob/development/howtos/publish-a-dataset-howto.md)) and provide the link here. If you want to submit more than one data set at the same time, please indicate which file corresponds to which algorithm.]
https://drive.google.com/file/d/1ipmRKyV_lQd1TkwHpvgwMGpN7g5d3KmV/view?usp=sharing

#### Optional: Source Code of Experiment
[We are happy to also share any source code of the algorithm and the COCO experiment, you were running. Please provide, if you wish, any code, links, etc. here]
None

**Comment by brockho** [comment]
Dear @satuma777,

Many thanks for your submission. I had a look at it and all looks clean and complete. I will make the data available on our https://numbbo.github.io/data-archive/ page if your BBOB-2022 paper gets accepted (notification deadline is April 25, 2022).

**Comment by brockho** [comment]
Hello again,

Eventually, the submitted data set is up and running and can be used via the `cocopp` postprocessing module. In case you have used the `cocopp` module before, you might need to run `cocopp.archives.update_all()` in your preferred (I)python/Jupyter shell/notebook to get the latest data description.
