### ISSUE TITLE
[DATA SUBMISSION] AL-CMA-ES on bbob-constrained

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#2102]
Hello COCO admin!

#### Reference
Preprint and code are available at:
Paul Dufossé, & Asma Atamna. (2022, July 13). Benchmarking several strategies to update the penalty parameters in AL-CMA-ES on the bbob-constrained testbed. https://doi.org/10.5281/zenodo.6463535

#### Description of the Algorithm(s)
AL-CMA-ES from the pycma package. See the preprint for more details.

#### Link to Data
https://drive.google.com/file/d/1gmpEbkl-2eolrWCZ-Qf44otIVlApkFv-/view?usp=sharing

#### Optional: Source Code of Experiment
See the Zenodo deposit

**Comment by brockho** [comment]
Hello @paulduf,

Many thanks (once again) for uploading the data of your BBOB-2022 submission. Eventually, both COBYLA and all four AL-CMA-ES variants are now available via COCO's [data archive](https://numbbo.github.io/data-archive/bbob-constrained/) (under the naming AL1-CMA-ES, ..., AL4-CMA-ES for be able to distinguish them in the plots). You might need to run

```
import cocopp
cocopp.archives.update_all()
```

to get the newest archive definition file before the data sets are visible.

**Comment by brockho** [comment]
Given that the data is online already for more than half a year, I'll close this issue.
