### ISSUE TITLE
[DATA SUBMISSION] TPB, EDN, KRVEA, KTA2, MOTPE, and ParEGO on the bbob-biobj suite for an expensive optimization scenario

### ISSUE THREAD

**Issue by ryojitanabe** [numbbo/coco#2104]
Dear Organizers of COCO,

I would like to submit the benchmarking results of six optimizers (TPB, EDN, KRVEA, KTA2, MOTPE, and ParEGO) on the ``bbob-biobj`` suite for an expensive optimization scenario. Could you please upload them to the COCO data archive?

Best regards,
Ryoji

#### Reference

Ryoji Tanabe, Youhei Akimoto, Ken Kobayashi, Hiroshi Umeki, Shinichi Shirakawa, Naoki Hamada: A Two-phase Framework with a Bezier Simplex-based Interpolation Method for Computationally Expensive Multi-objective Optimization, accepted to GECCO2022 (https://arxiv.org/abs/2203.15292).

#### Description of the Algorithm(s)

TPB is our proposed two-phase framework with a Bezier simplex-based interpolation method for computationally expensive multi-objective optimization. The others are meta-model-based optimizers. In our study, the maximum number of function evaluations was set to 20D, 30D, and 40D, where D is the number of variables. We only submit the results for 20D evaluations.

EDN, KTA2, and ParEGO require very time-consuming computation. I stopped EDN, KTA2, and ParEGO when they did not finish within a week. For this reason, their benchmarking data are incomplete as follows:

- The results of EDN for D=20 are incomplete.
- The results of ParEGO for D=20 are incomplete.
- The results of KTA2 for D=10 are incomplete.

#### Link to Data

https://drive.google.com/drive/folders/1rJB95p5PgXAdgiPwRksn1b8Al9o1LKqV?usp=sharing

#### Optional: Source Code of Experiment

https://github.com/ryojitanabe/tpb

**Comment by brockho** [comment]
Dear @ryojitanabe,

Many thanks for your submitted data. I eventually managed to check the data more thoroughly and I can confirm that the following data sets are incomplete:

* EDN: missing data, starting from f19 in 20-D
* KTA2: missing data, starting from f33 in 10-D
* ParEGO: missing data, starting from f20 in 20-D

We will therefore not include those ones into the official archives (yet). Happy to receive an update though in case you have finished the experiments in 20-D at some point (note that 40-D data are not mandatory).

The submitted data set for KRVEA had, in addition, an incomplete set of results for 40-D, but I will simply remove the data for the two completed functions in 40-D to get a valid data set. So KRVEA, MOTPE, and TPB can be made available soon. An update follows here as soon as this is done.

**Comment by ryojitanabe** [comment]
Thank you very much for the sanity checks. Because EDN, KTA2, and ParEGO are very time-consuming for more than 10 dimensions, I gave up finishing the experiments for them.

Many thanks for fixing the incomplete data of KRVEA for 40 dimensions. I would be glad if you consider only the benchmarking data set of KRVEA, MOTPE, and TPB.

**Comment by brockho** [comment]
The data sets of KRVEA, MOTPE, and TPB are now available in the postprocessing. You might need to call

```python
import cocopp
cocopp.archives.update_all()
```

once to update the list of available algorithms (no new install needed). Otherwise, `python -m cocopp bbob-biobj/2022*` will do the job to compare the three algorithms.
