### ISSUE TITLE
ddcma-2022 bbob data

### ISSUE THREAD

**Issue by Mohamed-gharafi** [numbbo/coco#2110]
## Reference

Paper link to be released.

## Description of the Algorithm(s)

(see paper for more details) \
The benchmarked algorithms are variations of CMA-ES, that allows for an acceleration of the covariance matrix adaptation on separable functions without decreasing the performance of the algorithm on none-separable ones.

The CMA-ES is considered the state of the art algorithm for solving stochastic black-box optimization problems. It maintains a normal sampling distribution, to search for better candidate solutions with regard to a fitness function. Which translates to updating the sampling distribution parameters previously sampled solutions, namely : the mean vector and the covariance matrix. The latter is denoted as **sigma²DCD** where:

- **sigma** is the scalar called the step size, which controls the scaling of the sampling distribution spread.
- **C** is the covariance matrix updated by original CMA-ES, it represents the shape of the distribution spread.
- **D** is the so-called diagonal decoding matrix, it represents the scaling factor of each design variable. (it is usually fixed, in the case of original CMA-ES **D** = **I**)

Given this form of the covariance matrix of the sampling distribution, when activated, the diagonal decoding updates simultaneously, the matrix **C** using original CMA-ES method and the matrix **D** using separable-CMA-ES method, at different learning rate (the learning rate of **D** updates is higher). This rate is monitored and adapted in order to avoid disturbing the update the **C** matrix.

The algorithms benchmarked are provided by two different implementations of CMA-ES. They are distinguished in the dataset by:

- **cma** for code used from the unreleased new version of pycma
- **ddcma** for code used from another implementation by Youhei and Hanssen [see code here](https://gist.github.com/youheiakimoto/1180b67b5a0b1265c204cba991fa8518)

For each implementation, we used the CMA-ES with and without diagonal decoding. This is denoted by adding suffix (**0** or **1**) to the name of the algorithm:

- **0** for disabled diagonal decoding
- **1** for enabled diagonal decoding

## Summary : 
- CMA-ES-DD-pycma-2022/CMA-ES-DD-pycma-2022 :arrow_right: **cma1**
- CMA-ES-pycma-2022/CMA-ES-pycma-2022 :arrow_right: **cma0**
- ddcma-dd-youhei-hanssen/ddcma-dd-youhei-hanssen :arrow_right: **ddcma1**
- ddcma-youhei-hanssen/ddcma-youhei-hanssen :arrow_right: **ddcma0**
### Archive tree
```python
[
('CMA-ES-DD-pycma-2022/CMA-ES-DD-pycma-2022.zip', '045e51554e12d45c96d31ea7effee36b3615911172f67161fa03f6a87da5d17e', 23688),
('CMA-ES-pycma-2022/CMA-ES-pycma-2022.zip', '1271d3b5b25cdac8da2ff6fab3101c24b018a83b9bd824aaafbea1a67e2d2ef0', 23800),
('ddcma-dd-youhei-hanssen/ddcma-dd-youhei-hanssen.zip', '4c74559623524040fe252831f2345d4b2806daa0f870160307f1dd66dcf38b26', 23201),
('ddcma-youhei-hanssen/ddcma-youhei-hanssen.zip', '2e8c83cc747cb15137f347c3c95b742447ca4e627242df628ee02a6696f2a086', 23448)
]
```

## Link to Data

Please find the COCO data here : [bbob-ddcma-data](https://github.com/Mohamed-gharafi/bbob-dd-cma/tree/gh-pages/docs/ddcma-2022)

## Source Code of Experiment

Please find the source code of the experiments here : [Source](https://github.com/Mohamed-gharafi/bbob-dd-cma/tree/gh-pages/docs/src)

**Comment by brockho** [comment]
Dear @Mohamed-gharafi, 

Many thanks for your data submission. Everything should be now available via the postprocessing (at least after typing `import cocopp; cocopp.archives.update_all()` in your favorite python shell/notebook).
