### ISSUE TITLE
[Feature request] Reducing the file size in the latest cocopp (2.4.1.1 and 2.6)

### ISSUE THREAD

**Issue by ryojitanabe** [numbbo/coco#2111]
I would be grateful if you could implement a postprocessing option like --save_file_size in the latest version of cocopp, where the option reduces the file size.

I am preparing a camera-ready version of my BBOB2022 paper, but I am facing a file size issue. The GECCO2022 submission system only allows uploading of pdf files less than 30 MB. However, the file size of my paper using cocopp 2.6 is 33.7MB. In the first submission, I addressed this issue by downgrading the version of cocopp from 2.6 to 2.4. Here, the file size of my paper using cocopp 2.4 is only 2.6MB.

- My paper using cocopp 2.6: https://drive.google.com/file/d/1jPXRXWEbiyQKszwyicqqFGiqf5N152n7/view?usp=sharing
- My paper using cocopp 2.4: https://drive.google.com/file/d/1A5-ATXVacEjmOODqa1Vx-qe_jDT-nOLH/view?usp=sharing

It seems that the file size generated by the latest version of cocopp (2.4.1.1 and 2.6) is approximately 21 times larger than that by the old version (<= 2.4) as follows, where the attached ppfig files are for the sake of reference.

- The file size by v2.4 = 18.8 kB (ppfigs_f001_cocopp24.pdf)
- The file size by v2.4.1.1 = 387.2 kB (ppfigs_f001_cocopp2411.pdf)
- The file size by v2.6 = 387.2 kB (ppfigs_f001_cocopp26.pdf)
[ppfigs_f001_cocopp24.pdf](https://github.com/numbbo/coco/files/8559625/ppfigs_f001_cocopp24.pdf)
[ppfigs_f001_cocopp26.pdf](https://github.com/numbbo/coco/files/8559626/ppfigs_f001_cocopp26.pdf)
[ppfigs_f001_cocopp2411.pdf](https://github.com/numbbo/coco/files/8559627/ppfigs_f001_cocopp2411.pdf)

**Your System (please complete the following information when it seems relevant):**

- Operating system: Ubuntu 18.04 LTS
- COCO version: 2.6

**Comment by nikohansen** [comment]
Thanks for reporting! This could be somehow related to #1950.

**Comment by ryojitanabe** [comment]
Thank you for the information about #1950. The  ``--include-fonts`` option is exactly what I was looking for.

**Comment by nikohansen** [comment]
See also #2112
