### ISSUE TITLE
Documentation link for bbob-noisy is not working

### ISSUE THREAD

**Issue by zhoutianxun** [numbbo/coco#2126]
The link provided in "Comprehensive List of Documentations" section for bbob-noisy is not working:
http://coco.lri.fr/downloads/download15.03/bbobdocnoisyfunctions.pdf

**Comment by brockho** [comment]
Dear @zhoutianxun,

Many thanks for pointing out the wrong link and sorry for the very slow response. The link is now corrected in the `development` branch and you can find the documentation of the test suite here: branch: https://hal.inria.fr/inria-00369466/document/.
