### ISSUE TITLE
Documentation in io pages

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2132]
The links in [this table](http://numbbo.github.io/coco/testsuites) should probably rather be at the level of the testbeds themselves. The links must be anyway provided with the respective suite, so the table has little added value and even prevents to visit the page of the respective test suite which might give additional usability.

**Comment by brockho** [comment]
TODO:
* move links from here http://numbbo.github.io/coco/testsuites to the single test suite pages
* have all test suites appear by default in the navigation pane

**Comment by brockho** [comment]
Both TODOs are addressed now such that I consider the issue to be closed.
