### ISSUE TITLE
[Bug report] Missing data in large-scale archive

### ISSUE THREAD

**Issue by Dvermetten** [numbbo/coco#2135]
**Describe the bug**
In the table on the data archive for the large-scale suite (https://numbbo.github.io/data-archive/bbob-largescale/), the links for accessing datasets 006,007 and 008 (VD, V2D and VkD algorithms) result in a 404 error.

**Comment by brockho** [comment]
Dear @Dvermetten,

Many thanks for reporting this. I will correct the links when I am back from vacation in early August. Via the postprocessing, the data should be available though:

```
import cocopp
cocopp.archives.get('VD-CMA')
```

for example should download the data of `VD-CMA` into your `HOME/.cocopp` folder (and return you the path where it is then located).

**Comment by brockho** [comment]
The links on the webpage as well as the names of the three corresponding algorithms are corrected now. Many thanks again, @Dvermetten, for reporting this.
