### ISSUE TITLE
[Bug report] Code crashes with the latest constrained test suite

### ISSUE THREAD

**Issue by paulduf** [numbbo/coco#2142]
The current version of the code in the `development` branch crashes at different moments when calling it from the Python or Matlab interface.

## Python observations

Instantiating with 

```python
import cocoex
suite = cocoex.Suite("bbob-constrained", "", "")
```

Running

```python
for problem_index, problem in enumerate(suite):
    problem(problem.initial_solution)
```

is fine, but 

```python
for problem_index, problem in enumerate(suite):
    problem._best_parameter('print')
    _xopt = np.loadtxt('._bbob_problem_best_parameter.txt')
```

results in a C error. If I remove/comment the `np.loadtxt` line, it is fine again. 
I have no clue why reading with numpy from a file is making the code to crash.

## Conclusions

This looks like some memory management is done bad. Or maybe the interfaces need to be updated? I am not familiar with this code. 

We should probably initiate a working branch from the current development branch to fix this, maybe revert the PR https://github.com/numbbo/coco/pull/2139 (or not if it crashes only when asking for the optimum because this shall not be used in experiments anyway). I find it also suspect that all tests pass on the CI.

## System

- Ubuntu 18.04
- Python 3.8.6
- gcc 8.4.0
- latest development branch

**Comment by nikohansen** [comment]
`np.loadtxt` is not likely the reason for the crash. I think it makes sense to do much more "arbitrary" testing to separate out when (and where exactly) it happens and when it does not happen. In the above case, we would also want to know where the code crashes. Is it always the same problem or which problems are concerned, does this change when something else (e.g. memory heavy) is run before...?

**Comment by brockho** [comment]
On my system (Windows 10, Anaconda with python 3.9.7, MinGW with gcc 6.3.0 and the latest development branch version of the code), all the above code runs through without problems. It is indeed important to understand better when the error occurs. Could you also share the actual error message? That might give already some hint.

**Comment by olafmersmann** [comment]
I've taken a look at this and can't reproduce it.
The code path for `_best_parameter` doesn't allocate any memory and only reads fields which should be safe (i.e. `problem->best_parameter`) and doesn't write to any fields at all.

**Comment by paulduf** [comment]
I could not reproduce either on my new machine. I guess this is on my side with an outdated/unreliable Python setup. We can probably close this issue.
