### ISSUE TITLE
Compare Multiple Solvers

### ISSUE THREAD

**Issue by s4ksb** [numbbo/coco#2143]
Hi, I want to compare multiple solvers against each other by having them plotted on the same plots, similar to figure 6 in the "COCO: A Platform for Comparing Continuous Optimizers in a Black-Box Setting" paper. Currently I have 

<### PERFORM BENCHMARKING
for solver in solvers:
    print(f"Solver: {solver['name']}")
    output_folder = solver['name']
    observer = cocoex.Observer(suite_name, f"result_folder: {output_folder}")
    for problem in suite:  # this loop will take several minutes or longer
        problem.observe_with(observer)  # generates the data for cocopp post-processing
        x0 = problem.initial_solution
        # apply restarts while neither the problem is solved nor the budget is exhausted
        while (problem.evaluations < problem.dimension * budget_multiplier
            and not problem.final_target_hit):
                       
            solver["solver"].fmin(
                problem,
                x0,
                {key:eval(value) for key,value in solver["cocoargs"].items()},
                solver["methodargs"]
                # **{key:eval(value) for key,value in solver["kwargs"].items()}
            )

            # Reset initial guess to be random
            x0 = problem.lower_bounds + ((rand(problem.dimension) + rand(problem.dimension)) *
                        (problem.upper_bounds - problem.lower_bounds) / 2)
        
        minimal_print(problem, final=problem.index == len(suite) - 1)

    ### post-process data
    cocopp.main(observer.result_folder)  # re-run folders look like "...-001" etc
webbrowser.open(f"file://{os.getcwd()}/ppdata/index.html")>

which loops through the solvers I have, but the resulting html just has the results for each solver independently. Any help would be much appreciated.

Thanks
Karl

**Comment by brockho** [comment]
Dear Karl,

Thanks for your question. Here is hopefully an answer that allows you to do what you want to do.

To see the results of several solvers in the plots, you will have to do the experiments for each solver on a separately observed function. In your code, you add the observer to each function for each new solver (which is the right thing to do) but I am not sure that the observers don't get added and added, meaning that the runs of the later solvers still record in the old experiments folders. The easiest seems to be to also create the suite object anew each time within the solver loop. This will make sure that COCO logs for each solver in a new folder (and stops logging in the folders of other solvers), Once you have created all those folders for the different solvers, you can run the postprocessing via
```
cocopp.main('folder_1/ folder_2/ ... folder_n/')
```
with the `folder_i/` being the folder for solver `i`. This should, as before, automatically open your browser once it is finished and show the results of all algorithms.

Note that you can also easily compare with any other algorithm, already present in the [COCO data repository](https://numbbo.github.io/data-archive/), by simply adding the corresponding algorithm name(s) to the string:
```
cocopp.main('myfolder_1/ ... myfolder_n/ L-BFGS')
```
for example compares the algorithms from the local `myfolder_i` folders with the largescale variant of the Quasi-Newton BFGS.

Please let us know in case you still have problems.

**Comment by s4ksb** [comment]
Hi,

Thanks for the quick response! All is working well and I'm getting the plots I wanted.

Thanks
Karl

**Comment by brockho** [comment]
I am happy that we could help.
