### ISSUE TITLE
[Bug report] cocoSuiteGetProblem returns 0 in Matlab

### ISSUE THREAD

**Issue by juanrasinesmazo** [numbbo/coco#2144]
**Describe the bug**
I am attempting to run the bbob-biobj problems on [PlatEMO](https://github.com/BIMK/PlatEMO) using the Matlab- compiled version of cocoex, which I installed as:

`python do.py run-matlab`

I define the problem suite and instances as follows:

`suite = cocoCall('cocoSuite', 'bbob-biobj', 'year: 2016', 'dimensions: 10');`

But when I attempt to obtain the problem by index (i.e. bbob-biobj f1), I do not get the correct pointer:

```
>> problem = cocoCall('cocoSuiteGetProblem', suite, 0)
problem =
  int64
   0
```
This way also returns the exact same result, no matter the index I try:
```
>> cocoSuiteGetProblem(suite_t, 100)
ans =
  int64
   0
```
Confusingly, using `cocoSuiteGetNextProblem`, I seem to get correct pointers:
```
>> observer = cocoObserver('no_observer', '');
>> problem = cocoSuiteGetNextProblem(suite, observer);
ans =
  int64
   140534359439712
```
The problem is I only know how to extract the problem by index from the Python implementation, where I need to following formula to get the correct problem (i.e. f5 => index = 40):
`problem_index = 10 * (problem_number - 1)
`
I have no idea why this is the case or if it applies to the Matlab implementation. I was hoping someone could guide me to the correct usage or if there is actually a bug with my Matlab/cocoex/operating system.

Thanks in advance,

Juan

**Your System (please complete the following information when it seems relevant):**
 - Operating system: Ubuntu20.04
 - COCO version: cocoex 2.6.2

**Comment by brockho** [comment]
Dear Juan,

Many thanks for this bug report. It seems to be valid as I can observe the same. I digged a bit deeper and found something. When I try to get (only) the first of the default dimensions, it works, but for later ones, it does not, see the following Matlab code:
```matlab
>> suite = cocoCall('cocoSuite', 'bbob-biobj', 'year: 2016', '')

suite =

  int64

   140691159636336

>> problem = cocoCall('cocoSuiteGetProblem', suite, 0)

problem =

  int64

   140691158582464

>> suite = cocoCall('cocoSuite', 'bbob-biobj', 'year: 2016', 'dimensions: 2')

suite =

  int64

   140691160704976

>> problem = cocoCall('cocoSuiteGetProblem', suite, 0)

problem =

  int64

   140691158584496

>> suite = cocoCall('cocoSuite', 'bbob-biobj', 'year: 2016', 'dimensions: 10')

suite =

  int64

   140691160705264

>> problem = cocoCall('cocoSuiteGetProblem', suite, 0)

problem =

  int64

   0
```

I did not check whether this also happens in C, but I can imagine. @ttusar: would you have time to check whether the dimension option is faulty in `coco_suite.c`?

**Comment by nikohansen** [comment]
I am not familiar with the Matlab interface, so I have no idea whether this quick-and-dirty workaround could work (it should in Python): for each problem you are looking for, first call `'cocoSuite'` and then call `cocoSuiteGetNextProblem` until you get the problem you want. For this, you need to (be able to) check the problem properties you are looking for. There is, for example, a `cocoProblemGetId` function. So if you can map each index to the correct `Id` that should do the job. If you just want all problems with dimension=10, you can store a counter how many problems were already done and skip as many which match when you look for the next. You could also generate a map from the position in the `cocoSuiteGetNextProblem` loop to whichever property you are interested in and implement a function which returns only the `i`-th function which comes up during this loop or only the next function with this property. Just throwing around ideas...

**Comment by juanrasinesmazo** [comment]
Thanks for the tip @nikohansen. I was hoping not to resort to that but I went ahead and tried it anyways. I have put together the following code snippet to give the 'correct' bbob-biobj problem instance given the problem number `f_num`:
```
% Define BIOBJ object
f_num = 6;
prob_num = 1 + 10*(f_num - 1);
suite_name = 'bbob-biobj';
suite_instances = 'year: 2016';
suite_options = sprintf('dimensions: %.0f', D);
suite = cocoSuite(suite_name, suite_instances, suite_options);
observer = cocoObserver('no_observer', '');
                
% Iterate through problems until correct one is found 
for i = 1:prob_num
    problem = cocoSuiteGetNextProblem(suite, observer);
end
disp(cocoProblemGetId(problem));
disp(cocoProblemGetName(problem));
```
This outputs the problem name and info:
```
bbob-biobj_f06_i01_d10
bbob_f001_i02_d10__bbob_f014_i04_d10
```
Which matches the output from the python cocoex version (I have checked the function outputs also). Leaving this here for anyone who comes across the same bug. Any possibility of having the `cocoSuiteGetProblem()` function fixed at some point in the near future @brockho @ttusar? (:

Cheers,

Juan

**Comment by EricZheng1024** [comment]
I have implemented the use of the BBOB test suite on PlatEMO, and hope it might be helpful. See [here](https://github.com/EricZheng1024/BBOBxPlatEMO) for details.
