### ISSUE TITLE
[Feature request] Getting pprldmany data

### ISSUE THREAD

**Issue by s4ksb** [numbbo/coco#2153]
Hi there,

I am running a coco experiment to test a solver and I want to get the numerical values used for the pprldmany plots. How/what is the best way to get these values?

Thanks
Karl

**Comment by nikohansen** [comment]
These data are generated in the `cocopp.compall.pprldmany.main` function, specifically collected in the `dictData` variable in the function and plotted with `cocopp.compall.pprldmany.plotdata`. Current `main` seems to return `None`.

One can load datasets with `cocopp.load` and then call the above `main` function. Setting `cocopp.compall.pprldmany.close_figure = False` would prevent the created figures from being closed such that it should be possible to get the data from the `matplotlib` figures.
