### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2166]
I get the following deprecation warning: `The py23 module has been deprecated and will be removed in a future release. Please update your code.` while running:
```
python -c "import cocopp; print(cocopp.__version__)"
python -m cocopp kerLQ.tar.gz kerCOMO.tar.gz   
```
```
2.6.1.138
Post-processing (2+)
  Using 2 data sets:
    kerLQ.tar.gz
    kerCOMO.tar.gz

Post-processing (2+)
  loading data...
  using pickled DataSetList   using: kerLQ.tar.gz
    archive extracted to folder .extracted_kerCOMO ...
  Data consistent according to consistency_check() in pproc.DataSet
  using: kerCOMO.tar.gz
  Will generate output data in folder ppdata/kerLQ_kerCO
    this might take several minutes.
ECDF runlength ratio graphs...
/Users/hansen/opt/anaconda3/lib/python3.9/site-packages/fontTools/misc/py23.py:11: DeprecationWarning: The py23 module has been deprecated and will be removed in a future release. Please update your code.
  warnings.warn(
  done (Fri Feb 17 13:23:38 2023).
[...]
```

**Comment by olafmersmann** [comment]
Will be fixed as part of the big `feat-build_infra` branch merge which also contains some modernisation of the cocoex and cocopp packages.

**Comment by brockho** [comment]
Looks like this is indeed integrated into the `development` branch now with the commit https://github.com/numbbo/coco/commit/29da572beaff165e0228c9cd8a53d69346163041 by @olafmersmann.

**Comment by olafmersmann** [comment]
> Looks like this is indeed integrated into the `development` branch now with the commit [29da572](https://github.com/numbbo/coco/commit/29da572beaff165e0228c9cd8a53d69346163041) by @olafmersmann.

yes, but the fix is broken. Not sure how I didn't catch it, will be fixed in an upcoming commit.
