### ISSUE TITLE
Significance test when the Df precision value is negative

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2167]
This line in `toolsstats.py`. 
```python
tmp[idx] = -fvalues[j][idx]
```
assigns the $f$-value data used in the significance test which are combined with inverted evaluation numbers (hence larger is better).

This looks wrong when `fvalues` is negative, which can be the case on the biobjective test suite?

**Comment by brockho** [comment]
In our current data sets (where we first observed the bug), all `.funvals` are positive for the case of f5 in 5-D (where the problem in the table appears).

Note: the same issue appears when comparing the two `bbob-biobj` data sets from 2021.

**Comment by nikohansen** [comment]
This is not a/the bug "we observed", it's a bug I observed by reading the code.
