### ISSUE TITLE
How are the evals of the reference algorithm meant to look like?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2176]
The `_evals` attribute and hence the results of calling `detEvals` from the `best 2009` reference algorithm has currently only one "column", that is, one measured evaluations (see example below). Is this a feature or [a bug](https://github.com/numbbo/coco/issues/2175)? By reading the code, the function [`cocopp.refalg.generate`](https://github.com/numbbo/coco/blob/09bc36419a15d5fad7d4f928f734ce9efc64edec/code-postprocessing/cocopp/bestalg.py#L457) seems to [generate data sets with more "columns"](https://github.com/numbbo/coco/blob/09bc36419a15d5fad7d4f928f734ce9efc64edec/code-postprocessing/cocopp/bestalg.py#L189) in `BestAlgSet.__init__`.

```python
import cocopp

_ = cocopp.load2('lq-CMA!')  # set reference algorithm
dsl = cocopp.bestalg.load_reference_algorithm(
    cocopp.testbedsettings.current_testbed.reference_algorithm_filename)
dsl[(40, 23)]._evals
```
```
[...]
[array([15.84893192,  1.        ]),
 array([10.,  7.]),
 array([ 6.30957344, 68.        ]),
 array([  3.98107171, 292.        ]),
 array([  2.51188643, 603.        ]),
 array([1.58489319e+00, 2.48700000e+03]),
 array([1.0000e+00, 1.1925e+04]),
 array([6.30957344e-01, 2.87240000e+04]),
 array([3.98107171e-01, 3.09090000e+04]),
 array([2.51188643e-01, 3.67700000e+04]),
 array([1.58489319e-01, 3.90030000e+04]),
 array([1.0000e-01, 7.5453e+04]),
 array([6.30957344e-02, 9.31460000e+04]),
 array([3.98107171e-02, 1.05801000e+05]),
 array([2.51188643e-02, 2.19334000e+05]),
 array([1.58489319e-02, 2.35539000e+05]),
 array([1.00000e-02, 6.60873e+05]),
 array([6.30957344e-03, 9.02792000e+05]),
 array([3.98107171e-03, 9.84553000e+05]),
 array([2.51188643e-03, 1.12794500e+06]),
 array([1.58489319e-03, 1.14015400e+06]),
 array([1.000000e-03, 1.278672e+06]),
 array([6.30957344e-04, 1.35893000e+06]),
 array([3.98107171e-04, 1.94653200e+06]),
 array([2.51188643e-04, 2.27568800e+06]),
 array([1.58489319e-04, 3.13842600e+06]),
 array([1.00000e-04, 3.15979e+06]),
 array([6.30957344e-05, 3.18497400e+06]),
 array([3.98107171e-05, 3.19539600e+06]),
 array([2.51188643e-05, 3.21474400e+06]),
 array([1.58489319e-05, 3.23051800e+06]),
 array([1.000000e-05, 3.242155e+06]),
 array([6.30957344e-06, 3.25764700e+06]),
 array([3.98107171e-06, 3.26969300e+06]),
 array([2.51188643e-06, 3.28283200e+06]),
 array([1.58489319e-06, 3.29243300e+06]),
 array([1.00000e-06, 3.30633e+06]),
 array([6.30957344e-07, 3.32154000e+06]),
 array([3.98107171e-07, 3.33290000e+06]),
 array([2.51188643e-07, 3.34097600e+06]),
 array([1.58489319e-07, 3.35098800e+06]),
 array([1.00000e-07, 3.36043e+06]),
 array([6.30957344e-08, 3.37527500e+06]),
 array([3.98107171e-08, 3.38912900e+06]),
 array([2.51188643e-08, 3.40144200e+06]),
 array([1.58489319e-08, 3.41295100e+06]),
 array([1.000000e-08, 3.427542e+06])]
```

**Comment by brockho** [comment]
If I remember correctly, we decided to have only one entry per dimension/function/target tupel because the algorithms contributing to the `bestalg` (might) come from different instances. The entry is thus the ERT for this dimension/function/target tupel of the best/reference algorithm.

**Comment by nikohansen** [comment]
I see. I don't quite understand (anymore) why different instances or a different number of instances would be a problem. The `_evals` attribute is not an array anymore but a list of arrays which can have different sizes (number of instances). What are the other reasons why we could not provide all evals? Too big in size? Maybe the above decision was taken before the list of arrays was implemented?

**Comment by nikohansen** [comment]
Reference algorithm data can be read/used as reference algorithms (as above) and also as a "normal" `DataSetList`. In the latter case, the `DataSet._evals` attribute is an array where each row has the same number of columns. For this use case, the entries were reduced to a single column, the ERT.
