### ISSUE TITLE
Links astray

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2191]
These links probably don't point to the right place:

- [x] http://numbbo.github.io/
- [x] http://numbbo.github.io/coco-doc/bbob-largescale/functions/
- [x] http://numbbo.github.io/coco-doc/bbob-biobj/functions/

**Comment by brockho** [comment]
Agreed. I guess, the first one should forward to https://numbbo.github.io/coco/ and the others to the corresponding PDFs? If so, I am happy to take care of that.

**Comment by nikohansen** [comment]
Makes sense to me. We also had a summary pdf for the constraint testbed but it's not linked under http://numbbo.github.io/coco-doc/bbob-cons/functions or http://numbbo.github.io/coco-doc/bbob-cons

**Comment by brockho** [comment]
Question: do we want to link to the function description pdf (such as https://hal.inria.fr/hal-01296987) if we have a link to a test suite (such as http://numbbo.github.io/coco-doc/bbob-biobj/functions/) or do we rather want to link to the test suite page of the (not so new anymore) COCO page (such as https://numbbo.github.io/coco/testsuites/bbob-biobj) with all the other links also available?

**Comment by ttusar** [comment]
Some time ago we discussed (and maybe even decided) to always link to the COCO page, which contains links to everything else. 

In the case of the bbob-biobj functions I would prefer not to link to http://numbbo.github.io/coco-doc/bbob-biobj/functions/ anywhere, because it is quite outdated and we now have a much better freely available paper on it.

**Comment by nikohansen** [comment]
> Question: do we want to link to the function description pdf (such as https://hal.inria.fr/hal-01296987) if we have a link to a test suite (such as http://numbbo.github.io/coco-doc/bbob-biobj/functions/) or do we rather want to link to the test suite page of the (not so new anymore) COCO page (such as https://numbbo.github.io/coco/testsuites/bbob-biobj) with all the other links also available?

I am confused, https://numbbo.github.io/coco/testsuites/bbob-biobj is outdated in your estimate? I was in the believe that this should be(come) the new entry point!

**Comment by nikohansen** [comment]
> Some time ago we discussed (and maybe even decided) to always link to the COCO page, which contains links to everything else.

What is _the COCO page_? I see at least two candidates in particular when we talk about documentation questions.

https://numbbo.github.io
https://github.com/numbbo/coco

**Comment by brockho** [comment]
> I am confused, https://numbbo.github.io/coco/testsuites/bbob-biobj is outdated in your estimate? I was in the believe that this should be(come) the new entry point!

The question is: do we want to link to the PDF also from somewhere else or only via this webpage?

**Comment by ttusar** [comment]
I think we said at some point that it would make sense to have a single entry point for all documentation (https://numbbo.github.io/) and link it from everywhere so that when we need to update/change something, we only have to do it once.

**Comment by brockho** [comment]
All above links are now linking to the (hopefully) correct pages/pdfs.

**Comment by nikohansen** [comment]
https://numbbo.it/ may become the new single entry point?
