### ISSUE TITLE
[DATA SUBMISSION] DIRECT-REV, BIRMIN, and I-DBDP-GL

### ISSUE THREAD

**Issue by JakubKudela89** [numbbo/coco#2196]
Hello COCO user!

Here is the right place to submit one or several COCO data sets to the official COCO archive (https://coco.gforge.inria.fr/doku.php?id=algorithms). Please provide the information requested below and submit the issue. Do not hesitate to read about the details in our [How to publish a dataset documentation](https://github.com/numbbo/coco/blob/development/howtos/publish-a-dataset-howto.md).

#### Reference
[Put the full reference (for citations) and a link to the pdf here.]

Kudela, J. Benchmarking State-of-the-art DIRECT-type Methods on the BBOB Noiseless Testbed. Submitted to the GECCO'23 workshop.

#### Description of the Algorithm(s)
[Please provide a short description for each algorithm in the data.]

State-of-the-art DIRECT-type methods from the DIRECTGOLib platform (DIRECT-REV, BIRMIN, and I-DBDP-GL)

#### Link to Data
[Please prepare and upload your COCO data (see [how to](https://github.com/numbbo/coco/blob/development/howtos/publish-a-dataset-howto.md)) and provide the link here. If you want to submit more than one data set at the same time, please indicate which file corresponds to which algorithm.] 

https://doi.org/10.5281/zenodo.7805629

#### Optional: Source Code of Experiment
[We are happy to also share any source code of the algorithm and the COCO experiment, you were running. Please provide, if you wish, any code, links, etc. here]

**Comment by brockho** [comment]
Dear Jakub,

Many thanks for your data submission and your contribution to the BBOB-2023 workshop! I had a look into you data (mainly postprocessing it and looking at the warnings) and found a few things that we should try to fix.

The first issue, I encountered was this message:
```
UserWarning: 100:150336|0.0e+00suite is an additional attribute.
  warnings.warn('%s is an additional attribute.' % (attrname))
```
which could be attributed to a missing line break in the corresponding .info file (nothing to be done here, I simply edited the file and don't see this warning anymore). The other issue, I cannot solve on my side, I guess. What I get is the following warning:
```
UserWarning: The data of DataSet(BIRMIN on f1 2-D) (and possibly further data) do not list the correct instances of function F1.
```
and what I found in the corresponding file was this line here:
```
data_f1/bbobexp_f1_DIM2_i1.dat, 1:100005|3.1e-11, 2:100006|1.1e-12, 3:100006|4.6e-12, 4:100004|6.1e-11, 5:100008|9.2e-13, 91:100007|6.5e-11, 92:100014|1.5e-08, 93:100002|3.5e-12, 94:100012|4.4e-06, 95:100007|1.8e-11, 96:100004|8.1e-13, 97:100002|2.4e-06, 98:100005|0.0e+00, 99:100021|1.2e-12, 100:100006|3.4e-13
```
It has a surprisingly unexpected `0.0e+00` value listed for instance 98. Given that the other instances are solved to a high precision, I wonder what went wrong here. Not sure, though, that this causes the warning. The `.dat` and `.tdat` files have the right amount of 15 instances.

Can you please have a look? Thanks in advance.

**Comment by JakubKudela89** [comment]
Dear Dimo,
thank you for the feedback.

Regarding the second issue, I also got a similar (although not exactly the same) warming when running the postprocessing scripts in python:

```
  instance numbers not among the ones specified in 2009, 2010, 2012, 2013, and 2015-2018')
UserWarning:   instance numbers not among the ones specified in 2009, 2010, 2012, 2013, and 2015-2018
```

but, as the resulting figures/statistics looked correct, I did not pay too much attention to it.

I think the problem is that the instance numbers that I used are not 'supported'.
I ran the COCO suite in version 2.6 in MATLAB, calling it with the following command (same for all methods):

`suite = cocoSuite(suite_name, '', 'dimensions: 2,3,5,10,20');
`
which produces instance numbers 1:5, 91:100.

I now tried to do a small experiment with added year specification:
`suite = cocoSuite(suite_name, 'year: 2018', 'dimensions: 2,3,5,10,20');`
which produced instance numbers 1:5, 71:80, and I did not get the errors in postprocessing anymore.

The question is, should I re-run the experiments

**Comment by JakubKudela89** [comment]
I've updated the cocopp and downloaded the data from zenodo to try to replicate the issue.

I now found the source of the first issue - the I-DTC-GL folder (that was uploaded) was not the right one. It should be I-DBDP-GL (I just mistook one for the other). I sincerely apologize for this. I've updated the zenodo files so that they are now correct.

Anyway, I tried recreating your steps - I run the comparison (on the first version of the files in zenodo)
`cocopp.main('BIRMIN I-DTC-GL DIRECT-REV')`
got the error about the missing line break, fixed it, and run the comparison again. I did get the following warning:
`UserWarning: The data of DataSet(I-DTC-GL on f1 5-D, 100:150336|0.0e+00suite = bbob) (and possibly further data) do not list the correct instances of function F1.`
Which went away once I deleted the previously generated .pickle files (i.e., I did not get any errors or warnings afterward).

I then added the results from the DIRECT method for comparison (from https://numbbo.github.io/data-archive/bbob/) and got an error that is very close to the one you have:
`UserWarning: The data of DataSet(DIRECT on f1 2-D) (and possibly further data) do not list the correct instances of function F1.
`
which might be caused by DIRECT being originally tested only on instances 1:5.

**Comment by brockho** [comment]
Dear Jakub,

One small question: is the data named "I-DTC-GL" the same as "I-DBDP-GL" from the paper?

**Comment by JakubKudela89** [comment]
Dear Dimo,
no, they are not. The 'I-DTC-GL' data were for a different method. Although it has nearly the same working principles as 'I-DBDP-GL' and the results on the BBOB set look almost identical.

**Comment by brockho** [comment]
Okay, thanks. Would you then be so kind and also upload the data for I-DBDP-GL from the paper here? It will be nice to have all of the data used in all workshop papers in the [official archive](https://numbbo.github.io/data-archive/bbob/). Many thanks in advance.

**Comment by JakubKudela89** [comment]
Certainly - they can be found in the second version of the zenodo submission (https://doi.org/10.5281/zenodo.7817847) in the [exdata_v2.zip] file. I'll try to make it more clear next time.

**Comment by brockho** [comment]
Ah, perfect. I have them now. Many thanks for the extremely quick response :-)

**Comment by brockho** [comment]
Many thanks again for your data submission. All three algorithms from your paper should be now available via the postprocessing of COCO. If you don't see the entries, you will have to type ```import cocopp; cocopp.archives.update_all()``` in your favorite python shell/notebook first.
