### ISSUE TITLE
[DATA SUBMISSION] 

### ISSUE THREAD

**Issue by icygreen-xy** [numbbo/coco#2202]
Hello COCO user!

Here is the right place to submit one or several COCO data sets to the official COCO archive (https://coco.gforge.inria.fr/doku.php?id=algorithms). Please provide the information requested below and submit the issue. Do not hesitate to read about the details in our [How to publish a dataset documentation](https://github.com/numbbo/coco/blob/development/howtos/publish-a-dataset-howto.md).

#### Reference
[1] N. Hansen, A. Auger, O. Mersmann, T. Tusar, and D. Brockhoff. 2016. COCO: A  Platform for Comparing Continuous Optimizers in a Black-Box Setting. ArXiv e-prints arXiv:1603.08785 (2016).
[2] S. Finck, N. Hansen, R. Ros, and A. Auger. 2009. Real-Parameter Black-Box Optimization Benchmarking 2009: Presentation of the Noiseless Functions. [Research Report] RR-7215, INRIA. 2010. ffinria-00462481f https://inria.hal.science/inria-00462481/document

#### Description of the Algorithm(s)
MAB optimizer 001 -014 

#### Link to Data

https://drive.google.com/file/d/11wG89gQhm6bH7jqRSClqG72hyEP57Tu4/view?usp=share_link

#### Optional: Source Code of Experiment
[We are happy to also share any source code of the algorithm and the COCO experiment, you were running. Please provide, if you wish, any code, links, etc. here]
`Collecting them in recent days...`

**Comment by brockho** [comment]
Hello!

Many thanks for your data submission and your submission to the workshop. I downloaded the file without problems but when postprocessing, I get many warnings of the type
```
UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110} found several times. Read data for F10 in 2-D might be inconsistent
```
and I see also several subfolders of the same/similar name in your `.zip` file but with different performances and different experiment lengths. Would you be so kind and send us a cleaned up version with only the data from a single experimental setup? Or let us know which of the subfolders (maybe `MBAoptimizer014_on_bbob`?) we should use as final data. Many thanks in advance.

**Comment by icygreen-xy** [comment]
Hello,Prof:

I am collecting them in recent days. May need 2 days, and I will update it here on the weekend.  
I do not encounter this error in my experiment, and maybe I should share my code and then there might be a more complete result. I might need to list a table to explain the subfoloders.  This table might be possible.

<img width="416" alt="image" src="https://user-images.githubusercontent.com/110183414/233526123-a15e320b-e3f1-4aec-b393-cb9a7beb4baa.png">

Many thanks

**Comment by icygreen-xy** [comment]
`MBAoptimizer014_on_bbob` I found here, and the last day I showed in the picture was MAB Optimizer 014.

I need to change my file name: `MABoptimizer014_on_bbob`  just named file was not correct. (`MBAoptimizer014_on_bbob` --> `MABoptimizer014_on_bbob`)

**Comment by icygreen-xy** [comment]
The data I collected from `coco-->exdata`
![image](https://user-images.githubusercontent.com/110183414/233785213-327d48fd-e1e3-4d98-a5ab-910c479531e6.png)

![image](https://user-images.githubusercontent.com/110183414/233785219-5e3a748e-bd54-4601-8caf-70c654c7fe5e.png)

**Comment by icygreen-xy** [comment]
Test **Postprocess **
![image](https://user-images.githubusercontent.com/110183414/233785686-c1406079-6671-4206-9970-701900aa46fb.png)'


Should I use `python -m cocopp [-o /Users/icygreen/coco/ppdata/MBArun_of_optimizer2_2D_on_bbob-016]` ?

**Comment by icygreen-xy** [comment]
Test **Postprocess **

![image](https://user-images.githubusercontent.com/110183414/233786958-e31827f7-0b5e-4f73-83dd-5415eeaa1a31.png)

Should I use `python -m cocopp [-o /Users/icygreen/coco/ppdata/MBArun_of_optimizer2_2D_on_bbob-016]`  to test?

**Comment by icygreen-xy** [comment]
Does the problem.lower_bound or upper_bound  in picture 1- format equal to that in picture 2? 
I notice there is an str `' array' `in front of `[-5,5]` : 
`[array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]), array([-5., -5.]),`


**Picture 1**
![image](https://user-images.githubusercontent.com/110183414/233790085-dcae7734-76d8-42ab-9437-f3938df74b24.png)



**Picture 2**

![image](https://user-images.githubusercontent.com/110183414/233790151-e9abe71e-adb5-4bfc-af27-facccbb2f5d9.png)


![image](https://user-images.githubusercontent.com/110183414/233790164-e8d5e693-db89-43d7-a134-c3c049147d6c.png)

**Comment by icygreen-xy** [comment]
I delete: generating function of an arrary -

```python
if not isinstance(lb, list):
    lb = [lb for _ in range(dim)]
    ub = [ub for _ in range(dim)]
lb = np.asarray(lb)
ub = np.asarray(ub)
``` 

I  am using `def MABrun(problem, problem.lower_bounds, problem.upper_bounds, problem.dimensions, NumOfRuns= ?, popSize=?,Iterations=?): `  to generate the data.

This single data can be sent in this link: waiting

**Comment by icygreen-xy** [comment]
> I delete: function of generating an array -
> 
> ```python
> if not isinstance(lb, list):
>     lb = [lb for _ in range(dim)]
>     ub = [ub for _ in range(dim)]
> lb = np.asarray(lb)
> ub = np.asarray(ub)
> ```
> 
> I am using `def MABrun(problem, problem.lower_bounds, problem.upper_bounds, problem.dimensions, NumOfRuns= 1, popSize=30,Iterations=35): ` to generate the data.
> 
> This single data was sent in this link: https://drive.google.com/file/d/1OqkSboyOqjKOKL8aYwjlK4MDa_gckz-C/view?usp=sharing Also, there was an email sent
> 
> `Can data in this link be post-processed? ` - If it's possible, let me know, thanks~ :D

**Question: Are there any constraints scope of calling the problem.lower_bounds/upper_bounds? for example, fixed constraint value [-5,5] or I can choose an available value from the scope of [-5,5] rather than a fixed constraint :-5 or 5**

**Comment by icygreen-xy** [comment]
> I delete: function of generating an array -
> 
> ```python
> if not isinstance(lb, list):
>     lb = [lb for _ in range(dim)]
>     ub = [ub for _ in range(dim)]
> lb = np.asarray(lb)
> ub = np.asarray(ub)
> ```
> 
> I am using `def MABrun(problem, problem.lower_bounds, problem.upper_bounds, problem.dimensions, NumOfRuns= 1, popSize=30,Iterations=35): ` to generate the data.
> 
> This single data was sent in this link: https://drive.google.com/file/d/1OqkSboyOqjKOKL8aYwjlK4MDa_gckz-C/view?usp=sharing Also, there was an email sent
> 
> `Can data in this link be post-processed? ` - If it's possible, let me know, thanks~ :D

If this can work in post-process, I'll provide a full file, not a single algorithm collection later.

**Comment by icygreen-xy** [comment]
Hello Profs,

I inspect my algorithm in recent days-- GA algorithm might be not suitable in my framework, and there is a more motification in the next version. ( Need more time to set up a different  initialization and framework for GA, GA has many sub functions that need to be called. )

Other left 4 algorithms and previous three algorithms can works in this framework, and I'll upload the result that can be checked.

(I am not sure  -  `def MABrun(problem, problem.lower_bounds, problem.upper_bounds, problem.dimensions, NumOfRuns= 1, popSize=30,Iterations=35): ` does it can work in post process? )


Left 4 algorithms might follow the previous three algorithms can get the result.  (But there is a bug poping out for some while, it looks a little unstable. )

![image](https://user-images.githubusercontent.com/110183414/235410547-0f610c54-6111-43a9-9744-4e095ea8ec86.png)
![image](https://user-images.githubusercontent.com/110183414/235410607-5cd271d4-1f97-4c17-a7ff-3d93ec4cf567.png)
![image](https://user-images.githubusercontent.com/110183414/235410607-5cd271d4-1f97-4c17-a7ff-3d93ec4cf567.png)

I am ready to open source - my code in my github after a while. Hope you can see and give me some sugggestions. Thanks~ 

( I have tests last weeks, and all my frineds around me can not understand this topics and  in my own individually time was limited, so I could not update in time. Thanks!)

**Comment by icygreen-xy** [comment]
> Hello Profs,
> 
> I inspect my algorithm in recent days-- GA algorithm might be not suitable in my framework, and there is a more motification in the next version. ( Need more time to set up a different initialization and framework for GA, GA has many sub functions that need to be called. )
> 
> Other left 4 algorithms and previous three algorithms can works in this framework, and I'll upload the result that can be checked.
> 
> (I am not sure - `def MABrun(problem, problem.lower_bounds, problem.upper_bounds, problem.dimensions, NumOfRuns= 1, popSize=30,Iterations=35): ` does it can work in post process? )
> 
> Left 4 algorithms might follow the previous three algorithms can get the result. (But there is a bug poping out for some while, it looks a little unstable. )
> 
> ![image](https://user-images.githubusercontent.com/110183414/235410547-0f610c54-6111-43a9-9744-4e095ea8ec86.png) ![image](https://user-images.githubusercontent.com/110183414/235410607-5cd271d4-1f97-4c17-a7ff-3d93ec4cf567.png) ![image](https://user-images.githubusercontent.com/110183414/235411561-7de7f5c9-fee0-469b-ab30-f89c6dba7079.png)
> 
> `RecursionError: Maximum recursion depth exceeded while calling a Python object.`
> 
> I am ready to open source - my code in my GitHub after a while. Hope you can see it and give me some suggestions. Thanks~
> 
> ( I have tests last week, and all my friends around me can not understand this topic and in my own individual time was limited, so I could not update in time. Thanks!)

My new test data was uploaded, and my open-source code was released 2 days ago:

1. https://drive.google.com/file/d/1Wa2WTajY9uLpnwGQfQK8bSzrGUntqVVE/view?usp=sharing
2.https://github.com/icygreen-xy/Heuristic-MAB/tree/main

**Comment by brockho** [comment]
As there is no official paper submission coming with this data, I suggest to close the issue.

**Comment by icygreen-xy** [comment]
that's ok with it, thanks, Profs. We're revising the experiment currently and this one can be closed. The new one will be submitted next time. Thanks for your help!
