### ISSUE TITLE
[DATA SUBMISSION] BORG MOEA on BBOB-BiObj

### ISSUE THREAD

**Issue by Slickytail** [numbbo/coco#2203]
#### Reference
Submitted to GECCO 2023 Workshop, will update once accepted/rejected

#### Description of the Algorithm(s)
BORG-MOEA: Borg MOEA with epsilon = 10^-4.
BORG-MOEA-adapt: Borg MOEA with epsilon set dynamically per objective, with eta = 10^-2.. See paper and code for details.

#### Link to Data
[https://slickytail.github.io/borg-adaptive-epsilon/data-archives](https://slickytail.github.io/borg-adaptive-epsilon/data-archives)

#### Source Code of Experiment
[slickytail/borg-adaptive-epsilon](https://github.com/Slickytail/borg-adaptive-epsilon)

**Comment by brockho** [comment]
Dear @Slickytail,

Many thanks for your submission of the BORG data. Unfortunately, I cannot download it because the above link does not work for me. The link to the source code, though, is working. Is it possible that you forgot to push your changes?

**Comment by Slickytail** [comment]
@brockho hello, the link I gave is to the root folder, which doesn't have any content. But the following links should work:

https://slickytail.github.io/borg-adaptive-epsilon/data-archives/coco_archive_definition.txt
https://slickytail.github.io/borg-adaptive-epsilon/data-archives/BORG-MOEA.zip
https://slickytail.github.io/borg-adaptive-epsilon/data-archives/BORG-MOEA-adapt.zip

**Comment by brockho** [comment]
Many thanks again for your data submission. Both Borg data sets should be now available via the postprocessing of COCO. If you don't see the entries in ```cocopp.bbob_biobj```, you will have to type ```import cocopp; cocopp.archives.update_all()``` in your favorite python shell/notebook first (once should be enough).
