### ISSUE TITLE
[DATA SUBMISSION] CMA-ES with modifications that facilitate a theoretical analysis

### ISSUE THREAD

**Issue by agissler** [numbbo/coco#2204]
#### Reference
Armand Gissler, Evaluation of the impact of various modifications to CMA-ES that facilitate its theoretical analysis. GECCO' 23 Companion. https://doi.org/10.1145/3583133.3596329

#### Description of the Algorithm(s)
CMA-ES with/without cumulation, with different updates on the stepsize, with/without affine-invariant path.

#### Link to Data
https://doi.org/10.5281/zenodo.7944085

#### Source Code of Experiment
https://github.com/agissler/Benchmarking_proof_variants_CMA-ES

**Comment by brockho** [comment]
Dear @agissler,

Many thanks for your data submission for the BBOB workshop. Unfortunately, some of the data sets contain results in multiple subfolders: this is not a problem per se but I can see from the postprocessing that not all data sets are consistent and it is more difficult to understand what are the "correct" data if multiple subfolders exist.

For adm-CMA-ES, for example, multiple (if not all) instances are duplicated, for dm-CMA-ES, instances are missing---according to the warnings that I get from the postprocessing. Maybe, the other algorithms are fine, but I am not 100% sure. Would you be so kind and re-check and upload the cleaned files here?

Many thanks in advance.

**Comment by agissler** [comment]
Hi @brockho, you are right, two folders were missing, sorry about that. I've updated the files in https://doi.org/10.5281/zenodo.7944085
