### ISSUE TITLE
Accessing problem's `xopt` and `fopt` from the python interface

### ISSUE THREAD

**Issue by FMGS666** [numbbo/coco#2219]
Today, during the RANDOPT meeting, @brockho told me about the way in which it should be possible to access the problem's   `xopt` and `fopt` from python.

He explained me that it is supposed to be done in a safe way by writing them to a file and then reading it.

I guess the reasons behind this are to protect these attributes, so that user could not mistakenly reassign them.

I just assumed it this morning and I forgot to ask whether this is actually the case, or there are other reasons that go beyond it.

I am asking because, during the implementation of the `bbob-noisy` suite, I had to check if these values were matching with the ones obtained from the legacy code, so I implemented a simple interface in the [`code-experiments/build/python/cython/interface.pyx`](https://github.com/numbbo/coco/blob/dev-bbob-noisy/code-experiments/build/python/cython/interface.pyx) file to access them as `@property`s of the `Problem` objec,  with `problem.best_value` and `problem.best_decision_vector` (returning respectively the `fopt` and the `xopt` of the C code). 

Professor Dimo asked me to remove this interface, as this data was intentionally hidden to the user.

What I didn't think about is that you cannot actually overwrite attributes defined with the `@property` decorator.

The following code snipped provides an example of this:

```
>>> import cocoex
>>> suite = cocoex.Suite("bbob-noisy", "", "")
>>> problem = suite[0]
>>> problem.best_decision_vector = [0,0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: attribute 'best_decision_vector' of 'cocoex.interface.Problem' objects is not writable
>>> problem.best_value = 10.0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: attribute 'best_value' of 'cocoex.interface.Problem' objects is not writable
```

If the only reason behind this way of accessing them is to avoid users to reassign them, then I think this implementation (which you can find in the `dev-bbob-noisy` branch) could do the same job in an easier way... 

If this doesn't make sense at all I will just delete the interface right away, I just wanted to mention this before doing so because this morning I didn't think about it, sorry.

Thanks again!

**Comment by brockho** [comment]
As discussed today with @FMGS666, we close the issue.
