### ISSUE TITLE
Installing cocopp fails

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2245]
Following [this prescription](https://github.com/numbbo/coco/blob/development/DEVELOPMENT.md#working-with-the-postprocessing-code) fails under macOS like

```
(coco) 16:00:13 0 11 coco% python -m pip install code-postprocessing                                                                                                                                                    [cwd: ~/git/coco]
ERROR: Could not find a version that satisfies the requirement code-postprocessing (from versions: none)
ERROR: No matching distribution found for code-postprocessing
```
whereas
```
python -m pip install --editable code-postprocessing
```
works fine.

**Comment by olafmersmann** [comment]
Commit 1b88b91 updates the instructions. You apparently cannot install a "directory", instead you need to change into the directory and then install `.` :shrug:
