### ISSUE TITLE
search space transformations applied to best_parameter

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#225]
As of now search space transformations do not change `best_parameter`, while some of them do change the optimum of the problem. This is a problem e.g. for the computation of contributing hyper-volumes in the MO case.

**Comment by ttusar** [comment]
It might be sensible to handle the issue #103 at the same time.

**Comment by asmaatamna** [comment]
The proper way to change best_parameter is by applying the inverse transformation to the best parameter of the inner problem, which might be difficult. However, doing it for transform_vars_shift.c (best_parameter = best_parameter_inner_problem + shift) already solves the problem, as the other transformations don't affect the best parameter (at least as they are applied now).

**Comment by nikohansen** [comment]
In any case, a transformation should check on initialization, whether the `best_parameter` remains the same. If this is not the case and the new `best_parameter` cannot be computed, a warning should be issued.

**Comment by asmaatamna** [comment]
I modified transform_vars_shift.c so that it now updates the best parameter dcf7016d98b095c8f1a617ed10b02be170af4889. I still have to implement warnings in transformations that don't update the best parameter.

**Comment by asmaatamna** [comment]
For the schweffel function, I update the best parameter in transform_vars_x_hat.c which might not be the most elegant way to do it (it's the best/easiest solution I could find). But I believe this transformation was written initially only for the Schweffel function (52d0346b6ebae59f5460c7b58b1127dcdd3af3db).

**Comment by nikohansen** [comment]
Couldn't we at least check what the current best parameter value is and act depending on the outcome? We are good if it is zero, we make the change if it looks like Schwefels function, we deliver a warning otherwise?

**Comment by asmaatamna** [comment]
How to know if a problem is rotated? Which part of its id gives this information?

**Comment by nikohansen** [comment]
I don't think there is anything in the ID telling. Why do you need to know whether a problem is rotated? I thought what you need to know is where the optimal parameter is and whether the transformation is going to change it (in which case a warning must be given).

**Comment by asmaatamna** [comment]
Ok then I didn't understand your previous comment. Say we shift the variables of a problem (its best parameter is also shifted i.e. it's not zero anymore). Then we apply a rotation to the shifted problem. The best parameter of the inner problem is not zero yet it's ok.

**Comment by nikohansen** [comment]
The general comment: all object instances should be in a consistent state all the time. 

If we apply a rotation to a problem (i.e. we input an instance of a problem object to the rotation which returns a modified instance of a problem object) which has non-zero best parameter, then either we compute the new best parameter and store it accordingly (because a rotation changes the non-zero best parameter and the problem state would become inconsistent) or we output a warning and set the best parameter to `NULL`. For this we don't need to know more than the value of the best parameter of the input problem, i.e. the problem to which the rotation is applied. The rest should happen within the rotation which outputs the new problem instance.

**Comment by asmaatamna** [comment]
I just created a pull request where I updated the transformations files such that a warning is generated when the best parameter is different than zero.

**Comment by brockho** [comment]
Since the pull-request has been merged with the development branch, can this issue be closed even if the problem itself is not yet solved? For this, we have issue #814 as a follow-up, I guess.

**Comment by asmaatamna** [comment]
closing the issue

**Comment by asmaatamna** [comment]
I can only comment (I don't see the button "comment and close" anymore)

**Comment by brockho** [comment]
@asmaatamna: Do I interpret your latest comment correctly when I say that you are in favor of closing the issue?

**Comment by asmaatamna** [comment]
@brockho: yes
