### ISSUE TITLE
[Bug report] Cant install release 2.6.2 longintrepr.h missing

### ISSUE THREAD

**Issue by yedidyakfir** [numbbo/coco#2262]
I am trying to install the coco release of 2.6.2 however when i run the command `python do.py run-python` I get the following error

> /----------------------------< EXCEPTION MESSAGE >----------------------------\
|                                                                             |
| NOTE: Using precompiled C file to build interface.                          |
| C:\ProgramData\anaconda3\envs\egl\Lib\site-packages\setuptools\_distutils\c |
| md.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.     |
| !!                                                                          |
|                                                                             |
|         ******************************************************************* |
| *************                                                               |
|         Please avoid running ``setup.py`` directly.                         |
|         Instead, use pypa/build, pypa/installer or other                    |
|         standards-based tools.                                              |
|                                                                             |
|         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.ht |
| ml for details.                                                             |
|         ******************************************************************* |
| *************                                                               |
|                                                                             |
| !!                                                                          |
|   self.initialize_options()                                                 |
| C:\ProgramData\anaconda3\envs\egl\Lib\site-packages\setuptools\_distutils\c |
| md.py:66: EasyInstallDeprecationWarning: easy_install command is deprecated |
| .                                                                           |
| !!                                                                          |
|                                                                             |
|         ******************************************************************* |
| *************                                                               |
|         Please avoid running ``setup.py`` and ``easy_install``.             |
|         Instead, use pypa/build, pypa/installer or other                    |
|         standards-based tools.                                              |
|                                                                             |
|         See https://github.com/pypa/setuptools/issues/917 for details.      |
|         ******************************************************************* |
| *************                                                               |
|                                                                             |
| !!                                                                          |
|   self.initialize_options()                                                 |
| coco.c                                                                      |
| interface.c                                                                 |
| cython/interface.c(198): fatal error C1083: Cannot open include file: 'long |
| intrepr.h': No such file or directory                                       |
| error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Pro |
| fessional\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed  |
| with exit code 2                                                            |
\-----------------------------------------------------------------------------/

Please note that the same version worked the last time I tried it (about a year ago)

 - Operating system: Windows 10
 - COCO version: 2.6.2
 - Browser : chrome
 - python: Conda python 3.11.7

**Comment by nikohansen** [comment]
The likely cause of the problem is Cython in Python 3.11. Using Python 3.10 or lower should do the trick.

See https://medium.com/coinmonks/installing-brownie-with-the-new-python-3-11-version-89f67594b0be
