### ISSUE TITLE
How can I run experiments such that it takes less time for execution? 

### ISSUE THREAD

**Issue by Yash-Pisat** [numbbo/coco#2263]
I am experimenting with a budget of 50 and 100 on all the functions in bbob test suite. It takes a lot of time with different solvers to run these experiments. Is there a way to maybe speed up the experiments I mean someway run the experiments parallely to save some time?

**Comment by nikohansen** [comment]
Yes, if you use this script

https://github.com/numbbo/coco/blob/master/code-experiments/build/python/example_experiment2.py

you can run the full experiment by launching any number of desired batches, each with a different `batch=i/n` argument where `n` must be the same in all cases, see the docstring of the script.

**Comment by Yash-Pisat** [comment]
Great! I will try this out! Thankyou!
