### ISSUE TITLE
Running experiments on Bbob noisy test suite

### ISSUE THREAD

**Issue by Yash-Pisat** [numbbo/coco#2264]
I am running experiments on Bbob noisy test suite. It says the it still operates on the old coco versions. Do I need to execute all the codes on python 2.6? or older version.

Also is it possible to compare the noisy test suites results with the bbob test suite result?

**Comment by nikohansen** [comment]
There exists a version which should work under Python 3 too:

```python
import cma
import cma.bbobbenchmarks as bbob

help(bbob.F101)

class F101(_FSphere, BBOBGaussFunction)
 |  F101(iinstance=0, zerox=False, zerof=False, param=None, **kwargs)
 |  
 |  Sphere with moderate Gauss noise
[...]
```
I don't have a usage example to run the entire benchmark from there at my fingertips (you need to loop over the desired functions and over the desired instances for each function). I'd expect that the logged data work with the `cocopp` module.

I don't see though how it would make sense to compare results from these two different test suites.

**Comment by Yash-Pisat** [comment]
Instead of running the experiments again with the new version. I tried to to use the logged data with the cocopp module but i get the below error:

`(base) yash.pisat@MBP-YUP-C02ZTE5UMD6T bbob.v15.03 % python -m cocopp 'python/firstexperiment' 
Post-processing (1)
  Using 1 data set:
    python/firstexperiment

Post-processing (1)
  loading data...
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F110 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F106 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F107 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F111 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F101 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F102 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F103 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F108 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F104 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:2364: UserWarning: in DataSetList.processIndexFile: instances {1, 2, 3, 4, 5, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50} found several times. Read data for F112 in 2-D might be inconsistent
  warnings.warn(warn_message)
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:850: UserWarning: Caught an ill-finalized run in python/firstexperiment/bbobexp_f113.info for python/firstexperiment/data_f113/bbobexp_f113_DIM2.dat
  warnings.warn('Caught an ill-finalized run in %s for %s'
/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py:850: UserWarning: Caught an ill-finalized run in python/firstexperiment/bbobexp_f113.info for python/firstexperiment/data_f113/bbobexp-01_f113_DIM2.dat
  warnings.warn('Caught an ill-finalized run in %s for %s'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/__main__.py", line 30, in <module>
    res = rungeneric.main(args)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/rungeneric.py", line 408, in main
    dsld = rungeneric1.main(alg, outputdir, genopts + ["-o", outputdir, alg])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/rungeneric1.py", line 72, in main
    dsList = DataSetList(alg)
             ^^^^^^^^^^^^^^^^
  File "/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py", line 2231, in __init__
    self.processIndexFile(name, alg_name)
  File "/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py", line 2325, in processIndexFile
    self.append(ds)
  File "/Users/yash.pisat/anaconda3/lib/python3.11/site-packages/cocopp/pproc.py", line 2371, in append
    i.funvals = alignArrayData(VArrayMultiReader([i.funvals, o.funvals]))
                                                  ^^^^^^^^^
AttributeError: 'DataSet' object has no attribute 'funvals'
(base) yash.pisat@MBP-YUP-C02ZTE5UMD6T bbob.v15.03 % `

**Comment by Yash-Pisat** [comment]
@nikohansen  I tried to processe the log data using cocopp module and it worked. Thankyou for the quick response.
