### ISSUE TITLE
[Bug report] "The path is too long" error

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2268]
**Describe the bug**
With the latest version, the path to the downloaded data changed from `C:\Users\dimo\.cocopp\data-archives\numbbo.github.io\data-archive\data-archive` in my case to `C:\Users\dimo\AppData\Local\cocopp\cocopp\Cache\data-archives\numbbo.github.io\data-archive\data-archive\`. As a consequence, I get again the infamous
```
  File "C:\Users\dimo\anaconda3new\Lib\site-packages\cocopp\findfiles.py", line 120, in get_directory
    raise IOError(2, 'Some of the files cannot be extracted ' +
FileNotFoundError: [Errno 2] Some of the files cannot be extracted from "C:\Users\dimo\AppData\Local\cocopp\cocopp\Cache\data-archives\numbbo.github.io\data-archive\data-archive\bbob-biobj\2016\RM-MEDA_Auger_bbob-biobj.tgz". The path is too long.
```
error.

**Your System (please complete the following information when it seems relevant):**
 - Operating system: Windows 10 [I guess it only happens under Windows]
 - COCO version: 2.6.4 from the `development` branch
 - latest `pip`

**Comment by nikohansen** [comment]
It looks very likely that lines 97-99 in `cocopp.archiving` from https://github.com/numbbo/coco/commit/f36e3438cb733a5fcbf8c56b72db4adc44301c14 create this problem
```python
import platformdirs
cocopp_home = platformdirs.user_cache_dir("cocopp", ensure_exists=True)
default_archive_location = os.path.join(cocopp_home, 'data-archives')
```

**Comment by brockho** [comment]
Installing Anaconda in a directory high in the hierarchy (such as `C:\\conda\`) worked for now. In the long run, we should probably flatten the folder structure in the archive.

Or we can find a more general way to deal with the issue: https://www.delftstack.com/howto/python/disable-path-length-limit-python/ has a suggestion that a Windows user would have to do during the installation of python and https://stackoverflow.com/questions/36219317/pathname-too-long-to-open/36237176 gives an idea how we could do within COCO by using "extended-length paths" in Windows.

**Comment by nikohansen** [comment]
FTR, the above error is raised in the coco code by testing a string length, not by the OS in failing to open a file.

**Comment by ttusar** [comment]
So - should we increase the allowed string length?

**Comment by nikohansen** [comment]
I don't know why the error was raised in the first place. Nevertheless, I now change the error into a warning which seems to me more Pythonic.

**Comment by nikohansen** [comment]
I also shortened the require path length, see https://github.com/numbbo/coco-postprocess/issues/29#issuecomment-2510347059

**Comment by brockho** [comment]
Thanks, @nikohansen, for the latest commit. Since then, I have seen no problems with too long paths: I am currently re-doing the plots for the ppdata archive and since this morning I had no problem for any bbob data set from 2009--2017. I think, we can close the issue.

**Comment by nikohansen** [comment]
The "fix" is more like a band-aid than a final fix, but we have [this issue](https://github.com/numbbo/coco-postprocess/issues/29) to follow up.
