### ISSUE TITLE
Missing data file for noisy regression tests

### ISSUE THREAD

**Issue by olafmersmann** [numbbo/coco#2272]
We are missing the file `bbob_noisy_regression_data_10.json` for the noisy regession tests.

**Comment by FMGS666** [comment]
Hello, 
I guess you are talking about the data  from the legacy code right?
The regression data for the new suite is already in the `numbbo/regression-test` repository, both 2 and 10.
I haven't uploaded the file containing the data for the regression test against the legacy code (basically the one needed to run [this script](https://github.com/numbbo/coco/blob/development/code-experiments/test/regression-test/bbob_noisy_regression_test/bbob_noisy_regression_test.py)), as it is pretty big (around 380 MB). 
I have a script for creating such data from the legacy code [here](https://github.com/FMGS666/bbob-legacy-code/blob/master/python/generate_regression_test_data.py). 
If you want I can upload the data file to `coco` but to be honest it didn't seem optimal to me to do so, considering the size of the file.
Let me know how you prefer to handle the situation

**Comment by brockho** [comment]
I guess this can be closed. We have the `bbob_noisy_regression_data_10` file in the `regression-tests` repository and we indeed do not need the file, resulting from the experiment of Random Search, because we have the script to create them via the above link.

**Comment by brockho** [comment]
We do have to consider [#2305](https://github.com/numbbo/coco/issues/2305#issuecomment-2191763351) though, i.e. turning off the standard regression tests for `bbob-noisy` (because they are actually non-reproducible) but instead write independent tests for the noiseless and the noisy part.
