### ISSUE TITLE
[Feature request] Smoother parallelisation of experiments (needed for RL and recommendations)

### ISSUE THREAD

**Issue by CIGbalance** [numbbo/coco#2276]
This is based on a conversation I had with @olafmersmann in Leiden last week and I was tasked with writing an issue. Olaf, please correct me if I'm misrepresenting.

Currently, it is not possible to have two instances of the same function at the same time. You can parallelise experiments by running them in different processes and skipping some functions (the batches in the example). However:
* If you wanted to run RL algorithms, they usually expect to have a vectorised environment (i.e. multiple independent instances of `problem`) to speed up the learning. I don't think this is currently possible
* For recommendations it would also be nice to have a second instance of the problem to track recommendations at runtime. There is a workaround where you store everything and postprocess later, though.

A related feature is being able to grab a specific function instance without having to iterate through the whole suite, but Olaf said he is already working on that.

**Comment by nikohansen** [comment]
> A related feature is being able to grab a specific function instance without having to iterate through the whole suite, but Olaf said he is already working on that.

Like this?
```python
import cocoex

suite = cocoex.Suite('bbob', '', '')
fun = suite.get_problem_by_function_dimension_instance(1, 10, 2)
fun.id
```
```
'bbob_f001_i02_d10'
```

**Comment by nikohansen** [comment]
> Currently, it is not possible to have two instances of the same function at the same time.

Maybe I misunderstand the request, but it seems possible to me:

```python
import cocoex

suite = cocoex.Suite('bbob', '', '')
fun1 = suite.get_problem_by_function_dimension_instance(1, 10, 2)
fun2 = suite.get_problem_by_function_dimension_instance(1, 10, 2)
fun1 == fun2, fun1.id, fun2.id, 
```
```
(False, 'bbob_f001_i02_d10', 'bbob_f001_i02_d10')
```
If we wrap these functions with an [`Observer`](https://numbbo.github.io/gforge/apidocs-cocoex/cocoex.Observer.html), it's probably a good idea to make them two instances with different output locations too.

**Comment by CIGbalance** [comment]
Huh, maybe my information was outdated then. This looks like it would solve my current issue at least. I'm not sure if Olaf was talking about something else or not, but I can at least try this out for my setup. Thanks :) 

I think we can close for now?

**Comment by nikohansen** [comment]
> I'm not sure if Olaf was talking about something else or not

Maybe it was related to getting a function instance in a dimension that is not available in the suite.
