### ISSUE TITLE
Understand sharp ridge function

### ISSUE THREAD

**Issue by yedidyakfir** [numbbo/coco#2277]
Hi, I am using the Coco dataset for my research. I am trying to reverse-engineer some of the functions. 
I went over the c code for the sharp ridge function. 
It seems the function equation is `sqrt(sum(x_i ** 2)) + sum(x_i ** 2)`, but I cant find out the rotation and other manipulation you do for each instance of the function.
Can you help me with that?

Thanks

**Comment by FMGS666** [comment]
Hello, 

the transformations are done in the `f_sharp_ridge_bbob_problem_allocate` function. 
If you want to find where these transformations are done you need to look at the `f_sharp_ridge_bbob_problem_allocate` function in the [ f_sharp_ridge.c ](https://github.com/numbbo/coco/blob/master/code-experiments/src/f_sharp_ridge.c)file. You can see that all the transformations of the instance of the function are done in lines 82-106.


In general, the code of each test function follows pretty much the following structure:

`f_<function-name>_raw` which  Implements the  raw and unaltered function ($f:\Omega \rightarrow \mathbb{R}$ WITHOUT any random transformation) without connections to any COCO structures. It takes as input the decision vector $x\in\Omega$ and simply returns the scalar value $f(x)$

`f_<function-name>_evaluate` Which evaluates the solution on a given instance of `coco_problem_t` (passed as first input to the function) by wrapping around the `f_<function-name>_raw`  function

`f_<function-name>_bbob_problem_allocate` which handles the actual allocation of the `coco_problem_t` instance and also computes all the random transformations.

I hope this could help

**Comment by yedidyakfir** [comment]
> the instance of the function are done

Can you explain a bit more? 
I see there is a calculation of 2 rotation matrices there, but where do we apply them to the data? 
Or make any use of them?
In other words, how do this lines affect the evaluate method?

**Comment by brockho** [comment]
FYI, the mathematical definitions of the bbob functions can be found here: https://numbbo.github.io/gforge/downloads/download16.00/bbobdocfunctions.pdf

**Comment by olafmersmann** [comment]
Can this issue be closed, or are there open questions left about the function definition?
