### ISSUE TITLE
Dimesion on a custom function in new test suite

### ISSUE THREAD

**Issue by Yash-Pisat** [numbbo/coco#2293]
I am not sure, If I am asking the right question but I am stuck at this point.

I am creating an input function with 11 inputs, Is it possible that instead of having any other dimension like 2,3,5, 10, I can just proceed with the 11th Dimension in the custom function? 

Also since its has 11 inputs, I want to include its derivatives in the custom function. Is it possible to include partial derivatives?

Thankyou in advance.

**Comment by nikohansen** [comment]
I think we would need to have more context to understand your question and/or links to related issues this is referring to.

**Comment by Yash-Pisat** [comment]
For example: 

If I define a new function which has 12 variables ranging from x1, x2 .... to x12. In this case, I want this function to have only 12 dimensions and not 2,3,5,10. 

Is this implementation possible? 

This is my function:
static double f_func_raw(const double *x, const size_t number_of_variables) {
    assert(number_of_variables >= 10);
    double x1 = x[0], x2 = x[1], x3 = x[2], x4 = x[3], x5 = x[4],
           x6 = x[5], x7 = x[6], x8 = x[7], x9 = x[8], x10 = x[9];

    double y = (1000 +
         -0.0001*pow(x1, 3) + -0.0001*pow(x1, 2)*x3 + -0.0003*pow(x1, 2)*x9 + -0.0000*pow(x1, 2)*x10 +
         -0.0030*x1*x2*x9 + -0.0001*x1*x2*x10 + 0.0006*x1*x3*x9 + -0.0002*x1*x3*x10 +
         -0.0002*x1*x4*x10 + -0.0000*x1*x6*x10 + 0.0003*x1*x7*x10 + 0.0073*x1*x8*x9 +
         -0.0005*x1*x8*x10 ;

    return y;
}

And Is it possible to include the derivative of this equation?

**Comment by ttusar** [comment]
Sure, you can have a function with 12 dimensions. However, you need to make sure you use the same number of dimensions in your allocate function. You can also create a function that is the derivative of this one. I'm not sure what you mean by "including" it though ...

P.S. Please surround your C code snippets with a line containing only \````C (at the beginning) and another with only \```` at the end. In this way, the snippets is formatted nicely in the issue.

**Comment by olafmersmann** [comment]
Expanding on your question regarding the gradient. The `coco_problem_t` struct has a member `evaluate_gradient` which, if defined, evaluates the gradient of the function.

Take a look [here](https://github.com/numbbo/coco/blob/ffad392a7ceda07e124e6f242f3c6c95cb588886/code-experiments/src/f_bent_cigar.c#L67) to see how the gradient is defined and "wired into" the `coco_problem_t`for the bent cigar function.

**Comment by Yash-Pisat** [comment]
@ttusar @olafmersmann 

I had already referred to the existing functions but I was a bit confused. Since there are 10 variables, I was not sure how to calculate the gradient. So I am attaching the code snippet below:  

```
/* Calculates the value of the function polynomial equation */
static double f_func_raw(const double *x, const size_t number_of_variables) {
    assert(number_of_variables >= 10);
    double x1 = x[0], x2 = x[1], x3 = x[2], x4 = x[3], x5 = x[4],
           x6 = x[5], x7 = x[6], x8 = x[7], x9 = x[8], x10 = x[9];

    double y = (25.5286 +
         -0.0001*pow(x1, 3) + -0.0001*pow(x1, 2)*x3 + -0.0003*pow(x1, 2)*x9 + -0.0000*pow(x1, 2)*x10 +
         -0.0030*x1*x2*x9 + -0.0001*x1*x2*x10 + 0.0006*x1*x3*x9 + -0.0002*x1*x3*x10 +
         -0.0002*x1*x4*x10 + -0.0000*x1*x6*x10 + 0.0003*x1*x7*x10 + 0.0073*x1*x8*x9 +
         -0.0005*x1*x8*x10 + -0.0013*x1*pow(x9, 2) + 0.0000*x1*x9*x10 + -0.0001*x1*pow(x10, 2) +
         -0.0001*pow(x2, 2)*x10 + -0.0001*x2*x3*x10 + -0.0003*x2*x4*x10 + 0.0009*x2*x5*x10 +
         0.0009*x2*x6*x10 + 0.0010*x2*x8*x10 + -0.0000*x2*x9*x10 + -0.0001*pow(x2*x10, 2) +
         -0.0001*pow(x3, 2)*x10 + 0.0000*x3*x4*x10 + -0.0001*x3*x5*x10 + -0.0004*x3*x6*x10 +
         -0.0003*x3*x8*x10 + -0.0002*x3*x9*x10 + -0.0001*pow(x3*x10, 2) + 0.0005*pow(x4, 2)*x10 +
         0.0005*x4*x6*x10 + 0.0004*x4*x8*x10 + 0.0018*pow(x4*x9, 2) + -0.0005*x4*x9*x10 +
         -0.0001*pow(x4*x10, 2) + 0.0004*pow(x5, 2)*x10 + -0.0007*x5*x8*x10 + 0.0016*x5*x9*x10 +
         -0.0002*pow(x5*x10, 2) + 0.0007*x6*x9*x10 + -0.0001*pow(x6*x10, 2) + -0.0016*x7*x9*x10 +
         -0.0001*pow(x7*x10, 2) + 0.0013*x8*x9*x10 + -0.0001*pow(x8*x10, 2) + 0.0019*pow(x9, 3) +
         -0.0003*pow(x9, 2)*x10 + -0.0001*x9*pow(x10, 2) + -0.0000*pow(x10, 3));
 
    return y;
}

static void f_function_evaluate_gradient(coco_problem_t *problem, const double *x, double *y) {
    assert(problem->number_of_variables >= 10);

    double x1 = x[0], x2 = x[1], x3 = x[2], x4 = x[3], x5 = x[4],
           x6 = x[5], x7 = x[6], x8 = x[7], x9 = x[8], x10 = x[9];

    // Partial derivatives computed analytically
    y[0] = -0.0003 * pow(x1, 2) - 0.0002 * x1 * x3 - 0.0006 * x1 * x9 - 0.0003 * x2 * x9 - 0.0001 * x2 * x10
         + 0.0006 * x3 * x9 - 0.0002 * x3 * x10 - 0.0002 * x4 * x10 + 0.0003 * x7 * x10 + 0.0073 * x8 * x9
         - 0.0005 * x8 * x10 - 0.0013 * pow(x9, 2) - 0.0001 * pow(x10, 2);
    y[1] = -0.0030 * x1 * x9 - 0.0001 * x1 * x10 - 0.0001 * pow(x2, 2) - 0.0001 * x2 * x3 - 0.0003 * x2 * x4
         + 0.0009 * x2 * x5 + 0.0009 * x2 * x6 + 0.0010 * x2 * x8 - 0.0001 * x2 * x9;
    y[2] = -0.0001 * pow(x1, 2) + 0.0006 * x1 * x9 - 0.0002 * x1 * x10 - 0.0001 * x2 * x10
         - 0.0001 * pow(x3, 2) + 0.0000 * x3 * x4 - 0.0001 * x3 * x5 - 0.0004 * x3 * x6
         - 0.0003 * x3 * x8 - 0.0002 * x3 * x9 - 0.0001 * pow(x3, 2);
    y[3] = 0.0000 * x1 * x10 - 0.0003 * x2 * x10 + 0.0000 * x3 * x10 + 0.0005 * pow(x4, 2) + 0.0005 * x4 * x6
         + 0.0004 * x4 * x8 + 0.0018 * pow(x4, 2) - 0.0005 * x4 * x9 - 0.0001 * pow(x4, 2);
    y[4] = 0.0009 * x2 * x10 + 0.0000 * x3 * x10 + 0.0004 * pow(x5, 2) - 0.0007 * x5 * x8
         + 0.0016 * x5 * x9 - 0.0002 * pow(x5, 2);
    y[5] = -0.0000 * x1 * x10 + 0.0009 * x2 * x10 - 0.0004 * x3 * x10 + 0.0005 * x4 * x10 + 0.0004 * pow(x5, 2)
         - 0.0007 * x5 * x8 + 0.0016 * x5 * x9 - 0.0002 * pow(x5, 2);
    y[6] = 0.0003 * x1 * x10 + 0.0009 * x2 * x10 - 0.0004 * x3 * x10 + 0.0005 * x4 * x10 + 0.0004 * pow(x5, 2)
         - 0.0007 * x5 * x8 + 0.0016 * x5 * x9 - 0.0002 * pow(x5, 2);
    y[7] = 0.0073 * x1 * x9 - 0.0005 * x1 * x10 + 0.0010 * x2 * x10 - 0.0003 * x3 * x10 + 0.0005 * x4 * x10
         - 0.0007 * x5 * x10 + 0.0016 * x5 * x10 + 0.0013 * x8 * x9 - 0.0001 * pow(x8, 2);
    y[8] = -0.0006 * pow(x1, 2) + 0.0073 * x1 * x8 - 0.0013 * x1 * x9 + 0.0000 * pow(x9, 3) - 0.0001 * x10
         + 0.0005 * pow(x10, 2) - 0.0002 * pow(x9, 2);
    y[9] = -0.0000 * pow(x1, 2) - 0.0001 * x1 * x10 - 0.0001 * pow(x2, 2) - 0.0003 * x2 * x3 - 0.0003 * x2 * x10
         + 0.0000 * pow(x10, 3) - 0.0000 * pow(x10, 2);
}

```

Is this way of calculating and storing the derivatives correct?

**Comment by olafmersmann** [comment]
> @ttusar @olafmersmann

*snip*

> Is this way of calculating and storing the derivatives correct?

I didn't check the math, but assumning the partial derivates are correct, that is the way you store/return the gradient. 👍

**Comment by Yash-Pisat** [comment]
Great! I just wanted to know if it is the correct way of storing the gradient. Thank you.
