### ISSUE TITLE
Postprocessing ignores instance repetitions

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2296]
Repetitions that come from the same folder/info-file trigger this warning

```
cocopp\pproc.py:2384: UserWarning: same DataSet found twice, skipping the second one from ['exdata\\debug-0002\\bbobexp_f1.info'] with instances [1, 2, 3, 4, 5, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]
  warnings.warn("same DataSet found twice,"
```

and are hence ignored, which, at this point in time, should be considered as a bug.

**Comment by nikohansen** [comment]
This should only happen if the _data_ are _actually_ the same (compared in the method `DataSet._data_differ`), not only the instances.

I am not sure what the right action should be in this case.

**Comment by ttusar** [comment]
It is the same data.

**Comment by nikohansen** [comment]
Should be more or less fixed by now?
