### ISSUE TITLE
Missing tests for the current development code

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#2299]
Currently, the C tests (unit tests, regression tests and integration tests) are not being run on the code on the development branch. In addition, there are no instructions to run the integration tests locally.

**Comment by olafmersmann** [comment]
The unit and integration tests are run in the `source-build` step of the `build` CI workflow.

Do we want explicit workflows to run these independent of the larger build workflow on every platform?

**Comment by olafmersmann** [comment]
Regression tests should use pre-calculated data from the `numboo/regression-tests` repository and be added to the CI runs.

**Comment by brockho** [comment]
Looks like this can be closed, right?

**Comment by olafmersmann** [comment]
Yes.
