### ISSUE TITLE
Document the new biobjective test suite

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#230]
It will be important to also document the problems of the new biobjective test suite similar to the old document of the single-objective BBOB functions.

**Comment by nikohansen** [comment]
Do we want/need sophisticated displays and which ones?

**Comment by brockho** [comment]
For the first release, we don't have the time for displays, I would say and which is why we will propose first a documentation without.

Later on, we should definitely have the displays mentioned in the todo on top of the current documentation:

* plots of the best known approximations of the Pareto set and the Pareto front
* potentially the outcomes of example algorithms
* plots (in objective space) of randomly sampled search points
* potentially function value distributions along cuts through the search space

With @ttusar's new code to read in the archive files, the first item should be relatively easy to do. Item two can follow after the workshop participants submitted their results and if I remember correctly, @dotran has produced already results for items three and four, so the python scripts must be available.

**Comment by brockho** [comment]
A first version of the `bbob-biobj` function documentation is now online at http://numbbo.github.io/coco-doc/bbob-biobj/functions/. Since there are still open TODOs for this issue, I keep it open but transfer it to another milestone.

**Comment by brockho** [comment]
Finally, the plots (for 5-D) are included in the online documentation at http://numbbo.github.io/coco-doc/bbob-biobj/functions/ such that the issue can be closed eventually.
