### ISSUE TITLE
Minor formatting issue in scaling figure caption

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2300]
The html looks like (highlight marking by me)

<img width="805" alt="Screenshot 2024-06-12 at 14 32 53" src="https://github.com/numbbo/coco/assets/7316439/582696c6-d8a1-4859-8e5a-1914218bb9c2">

The html code is `10^{&#8722;8}`.

**Comment by brockho** [comment]
This specific one is solved now.
