### ISSUE TITLE
Why does the ECDF plot starts from outside of the x and y axis

### ISSUE THREAD

**Issue by Yash-Pisat** [numbbo/coco#2304]
I have added a custom function and ran an experiments on the same function.

This is the plot that I get after running the experiment:
@
<img width="569" alt="Screenshot 2024-06-14 at 02 24 04" src="https://github.com/numbbo/coco/assets/111347181/7a735756-20b1-484a-8f16-3b11071d3c69">

Why is it so? is it something that I missed while defining the function?

Thanks in advance

**Comment by olafmersmann** [comment]
To me it looks like all progress is made in the first 10 function evaluations. Note that the x axis displays $\log_{10}(\text{f-evals} / \text{dimension})$. So a value of 0 on the x axis, given that your problem has 10 dimensions, corresponds to 10 evaluations of the objective function.

**Comment by brockho** [comment]
I agree with @olafmersmann. In addition, we see only three actual improvements (=3 steps). One possibility is to play around with the difficulty of the displayed problems in terms of the choice of the targets. It seems that the chosen targets are just too simple to achieve (or it is even that the problem definition does not allow for many intermediate targets, for example because the objective function itself has (large) discrete steps).

**Comment by Yash-Pisat** [comment]
@olafmersmann  Thank you for the explanation, I understand it now! 

@brockho  How do I define the targets? So the custom function that I have defined has 10 variables(dimensions) and I am using Bayesian Optimization as a solver and trying to optimize the function by getting it in a desired range. Is it possible to define targets in COCO?

**Comment by nikohansen** [comment]
Targets for the various plots are generally defined in `cocopp.genericsettings` or `cocopp.testbedsettings` (for example, `pprldmany_target_values` of the used suite class in `testbedsetting` may be what you are looking for). The recorded targets are defined by the observer/logger in the C code.

**Comment by brockho** [comment]
> Targets for the various plots are generally defined in `cocopp.genericsettings` or `cocopp.testbedsettings` (for example, `pprldmany_target_values` of the used suite class in `testbedsetting` may be what you are looking for). The recorded targets are defined by the observer/logger in the C code.

Agreed. In order to plot the ECDFs with smaller targets, though, you will have to make sure to set `problem->final_target_delta[0]` to a smaller value than the (default) $10^{-8}$.

**Comment by Yash-Pisat** [comment]
@nikohansen  @brockho 
What is the difference between between the listed variables :
```
ppfigdim_target_values=(10, 1, 1e-1, 1e-2, 1e-3, 1e-5, 1e-8),
pprldistr_target_values=(10., 1e-1, 1e-4, 1e-8),
pprldmany_target_values=10 ** np.arange(2, -8.2, -0.2)
```

So my target is a desired range of 7.5 - 9.5?

**Comment by nikohansen** [comment]
The above define the target precisions used in different figures. The first are the ERT vs dimension figures, the third are the runtime distribution figures. `f_opt` needs to be defined somewhere too, if it is zero the target values equal the precision values.

**Comment by Yash-Pisat** [comment]
'''
/* Allocates the problem with transformations */
static coco_problem_t *f_viscosity_problem_allocate(const size_t function,
                                                    const size_t dimension,
                                                    const size_t instance,
                                                    const long rseed,
                                                    const char *problem_id_template,
                                                    const char *problem_name_template) {
    double *xopt, fopt;
    coco_problem_t *problem = NULL;

    // Allocate and compute the optimal solution xopt based on the dimension and random seed
    xopt = coco_allocate_vector(dimension);
    bbob2009_compute_xopt(xopt, rseed, dimension);
    // Compute the optimal function value fopt based on the function ID and instance
    fopt = bbob2009_compute_fopt(function, instance);

    // Allocate the viscosity problem with the given dimension
    problem = f_viscosity_allocate(dimension);  // Corrected to pass only one parameter
    // Shift the variables of the problem by xopt
    problem = transform_vars_shift(problem, xopt, 0);

    // If the problem is part of a large-scale test suite, normalize the objective by dimension
    if (coco_strfind(problem_name_template, "BBOB large-scale suite") >= 0) {
        problem = transform_obj_norm_by_dim(problem);
    }
    // Shift the objective function by fopt
    problem = transform_obj_shift(problem, fopt);

    // Set the problem ID and name using the provided templates and problem characteristics
    coco_problem_set_id(problem, problem_id_template, function, instance, dimension);
    coco_problem_set_name(problem, problem_name_template, function, instance, dimension);

    // Free allocated memory for xopt after using it
    coco_free_memory(xopt);
    return problem;
}
'''

In the above code, Instead of doing calculating fopt = bbob2009_compute_fopt? Should I just define the desired range here? Will that work?

**Comment by brockho** [comment]
`fopt` in the above code is the optimal function value of the problem, you define with `transform_obj_shift`, assuming that the "raw" problem (before any transformation) has its optimum $`x^*`$ at $`f(x^*)=0`$.

**Comment by Yash-Pisat** [comment]
@brockho  Okay got it, I checked the 'transform_obj_shift' function and basically it is designed to handle a single value. 

So if I set fopt as 8.5, that would set the target of my function as 8.5. So when I run the optimization experiment with this function, ECDF will indicate 1 when the the value of this function is 8.5? Is that correct?

**Comment by nikohansen** [comment]
> There are many similar cases I could show, 

The likelihood that the global optimum is so close to -4 or +4 should be pretty small, it should be on most functions in the order $2D\times10^{-5}$. So, yes, I would be curious to learn about more cases, specifically the $x$-value of the optimum.

> but one example is in the 2016 set, for f16, D=2, instance=15, where my run stopped when it found the target to the required precision.
5239 0 +1.478454692e-09 -1.240400000e+02 -1.240400000e+02 -3.5796e+00 +4.2162e+00

`f16` has many global optima, inside and outside of the $[-4, 4]^D$ domain. The above data line does not look like an example of the described effect but looks like a global optimum outside of $[-4, 4]^D$.

> I mention this here because I have noticed that some researchers start their runs with a population drawn uniformly from points inside [-4,4]^D

Right, we have been doing this since we implemented the `bbob` testbed.

**Comment by brockho** [comment]
Hi,

You can also get an idea about how easy it is to reach certain targets when comparing Random Search in various domains. The corresponding data can be found in the postproccessing data archive here: https://numbbo.github.io/ppdata-archive/bbob/2019/index.html Algorithms with names starting `RS-a-bbob` are Random Search within $[-a,a]^n$, `RS-a-init` evaluate the origin as the first search point and then continue like `RS-a-bbob`.

We specifically have the data for `RS-5` and `RS-4` but also for many other values of `a`. If you look at the performance aggregated over all 24 `bbob` problems, among the tested values for `a`, `RS-6` performs best in the lowest dimensions while in higher dimensions, the important thing is whether the origin is evaluated or not. The reason for this is that the randomly chosen optimum is (in high dimension) closer to the origin than to any other point chosen uniformly at random (if the uniform sampling is symmetric with respect to the origin).

**Comment by nikohansen** [comment]
> `RS-6` performs best in the lowest dimensions

Strangely, `RS-10` has the best performance (only) in dimension 10 when the first evaluation is at all-zeros. The reason for these observations is that the linear function has a "large" globally optimal volume _outside_ of the "domain of interest" $[-5, 5]^D$.

It may be interesting to have a look at the global performance data of random search _except on `f5`_, which is then probably more "representative" for finding the best random search interval. FTR, the best random search interval is also not necessarily (or even not likely) the best distribution for the initial solution.

**Comment by LazyLysistrata** [comment]
@nikohansen
You might be correct that the global minimum for the wildly oscillating f16 is outside [-4,4]^D, but that's something you and for team to investigate.

As I said earlier, I don't believe that there are necessarily any errors in the benchmarks: my point is that it should be emphasized in the documentation that (for the 1e-8 constant) algorithms can stop if they find a local minimum outside
[-4,4]^D.

I haven't saved all the results where I found the behaviour I referred to earlier, but I've included some more examples from a few different runs using three variations of my own algorithms. All use the 2016 suite, but I'm happy to check suites for other years if you need them.

These two examples best illustrate what I mean...

For D=3, in Run1, the algorithm stopped inside [-4,4]^D, in Run2 it stopped outside.
Run1: f16, D=3, Instance=10.
3406 0 +3.297770945e-10 -7.982000000e+01 -7.982000000e+01 +1.8560e+00 +9.3876e-01 +1.9452e+00
Run2: f16, D=3, Instance=10.
1224 0 +2.004256316e-09 -7.982000000e+01 -7.982000000e+01 +4.0293e+00 -3.3371e+00 -4.8164e+00

For D=5, in Run1, the algorithm stopped outside [-4,4]^D, in Run3 it stopped inside.
Run1: f16, D=5, Instance=2.
4854 0 +8.213362435e-09 -3.552200000e+02 -3.552200000e+02 -4.5965e-01 -4.6387e+00 +1.8287e+00 -5.7002e-01 -1.7816e+00
Run3: f16, D=5, Instance=2.
5083 0 +1.890384738e-09 -3.552200000e+02 -3.552200000e+02 -8.6820e-01 -3.5775e-02 -8.6941e-01 -1.7142e+00 -3.1739e-01

Here are a few more examples if in case they are of any help.
Run1.
f16, D=3, Instance=1.
1503 0 +1.971343977e-09 +7.135000000e+01 +7.135000000e+01 -4.8078e+00 +4.6876e+00 -4.8596e+00
f16, D=3, Instance=3.
1158 0 +2.670219601e-11 +9.917000000e+01 +9.917000000e+01 +3.1090e+00 -4.7083e+00 +3.7623e+00
f16, D=3, Instance=11.
1002 0 +6.810978448e-10 +1.925800000e+02 +1.925800000e+02 +1.6561e+00 +4.6624e+00 -1.7631e+00

Run2.
f16, D=3, Instance=1.
3737 0 +1.099337510e-09 +7.135000000e+01 +7.135000000e+01 -4.8455e+00 +1.2302e+00 -3.3971e+00

f16, D=5, Instance=4.
8331 0 +6.936602404e-09 -5.179100000e+02 -5.179100000e+02 +2.2152e+00 +4.2716e+00 +8.1194e-01 -2.0882e+00 +1.2636e+00
f16, D=5, Instance=9.
1475 0 +7.019828274e-09 +3.513000001e+01 +3.513000001e+01 -4.4330e+00 -4.5626e+00 -1.1213e+00 +1.2377e+00 -2.3327e+00

f16, D=10, Instance=9.
28030 0 +3.847659968e-09 +3.513000000e+01 +3.513000000e+01 -4.2890e+00 -1.8540e+00 +2.0038e+00 -4.2225e-01 +1.1998e+00 -3.6747e+00 -3.2932e+00 +5.1332e-02 +2.1369e+00 -9.3504e-01
f16, D=10, Instance=10.
14097 0 +7.031928817e-09 -7.981999999e+01 -7.981999999e+01 +7.8676e-02 -5.6594e-01 -1.0558e+00 -1.6405e+00 +1.3652e+00 +2.5691e+00 -6.0379e-01 -4.3906e+00 +2.4045e+00 +2.7796e+00
f16, D=10, Instance=12.
55579 0 +9.154291547e-09 -2.684800000e+02 -2.684800000e+02 +1.6209e+00 -1.0193e+00 +1.5493e-01 +9.5534e-01 -3.7909e-01 +1.4577e+00 -2.1170e+00 -4.0606e+00 -2.4149e+00 -1.5853e+00

Run3.
f16, D=5, Instance=4.
24247 0 +4.158664524e-10 -5.179100000e+02 -5.179100000e+02 -3.5052e+00 -7.8630e-01 +2.0823e-01 -2.9243e+00 +1.3847e+00

**Comment by nikohansen** [comment]
Thanks for the data, they seem to be perfectly in line with my conception. As far as I can tell, they don't indicate that a solution found outside of $[-4, 4]^D$ triggers the final target from a global optimum within $[-4, 4]^D$. I am not suggesting that this cannot happen, I just suggest that it did not happen in the shown data.

> that's something you and for team to investigate.

Thanks for the suggestion, I don't quite agree though: you have been indicating that it makes a relevant difference that the "_extra 10^{-8} means that a run can terminate when it has found a solution outside of [-4,4]^D_", but you have failed to support the claim with data. So it is on you, _and only you,_ to scrutinize your methods for how to support your claim.

> As I said earlier, I don't believe that there are necessarily any errors in the benchmarks: my point is that it should be emphasized in the documentation that (for the 1e-8 constant) algorithms can stop if they find a local minimum outside
[-4,4]^D.

I don't think so. Algorithms which stop when they found a local minimum outside of $[-4, 4]^D$ may well hurt their performance when this local minimum is not a global minimum. Algorithms which "found a global minimum" can stop irrespectively of whether it is inside or outside of $[-4, 4]^D$, however there is no viable way to determine for an algorithm whether it found a global optimum other than checking whether the final target was hit.

To summarize this point, as far as I am aware, algorithms can stop without affecting the performance assessment _if and only if_ they find that (in Python) ``bool(problem.final_target_hit) is True``.  This is [described here](https://numbbo.github.io/coco-doc/experimental-setup/#initialization-and-input-to-the-algorithm) and reflected in the code examples [here (line 111)](https://github.com/numbbo/coco/blob/master/code-experiments/build/python/example/example_experiment_complete.py#L111) and [here (line 146)](https://github.com/numbbo/coco/blob/68baeb8c0ea54bfc15d310624cc42a5e668aabe5/code-experiments/build/python/example/example_experiment2.py#L146) and [here (line 123)](https://github.com/numbbo/coco/blob/68baeb8c0ea54bfc15d310624cc42a5e668aabe5/code-experiments/build/python/example/example_experiment_complete.py#L123).

I'd agree that it would not hurt to make this a little more explicit in other parts of the documentation or provide links to the above.

**Comment by LazyLysistrata** [comment]
@nikohansen
Sorry, but I am still not quite clear about some aspects.

I am not saying that COCO has terminated because it has falsely triggered a return code indicating that it has found the *global* minimum inside [-4,4]^D, when my solution is clearly outside, or very close to the boundary.

BTW, I am using the C version where the relevant lines are:
if ( coco_problem_final_target_hit(PROBLEM) ) {
  break;
}

If my solution has an f-value < fopt + 1e-8, no matter where it is within [-5,5]^D, I believe that COCO terminates correctly.
(I also agree that the last example I gave contains a value -4.0606 which is close to the boundary.)

However, the data I gave in the 2nd example shows that COCO accepted the result when the closest value to the boundary is 4.6387.
4854 0 +8.213362435e-09 -3.552200000e+02 -3.552200000e+02 -4.5965e-01 -4.6387e+00 +1.8287e+00 -5.7002e-01 -1.7816e+00

COCO accepted that solution because the f-value was fopt + 8.213362435e-09.
(It would not have accepted the solution if the tolerance was smaller, say 1e-10.)

Are you suggesting that users should also check that the *location* of their solution also lies within [-4,4]^D (for all functions except f5)?

**Comment by LazyLysistrata** [comment]
@nikohansen 
Further to my previous post...
I noticed that in your own results for lq-CMA-ES in the data archives, a result for f16, D=3 which also shows COCO terminated a run when it was quite distant the boundary, i.e. the closest point is -4.6928e+00.

lq-CMA-ES_Hansen/102/fmin2_of_cma.evolution_strategy_200000D_on_bbob_batch020of30/data_f16/bbobexp_f16_DIM3_i71.tdat
1622 0 +7.541700597e-11 +6.626000000e+01 +6.626000000e+01 +1.1351e+00 +3.3636e+00 -4.6928e+00

Please don't think that I am annoyed or critical of COCO over this issue: I am an ardent supporter and fan.
I am just trying to understand if I need to change anything about my approach and algorithms.

**Comment by nikohansen** [comment]
> (It would not have accepted the solution if the tolerance was smaller, say 1e-10.)

Right. If our tolerance were `1e-11` we would overwhelmingly accept solutions we would not have accepted when our tolerance were, say, `1e-14`.

> Are you suggesting that users should also check that the location of their solution also lies within [-4,4]^D (for all functions except f5)?

No. The algorithm is neither allowed to use the function identifier as input, nor the information about the location of the global optima (or, strictly speaking, even their distribution), which would both be needed to make such decision correctly.

For the performance assessment it doesn't matter which global optimum the algorithm has approximated close enough.

**Comment by nikohansen** [comment]
You write

> COCO accepted the result when the closest value to the boundary is 4.6387.

and

>  COCO terminated a run when it was quite distant the boundary, i.e. the closest point is -4.6928e+00.

First, I just want to make sure: $-4$ or $4$ are _not_ boundary values. 

Second, you seem to think that the above observations are remarkable. I don't see why. [The documentation](https://numbbo.github.io/gforge/downloads/download16.00/bbobdocfunctions.pdf#page=2) says

> All functions have their global optimum in $[−5, 5]^D$. The majority of functions has the global optimum in $[−4, 4]^D$ and for many of them $x_\text{opt}$ is drawn uniformly from this compact.

Let me say again that this information about the functions is for researchers and for interpreting results but, strictly speaking, the algorithm is not permitted to use this information.

The documentation does not say, as you wrote above

> the optimum is usually inside [-4,4]^D for functions except f5

which seem however, depending on the reading, not necessarily wrong (usually != always) and in line with all of your observations too.

The [documentation for f16](https://numbbo.github.io/gforge/downloads/download16.00/bbobdocfunctions.pdf#page=80) says

> Highly rugged and moderately repetitive landscape, where the global optimum is not unique

The observations we have been discussing back and forth and the actual documentation are, AFAICS, perfectly in sync.

**Comment by LazyLysistrata** [comment]
@nikohansen
Thanks for the clarifications. You've explained it (appropriately!) like I'm a 70 year old. :)

My confusion arose because of the difference between finding the true global minimum and any solution whose f-value is within 1e-8 of the f-value of the global minimum because those local minima (which might also be global minima) could be relatively far from the location of the true global minimum.

**Comment by nikohansen** [comment]
> the difference between finding the true global minimum and any solution whose f-value is within 1e-8 of the f-value of the global minimum

I don't know that there is any difference between these two with the `bbob` function suite, if we come to  define the first properly:
- I don't know the difference between a "global optimum" and a "true global optimum". The phrase "_the_ true global optimum" is ill-posed if there is more than one global optimum.
- We need to properly define what "_finding_ the true global minimum" means, because we generally can't "find" an optimum in continuous domain, we can only approximate it. This is why we define an approximation precision.

**Comment by LazyLysistrata** [comment]
Thanks for taking the time to explain.
The word "generally" provided the necessary key to understanding for me. :)
