### ISSUE TITLE
[Bug report] `cocopp` is incomaptible with numpy >= 2.0.0

### ISSUE THREAD

**Issue by olafmersmann** [numbbo/coco#2306]
`cocopp` uses some deprecated NumPy functions and constants (`np.Inf` f. e.). 
We should clean that up before the next release.

**Comment by olafmersmann** [comment]
Temporarily force numpy < 2.0.0 with commit 82d1575c68da737c7394009bbc6e4074bd168cdf.

**Comment by nikohansen** [comment]
```sh
ruff check cocopp --select NPY201  
```
does not complain anymore.
