### ISSUE TITLE
coco-experiment versus cocopp

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2311]
Reconsidering the question: would it be a good idea to split `code-postprocessing` into a different repository?

**Comment by olafmersmann** [comment]
+1

I see no reason to keep them in the same repository. Especially since there is no reason to release `cocopp` and `cocoex` in lock step.

**Comment by olafmersmann** [comment]
I also moved coco-experiment to a seperate repository. If we also move the preprocessing stuff to a new repository, we could mark this repository as archived and keep it for historical purposes. I think the big monorepo hasn't really worked out for us and we usually don't need to synchronize minor releases of the different parts of COCO.

**Comment by nikohansen** [comment]
Sounds good, we polish the readme to point to the right places and remove everything else in the repo such that the readme is visible without scrolling down?
