### ISSUE TITLE
 [DATA SUBMISSION] DE-NO-r1-B, DE-j-r2-B, and DE-CoBi-r1-L on the bbob-mixint suite

### ISSUE THREAD

**Issue by ryojitanabe** [numbbo/coco#2314]
Dear Organizers of COCO,

I would like to submit the benchmarking results of three optimizers (DE-NO-r1-B, DE-j-r2-B, and DE-CoBi-r1-L) on the bbob-mixint suite. Could you please upload them to the COCO data archive?

Best regards,
Ryoji

#### Reference
Ryoji Tanabe: Benchmarking Parameter Control Methods in Differential Evolution for Mixed-Integer Black-Box Optimization, Proc. ACM Genetic and Evolutionary Computation Conference (GECCO2024), [arXiv](https://arxiv.org/abs/2404.03303)

#### Description of the Algorithm(s)

The above paper benchmarked parameter control methods for scale factor and crossover rate in differential evolution (DE) on the bbob-mixint suite. The results show that using a suitable parameter control method significantly improves the performance of DE on the bbob-mixint suite.
I benchmarked 160 DE configurations, where I used 10 parameter control methods, 8 mutation strategies, and 2 repair methods. However, uploading the benchmarking data of the 160 optimizers to the COCO data archive is not possible. For this reason, I would like submit only the benchmarking results of the following three optimizers. Here, in the notation "DE-X-Y-Z", X represents the type of parameter control method, Y represents the type of mutation strategy, and Z represents the type of repair method.

- **DE-NO-r1-B**: DE with no parameter control method, the rand/1 strategy, and Baldwinian repair method. This is the most classical DE algorithm.
- **DE-j-r2-B**: DE with the parameter control method in [jDE](https://ieeexplore.ieee.org/document/4016057), the rand/2 strategy, and Baldwinian repair method. This DE performs the best out of the 160 DE configurations for 160 dimensions.
- **DE-CoBi-r1-L**: DE with the parameter control method in [CoBiDE](https://www.sciencedirect.com/science/article/pii/S1568494614000581), the rand/1 strategy, and Lamarckian repair method. This DE performs the best out of the 160 DE configurations for 5 dimensions.

Both DE-j-r2-B and DE-CoBi-r1-L show better performance than CMA-ES-pycma, CMA-ESwM, and cmaIH1e-1 for high dimensions and larger budgets of function evaluations.

#### Link to Data
https://drive.google.com/file/d/1PzABfbLLO2lcYaCU02DXdrqRROYs2MYb/view?usp=sharing

#### Optional: Source Code of Experiment
https://github.com/ryojitanabe/de_bbobmixint

**Comment by brockho** [comment]
Dear @ryojitanabe,

Many thanks for submitting your GECCO-2024 data files to us. All files are clean, postprocess without problems and the documentation is clear as well (including the link to the paper and the source code - ideal!). I put them now online on our current [data archive page](https://numbbo.github.io/data-archive/bbob-mixint/) and they are also available already via the postprocessing (after running `cocopp.archives.update_all()`).

**Comment by ryojitanabe** [comment]
Thank you very much for the upload!

**Comment by brockho** [comment]
The files are now in the COCO data archive for more than four months already, such that this issue can be closed.
