### ISSUE TITLE
Cant install coco package

### ISSUE THREAD

**Issue by yedidyakfir** [numbbo/coco#2318]
Hi, I am trying to install the coco package, following the guide in the readme.md file.
I run `python do.py run-python` command, however I get the following error

> ERROR: return value=1
> Traceback (most recent call last):
>   File "C:\Users\aim\Desktop\work\new\coco\code-experiments\build\python\example_experiment.py", line 46, in <module>
>     import cocoex
> ModuleNotFoundError: No module named 'cocoex'
> 

**Your System (please complete the following information when it seems relevant):**
 - I am using windows 10
 - I tried for both tags 2.6.2 and 2.6.3 and they return the same error
 - I tried to downgrade setuptools to version 65 (Like I saw in previous issues) but it did not change the outcome

**Comment by nikohansen** [comment]
By now, there is a simpler way to install [`cocoex`](https://pypi.org/project/coco-experiment), namely by
```
pip install coco-experiment
```

Remark also that the `example_experiment.py` is deprecated (as mentioned in the docstring). Rather use

https://github.com/numbbo/coco/blob/master/code-experiments/build/python/example/example_experiment_simple.py

or 

https://github.com/numbbo/coco/blob/master/code-experiments/build/python/example/example_experiment_complete.py

**Comment by yedidyakfir** [comment]
And how would I go about install previous versions (specifically version v2.6.2)

**Comment by nikohansen** [comment]
To all I know 

```
python do.py run-python
```

The error from the OP is probably due to running `example_experiment.py` with a different python installation than `do.py`?

**Comment by nikohansen** [comment]
Can this be closed?
