### ISSUE TITLE
[Bug report] data-archive does not deploy

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2320]
**Describe the bug**
While trying to solve #2319, the triggered deployment of our (old) data archive page did not work: https://github.com/numbbo/data-archive/actions/runs/9966245285/job/27538064265#step:5:19

@olafmersmann: could you have a look - maybe you know a quick fix? Many thanks in advance.

**Your System (please complete the following information when it seems relevant):**
 - unimportant (because the change was made via the web-interface of github and the problem comes from the CI)

**Comment by olafmersmann** [comment]
Fixed by upgrading all actions in the workflow, adding the `vendor/` directory to the excludes and setting the `repository` variable in the config.
