### ISSUE TITLE
sbox-cost data archive 2nd data set 404

### ISSUE THREAD

**Issue by LazyLysistrata** [numbbo/coco#2321]
On the page for sbox-cost data archive, the 1st set has been fixed.
https://numbbo.github.io/data-archive/sbox-cost/

The 2nd one still gives a 404.
https://numbbo.github.io/data-archive/data-archive/sbox-cost/2023/cma-bt-sboxcost_Brockhoff.tgz

**Comment by brockho** [comment]
Sorry for the inconvenience, it should work now.
