### ISSUE TITLE
Running experiments on sbox-cost suite

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2322]
```python
import cocoex
import cocopp

print(print(cocopp.archives.all('cma-b')))
print(cocoex.known_suite_names)
```
```
['bbob/2023/cma-bp-bbob_Brockhoff.tgz', 'bbob/2023/cma-bt-bbob_Brockhoff.tgz', 'sbox-cost/2023/cma-bp-sboxcost-Brockhoff.tgz', 'sbox-cost/2023/cma-bt-sboxcost-Brockhoff.tgz']
['bbob', 'bbob-biobj', 'bbob-biobj-ext', 'bbob-constrained', 'bbob-largescale', 'bbob-mixint', 'bbob-biobj-mixint', 'bbob-noisy']
```

I would have expected to see `sbox-cost` in the latter list of known suites too, because it is in the former and I have seen runtime distribution which display this name as the benchmarked suite.

**Comment by brockho** [comment]
Agreed. I will change that next week during ISMP.

**Comment by nikohansen** [comment]
For the record
```python
import cocoex
suite = cocoex.Suite('sbox-cost', '', '')
```
crashes the kernel, that is, the suite is not implemented/compiled?

**Comment by brockho** [comment]
Duplicate of #2325 which shows more information than here - hence, I am closing this one.
