### ISSUE TITLE
[Bug report] can't install coco-experiment

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2323]
Under Linux
```sh
~$ python -c 'import sys; print(sys.version)'
3.7.7 (default, Mar 13 2020, 13:32:22) 
[GCC 7.3.0]

~python -m pip install coco-experiment
ERROR: Could not find a version that satisfies the requirement coco-experiment (from versions: none)
ERROR: No matching distribution found for coco-experiment
```

**Comment by nikohansen** [comment]
I suspect that this
```
- python >=3.10.8
```
requirement in `env.yaml` is the reason?

Could we please(!) not require an uptodate Python distribution for running experiments on worker machines which are notoriously difficult to have maintained uptodate?

**Comment by nikohansen** [comment]
Thanks, I was able to revive conda and install python `3.12`, hence I currently have no _specific_ urgency for this anymore.

**Comment by olafmersmann** [comment]
👍 Can I close the bug with wontfix?

**Comment by nikohansen** [comment]
OK
