### ISSUE TITLE
[Bug report] compatibility of cocoex with numpy 2.0

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#2324]
**Describe the bug**
`cocoex` bailes with `numpy` 2.0, due to [this code](https://github.com/numbbo/coco/commit/12c2e374cbf317f55eb67c477c7881fbec798701) which is now fixed. I didn't check yet whether it works now.

We should have a test checking that the package is compatible with `numpy` 2.0?

**Comment by nikohansen** [comment]
Update: my local installation of `cocoex` from the `development` branch works with `numpy` 2.0.

**Comment by olafmersmann** [comment]
I just released a new version (2.6.99rc3) to PyPI so the pip-installable version should also be compatible with numpy 2.0.
