### ISSUE TITLE
conda update not working for me with env.yaml

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#2326]
When running `conda update -f env.yaml` as suggested in [DEVELOPMENT.md](https://github.com/numbbo/coco/blob/master/DEVELOPMENT.md), I get the following output (under CentOS Linux 7):

```


WARNING: The --force flag will be removed in a future conda release.
         See 'conda update --help' for details about the --force-reinstall
         and --clobber flags.



PackageNotInstalledError: Package is not installed in prefix.
  prefix: /home/labcmap/dimo.brockhoff/anaconda3
  package name: env.yaml


```

Not sure if this is problematic in any way. The `conda` version is 23.7.4, `python` is version 3.11.5.

**Comment by nikohansen** [comment]
I suspect you must use `conda update --file env.yaml` instead of `-f`.

**Comment by brockho** [comment]
> I suspect you must use `conda update --file env.yaml` instead of `-f`.

Thanks for the suggestion, but with `--file` instead of `f`, I get the following:

```
CondaValueError: could not parse 'name: coco' in: env.yaml
```

**Comment by nikohansen** [comment]
Apparently it has to read `conda env update --file env.yaml` or `conda env update --file env.yaml --prune` to also remove packages that have been removed from the yaml file.

**Comment by brockho** [comment]
The last suggestion works :-) It was actually already correctly written in `DEVELOPMENT.md` a bit above where I was reading. I corrected the documentation further down in `DEVELOPMENT.md` accordingly in the `development` branch. Thanks @nikohansen!
