### ISSUE TITLE
Python script for updating reference set and hypervolume reference values

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#235]
For the bi-objective testbed to work with the best possible reference set, we need a python script which takes two algorithm data sets (of which typically one will be the reference set itself) and creates a new reference set together with an updated best_values_hyp.txt file. Both input data sets shall comply with the format, the biobjective logger is writing (i.e. it shall check in all .info files to find the corresponding archive files and read them for all instances and the merge shall be done instance-wise of course).

Notes:
1) Reading in data sets of the biobjective BBOB format has to be implemented anyway in the postprocessing.
2) For efficiency reasons, the C code for the online archiving and hypervolume calculations shall be used for merging the data files.

**Comment by brockho** [comment]
Moved to release v0.7 because it is not crucial for v0.5 because we have already quite good reference sets for the first five instances. Work should be rather spend on documentation and making the basic postprocessing work.

**Comment by ttusar** [comment]
Done.
