### ISSUE TITLE
Single-Run Plot Function

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#24]
```
implement a single-run plot function: input is, for the time being, an .tdat 
file, the first run found

- read in data (just as an array)
- plot data
- design a single-run class? 


```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 4:45

**Comment by nikohansen** [comment]
We do have single function ECDFs now. 

Why not plotting all data from the `evals` attribute?
