### ISSUE TITLE
Add multiple observers to a single problem

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#252]
We would like to have something like this:
````
  coco_suite_t *suite;
  coco_observer_t *observer;
  coco_problem_t *problem;

  observer = coco_observer(observer_name, observer_options);
  observer2 = coco_observer(observer_name, observer_options);
  suite = coco_suite(suite_name, suite_options);

  while ((problem = coco_suite_get_next_problem(suite, observer)) != NULL) {
    // problem = observer_add(observer, problem);  // should be possible?
    // problem = observer_add(observer2, problem);  // should be possible?
    optimizer(problem);
  }
  coco_suite_free(suite);
  coco_observer_free(observer2);
  coco_observer_free(observer);  // could be done by the suite, if the observer were passed to coco_suite
````

**Comment by nikohansen** [comment]
Tested with `bbob-biobj` observer in Python and fails: 
```
In [3]: whos
observer_name       unicode     bbob-biobj
observer_options    unicode     result_folder: random_sea<...>s: log_nondominated: all 
suite_instance      unicode     
suite_name          unicode     bbob-biobj
suite_options       unicode     
In [4]: s = Suite(suite_name, suite_instance, suite_options)
In [6]: o1 = Observer(observer_name, observer_options)
In [9]: o2 = Observer(observer_name, 'result_folder: test2')
In [10]: p = s.next_problem()
In [11]: p
Out[11]: <interface.Problem(), id='bbob-biobj_f01_i01_d02'>
In [12]: o1.observe(p)
Out[12]: <interface.Observer at 0x10c3b2be0>
In [13]: o2.observe(p)
/Users/hansen/anaconda/bin/python.app: line 3: 47157 Segmentation fault: 11  /Users/hansen/anaconda/python.app/Contents/MacOS/python "$@"
```

**Comment by nikohansen** [comment]
Tested with `bbob` observer in Python and fails: 
```
In [1]: run example_experiment.py
Benchmarking solver '<function random_search' with budget=10 * dimension, Thu Jan 14 23:22:43 2016
Simple usecase ...
bbob done (2160 of 2160 problems benchmarked), Thu Jan 14 23:22:47 2016 (0.06 min).
In [2]: s = Suite(suite_name, suite_instance, suite_options)
In [3]: p = s.next_problem()
In [4]: o1 = Observer(observer_name, observer_options)
In [5]: o2 = Observer(observer_name, 'result_folder: test2')
In [6]: o1.observe(p)
Out[6]: <interface.Observer at 0x10c6ea870>
In [7]: o2.observe(p)
FATAL ERROR: The current bbob_logger (observer) must be closed before a new one is opened
```

**Comment by nikohansen** [comment]
What should be tested is whether different observers can be used for the same problem (i.e. everything is propagated in order). Due to the lack of different observers for the same test suite this cannot be done at the moment.

**Comment by ttusar** [comment]
Maybe the toy observer could be used on the bbob suite...

**Comment by nikohansen** [comment]
Good point. Tested in Python. Wrapping first the toy observer and then the bbob observer seem to produce the normal output for the bbob observer. Wrapping in the other order, there is no output on the bbob observer. I believe this should be considered as a bug.

**Comment by ttusar** [comment]
I have recently removed a dependency in the biobjective observer that might help achieving this goal. Haven't tested it yet...

**Comment by ttusar** [comment]
Wrapping multiple observers/loggers now works if used in the following way:

````
  coco_suite_t *suite;
  coco_observer_t *observer_inner, *observer_middle, *observer_outer;
  coco_problem_t *problem_inner, *problem_middle, *problem_outer;

  suite = coco_suite("bbob-biobj", "year: 2016", "");

  observer_inner = coco_observer("toy", "");
  observer_middle = coco_observer("bbob-biobj", "");
  observer_outer = coco_observer("toy", "");

  while ((problem_inner = coco_suite_get_next_problem(suite, observer_inner)) != NULL) {

    problem_middle = coco_problem_add_observer(problem_inner, observer_middle);
    problem_outer = coco_problem_add_observer(problem_middle, observer_outer);

    my_optimizer(problem_outer);

    problem_middle = coco_problem_remove_observer(problem_outer, observer_outer);
    problem_inner = coco_problem_remove_observer(problem_middle, observer_middle);

  }

  coco_observer_free(observer_inner);
  coco_observer_free(observer_middle);
  coco_observer_free(observer_outer);

  coco_suite_free(suite);
````

That is, for every `coco_problem_add_observer` function call, we need one `coco_problem_remove_observer`, which returns the problem without this last observer. 

In C this is implemented only as an integration test for now.

**Comment by nikohansen** [comment]
Just to be clear, the _different_ problems for assignment are not needed, I assume. 

I also assume the order in which the observers are free'd doesn't matter (as in this case freeing the outer observer first would be more logical).

Could `coco_observer_free` return a  pointer to the "next" observer still observing the problem?

**Comment by ttusar** [comment]
> Just to be clear, the different coco_problem_t *problems for assignment are not needed, I assume.

I'm not sure they are not... I'll have to try. 

> I also guess that the order in which the observers are free'd doesn't matter (as in this case freeing the outer observer first would be more logical).

It matters, you cannot free the middle one first (the outer observer _is_ the first one that is freed).  

> Could coco_observer_free return a pointer to the "next" observer still observing the problem?

I think not. The observer does not actually wrap the problem, it's logger does. The observer is a long-lasting entity that has little to do with the current problem.

Is there any particular use-case not yet covered behind these questions? I made this example with three observers "for fun". I'm not sure we can expect this to be used often.

**Comment by nikohansen** [comment]
> It matters, you cannot free the middle one first (the outer observer is the first one that is freed).

AFAICS not in the code you pasted, unless the outer observer is named `observer_inner`, or there is some other magic I cannot think of. 

> Is there any particular use-case not yet covered behind these questions? 

No, not really. 

> I made this example with three observers "for fun". I'm not sure we can expect this to be used often.

Agreed.

**Comment by ttusar** [comment]
> AFAICS not in the code you pasted, unless the outer observer is named observer_inner, or there is some other magic I cannot think of. 

Yes, sorry, I had the removing of observers in mind, where the order is important. In freeing is not.

**Comment by ttusar** [comment]
Can this issue be closed now?

**Comment by ttusar** [comment]
@nikohansen Do we have any (existing) Python code that uses two observers on one problem? That is, an implementation of the code above in Python?

**Comment by nikohansen** [comment]
I don't think so.
