### ISSUE TITLE
suites implementation

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#253]
The functions `coco_suite_get_problem_from_indices` and `coco_suite_intialize` seem to suffer from some unnecessary code duplication. It seems logical to rather assign the function pointer in the initializer, instead of repeating the exact same `if else if` etc construct twice.

The two access functions

```
coco_problem_t *coco_suite_get_next_problem(coco_suite_t *suite, coco_observer_t *observer);
```

and

```
coco_problem_t *coco_suite_get_problem(coco_suite_t *suite, size_t problem_index);
```

are somewhat inconsistent, as one suggests to return an observed function, the other does not. This might be a feature rather than a bug though. ~~However, there seems to be no public way to find out the `problem_index`, which is a little weird, given there is a public way to access the problem by index.~~

**Comment by ttusar** [comment]
I agree and will take care of this.

**Comment by ttusar** [comment]
By the way, there is a public interface to `problem_index`, it's maybe just awkwardly named:
```
size_t coco_problem_get_suite_dep_index(coco_problem_t *problem)
```

**Comment by ttusar** [comment]
How come did you close this issue? I haven't done anything about it yet...

**Comment by nikohansen** [comment]
Right, I guess it's too late...

**Comment by nikohansen** [comment]
Do we leave it like that as a wont'-fix, as now the API is used by all the language interfacing code and changes are likely to break one place or the other?

**Comment by ttusar** [comment]
Yes, I think this might be best.
