### ISSUE TITLE
minimal (global) documentation of important interfaces

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#254]
The "official" interface documentation of relevant functions in `coco.h` is lacking in some cases. Very short or incomplete documentation seems OK for unimportant functions for the time being, but, for example, the `suite_t` and `observer_t` constructor interface documentation should not be missing or incomplete.

**Comment by ttusar** [comment]
The methods from 'coco.h' are now commented in great detail. The other files need some (not so detailed) comments as well, so I would like to keep the issue open until this is completed too

**Comment by brockho** [comment]
@ttusar will continue working on the documentation, but the most important global interfaces have been already documented such that I will close the issue now.
