### ISSUE TITLE
Handle Non-anytime Algorithms

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#28]
```
non-anytime algorithms

- restart signal must point to a unique run
- write scripts in Matlab, Java, C/C++, Python, that benchmark a non-anytime 
algorithm by doing restarts with increasing budgets.
- transform non-anytime algorithm data into budget-less data (we need restart 
annotations for that). 


```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 4:50

**Comment by nikohansen** [comment]
One possible solution: implement an `example_experiment`, which opens the suite twice, where only one of them is observed. Then, for each problem:

- Initialization: run the algorithm with minimum `budget` [number of evaluations] once on the observed problem. 
- Loop: increment the budget, run the algorithm again and evaluate only the incremented evaluations on the observed problem.

For this, either the problem must be switched, or the additional solutions must be stored and evaluated twice. In Python, a function wrapper which switches the problem after a given budget (namely switch from `f_unobserved` to `f_observed` when `f_unobserved.evaluations >= f_observed.evaluations`) is a simple way to achieve this goal. In this case, the Initialization and the Loop do not need to be distinguished.
