### ISSUE TITLE
Separating Unit Tests for Users and Developers

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#29]
```
implement a unit test separate for users and developers: maybe based on some 
"automatic detection" of finding the data. Related: data might be downloaded 
automatically (but we don't want to annoy the user, so we should be smart about 
the interface). 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 4:51

**Comment by brockho** [comment]
Can this be closed after we have the unit tests now in the do.py?

**Comment by ttusar** [comment]
The unit tests in do.py are not related to post-processing.

**Comment by dtusar** [comment]
I don't know what was the idea behind this. 
Currently we have tests for the post-processing which automatically download the necessary data if it was not there yet. We don't have separate tests for users and developers, but I don't think that we need them.

**Comment by nikohansen** [comment]
I believe the point of this issue was that a comprehensive testing of the post-processing probably needs more data than we would want to bother a normal user with to download.

**Comment by brockho** [comment]
Looks like this can be closed.
