### ISSUE TITLE
Invisible ftarget

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#31]
```
ftarget should become invisible to the solver: instead of returning ftarget, a 
call-back function should return a flag whether a final termination condition 
is reached. 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 5:07

**Comment by brockho** [comment]
Isn't this solved by now? I guess the postprocessing label is just wrong: the original text only refers to the experiment code.

**Comment by nikohansen** [comment]
Is solved with the new experimental setup, http://numbbo.github.io/coco-doc/experimental-setup, by providing only [`coco_problem_final_target_hit`](http://numbbo.github.io/coco-doc/C/coco_8h.html#a1164d85fd641ca48046b943344ae9069)
