### ISSUE TITLE
set up a C++ example experiment

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#310]
This might be the same `example_experiment.c` file (with some additional compiler directives), or there might be some other way to share some of the C code. It might be useful to check out what we had in the old code.

**Comment by ttusar** [comment]
After some effort, the C example experiment can be compiled also with a C++ compiler. However, if the same Makefile is used, some warnings are produced:
````
cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
cc1plus: warning: command line option '-std=c90' is valid for C/ObjC but not for C++
````
Is there a simple solution to this (I don't know much about Makefiles, but I would like to avoid making a new one for C++ as we already have multiple ones)?

**Comment by ttusar** [comment]
Also, what is the plan with C++? Will we support it in `do.py`?

**Comment by nikohansen** [comment]
I wrote a `make.py` which should replace the makefile and `make`. Not yet committed. From there it should be simpler to factorize out the warnings.

**Comment by ttusar** [comment]
This makes the "verbatim" option even more needed...

**Comment by nikohansen** [comment]
I didn't get what verbatim option means. 

FYI, we now have a `build/c/make.py` which is called in `build_c()` of `do.py`. `python make.py` executed in `build/c` is supposed to do the same as `make` does.

**Comment by ttusar** [comment]
> I didn't get what verbatim option means. 

Some time ago we talked about adding an option to `do.py` to show more output. See also issue #554

**Comment by nikohansen** [comment]
I see, you mean verbose.

**Comment by ttusar** [comment]
Yes, I do :)

**Comment by nikohansen** [comment]
The `C` example experiment now runs in `C++`. When the example experiment code has stabalized, we will re-consider to provide an additional `C++` example.
