### ISSUE TITLE
check-data-set: Informative Error Message 

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#32]
```
Implement a check-data-set that gives informative error message, e.g. if trials 
are missing.
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 5:12

**Comment by brockho** [comment]
I think this is an old issue and can be closed?

**Comment by nikohansen** [comment]
Somewhat related to #1117, hence closed for the time being.
