### ISSUE TITLE
clean do.py and make it consistent

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#322]
* check whether CMA-ES example is still running
* move `run_python` to a `clean_run_python` (or something similar) and prepare a `run_python` that actually builds and compiles as a first start for the user like it exists already for the other languages
* add notes in documentation that the `test` part is for internal usage only

**Comment by nikohansen** [comment]
I moved `run_python` to `run_sandbox_python`. `run_python` now installs the `cocoex` module, runs _all_ Python tests (`build/python/coco_test.py`) and runs the example experiment, as the help suggests. 

I will check the CMA-ES example, I prefer to remove it for the time being as it produces strange output.

**Comment by nikohansen** [comment]
I moved around the comments in the help to be sorted for whether they are for users of developers. CMA-ES example is removed for now.
