### ISSUE TITLE
logger output at prescribed times

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#325]
The logger should write additionally a output line for fixed number of f-evaluations. 
For example at `dimension * [1, 2, 5, 10, 20, 50, 100, 200, ...]`. 
This allows, for example, for rigorous statistical testing up to a given budget, when all compared algorithms surpassed this budget.

**Comment by ttusar** [comment]
Is up to 200 enough?

**Comment by nikohansen** [comment]
no! the ellipsis ... was there to suggest that this sequence goes to infinity, it should preferably dynamically generated, e.g. from the sequence `small_factors = [1, 2, 5]` like
```
if (idx_small_factor < 2) {
    idx_small_factor += 1
    factor *= small_factors[idx_small_factor] / small_factors[idx_small_factors - 1]
} else if (idx_small_factor == 2) {
    idx_small_factor = 0
    factor *= 10 / small_factors[2]
} else 
    raise ValueError() ;-)
```

**Comment by ttusar** [comment]
Should this be output in the `*.dat` files or the `*.tdat` files (currently non existing in the biobj logger)?

**Comment by nikohansen** [comment]
As additional line in the `.dat` file (given a line has not been written at this time step).

**Comment by ttusar** [comment]
Done for the biobjective logger. Should the issue stay opened for some other logger or can we close it?

**Comment by nikohansen** [comment]
Let's have this for the `bbob` observer as well.

**Comment by ttusar** [comment]
@oaelhara You can use the `coco_observer_evaluation_to_log(size_t number_of_evaluations, size_t dimension)` function in `coco_observer.c` to check if the current evaluation number matches the predefined values. [It's now being tested on the test1 branch, but it should be moved to development soon.]

**Comment by oaelhara** [comment]
Thanks for the pointer @ttusar.
I'm not sure I understand why it should be in the .dat files not the .tdat files when the latter are the ones that contain the number of function evaluations aligned data. As I see it, we want additional, dimension dependent, nbfevals triggers which don't belong in the function value aligned data files (.dat) but in the .tdat files.

**Comment by ttusar** [comment]
The `dat` vs. `tdat` discussion was for the biobjective logger, which does not yet have a `tdat` file (and won't need one as it seems). I think for the bbob logger it makes more sense to put it in the `tdat` files (I'm sure @nikohansen will correct me if I'm wrong :)).

**Comment by oaelhara** [comment]
Implemented for the bbob_logger, writes to the .tdat files

**Comment by nikohansen** [comment]
The question would be whether we can and should get rid of the `.tdat` files alltogether? 

If the post-processing can read in non-standard (i.e. not target triggered) lines correctly, there seems no reason to clutter the folder with more files. 

The question remains whether the post-processing can know for sure whether a line is non-standard.

**Comment by dtusar** [comment]
I think the post-processing should not rely on the logic for the creation of these lines. So the non-standard lines should be marked as such directly in in the data files. In that way you can change the logic without any impact on the post-processing. Not sure how the data from different logic can be compared though. 

But if we can say that the logic for choosing the non-standard iterations will remain the same (forever and ever :)) then I can use the same logic also in the post-processing and the data does not need to change. 

In both cases we can get rid of the tdat files, but the post-processing will still have to be backwards compatible (for the single objective case).

**Comment by nikohansen** [comment]
"_So the non-standard lines should be marked as such directly in in the data files_"

I am not a fan. This prevents to read the data in one sweep as a matrix and complicates matter quite a bit (maybe I am missing something though). 

"_But if we can say that the logic for choosing the non-standard iterations will remain the same (forever and ever :)) then I can use the same logic also in the post-processing and the data does not need to change._"

The logic for the non-standard entries is in some way none: they just happen to be all written with the same time stamp, which makes them useful for comparison purposes. 

What bothers me is the logic of the standard lines, which is indeed currently somewhat like they must _remain the same (forever and ever_, not a good thing to have.

**Comment by dtusar** [comment]
You are right. I should just look for the iteration numbers that exist in all files.

**Comment by nikohansen** [comment]
It's a little more complicated that that. If single run reaches the final target quickly, no further records are taken, but we "know" the outcome of all further records (which is: as good as it can get). In general, aligned records which are not available in all datasets are likely to be valuable, for example if we happen to investigate only a subset where they _are_ present.

**Comment by ttusar** [comment]
Now both the single- and bi-objective loggers produce the `dat` and `tdat` files and the post-processing handles this correctly. I think this issue can be closed.
