### ISSUE TITLE
do.py should install the post-processing

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#331]
A python file (residing in each build/language folder) like
```python
import sys
try:
    from cocopp import rungeneric
except ImportError:
    from bbob_pproc import rungeneric

if __name__ == "__main__":
    rungeneric.main(sys.argv[1:])
```
should work and reduce the burden to always find the right path to the post processing folder. To make it work, module `cocopp` has be installed when `do.py` is called.

**Comment by brockho** [comment]
Except for the name change from `bbob_pproc` to `cocopp`, it works now smoothly for me (Windows 7) and Niko (Mac OSX).

**Comment by nikohansen** [comment]
And with the call `python -m bbob_pproc` available there is also no need for the above Python file.
