### ISSUE TITLE
Allow the following web pages to be accessed

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#332]
http://numbbo.github.io/
http://numbbo.github.io/numbbo/
http://numbbo.github.io/register

In order to do so, we need to either provide a basic html file with links towards the other documentation or a direct link to to existing pages (if the web server allows this for example via .htaccess).

**Comment by brockho** [comment]
The following redirects are now installed through Github Pages' html redirects:
http://numbbo.github.io/  --> https://github.com/numbbo/coco
http://numbbo.github.io/numbbo/   --> https://github.com/numbbo/coco
http://numbbo.github.io/coco/   --> https://github.com/numbbo/coco
http://numbbo.github.io/register  --> https://docs.google.com/forms/d/1GS48SXGjapUu6WY6Zt-Ma5HCl2izq4ydT7sMa5ujUDI/viewform

Instead of https://github.com/numbbo/coco, we might want to have a brief overview with links to all documentations as html file in the long run?

**Comment by nikohansen** [comment]
Yes, a link overview seem super helpful, even I am slightly lost in what is important to look at.

**Comment by brockho** [comment]
Since this issue is open for some time, but we already have the links to the documentation at https://github.com/numbbo/coco#Further-Links: can we close the issue and we keep updating the list of documentations there whenever we have something new?

**Comment by nikohansen** [comment]
I have put a shortlist of links in the beginning of the entry readme. Try to keep it updated with improved entries to the documentation when available.
