### ISSUE TITLE
postprocessing removing dependency of name bbob_pproc 

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#336]
When I try to remove the `from bbob_pproc` in `rungeneric.py`, I get the following error: 

```
postprocessing/bbob_pproc/rungeneric.py", line 25, in <module>
    from . import genericsettings, rungeneric1, rungeneric2, rungenericmany
ValueError: Attempted relative import in non-package
```

This is understandable, but what is the solution such that we still can call `rungeneric.py`? 

Probably we should abandon this use case in the long run, as installation of the package should suffice to use it properly (without the need to know the location of the build)?

**Comment by nikohansen** [comment]
It seems that this design pattern might work: 
```
if __name__ == "__main__":
    # add ".." to the Python search path, import the module to which
    # this script belongs to and call the main of this script from imported
    # module. Like this all relative imports will work smoothly. 
    (filepath, filename) = os.path.split(sys.argv[0])
    sys.path.append(os.path.join(filepath, os.path.pardir))
    try:
        import cocopp
    except ImportError:
        import bbob_pproc as cocopp
    res = cocopp.rungeneric.main(sys.argv[1:])
    sys.exit(res)
```

**Comment by nikohansen** [comment]
Many if not most imports are now relative `from .` instead of `from bbob_pproc`, but there are still quite a few left. 

The dependency of the tests in `__main__` remain as well and it's not clear to me how to proceed with them other than changing their name manually when necessary.

**Comment by brockho** [comment]
Making sure that no `bbob_pproc` appears anywhere in the code is one thing, the other is that the pickle files for the bestalg contain the string as well. However, they will be removed soon with the planned merge of the `feature-refalg` to the `development` branch such that we should aim at having this issue closed for the 2.0 release, i.e., have at least the change to `python -m cocopp` working.

**Comment by brockho** [comment]
In the `feature-refalg` branch, the rename from `bbob_pproc` to `cocopp` is now done and runs through the tests. The only thing missing seems to be a rename of the `bbob_pproc_commands.tex` to `cocopp_commands.tex` which also involves the LaTeX templates.

**Comment by nikohansen** [comment]
Renaming of the `.tex` file seems not strictly necessary though.

**Comment by dtusar** [comment]
The `bbob_pproc_commands.tex` was renamed to `cocopp_commands.tex`. The LaTeX templates were updated accordingly.
