### ISSUE TITLE
Display testbed ID in ECDF graphs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#34]
```
display testbed ID in the ECDF graphs (now functions and dimensions are shown). 
We also need to define how an ID should look like, where this information is 
stored and how it is passed around. 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 5:46

**Comment by dtusar** [comment]
@brockho Can you please define the testbed IDs for the current two testbeds?

**Comment by brockho** [comment]
As a first step, I suggest to use the actual names `bbob` and `bbob-biobj` (plus potentially `bbob-noisy`). And maybe, we want to add a version number, which for the bi-objective suite will ease the identification of the reference sets/hypervolume reference targets used. I don't know, however, how to integrate this version number best. The simplest will be to add the github commit id via `git_version()`, but this might be too unreadable if we add this in all figures.

**Comment by dtusar** [comment]
OK, I will add the names. But I wouldn't suggest having the version numbers in the headers of the figures. Maybe we should think of adding some kind of footnote on all figures for debugging related information.

**Comment by brockho** [comment]
The version number could be as small as the indication whether the standard absolute or the runlength-based target scenario is displayed, e.g. at the bottom left of this type of figure:

![ppfigdim_f001](https://cloud.githubusercontent.com/assets/13706996/13916214/94ff5ec8-ef59-11e5-9a0d-1e8e22f0baf9.png)

For plots like the ECDF graphs, on the other hand, the testbed itself should probably be displayed indeed in front of the function name at the top (e.g. something like `bbob-biobj - f42`).

**Comment by dtusar** [comment]
Is the version number relevant only for us or also for the people who are using COCO? If it's only for us, I would suggest a lighter color.

Regarding the testbed name, should it be on all ECDF figures? On this one the header becomes rather long.

![example](https://cloud.githubusercontent.com/assets/13744819/13916888/92c4ab64-ef5d-11e5-9554-7674cd14de79.png)

**Comment by brockho** [comment]
I agree with you on the above figure, the header is definitely too long. Why not putting the testbed id in the second line then? 

I also agree for the lighter color for the version number.

**Comment by dtusar** [comment]
I added the testbed name to the ECDF figures and git version to all figures. Currently we have labels in different positions on different figures. So I put the git version label where it does not overlap with other labels.

**Comment by nikohansen** [comment]
> Is the version number relevant only for us or also for the people who are using COCO?

Given the choice of targets (reference indicator value) changes over different versions, this is relevant to *anyone* looking at the graphs. Given the change of the reference indicator value makes a relevant difference, there is no way to make any reasonable comparative interpretations without knowing the version number.

**Comment by loshchil** [comment]
It would be nice to have a file where the reference values are stored and
are used to count solved targets *during* the post-processing. In this
case, we would not need to rerun the algorithm if new target values are
available.
Bad thing about it is that a *wise* man can easier create fake figures.

**Comment by nikohansen** [comment]
I don't understand how a file with reference values can help to prevent the need to rerun algorithms.

**Comment by loshchil** [comment]
I run an algorithm A once, hypervolume values found by A vs function
evaluations are stored in the files
The postprocessing plots how far the algorithm values are from the
reference values stored in a file.
If the reference file is updated, I don't need to rerun my algorithm to get
correct plots as they are now computed w.r.t. the updated reference file.

**Comment by nikohansen** [comment]
It seems to me that this assumes that each time step with an improvement is recorded. AFAICS, and I might be wrong, but the only problem with new target values is that this is not the case. We might want to reconsider this policy and/or consider an option which would record each hypervolume improvement.

**Comment by loshchil** [comment]
I might be wrong, but I have a feeling that a potential loss in the current
case would be in order of one target per function, i.e., 1-2% on ECDF
curves
