### ISSUE TITLE
Rename repository to COCO

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#342]

**Comment by nikohansen** [comment]
Capital letters or not? We should preferably follow the Github conventions.

**Comment by ttusar** [comment]
It seems there is no written convention, but people mostly use lower-case names with hyphens (if needed). So it's maybe best to call it coco and, while we are at it, also rename the COCOdoc repository to coco-doc. 

In addition to taking care of CI, we'll have to change also the links to the repository that we have already put in the old websites and on the CFP.

**Comment by dtusar** [comment]
The repository is renamed to coco (i.e. numbbo/coco). It will all still work for you if you use numbbo/numbbo, but you should eventually update it everywhere to coco. 

Also the COCOdoc is renamed to coco-doc.

**Comment by dtusar** [comment]
The links to the doc repository are not updated yet.

**Comment by dtusar** [comment]
I updated the links in the files in the github repositories. The links should also be updated on other web pages.
