### ISSUE TITLE
decision on budget and dimensions in all example experiments

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#346]
see also #286, the final decision needs yet to be taken.

**Comment by brockho** [comment]
I thought we agreed upon the following yesterday:
- budget: 2*dimension
- dimensions: 2, 3, 5, 10, 20, 40
- only `bbob-biobj` suite with random search runs by default; code for running grid search and other suites might be provided, but should be uncommented
- today, we also said that the possibility of restarts should be implemented (though random search will not restart itself, it will allow restartable algorithms to be connected easily in a restart configuration which in particular for the single-objective suite(s) is the suggested way to go anyway; and also for the multi-objective case, it is expected to give better results, see for example the OCD paper by Tobias and co-authors)

**Comment by nikohansen** [comment]
Looks good to me. Adding a tiny detail: in the SO case, the Python code proposes for the first start the middle of the search interval as initial solution, and afterwards a uniform distribution over the middle 80% of each variable range.
