### ISSUE TITLE
readme in build/c folder

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#356]
is missing, it should at least point to the root readme [here](https://github.com/numbbo/coco/blob/master/README.md)

**Comment by ttusar** [comment]
Many other READMEs are also missing (or should be reformatted from `txt` to `md`).

**Comment by ttusar** [comment]
Created the `README.md` in the `build/c` folder and updated the one in the `build/java` folder. Now all subfolders of `build` have a `README`. 

What about `README` files in the `code-postprocessing` folder? There aren't any there...

**Comment by nikohansen** [comment]
Just a reminder: duplication of material is a serious maintainability problem. Consider always using a reference to a single most authoritative source.

**Comment by ttusar** [comment]
I'm not sure I understand what you mean: you want to redirect the user to Python's prerequisites instead of having them copied in the C readme?

**Comment by nikohansen** [comment]
I wanted to make a reminder of a general rule. I hadn't looked at anything specifically. In general, I don't want to have duplicate instructions (in form of code or text) around, if they could be a possible target of changes – for example when they have become outdated – because this causes a major maintainability problem.

There are trade-offs, and sometimes you want to sacrifice maintainability for usability. For example, if a link would be difficult to access for the user, you might decide to copy or repeat the information. Yet, maintainability I would put rather high on the list of important things to have.
