### ISSUE TITLE
documenting troubles and their solutions

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#357]
This is just a friendly reminder that we have a section [**Known Issues / Trouble Shooting**](https://github.com/numbbo/coco/blob/master/README.md#known-issues--trouble-shooting) in our root readme. 

It would be very useful to incrementally document there known issues the user could face and we cannot,  or have no time to solve once and for all now.

**Comment by brockho** [comment]
I would guess that, by now, everybody knows about this Known Issues / Trouble Shooting section in the readme (or at least the people who would at some point feel responsible to add things there). Hence, I suggest to close the issue. But I am also fine if somebody wants to keep it open.
