### ISSUE TITLE
Design of Testbed and Display Settings

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#36]
```
how can testbed settings and display settings be organized in the best way? See 
files genericsettings.py config.py. 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 13 Jun 2014 at 5:56

**Comment by brockho** [comment]
This is a very old issue but at least in part dealt with via the new `Testbed` class. Can this issue be closed?

**Comment by nikohansen** [comment]
It's probably still a valid question, unless we feel the organization is sufficiently simple or cannot be improved. I will close it anyway, because it seems a little too generic for an issue to be addressed.
