### ISSUE TITLE
pickle files contain a bbob_pproc module name "hard-coded"

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#372]
The pickle files should work when we rename the `bbob_pproc` module to `cocopp`. One way would be to produce new pickle files. Like this we could also try to let `DataSet` derive from `object` (new style class), see #45, #46, which is a major obstacle. Or maybe we find a different format, which does a more generic job.

**Comment by brockho** [comment]
The plan is to provide the bestalg data sets as standard data sets such that the remaining pickle files will become obsolete. For standard algorithm data sets, pickle files are already not provided anymore. This issue can therefore hopefully be closed as soon as the `feature-refalg` branch is merged into `development`.
