### ISSUE TITLE
Getting a lot of "Observed fitness smaller than optimal fitness" warnings in Octave

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#384]
When running the Matlab/Octave wrapper in coco-experiments/build/matlab with random search on the `bbob` suite, many warnings of the type

```
COCO WARNING: Observed fitness is smaller than supposed optimal fitness.
```

are displayed. This happens for f5 in all dimensions with the number of instances with warnings dropping from 5/5 in dimension 2 and 3 to 2/5 warnings in dimensions 20 and 40.

Reproducible at least under Mac (Asma's computer) and Windows 7 (Dimo's computer).

**Comment by ttusar** [comment]
Pushed a new version on the development branch. @brockho and @asmaatamna, can you try again and let me know?

**Comment by brockho** [comment]
Output looks fine and is without warnings under Windows for me.

**Comment by ttusar** [comment]
Can we close this issue?

**Comment by brockho** [comment]
From my viewpoint yes, but maybe, we wait for @asmaatamna's reply?
