### ISSUE TITLE
do.py needs to be extended to allow for accessing exampleexperiment.m through Octave

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#388]
Issue: `octave --no-gui` closes Windows `cmd` shell after running the script :-(

**Comment by nikohansen** [comment]
Could it be that it interprets the `exit` command in that way?

**Comment by brockho** [comment]
Is solved except for the issue under some Windows Octave installations where the octave.bat should be edited. Since this is documented and we opened an according new issue (#399) already, we should close this one.
