### ISSUE TITLE
Overlapping help in rungeneric.py and related files

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#39]
```
the help of rungeneric.py and rungenericmany.py etc. are very much overlapping 
(as one calls the other in case). Is there a better way to organize this? 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 14 Jun 2014 at 11:42

**Comment by brockho** [comment]
In the long run, `rungeneric1.py`, `rungeneric2.py`, and `rungenericmany.py` should be integrated into the `rungeneric.py` such that the problem with the overlapping help will be solved along this refactoring. This will also help to remove a lot of duplicated code for reading in and checking data.

**Comment by nikohansen** [comment]
See also #1364, quite related.

**Comment by brockho** [comment]
With the changes from end of March in the development branch, the overlapping docstrings of `rungenericmany.py`, `rungeneric1.py`, and `rungeneric.py` are cleaned up now. The `rungenericmany.py` and `rungeneric1.py` are only called from within `rungeneric.py` and thus accessed via a single entry point from both the command line and from `cocopp.main(...)`.
