### ISSUE TITLE
Octave under Windows crashes Command Window

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#399]
The standard Octave installation under Windows creates an `octave.bat` file through which Octave can be called from the command line. Unfortunately, this `.bat` script closes by default the command window from which octave is called as well.

To solve this issue, one can outcomment the 'exit' in the last line of this `octave.bat` file (already documented in the README.md in `build/matlab/`. In the long run, however, this should be solved directly from the `do.py` script, e.g. by calling `octave-cli.exe` directly. For this, the Windows path has to be set to the new location as well, but maybe this is a cleaner way of handling this issue than messing up with `.bat` files.

**Comment by nikohansen** [comment]
How about opening a `shell` first and than calling `octave.bat` from this shell (which will invoke another shell)?

**Comment by brockho** [comment]
There is actually another issue with Octave under Windows. It is already commented in the known issues of our overall README.md and now causes in particular problems on the Windows CI slave: once `octave` is started under Windows via the `octave.bat` file, the compiler of Octave becomes available and crashes our `run-c`. Since `octave.bat` changes the Windows path only locally/temporarily, everything is fine again in a new command window. But both `run-octave` and `run-c` cannot be started at the moment from one and the same command window.

For the CI, I suggest to start a third Windows slave which runs the Octave tests while the other tests continue to run on the other slaves. In the long run, we should, however, solve this issue within the `do.py` as suggested above.

**Comment by dtusar** [comment]
Now we have a windows slave on which we only test `build-octave` and `test-octave`.

**Comment by brockho** [comment]
Current suggestion is:
* in `do.py`: distinguish between Windows and not. If Windows, call `octave-cli.exe` without the `--no-gui` option directly, otherwise keep as is
* restrict usage to Octave >= 4.0.0 under Windows and document that the `bin/` folder has to be in the path

I will implement that.

**Comment by tobiaswagner** [comment]
When we recommend to have the `bin/` folder in the path, we will directly run into the problems with the duplicity of the gcc, sh, ... commands.

**Comment by brockho** [comment]
Latest update (Tobias and Dimo): we will probably provide a new `octavecoco.bat` file, a Windows Octave user is supposed to but in her/his Octave folder (where the `octave.bat` already lies). In this, we can setup everything we need, but not more (for example `cd` in the `bin/` folder to start `octave-cli.exe` without interfering with the user's installation. This is the cleanest way with the smallest effort. And it will remove quite some explanations in the known issues.

**Comment by brockho** [comment]
Done with pull request #619 as suggested. An 'octave_coco.bat` file is now placed under Windows by `run-octave` into the Octave folder which replaces the standard `octave.bat` without messing up paths.
