### ISSUE TITLE
Move log_level out of the observer options

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#400]
`log_level` is not really connected to the observer and should be accessible in some other way. Maybe we should make a `coco_set_log_level()` function in order to be able to change it...

**Comment by ttusar** [comment]
Done! 

The `"log_level: string"` option in the observer options will be ignored now, therefore the other languages need to implement an interface to the `coco_set_log_level()` function if they wish to set the `log_level` to some other value than the default (`info`). I just did this for Java (it's not on the development branch yet, but will be shortly). 

TODO: Matlab/Octave and Python

BTW, do we also need a `coco_get_log_level()` function?

**Comment by ttusar** [comment]
Issues #433 and #434 have now been created for this, therefore I'm closing this issue.

**Comment by nikohansen** [comment]
"_BTW, do we also need a coco_get_log_level() function?_" 

I just stumbled of the use case where I want to change the level temporarily. So yes, but in this case it would be sufficient for the setter to return the old level. 

Input "" could then serve as indicator to set nothing but return the current level. 

Other unknown input values should issue a coco_warning. 

So, no, but...

**Comment by ttusar** [comment]
Isn't it cleaner to just have a `coco_get_log_level()` function?
I will take care of the warning.

**Comment by nikohansen** [comment]
I believe the above is a common design pattern. It allows for
```
old_level = coco_set_log_level(new_level) // enter
dirty work work work
coco_set_log_level(old_level)  // exit
```
instead of 
```
old_level = coco_get_log_level()  // prepare
coco_set_log_level(new_level)  // enter
dirty work work work
coco_set_log_level(old_level)  // exit
```
which is considerably more ugly. 

One could have both...

**Comment by ttusar** [comment]
I see how it can be "easier" to use, but I still think one expects the getter to return some value and the setter to set it, not a setter to get it and set it...

**Comment by ttusar** [comment]
What if I provide the two "clean" functions in C and then you do your magic in Python within the interface?

**Comment by nikohansen** [comment]
Another advantage, I admittedly did not mention, for having only one function is that the interface remains (c)leaner. Having getter and setter functions is rather needless clutter. And we might come up with more variables we like to be able to manipulate in future. 

Looking at the `build/matlab` folder is rather ugly. That's of course also the problem of Matlab, but keeping an interface to a small number of functions is, I believe, a value in itself.

I let you decide anyway. 

[Evil](http://www.javaworld.com/article/2073723/core-java/why-getter-and-setter-methods-are-evil.html)

**Comment by ttusar** [comment]
OK, I agree that having less functions is better than more (especially in the interface), but you cannot make the "evil" argument when you are not proposing something less "evil" :)

**Comment by nikohansen** [comment]
Granted, explicit is usually better than implicit, but when I look for a getter and find none, I will check out the setters, or I don't deserver better.

**Comment by nikohansen** [comment]
FWIW, think of it as a `coco_log_level` _variable_ rather than a `coco_set_log_level` _function_. BTW, the naming convention we followed lately would suggest to name it `coco_log_level_set`. Indeed `coco_log_level` seems to make quite some sense to me as well.

**Comment by ttusar** [comment]
Well, we do already have a static global `coco_log_level` variable. The `coco_set_log_level` function is now used as you wanted (it's already in the development branch). Do you want me to rename it to `coco_log_level_set`? I'm not sure how C89 would react to having the same name for a variable and a function (not to mention it's a bit confusing)...

**Comment by nikohansen** [comment]
Sure, you can't have the same name for a function and a variable. Python convention is to have the same name and prepend a `_` for the variable within, which doesn't work for C. I don't know the usual conventions for this design pattern. Don't worry, use the names which you feel comfortable with. 

The return value should be `const char *` or `char const *` rather than `char *`.

**Comment by ttusar** [comment]
Good catch, thanks! I will take care of this together with something else I'm working on now, so it might take a bit...

**Comment by nikohansen** [comment]
You will need to change the declaration in line 26 of interface.pyx
```
char* coco_set_log_level(const char *level)
```

FTR, the log level interfacing implementation in Python
```python
def log_level(level=None):
    """`log_level(level=None)` return current log level and
    set new log level if `level is not None`.
    
    `level` must be 'error' or 'warning' or 'info' or 'debug', listed
    with increasing verbosity, or '' which doesn't change anything.
    """
    cdef bytes _level = _bstring(level if level is not None else "")
    return coco_set_log_level(_level)
```

**Comment by ttusar** [comment]
ok

**Comment by nikohansen** [comment]
I can do the changes, as I am just testing it anyway.

**Comment by nikohansen** [comment]
Done.

**Comment by ttusar** [comment]
Great, thanks. I guess we can close this issue now.
