### ISSUE TITLE
entry point for looking at figures

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#402]
I wonder if we shouldn't have a simple entry point to look at the results. For example an `ppdata/index.html` file, or maybe even better, a `ppdata.html` file in the current folder or maybe both? 

Depending on what we regard as the default usecase/workflow, the `--svg` option should become default?

**Comment by nikohansen** [comment]
I am also in favor to have by default the`--rld-single-fcts` option to be on. 

I wrote once a Python script that searches for all pictures in a folder and generates an `html` page which displays them in some semi-smart way. It's not too difficult to do.

**Comment by dtusar** [comment]
OK, we can change the default behavior if nobody is against it. So now we would have the `--no-rld-single-fcts` option.

I would prefer having one entry page (as you suggested in the first comment) which has links to the other pages (and vice versa). We already have some html pages but not all pictures are in. Probably we should discuss which pictures to display and how to organize the html pages.

**Comment by nikohansen** [comment]
Agreed, and a single html page should preferably not become tens of pages long. The organization is a little bit a matter of trial and error.

**Comment by dtusar** [comment]
Now we have a starting file `ppdata.html` which has links to the other `html `pages and vice versa. The existing `html `pages are currently used. Maybe we should reorganize them a little.

Also the `svg `files and the runlength distribution figures are included by default.
