### ISSUE TITLE
output data "result_folder"

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#405]
I suggest to write all experiment data by default into a folder named `exdata`, analog to the `ppdata` folder of the post-processing. A simple way to proceed would to adapt the example experiment observer options accordingly.

**Comment by ttusar** [comment]
Sure, we can change the default. But what to do in the experiments then, just delete that option so that the default is used? I guess this would be best...

**Comment by nikohansen** [comment]
Good point. Either prepending the folder with `exdata`. Or writing `exdata/...` explicitly, so to speak by default. I tend to prefer the second version.

**Comment by nikohansen** [comment]
The Matlab/Octave example experiment now writes to `exdata/LS...` by default.

**Comment by ttusar** [comment]
Set `exdata` as the default `folder_name` and have a separate `subfolder_name` for the actual results.

**Comment by nikohansen** [comment]
We tend to choose a fixed `exdata` folder and the `result_folder` defines a folder name within this folder.

**Comment by ttusar** [comment]
This is now done in C. By default the results go into the `exdata/default` folder and the name of the inner folder can be changed through the `result_data` option of the observer. 

The python code should be updated before closing this issue.

**Comment by nikohansen** [comment]
`result_data` seems to have no effect for me, `result_folder` works to change the inner folder name.

**Comment by ttusar** [comment]
Yes, sorry, typo :)
