### ISSUE TITLE
size_t handled as int in Matlab interfaces

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#407]
I have no idea if this is a real issue or not, but it should at least be checked.

In some Matlab interfaces, `int` is used to store `size_t` or `long` returns from `coco_problem_get_*` functions (see for example cocoProblemGetEvaluations.c and cocoProblemGetDimension.c). Maybe `int` in Matlab is larger than in C and this is ok...

**Comment by tobiaswagner** [comment]
Actually, there is no „int“ in MATLAB. There are either int8, int16, int32, int64, single, uint8, uint16, uint32 or uint64. Without special declaration, everything is converted into double.

Von: ttusar [mailto:notifications@github.com]
Gesendet: Dienstag, 19. Januar 2016 15:21
An: numbbo/coco <coco@noreply.github.com>
Betreff: [coco] size_t handled as int in Matlab interfaces (#407)


I have no idea if this is a real issue or not, but it should at least be checked

In some Matlab interfaces, int is used to store size_t or long returns from coco_problem_get_* functions (see for example cocoProblemGetEvaluationsc and cocoProblemGetDimensionc) Maybe int in Matlab is larger than in C and this is ok

**Comment by ttusar** [comment]
Right, this is actually C's int...

**Comment by brockho** [comment]
The Matlab wrapper is now cleaned according to the above issue (see pull-request #547). In case I have overlooked something, please re-open the issue.
