### ISSUE TITLE
LaTeX templates for bbob-biobj suite

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#418]
LaTeX templates for displaying the results on the bi-objective `bbob-biobj` suite are needed. As a first step, we should at least provide ACM compliant files. Before, however, we have to decide what we actually want to (and what we can) display within the 8 pages limit.

**Comment by dtusar** [comment]
Enable the creation of the pdf from the template in the CI test.

**Comment by brockho** [comment]
We will first focus on having a working 1-algorithm template. It should display the ECDFs for single functions (organized in rows of 4 plots, split into three figures with 4, 5, and 5 rows) and for all subplots (in a 4x4 layout).

**Comment by brockho** [comment]
A first version of the single-algorithm template is available in the doc branch and should be merged and released as soon as the documentation papers are on arXiv.

**Comment by ttusar** [comment]
I get this problem:

```
./templateBIOBJarticle.tex:258: Undefined control sequence.
<argument> ...ngleOne} \bbobecdfcaptionsinglefcts 
                                                  {} }}{\thepage }}
l.258  }
```
@dtusar checked and said `\bbobecdfcaptionsinglefcts` doesn't exist. Any ideas where the problem is?

**Comment by ttusar** [comment]
Was on the wrong branch... everything works fine now.

**Comment by nikohansen** [comment]
I do get the same error, while I believe I used the most current branch(es). What am I doing wrong?

**Comment by ttusar** [comment]
Works on the doc branch (where the template is), but not on the development one as the two were not merged yet.

**Comment by nikohansen** [comment]
I am on the doc branch.

**Comment by dtusar** [comment]
Did you also run the post-processing on the doc branch? Otherwise this command does not exist in the `bbob_pproc_commands.tex`.

**Comment by nikohansen** [comment]
Do I also have to *install* the post-processing from the doc branch?

**Comment by dtusar** [comment]
Yes.

**Comment by brockho** [comment]
The single-algorithm LaTeX template is now available for the bbob-biobj suite which is why I removed this issue from the v0.9 milestone.

Still missing (in this repository at least):
- bbob-biobj templates for 2 and 3+ algorithms
- IEEE style templates (e.g. for CEC) for all settings

**Comment by ash-aldujaili** [comment]
When are the templates for 2 and 3+ algorithms going to be released?

**Comment by nikohansen** [comment]
Maybe we should rather try to have one for 2+ algorithms.

**Comment by brockho** [comment]
Since the LaTeX template for 2+ algorithms on the `bbob-biobj` test suite has been in the master branch for some time now and also the tests have been added to our continuous integration system, I consider this issue solved for the moment (e.g. until we need again some IEEE style templates).
