### ISSUE TITLE
octave requirements

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#426]
Someone who knows more should try to improve on "_Octave: needs to be installed._" in Section Language-Specifics of https://github.com/numbbo/coco/blob/development/README.md

**Comment by brockho** [comment]
Sure. I will do it. Thanks for already assigning me. I would have done it myself anyway.

**Comment by brockho** [comment]
closed with 21ce1ed540ae495e092f4327116b219b04cbfe3b
