### ISSUE TITLE
referencing sections in markdown

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#428]
It would be useful to make a reference to sections in Markdown documents, but I haven't been able to figure out how (or even whether) this works.

**Comment by ttusar** [comment]
This is how you do it:

In the section you say:
````
### Section title <a name="tag"></a>
````
In the text, when you wish to make a reference, you say:
````
[see this great section](#tag)
````

Glad that the time I spent looking for a solution to this will be beneficial to someone else as well...

**Comment by nikohansen** [comment]
Great, i.e. using `html` syntax for creating a tag. I believe I saw this, but somehow didn't manage to make it work. Works like charm now, thanks!
