### ISSUE TITLE
Review of __all__

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#43]
```
is __all__ up to date? 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 16 Jun 2014 at 12:11

**Comment by brockho** [comment]
In the new code, I cannot find any `__all__`: can we close this issue as well?

**Comment by dtusar** [comment]
Actually we do have `__all__` in some files (e.g. all the `rungeneric` files), but I'm not sure if we need them elsewhere or if we have to update the existing ones?

**Comment by brockho** [comment]
Okay, I will check.

**Comment by brockho** [comment]
Issue can be closed as `__all__` seems up-to-date in all python files after the slight clean up of ca90869.
