### ISSUE TITLE
propagate function `coco_set_log_level` into Matlab/Octave

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#434]

**Comment by brockho** [comment]
I will try my best to take care of this one.

**Comment by brockho** [comment]
A first test (as commited to the development branch) shows a larger problem: Coco's global variables cannot be accessed from Matlab via different `.c` files. The only way out seems to be to replace the many wrappers (one for each Coco function) with a single `cococall.c` file that takes as first argument the Coco function to call and then does a long switch/case.

**Comment by brockho** [comment]
Done with pull request #619.
