### ISSUE TITLE
Clean out the warnings

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#438]
````
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment.o example_experiment.c
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o coco.o coco.c
code-experiments/src/large_scale_transformations.c: In function 'ls_compute_blockrotation':
code-experiments/src/large_scale_transformations.c:79:22: warning: variable 'current_gvect_pos' set but not used [-Wunused-but-set-variable]
code-experiments/src/large_scale_transformations.c: In function 'ls_rand_int':
code-experiments/src/large_scale_transformations.c:202:53: warning: conversion to 'double' from 'long int' may alter its value [-Wconversion]
code-experiments/src/large_scale_transformations.c:202:61: warning: conversion to 'double' from 'long int' may alter its value [-Wconversion]
code-experiments/src/large_scale_transformations.c: In function 'ls_get_block_sizes':
code-experiments/src/large_scale_transformations.c:294:39: warning: conversion to 'double' from 'size_t' may alter its value [-Wconversion]
code-experiments/src/logger_bbob.c: In function 'logger_bbob_initialize':
code-experiments/src/logger_bbob.c:325:59: warning: conversion to 'double' from 'size_t' may alter its value [-Wconversion]
code-experiments/src/logger_bbob.c:326:57: warning: conversion to 'double' from 'size_t' may alter its value [-Wconversion]
cc -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment coco.o example_experiment.o -lm
````
And rename the file `large_scale_transformations.c` using the (obvious) naming convention.

**Comment by oaelhara** [comment]
It turns out, I had an outdated version of gcc (4.2) so couldn't see these warnings. I updated to version 4.9 so I can see the warnings now.

For the convention on filenames, you mean something like coco_... or more suite_largescale_compute.c (even though the transformations aren't applicable only to the large scale suite)? The only similar file I see is suite_bbob_legacy_code.c and it shouldn't remain there for very long since it's legacy code.

**Comment by nikohansen** [comment]
I am puzzled, `transform_vars_large_scale.c` seems the directly obvious name to me, respecting the conventions used. `transform_vars_sparse.c` would maybe be a better name. 

Permutations and block-rotations should preferably be separate transformations which can be applied independently.

"_suite_bbob_legacy_code.c [...] shouldn't remain there for very long since it's legacy code._" 
According to its documentation this is `Legacy code from BBOB2009 required to replicate the 2009 functions.` I don't think this should go away ever, as I think we should be able to replicate the 2009 functions for a very long time.

**Comment by oaelhara** [comment]
I think @ttusar is talking about "code-experiments/src/large_scale_transformations.c" which contains the functions that generate the matrices and permutations used in "transform_vars_permblockdiag.c" and in the function-definition files such as "f_ellispoid.c".
For the functions in suite_bbob, these files use the functions implemented in "suite_bbob_legacy_code.c" such as "bbob2009_compute_xopt()" and "bbob2009_compute_rotation()".

**Comment by nikohansen** [comment]
Correct, we have been talking about the file name `large_scale_transformations.c`.

**Comment by nikohansen** [comment]
Files that compute x-space transformations should start with `transform_vars_`. Files that define functions should start with `f_`. I suggest to have `transform_vars_permutation.c` and `transform_vars_blockrotation.c`, but depending on the specific content other solutions might be preferable.

**Comment by oaelhara** [comment]
Is something like "coco_matrices.c" and "coco_permutation.c" okay for the implementation of the functions that "generate" the matrices (maybe add bbob2009_compute_rotation()... ) and permutations?
The "transform_vars..." files "apply" the transformations and the f_... files define which transformations are applied for a given function (in the non ..._raw() definitions). We still need additional file(s) to actually compute these transformations.

**Comment by nikohansen** [comment]
Why do we need additional files?

**Comment by oaelhara** [comment]
To implement functions such as:
static void ls_compute_truncated_uniform_swap_permutation(size_t *P, long seed, size_t n, size_t nb_swaps, size_t swap_range);

**Comment by nikohansen** [comment]
Why do we need additional files for that?

**Comment by oaelhara** [comment]
To keep the same format for the "transform_..." files:
° the structure/object
° the evaluate function
° the free function
° the __init__() like function
At least this is how I see it: we do not want to add functions such as ls_compute_truncated_uniform_swap_permutation() to these files the same way we did not put "bbob2009_compute_rotation()" in "transform_vars_affine.c".
As it stands, bbob2009_compute_rotation() is in "suite_bbob_legacy_code.c"

**Comment by nikohansen** [comment]
The `bbob2009_compute_rotation` function is in legacy code, because we want to discourage its use in new code. For this reason we wouldn't want it to be in `transform_vars_...`.

Apparently you want to have a `transform_vars_permutation_helpers.c` file?

**Comment by oaelhara** [comment]
Something like that By the way, I can no longer find the other "helper" functions.

**Comment by ttusar** [comment]
That "helper" file does not exist anymore, true, but you can make one if you need it. The 'coco_*.c' names are reserved for general things of the platform, specific stuff should be grouped together by name (appending a _helper to a file keeps it together with the file that needs the helper).

**Comment by oaelhara** [comment]
Okay, noted. I'll also separate the permutations from the block-diagonal matrix application.

**Comment by oaelhara** [comment]
I close this issue and open a new one (#472) to address this.
