### ISSUE TITLE
readability of howtos

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#448]
The [documentation howto](https://github.com/numbbo/coco/blob/master/howtos/documentation.howto) is online essentially unreadable (to me), because it has only few but VERY long lines.

**Comment by brockho** [comment]
Same holds for the [release howto](https://github.com/numbbo/coco/blob/master/howtos/release.howto). Maybe, we should change to Markdown here?

**Comment by nikohansen** [comment]
No objection from my side, Markdown starts to become second nature.

**Comment by brockho** [comment]
Done for the howtos with pull-request #510. Hard wraps after about 80 characters in all readmes TBD.

**Comment by brockho** [comment]
I tried my best to find all readmes and changed to hard wraps now. Issue can be therefore closed.
