### ISSUE TITLE
octave should be tested in CI

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#449]

**Comment by dtusar** [comment]
Added octave build.

**Comment by nikohansen** [comment]
Build or run?

**Comment by dtusar** [comment]
Build, run shouldn't be used on CI machines.

**Comment by brockho** [comment]
Why not? I thought that the `run` includes now a simple and quick integration test. Or is the idea to have only the builds run at each commit and the tests regularly (say every hour) because they are more costly?

**Comment by nikohansen** [comment]
I guess this is because of time concerns, but shouldn't we run at least a tiny test example (filtered suite, e.g. `"dimensions=2-3 function_idx=1-2 instance_idx=4"), which could run in a second?

**Comment by dtusar** [comment]
Maybe it only has the wrong name. In other languages we have options build, run in test. Options build and test are running on CI, but run is not, because does not delete the created folders afterwards. Is that not the case for octave?

**Comment by brockho** [comment]
I see. Good point with not deleting the folders. Then I will add a `test-octave` which does run a short example experiment and deletes the folder.
