### ISSUE TITLE
easiest target

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#451]
There should not be an easiest target hard coded in the logger.

**Comment by ttusar** [comment]
Actually, we said that none of the targets should be read from a file. I'm on it.

**Comment by nikohansen** [comment]
Reading from a file has anyway the problem that you need to find the file, no?

**Comment by ttusar** [comment]
Sorry, I was not expressing myself accurately (again) - they are read from an array of values, which is stored in a separate file, I'm not actually reading from a file...

**Comment by ttusar** [comment]
This issue and #501 will be solved together.

**Comment by ttusar** [comment]
Done.
