### ISSUE TITLE
changes in the master branch

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#462]
<img width="340" alt="screen shot 2016-01-21 at 17 13 30" src="https://cloud.githubusercontent.com/assets/7316439/12486315/69746968-c062-11e5-9d1b-3b1903c1437b.png">

We do have a (small) problem with the master branch.

**Comment by brockho** [comment]
There seems to be something like `git revert dd61ab32` where `dd61ab32` is obviously the commit one wants to revert.

**Comment by nikohansen** [comment]
It somewhat won't help, because AFAICS it will add another commit, i.e. development will become 4 commits behind. AFAICS the content of master didn't change, only the commit history. I guess in the end it's just a cosmetic problem.
