### ISSUE TITLE
CI test of the bi-objective postprocessing

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#464]
The latest problems in our release have shown that we definitely need a CI test of the bi-objective postprocessing.

**Comment by nikohansen** [comment]
I implemented a provisional version line 506 in [`do.py`](https://github.com/numbbo/coco/blob/development/do.py) which can be uncommented if necessary.

**Comment by dtusar** [comment]
In order to add the test we need one bi-objective algorithm to be accessible on the http://coco.gforge.inria.fr server (similar as the single objective algorithms).

**Comment by dtusar** [comment]
This works now.
