### ISSUE TITLE
test coverage of post-processing

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#465]
a bi-objective data set should be part of the test coverage of the post-processing

**Comment by nikohansen** [comment]
See also #464

**Comment by brockho** [comment]
almost the same as #464

**Comment by brockho** [comment]
A simple random search data set (200*DIM many function evaluations) is available now at http://coco.gforge.inria.fr/data-archive/biobj-test/

**Comment by dtusar** [comment]
I don't what is the problem with this file, but on both windows slaves it's not extracted correctly (some files missing). Therefore the test fails on them. On linux and mac slaves and also on my computer it works fine.

**Comment by dtusar** [comment]
It was the problem of a too long path. I made a quick fix, but we should probably shorten the various names in the CI (like project name and computer name) because it all adds up when the build folder is created.
