### ISSUE TITLE
run-java issue on Ubuntu

### ISSUE THREAD

**Issue by dhadka** [numbbo/coco#466]
Running `python do.py run-java` on Ubuntu Linux has an error compiling the C code:

```
gcc -I /usr/lib/jvm/java-7-openjdk-amd64/include/ -I /usr/lib/jvm/java-7-openjdk-amd64/include//linux -o libCocoJNI.so -shared CocoJNI.c
/usr/bin/ld: /tmp/ccbup2Sl.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
```

Needed to add `-fPIC` to the gcc command on line 467 in `do.py`:

```
run('code-experiments/build/java', ['gcc', '-I', jdkpath1, '-I', jdkpath2, '-o', 
                           'libCocoJNI.so', '-fPIC', '-shared', 'CocoJNI.c'])
```

**Comment by nikohansen** [comment]
Thanks for the report! FTR, `-fPIC` stands for _Position Independent Code_, see
[here](http://stackoverflow.com/questions/6634387/c-statically-linked-shared-library). 
I guess we should add this in our next release?

**Comment by dtusar** [comment]
Solved by #468.

**Comment by dhadka** [comment]
Note that this likely affects all of the run-* scripts that need to compile shared objects on a system needing position independent code, although I only tested run-java thus far on Ubuntu Linux.

**Comment by nikohansen** [comment]
I am a dummy here, so wondering, which other languages have the position independent code concept adopted?

**Comment by dhadka** [comment]
Not sure, I can test them and provide feedback here.
