### ISSUE TITLE
Some errors for matlab experiment

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#469]
In code-experiments\build\matlab:
1) printf() in setup.m (line 44, 46) should be changed to sprintf()? because printf() does not work in Matlab.
2) The character " (quotation mark) in exampleexperiment.m does not valid for matlab 2013a.

**Comment by nikohansen** [comment]
Thanks for the report! We will try to take care of it. 

Which quotation mark is the problem? The one which is escaped with `\`?

**Comment by NDManh** [comment]
It seems that all the quotation mark since it is invalid character in Matlab.

**Comment by brockho** [comment]
The first part of your request should now be taken care of in the development branch (and soon in the next release). Thanks for reporting this.

For the second part, I would need more information about what works and what not with your Matlab, because the current version works with my Matlab2008b and I do not have another younger version available.

**Comment by nikohansen** [comment]
All right, I am just puzzled that this work with some Matlab versions...

Agreed, we should use single quotation marks.

**Comment by nikohansen** [comment]
@NDManh feel free to propose a fix via Github.

**Comment by NDManh** [comment]
I've tried to replace :
-----
suite_name = 'bbob-biobj'; % works for 'bbob' as well
observer_name = suite_name; 
observer_options = sprintf("result_folder: exdata/RS_on_%s \
                            algorithm_name: RS \
                            algorithm_info: \"A simple random search algorithm\" \
                            log_level: info", suite_name);
     

% dimension 40 is optional:
suite = cocoSuite(suite_name, "year: 2016", "dimensions: 2,3,5,10,20,40");
-------
by the following codes: 
-------
suite_name = 'bbob'; % works for 'bbob' as well
observer_name = suite_name; 
observer_options = ['result_folder: exdata/RS_on_bbob \',...
                    'algorithm_name: RS \',...
                    'algorithm_info: "A simple random search algorithm" \',...
                    'log_level: info'];
                
% dimension 40 is optional:
suite = cocoSuite(suite_name, 'year: 2016', 'dimensions: 2,3,5,10,20,40');
-------
then the exampleexperiment.m have crashed (matlab exits immediately) when running the command:
observer = cocoObserver(observer_name, observer_options);

I don't understand why?

**Comment by brockho** [comment]
Look at your `observer_option`. Most likely, you pass escape sequences like `\a` within the options.

**Comment by asmaatamna** [comment]
@NDManh: did you try to remove "/" from the result folder name? Maybe your problem comes from there?

**Comment by nikohansen** [comment]
@NDManh you can use \` to annotate code like
\`\`\`matlab
```matlab
suite_name = 'bbob-biobj'; % works for 'bbob' as well
observer_name = suite_name; 
observer_options = sprintf("result_folder: exdata/RS_on_%s \
algorithm_name: RS \
algorithm_info: \"A simple random search algorithm\" \
log_level: info", suite_name);

suite = cocoSuite(suite_name, "year: 2016", "dimensions: 2,3,5,10,20,40");

by the following codes:

suite_name = 'bbob'; % works for 'bbob' as well
observer_name = suite_name; 
observer_options = ['result_folder: exdata/RS_on_bbob \',...
'algorithm_name: RS \',...
'algorithm_info: "A simple random search algorithm" \',...
'log_level: info'];
suite = cocoSuite(suite_name, 'year: 2016', 'dimensions: 2,3,5,10,20,40');

then the exampleexperiment.m have crashed (matlab exits immediately) when running the command:
observer = cocoObserver(observer_name, observer_options);
```
\`\`\`

**Comment by nikohansen** [comment]
What strikes me is that some " look different than others, could this be an encoding problem?

**Comment by NDManh** [comment]
I have modified :
observer_options = ['result_folder: exdata/RS_on_bbob  ',...
                    'algorithm_name: RS  ',...
                    'algorithm_info: "A simple random search algorithm"  ',...
                    'log_level: info'];

(the output: 
observer_options =
result_folder: exdata/RS_on_bbob algorithm_name: RS algorithm_info: "A simple random search algorithm" log_level: info
)
and the problem is the same. 
@brockho : Could you let me know what the output is when you use 
observer_options = sprintf("result_folder: exdata/RS_on_%s \
                            algorithm_name: RS \
                            algorithm_info: \"A simple random search algorithm\" \
                            log_level: info", suite_name);

**Comment by nikohansen** [comment]
@NDManh you can display code using the accent grave \` character:
\`\`\`matlab
```matlab
observer_options = ['result_folder: exdata/RS_on_bbob ',...
'algorithm_name: RS ',...
'algorithm_info: "A simple random search algorithm" ',...
'log_level: info'];

(the output: 
observer_options =
result_folder: exdata/RS_on_bbob algorithm_name: RS algorithm_info: "A simple random search algorithm" log_level: info
)
and the problem is the same. 
@brockho : Could you let me know what the output is when you use 
observer_options = sprintf("result_folder: exdata/RS_on_%s \
algorithm_name: RS \
algorithm_info: \"A simple random search algorithm\" \
log_level: info", suite_name);
```
\`\`\`

**Comment by nikohansen** [comment]
I think the commata should not be there: `,...` should be `...`

**Comment by brockho** [comment]
I proposed a new version in the developmet branch. @NDManh: could you check whether it works for you now?

**Comment by NDManh** [comment]
I've tried with the proposed version and the program also has crashed when run the command : 
dimension = cocoProblemGetDimension(problem);

Maybe the input "problem" is not good. The info of 'problem' is : 
K>> problem

problem =

             74343424

**Comment by nikohansen** [comment]
Can you try this:
```matlab
% This script runs random search for 2*DIM function evaluations on 
% the biobjective 'bbob-biobj' suite.
% 
% An example experiment on the single-objective 'bbob' suite can be started
% by renaming the suite_name below.

more on; % to get immediate output in Octave


BUDGET = 2; % algorithm runs for BUDGET*dimension funevals
suite_name = 'bbob-biobj'; % works for 'bbob' as well
observer_name = suite_name; 

observer_options = strcat('result_folder: RS_on_', ...
                    suite_name, ...
                    ['algorithm_name: RS '...
                    'algorithm_info: "A simple random search" '...
                    'log_level: info']);

% dimension 40 is optional:
suite = cocoSuite(suite_name, 'year: 2016', 'dimensions: 2,3,5,10,20,40');
observer = cocoObserver(observer_name, observer_options);

disp(['Running random search on the ', suite_name, ' suite...']);
while true
    problem = cocoSuiteGetNextProblem(suite, observer);
    if (~cocoProblemIsValid(problem))
        break;
    end
    dimension = cocoProblemGetDimension(problem);
    my_optimizer(problem, cocoProblemGetSmallestValuesOfInterest(problem), ...
                 cocoProblemGetLargestValuesOfInterest(problem), BUDGET*dimension);
end
disp(['Done with ', suite_name, ' suite.']);
cocoObserverFree(observer);
cocoSuiteFree(suite);
```

**Comment by NDManh** [comment]
With above codes, the program cashes when running the command :
observer = cocoObserver(observer_name, observer_options);

**Comment by nikohansen** [comment]
OK, the " characters in the observer options need escapes, maybe.

**Comment by asmaatamna** [comment]
@NDManh: I think the problem comes from .c files (it's the case for me at least). You can try to change '''const size_t dims[2] = {1, 1};''' to '''const mwSize dims[2] = {1, 1};''' in cocoProblemGetDimension.c and run setup.m again.

**Comment by nikohansen** [comment]
@asmaatamna you can use the accent grave \` character to write code like change \``const size_t dims[2] = {1, 1};`\` to \``const mwSize dims[2] = {1, 1};`\`

**Comment by NDManh** [comment]
@nikohansen the same problem appears with : 
                                           'algorithm_info: \"A simple random search\" '...

**Comment by nikohansen** [comment]
Thanks can you try 
```
  'algorithm_info: A_simple_random_search '...
```
instead?

**Comment by NDManh** [comment]
@nikohansen Sorry but the problem is the same.

**Comment by nikohansen** [comment]
OK, thanks, then I think the problem is not the string :-)

**Comment by asmaatamna** [comment]
Related to commit #7a9faae22044aa587ee97b3f5b86108afd877cfe, ```mwSize``` should be changed to ```size_t``` everywhere (this is not done in lines 25 and 28 in ```cocoSuiteGetNextProblem.c``` for example). This causes warnings under both Octave and Matlab when running setup.m.

Also,  ```plhs[0] = mxCreateNumericArray(2, dims, mxINT32_CLASS, mxREAL);``` in ```cocoProblemGetDimension.c``` for example causes a warning: the second parameter of ```mxCreateNumericArray``` should be a ```mwSize```array but ```const size_t dims[2] = {1, 1};```. The declaration of ```dims```should be ```const mwSize dims[2] = {1, 1};```instead.

This being done, no more warnings from my side.

**Comment by nikohansen** [comment]
@asmaatamna, can you commit such that @NDManh can test?

**Comment by NDManh** [comment]
It does work in Matlab 2013a, so I close this issue.
