### ISSUE TITLE
Separate Permutation-transformations from Block-Diagonal Matrix transformations

### ISSUE THREAD

**Issue by oaelhara** [numbbo/coco#472]
Permutations and Block-Diagonal transformations should be applied independently. 
Also, implement the needed functions in corresponding files "transform_vars_permutation_helpers.c" and "transform_vars_blockdiag_helpers.c" and remove "large_scale_transformations.c".

**Comment by ttusar** [comment]
In addition, please make sure all functions are static (only the ones in the API should be public) and if you implement a general function, consider moving it to `coco_utilities.c`

**Comment by nikohansen** [comment]
See #438, can the `large_scale_transformations.c` file be deleted?

**Comment by oaelhara** [comment]
Yes, in the current version (in my fork), it is replaced by `transform_vars_blockrotation_helpers.c` and `transform_vars_permutation_helpers.c` and the two transformations (block-rotation and permutation) are completely independent from one another

**Comment by brockho** [comment]
Is this issue still open?

**Comment by oaelhara** [comment]
Yes, as long as the large-scale suite is not merged with the reste of the code which should probably note be done before the submission for the bi-obj workshop closes and we move into the next "development" phase.
