### ISSUE TITLE
precision of xopt for fschwefel 20

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#485]
The f-value for the hard-coded xopt best parameter value of the _raw_ function was more than `1.6e-12` off the true optimal value. Varying about the new `xopt` value in 2-D results in the shown f-values:
<img width="532" alt="screen shot 2016-01-23 at 16 18 15" src="https://cloud.githubusercontent.com/assets/7316439/12530873/01d41de4-c1ed-11e5-9bf8-453634a689ee.png">
<img width="572" alt="screen shot 2016-01-23 at 16 12 11" src="https://cloud.githubusercontent.com/assets/7316439/12530849/1e4e6b74-c1ec-11e5-8aaa-a0e4b45d04c8.png">
I didn't compute the impact on the final (scaled/transformed) version of the function. 
(OSX 10.9.5, Python 2.7.11)

see d7e5df4 for details.

**Comment by nikohansen** [comment]
@ttusar @asmaatamna , FYI, as you might be interested in this detail...

**Comment by ttusar** [comment]
How was the `xopt` value set in the first place?

**Comment by nikohansen** [comment]
To the left such that the f-value is about 500 times larger than y-range we are looking at (i.e. probably about a factor of `20~sqrt(500)` to the left of the x-range, see also the above commit link for the actual values.
