### ISSUE TITLE
development branch name change?

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#489]
I am working with git on a system shell and type all the time things like `git checkout development`. I would like to reduce this typing. git allows me to make an alias for checkout, `git co development`. But I don't see how to reduce the `development` part. If there is no other simple way, I would be in favor to rename the branch `development` to `develop`. It would be kind-of now or never, because renaming will irritate those who have already forked the repository.

**Comment by nikohansen** [comment]
Found a solution in that I can make a `git` alias for `cod` to mean `checkout development`.

**Comment by dtusar** [comment]
Are there any objections for this change?

**Comment by ttusar** [comment]
I'm fine with it, although if I understand @nikohansen correctly, he doesn't need it anymore...

**Comment by brockho** [comment]
Yes, I also understood @nikohansen in the same sense than @ttusar. If we want to shorten the branch name, however, do we go for `develop` or even to `devel` as in the CI?

**Comment by nikohansen** [comment]
Right, my need has dropped dramatically.

**Comment by dtusar** [comment]
Mine is still at zero, so I will just close this issue.

**Comment by nikohansen** [comment]
OK, the simplest way to deal with it is to rename the branch locally `git branch -m development dev`.
