### ISSUE TITLE
Errors about instance for bbob in Matlab

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#491]
In Matlab experiment, I found that when I added the "command disp(['Optimizing ', cocoProblemGetId(problem)]);" in the exampleexperiment.m as follows :
........
while true
    problem = cocoSuiteGetNextProblem(suite, observer);
    if (~cocoProblemIsValid(problem))
        break;
    end
    disp(['Optimizing ', cocoProblemGetId(problem)]);
    dimension = cocoProblemGetDimension(problem);
    my_optimizer(problem, cocoProblemGetSmallestValuesOfInterest(problem), ...
                 cocoProblemGetLargestValuesOfInterest(problem), BUDGET*dimension);
end
........
I got some infos not normal about instances such as "Optimizing bbob_f001_i51_d02", ..., "Optimizing bbob_f001_i60_d02"
>> exampleexperiment
Running random search on the bbob suite...
Optimizing bbob_f001_i01_d02
Optimizing bbob_f001_i02_d02
Optimizing bbob_f001_i03_d02
Optimizing bbob_f001_i04_d02
Optimizing bbob_f001_i05_d02
Optimizing bbob_f001_i51_d02
Optimizing bbob_f001_i52_d02
Optimizing bbob_f001_i53_d02
Optimizing bbob_f001_i54_d02
Optimizing bbob_f001_i55_d02
Optimizing bbob_f001_i56_d02
Optimizing bbob_f001_i57_d02
Optimizing bbob_f001_i58_d02
Optimizing bbob_f001_i59_d02
Optimizing bbob_f001_i60_d02
Optimizing bbob_f002_i01_d02
Optimizing bbob_f002_i02_d02
Optimizing bbob_f002_i03_d02
Optimizing bbob_f002_i04_d02
Optimizing bbob_f002_i05_d02
Optimizing bbob_f002_i51_d02
Optimizing bbob_f002_i52_d02
Optimizing bbob_f002_i53_d02
--more--

And also, the program stops at "--more--", and I have provide a character to continue.

**Comment by nikohansen** [comment]
@NDManh , you can format code using the "\`" character (accent grave), like
\`\`\`matlab
```matlab
while true
problem = cocoSuiteGetNextProblem(suite, observer);
if (~cocoProblemIsValid(problem))
break;
end
disp(['Optimizing ', cocoProblemGetId(problem)]);
dimension = cocoProblemGetDimension(problem);
my_optimizer(problem, cocoProblemGetSmallestValuesOfInterest(problem), ...
cocoProblemGetLargestValuesOfInterest(problem), BUDGET*dimension);
end
```
\`\`\`
You have to use exactly three of them. You can also use the preview tab above to check.

**Comment by brockho** [comment]
So what is wrong about the instances?

**Comment by brockho** [comment]
> And also, the program stops at "--more--", and I have provide a character to continue.
Did you also run the `more on;` command or just exactly what you wrote above?

**Comment by nikohansen** [comment]
I don't understand the issue. 

Re more: I assume the program continues running, just the output is buffered.

**Comment by NDManh** [comment]
@brockho : yes, I also run "more on;" (In fact, I just add only one command above in the original code)the issue for me is that before I only encounter for instance "bbob_f001_i05_d02" not such as "bbob_f001_i51_d02" where we have the instance "i51".

**Comment by brockho** [comment]
More or less, @nikohansen: in Octave, for example, the standard setting is to stop the execution after the first page of the screen is outputted (don't know why but this is the case under Windows for me). Hence, the `more on;` to prevent this. In my Matlab 2008b, the latter is already the default.

**Comment by brockho** [comment]
What exactly is your the problem with the instance 51? That's the setting for this year. Instances 1-5 and 51-60.

**Comment by NDManh** [comment]
@brockho  OK, I understand now we have more instances. However, I don't know why the program does not continue running (it seems to have a pause) when I add that command?

**Comment by brockho** [comment]
Solved by #492.

**Comment by NDManh** [comment]
@nikohansen  Thanks for the suggestion, I'll use it for the code in the next time.

**Comment by nikohansen** [comment]
It's somewhat a bug: `more on` should read `more off` (as in the old code), compare [here](http://fr.mathworks.com/help/matlab/ref/more.html). Thanks for catching it.

**Comment by brockho** [comment]
@nikohansen: why did you reopen the issue?

**Comment by nikohansen** [comment]
See last comment.

**Comment by brockho** [comment]
But also see my older comment "Solved by #492."

**Comment by brockho** [comment]
In any case: @NDManh thanks for catching the bug. I close the issue now (again).

**Comment by nikohansen** [comment]
ah, sorry.
