### ISSUE TITLE
superfluous warning from `import bbob_pproc`

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#493]
```
In [3]: import bbob_pproc as pp
/Users/hansen/anaconda/lib/python2.7/site-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)

```

Not nice when calling from within a Python shell.

**Comment by brockho** [comment]
I don't get this warning on my Windows 7 with Anaconda.

**Comment by nikohansen** [comment]
The reason might be that I import `matplotlib`-related stuff by default via `.pythonrc`.

**Comment by brockho** [comment]
Due to the time constraints before the v1.0 release, this low-priority issue was postponed to after the v1.0 release.

**Comment by brockho** [comment]
Maybe related to #693 and for sure to #1353 as well.

**Comment by nikohansen** [comment]
I just checked that I see this only when I have activated the `%pylab` mode, which makes perfectly sense. It seems that `matplotlib.use()` should be only be called conditionally or not at all.

**Comment by brockho** [comment]
If we really need the "Agg" backend, maybe the second answer here 
https://stackoverflow.com/questions/3285193/how-to-switch-backends-in-matplotlib-python
can be of help?

**Comment by nikohansen** [comment]
Using `warn=False` may be a workaround possibly however with surprises if a "wrong" backend was alreay active.

**Comment by brockho** [comment]
This issue looks like it will become a "won't fix" at some point in time.
