### ISSUE TITLE
Global f_gallagher_peaks get overwritten when f_gallagher is called a second time

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#500]

**Comment by ttusar** [comment]
The reason for having `f_gallagher_peaks` as a global variable in the first place is that they are used in the `f_gallagher_compare_doubles` function, which is a comparison function used in `qsort` and has a predefined format. The question is how to use `f_gallagher_peaks` for sorting without having a global variable.

**Comment by asmaatamna** [comment]
Couldn't we just:
1. add ```gallagher_peaks``` to the data structure
2. change ```f_gallagher_compare_doubles``` to something like
```
static int f_gallagher_compare_doubles(const void *a, const void *b) {
  double temp = *(const size_t *) a - *(const size_t *) b;
  if (temp > 0)
    return 1;
  else if (temp < 0)
    return -1;
  else
    return 0;
}
```
3. change ```qsort(rperm, number_of_peaks - 1, sizeof(size_t), f_gallagher_compare_doubles);``` to ```qsort(data->gallagher_peaks, number_of_peaks - 1, sizeof(size_t), f_gallagher_compare_doubles);```
?

**Comment by asmaatamna** [comment]
(the last point should be "3". I don't know why it displays "1"...)

**Comment by ttusar** [comment]
This look simple, thanks :)

**Comment by asmaatamna** [comment]
You're welcome :) (no I'm wondering why we didn't do it like this from the beginning)

**Comment by ttusar** [comment]
@asmaatamna I thought it was too simple to be true... I don't think this will work.

The Gallagher peaks (`f_gallagher_peaks`) shouldn't be sorted by `qsort`, because we are trying to sort a permutation based on the Gallagher peaks, not the Gallagher peaks themselves (at least this is what I understand from the code). The `rperm` permutation that is being sorted is afterwards used for computing conditioning. 

Is `f_gallagher_peaks` just a container for random numbers or does it have a deeper meaning? Can you take a look?

**Comment by asmaatamna** [comment]
@ttusar yes, ```f_gallagher_peaks``` is just a container for random numbers.
Here's a possible solution to our problem:
1. we can define a structure that has two fields
```
typedef struct {
  double value;
  int index;
} value_index_t;
```
2. ```f_gallagher_compare_doubles``` would look like this
```
static int f_gallagher_compare_doubles(const void *a, const void *b) {
  double temp = (*(const value_index_t *) a)->value - (*(const value_index_t *) b)->value;
  if (temp > 0)
    return 1;
  else if (temp < 0)
    return -1;
  else
    return 0;
}
```
3. ```rperm``` would be an array of ```value_index_t``` and would be iniallized as
```
for (i = 0; i < number_of_peaks - 1; ++i)
    rperm[i]->value = f_gallagher_peaks[i];
    rperm[i]->index = i;
```
for example. Let me know what you think (maybe we can do it simpler...)

**Comment by ttusar** [comment]
If all we wish to do is create a random permutation, then there are simpler ways of doing it and I'm inclined to go this way: https://en.wikipedia.org/wiki/Fisher%E2%80%93Yates_shuffle

@asmaatamna, please confirm, I wouldn't want to break something...

**Comment by nikohansen** [comment]
Be aware that we want to be able to create exactly the same instances as those in the original benchmark.

**Comment by ttusar** [comment]
Forgot about this! Thanks.

**Comment by ttusar** [comment]
Done, closing the issue.
