### ISSUE TITLE
precision between target values

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#501]
One of the regrets of the previous experimental design was the precision/distance of/between the target values. From hindsight, I would have preferred to see at most `10**-0.1` as factor between two targets, rather than `10**-0.2`. I would suggest to make `10**-0.1` the default value for the `bbob-biobj` logger. The postprocessing should have a switch as to whether or not to ignore the additional target values (a good way to catch bugs arising from these additional data).

**Comment by ttusar** [comment]
This should be done for the `bbob` logger as well.

**Comment by oaelhara** [comment]
Ok.
Note that in the bbob case (single objective), this is passed as a parameter (nbpts_fval) of the observer observer_bbob() which defaults, for now, to 5. So a simple change of the default value should do the trick. I'll do it.

**Comment by ttusar** [comment]
I need to rewrite the way the targets are processed in the biobjective logger (they are currently fixed, but they should be created dynamically). Since for the biobjective case we don't know the true optimum, we also have some negative targets. How should I handle these now?

**Comment by ttusar** [comment]
These are some of the currently used fixed targets:

````
 0.000000100000000,
 0.000000079432823,
 0.000000063095734,
 0.000000050118723,
 0.000000039810717,
 0.000000031622777,
 0.000000025118864,
 0.000000019952623,
 0.000000015848932,
 0.000000012589254,
 0.000000010000000,
 0.000000000000000,
-0.000000010000000,
-0.000000100000000,
-0.000001000000000,
-0.000010000000000,
-0.000100000000000,
-0.001000000000000,
-0.010000000000000,
-0.100000000000000
````

**Comment by nikohansen** [comment]
A possible alternative:
```
 0.000000100000000,
 0.000000079432823,
 0.000000063095734,
 0.000000050118723,
 0.000000039810717,
 0.000000031622777,
 0.000000025118864,
 0.000000019952623,
 0.000000015848932,
 0.000000012589254,
 0.000000010000000,
 0.000000000000000,
-0.000000010000000,
-0.000000012589254,
-0.000000015848932,
-0.000000019952623,
-0.000000025118864,
-0.000000031622777,
-0.000000039810717,
-0.000000050118723,
-0.000000063095734,
-0.000000079432823,
-0.000000100000000,
-0.00000012589254,
-0.00000015848932,
-0.00000019952623,
-0.00000025118864,
-0.00000031622777,
-0.00000039810717,
-0.00000050118723,
-0.00000063095734,
-0.00000079432823,
-0.000001000000000,
-0.0000012589254,
...
```

**Comment by ttusar** [comment]
Ok

**Comment by nikohansen** [comment]
Given that the original choice of number of targets was driven by the size of the generated data (around 20MB), we might now reconsider the number of targets again, as the acceptable size has considerably changed.

**Comment by dtusar** [comment]
The post-processing already uses 10**-0.1 as factor between two targets in the bi-objective case. Do we really need the switch to ignore the additional targets?

**Comment by nikohansen** [comment]
AFAICS there is no need for any special treatment, the post-processing can read in all data and depending on the routine chooses some predefined targets.
