### ISSUE TITLE
Bi-objective Postprocessing should take into account only five instances for the moment

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#504]
For the BBOB-2016 workshop, the postprocessing should take into account only the first five instances (1-5) in the displays.

**Comment by dtusar** [comment]
How does the post-processing know if the run is for the workshop or not. Should the user decide with a specific flag?

**Comment by nikohansen** [comment]
It seems that for the moment we don't need a flag, because we cannot do meaningful plots of the other instances anyway?
