### ISSUE TITLE
Testing backwards compatibility

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#506]
Do we want to have a test on backwards compatibility in the CI? For example using a newly generated data set with the old svn-coco postprocessing?

**Comment by nikohansen** [comment]
I believe we decided for a (slight) change of the data format in the `biobj` logger. That is, we cannot expect the old code to work on these new data.

Using the old post-processing with data generated with the new `bbob` logger seems a useful test of the new observer, not directly related to backwards compatibility though, as the new observer should do the same as the original.

**Comment by nikohansen** [comment]
Speaking about compatibility, it seems more important that any future version of the post-processing can deal with any old data sets. I would not mind to make a format change, given it is reasonable and useful, even if it breaks installations of previous versions of the post-processing. Installing the latest post-processing version is only one or two command lines away. For this reason the purpose of testing backwards compatibility in this direction is not quite clear to me. On the other hand, I am all for having a clear and explicit specification for the precise format of the info and data files.

**Comment by brockho** [comment]
Conclusion of BBOB/COCO discussion of May 23, 2017: Probably more important than the test is the documentation of the data format.

**Comment by nikohansen** [comment]
To my understanding the main point here is to have another test as to whether a (new) logger still obeys the specification of how to write data.

**Comment by brockho** [comment]
Question: is this issue still important or can we close it? It seems that with the new data format of the `bbob-new` logger, the suggested test ("not breaking the old post-processing code with a newly generated data set") is less important than before from my viewpoint.

**Comment by nikohansen** [comment]
OK for closing it.
