### ISSUE TITLE
Warnings with warnings.warn(...)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#51]
```
how to get with warnings.warn(...) a reasonable amount of warnings? 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 16 Jun 2014 at 12:39

**Comment by brockho** [comment]
I suggest to close this issue as the number of warnings looks reasonable to me right now.

**Comment by dtusar** [comment]
I agree.
