### ISSUE TITLE
Code rewrite regarding TargetValues class

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#53]
```
class TargetValues should be used everywhere where target values are utilized 
and, if necessary, adapted accordingly. 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 16 Jun 2014 at 12:56

**Comment by brockho** [comment]
That's a quite old issue which looks solved to me. Shall we close it? Or shall we try to find out concretely where it still needs work?

**Comment by dtusar** [comment]
Yes, I think we can close it.
