### ISSUE TITLE
negative delta-f values in the post-processing

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#539]
For the new biobjective suite we don't know the true best indicator value. For this reason, negative delta-_f_ values could occur. 

We need to check how the post-processing is dealing with negative delta-_f_ values. See also #501 #451

**Comment by nikohansen** [comment]
How about generating an artificial `exdata` folder with many negative values, say, by computing the estimated best indicator value differently for a single experiment?

**Comment by dtusar** [comment]
Negative values do not produce any errors in the post-processing. But before we close this issue, we should also check for any anomalies in the plots/tables.

**Comment by dtusar** [comment]
Yesterday @brockho and I checked the plots and they looked OK. So, I'm closing this issue.
