### ISSUE TITLE
Error when postprocessing non-standard dimensions

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#54]
```
in ppfigdim, when the data contains dimensions other than the default [2, 3, 5, 
10, 20, 40], an error is raised due to the absence of said dimension in bestalg 
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 16 Jun 2014 at 12:58

**Comment by nikohansen** [comment]
See also #57

**Comment by oaelhara** [comment]
The error is now only raised in compall/pprldmany.py
The same way it's done with `isBiobjective`, we can simply set `displaybest2009` to `False` whenever
 `(dim, f) not in bestalgentries.keys()`
This allows to still show the comparison for the standard dimensions when a suite (say a large-scale suite which starts with `dim = 40`) contains both standard and non-standard dimensions.

**Comment by brockho** [comment]
@oaelhara: would you be so kind and check whether this issue is still present with the current postprocessing? @dtusar recently improved a lot the way the bestalg is displayed or not, depending on the available bestalg data, and this issue could be solved already by these changes.

**Comment by oaelhara** [comment]
This issue can be closed now. Any remaining errors can be discussed in #1247

**Comment by brockho** [comment]
As far as I can see, this issue can indeed be closed. I even postprocessed data from the `bbob-largescale` suite with some from the old `bbob` suite and the html output displays well for all dimensions all algorithms for which data is available (e.g. 1 algo for dimensions <20, 2 algos for dimensions 20 and 40, and again 1 algo for dimensions >40). Also increasing or decreasing the number of displayed dimensions via `testbedsettings.py` works now.
