### ISSUE TITLE
No Output in Matlab Experiment 

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#545]
When running `exampleexperiment.m` within the Matlab shell (Matlab 2008b under Windows XP), no output is displayed from the experiment (as produced directly from the C code). Under Octave, however, the information is displayed in the Octave window.

**Comment by ttusar** [comment]
This is curious... Are you using the latest version from the development branch?

**Comment by ttusar** [comment]
Sorry, of course you are, otherwise you wouldn't be getting the output in Octave.

**Comment by ttusar** [comment]
The `info` messages are directed to `stdout`, while the `warning` end `error` ones are written to `stderr`. Maybe Matlab only outputs the `stderr`...

**Comment by tobiaswagner** [comment]
http://stackoverflow.com/questions/26271154/how-can-i-make-a-mex-function-printf-while-its-running

**Comment by NDManh** [comment]
Just a report: for newer version Matlab 2013 in window 10, it is not improved.

**Comment by brockho** [comment]
Solved by pull-request #619 with my Matlab 2008. @NDManh: could you please check whether this also works now in your Matlab 2013? If yes, we can finally close the issue.

**Comment by NDManh** [comment]
@brockho : It works well in Matlab 2013a! :-) and just a small remark about ```printf('Done\n');``` (line 9 in setup.m). It should be replaced by ```fprintf('Done\n');```?

**Comment by brockho** [comment]
@NDManh: thanks for testing and for pointing out the `printf` problem. It is solved now with the newest commit.

Issue closed.
