### ISSUE TITLE
A "log_level" kind of option for do.py

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#554]
It would be nice to have the possibility of choosing the amount of output produced by `do.py`. When everything is running smoothly, the current output seems unnecessary. When debugging, it would be nice to be able to see compiler warnings and such. Three logging levels should do the trick.

**Comment by nikohansen** [comment]
Now there is a `silent ...` command, which runs the `...` silently, if no error occurs. 

E.g. 
```
python do.py silent run-c
```
I don't see there is a general trick to add verbosity. It would probably be added in the `make()` function of `cocoutils`.

**Comment by nikohansen** [comment]
If this needs to be addressed further, I suggest to open another issue, based on the current situation.

**Comment by ttusar** [comment]
Thank you!

**Comment by dtusar** [comment]
@nikohansen I would like to output a message from a post processing test. How can I do that? Is there a way to avoid the suppression of the message?

**Comment by nikohansen** [comment]
@dtusar sorry, I have no idea.
