### ISSUE TITLE
Decision about final targets for bbob-biobj

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#557]
We eventually need to decide about which targets we actually record and display for the bi-objective experiments with the `bbob-biobj` suite.

**Comment by nikohansen** [comment]
Part of this decision is to set the virtual optimal indicator value. I would suggest to look at various experiments before to make these decisions. See also #501.

**Comment by nikohansen** [comment]
Here is another, I believe pretty useful, proposal for choosing the target values. We take the hyper-volumes associated with the reference set in the following way: the maximum hyper-volume of a subset of `10^i` points of the reference set for, e.g. `i=0, 1, 2,...` or `i=0, 1/4, 2/4, 3/4, 4/4, 5/4,...` or..., depending on how many targets we want to look at.

**Comment by tobiaswagner** [comment]
Sounds interesting. It’s definitely worth a try.

**Comment by nikohansen** [comment]
The questions remains whether this should be done already on the logger level, or whether this is (only) done on the post-processing side. I believe to decide this question, we should first look at the actual target values, which are generated by this method.

**Comment by ttusar** [comment]
Why is `dimension` included in there?

**Comment by nikohansen** [comment]
Because run-length is typically at least linear in the dimension, that is, if we want to have a comparable number of targets for each dimension we must multiply by dimension, possibly even with a larger factor, depending on the function.

**Comment by nikohansen** [comment]
After some discussion: the targets generated like this are already comparatively difficult. To proceed on the current displays, it might be sufficient to make a simple selection on the already recorded targets, in particular choosing the first and last target more carefully.

**Comment by nikohansen** [comment]
Some data that should be helpful to proceed to find the targets we want to display: 
- (the statistical median of) the HV of `[1, 10, 100, 1000]` random samples uniformly distributed in the search space.
- the nadir HV
- the best HV from [1, 10, 100, 1000, 10000] points of the reference set
- the HV of the reference set

**Comment by ttusar** [comment]
The hypervolume is always normalized with respect to the ideal and nadir points, so nadir HV = 0.

**Comment by nikohansen** [comment]
I know, a single value in this list remains entirely useless ;-) but already the second value arriving will start to be of some use...

**Comment by ttusar** [comment]
@nikohansen, I need some help with the python interface, could you have a look (see this branch: https://github.com/ttusar/coco/tree/feature-mo)?

I'm trying to perform merging of archives (by running `archive_update.py`, which uses the `Archive` class). In addition to the "true" `Archive` class that is defined in the `archive.pyx` interface file and is calling some functions implemented in C, I made a "mock" `Archive` class in the  `archive_mock.py` file. If I use the mock, everything works as it should, while if I use the interface file, I keep getting:
```python
  File "C:\Anaconda\lib\distutils\msvc9compiler.py", line 271, in query_vcvarsall
    raise DistutilsPlatformError("Unable to find vcvarsall.bat")
ImportError: Building module archive failed: ['DistutilsPlatformError: Unable to find vcvarsall.bat\n']
```

I am able to compile `archive.pyx` with cython without any problems using the `setup.py` file. 

I'm not sure whether I'm doing something wrong or this is a Windows problem...

In addition, while the other things in `archive.pyx` "should work", I don't know how to handle the call to the C function `coco_archive_get_next_solution_text()` in `get_next_solution_text()`. I need to catch the case when the C function returns `NULL` and return `None` when this happens, but don't know how and would appreciate some help.

**Comment by nikohansen** [comment]
The first looks like a Windows problem, [this](https://github.com/conda/conda-build/pull/314) or [this](http://www.scriptscoop.net/t/7a1576bcdd77/pyproj-with-pyhton-2-7-9-on-win7-64-gives-unable-to-find-vcvarsall-bat.html) might give a hint how to solve it.

**Comment by nikohansen** [comment]
Re calling a `C` function: I am by no means experienced or an expert, but I believe you can just assign the output value to a variable, a `Python` or `C` variable, whichever you like best. Did you have a look at the `build/python/cython/interface.pyx` file? It does stuff like `return coco_problem_get_name(self.problem)`, which returns a Python `str`.

**Comment by nikohansen** [comment]
I am in the process to gather some results on random search. To dominate the domain middle takes on average around ten evaluations on some instances of `bbob-biobj_f55_ixx_d10` or `bbob-biobj_f52_ixx_d10` and a million on a different instance of `bbob-biobj_f52_ixx_d10`. That is not good news, however it seems much less diverse on many (most?) other functions.

**Comment by nikohansen** [comment]
Run-length distribution of `random search in [-4, 4]^n` to dominate the domain middle point, `[0]^n`, taken over all problems: 
<img width="544" alt="screen shot 2016-02-23 at 1 51 37" src="https://cloud.githubusercontent.com/assets/7316439/13238077/c7d0c6f0-d9d0-11e5-9f6c-113899b715c2.png">

**Comment by nikohansen** [comment]
These are the current settings: 
```python
        self.ppfigs_ftarget = 1e-4
        self.ppfigdim_target_values = targetValues((1, 1e-1, 1e-2, 1e-3, 1e-5)) # possibly changed in config
        self.pprldistr_target_values = targetValues((1e-1, 1e-3, 1e-5)) # possibly changed in config
        self.pprldmany_target_values = targetValues(10**np.arange(0, -5, -0.2)) # possibly changed in config
        self.rldValsOfInterest = (1e-1, 1e-3, 1e-5) # possibly changed in config
        self.ppfvdistr_min_target = 1e-5
```

**Comment by nikohansen** [comment]
I suggest to change at least 
```python
self.pprldmany_target_values = targetValues(10**np.arange(0, -5, -0.1))
```
but I am pretty sure there should be more changes.

**Comment by brockho** [comment]
I agree with you. Independently, I have suggested something very similar in my fork (see https://github.com/brockho/numbbo/blob/dimo-develop/code-postprocessing/bbob_pproc/genericsettings.py) but did not yet commit to the development branch. One reason are the tests which currently run on the CI, the second is that I did not finish the LaTeX template and I hesitated whether I should commit this before finishing.

I actually suggest to use
```
self.pprldmany_target_values = targetValues(10**np.arange(0, -5.1, -0.1))
```
such that `10^{-5}` is included as target.

**Comment by brockho** [comment]
genericsettings.py has now been updated in one of the previous commits in the development branch and the suggested targets seem stable from my side for the figures (I guess also from @nikohansen's side?). What remains is most likely only #706. Can the issue therefore be closed now?

**Comment by nikohansen** [comment]
Fine by me.
