### ISSUE TITLE
make.py fails on Windows

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#558]
When calling `python do.py build-c` in the `coco` folder everything seems to be ok, but the executable files are not created. When calling `python make.py` in the `build/c` folder, the following text is displayed:

````
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o coco.o coco.c
'cc' is not recognized as an internal or external command, operable program or batch file.
cc -c -g -ggdb -std=c89 -pedantic -Wall -Wextra -Wstrict-prototypes -Wshadow -Wno-sign-compare -Wconversion -o example_experiment.o example_experiment.c
'cc' is not recognized as an internal or external command, operable program or batch file.
cc -o example_experiment coco.o example_experiment.o  -lm
'cc' is not recognized as an internal or external command, operable program or batch file.
````

**Comment by brockho** [comment]
I cannot confirm this problem on my Windows machine (Windows 7 64bit with MinGW and GNU make, but without any Cygwin!). Both calling the `build-c` via `do.py' and calling `python make.py` in the `code-experiments/build/c` folder create runnable `.exe` files. The problem seems to be caused by the Cygwin installation.

**Comment by ttusar** [comment]
Yes, sorry, I should have specified this happens on Windows with cygwin...

**Comment by brockho** [comment]
Don't be sorry - it could have been a general Windows problem. Hence good that we tested it on both and know more now already.

**Comment by nikohansen** [comment]
I guess we need to find out what `${CC}` is supposed to be on `cygwin`. Unfortunately my knowledge of this is limited.

**Comment by nikohansen** [comment]
In case we do not find a solution we can go back to `make` with a minimal change in `do.py`.

**Comment by ttusar** [comment]
On my computer it works with:
````
CC = os.environ.get('CC', 'cc', 'gcc'),
````
but it works also if I delete this whole line.

**Comment by ttusar** [comment]
The second variant (deleting the line) could be a more general solution... Any thoughts before I commit the change?

**Comment by nikohansen** [comment]
`CC = os.environ.get('CC', 'cc', 'gcc')` should raise an exception. If "it works", I would consider it as a semi-bug. 

Removing the line doesn't work on the Mac. 

If there isn't an obvious solution, would suggest we go back to using `make` for the time being. For users who use `C` this shouldn't be a big deal anyway.

**Comment by ttusar** [comment]
@nikohansen Have you seen this: https://code.google.com/archive/p/fabricate/

**Comment by nikohansen** [comment]
No, I only found `SCons`, 'doit', and other apparently more complex tools when googling :-(

**Comment by nikohansen** [comment]
`make.py` isn't used anymore, so I guess this can be closed.

**Comment by nikohansen** [comment]
Copy paste of an example using `fabricate`, just FTR:
```python
from fabricate import *

sources = ['program', 'util']

def build(): 
    compile() 
    link()

def compile(): 
    for source in sources: 
        run('gcc', '-c', source+'.c')

def link(): 
    objects = [s+'.o' for s in sources] 
    run('gcc', '-o', 'program', objects)

def clean(): 
    autoclean()

main() 
```
Not sure this can work out-of-the-box.
