### ISSUE TITLE
const qualifier for get_evaluations

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#563]
Shouldn't this
```c
size_t coco_problem_get_evaluations(coco_problem_t *problem);
```
rather read 
```c
size_t coco_problem_get_evaluations(const coco_problem_t *problem);
```
?

I get a compiler warning, because I pass a `const coco_problem_t *problem` to `coco_problem_get_evaluations`.

**Comment by ttusar** [comment]
Yes, I somehow failed to push this to the development branch... Doing it now.
