### ISSUE TITLE
Dependencies under Windows

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#572]
The [readme here](https://github.com/numbbo/coco/blob/development/README.md) suggests a dependency on `make` under Windows. I believe that this dependency exists only if experiments are run in `C`.

**Comment by nikohansen** [comment]
I changed the readme, the changes should be confirmed by someone.

**Comment by brockho** [comment]
Thanks for changing the documentation with this respect, @nikohansen. I can confirm that `build-java`, `build-python`, `build-matlab`, and `build-octave` do not depend on `make` under Windows (and also should not on any other operating system).

Issue can therefore be closed.
