### ISSUE TITLE
Build octave fails on mingw slave

### ISSUE THREAD

**Issue by dtusar** [numbbo/coco#578]
If I try this directly on the slave from command line I get this error:
octave-gui.exe - The procedure entry point __gmpn_cnd_add_n could not be located in the dynamic link library libgmp-10.dll.

Error from Jenkins:

Started by upstream project "Coco-experiments-test1-windows-mingw-octave" build number 12
originally caused by:
 Started by user 
Building remotely on numbbo-win32bitwithjremingw in workspace C:\builds\workspace\Coco-experiments-test1-windows-mingw-octave\dotype\build-octave\label\numbbo-win32bitwithjremingw
 > git rev-parse --is-inside-work-tree # timeout=10
Fetching changes from the remote Git repository
 > git config remote.origin.url https://github.com/numbbo/coco/ # timeout=10
Fetching upstream changes from https://github.com/numbbo/coco/
 > git --version # timeout=10
using GIT_SSH to set credentials 
using .gitcredentials to set credentials
 > git config --local credential.username NumbboCI # timeout=10
 > git config --local credential.helper store --file=\"C:\Users\ci\AppData\Local\Temp\git7034633575240892452.credentials\" # timeout=10
 > git -c core.askpass=true fetch --tags --progress https://github.com/numbbo/coco/ +refs/heads/*:refs/remotes/origin/*
 > git config --local --remove-section credential # timeout=10
Checking out Revision a73565671282ad9896e6a6f4aaaa8bb56f51f7f0 (refs/remotes/origin/devel-test1)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f a73565671282ad9896e6a6f4aaaa8bb56f51f7f0
 > git rev-list 7ea0daa4cf4aa65ce07c6df99c94312e942bdb43 # timeout=10
[numbbo-win32bitwithjremingw] $ cmd /c call C:\Users\ci\AppData\Local\Temp\hudson2567466428306559063.bat

C:\builds\workspace\Coco-experiments-test1-windows-mingw-octave\dotype\build-octave\label\numbbo-win32bitwithjremingw>python do.py build-octave 
AML	['code-experiments/src/coco_random.c', 'code-experiments/src/coco_suite.c', 'code-experiments/src/coco_observer.c', 'code-experiments/src/coco_runtime_c.c'] -> code-experiments/build/matlab/coco.c
COPY	code-experiments/src/coco.h -> code-experiments/build/matlab/coco.h
WRITE	code-experiments/build/matlab/REVISION
WRITE	code-experiments/build/matlab/VERSION
RUN	octave --no-gui setup.m in code-experiments/build/matlab
ERROR: return value=-1073741511

Traceback (most recent call last):
  File "do.py", line 686, in <module>
    main(sys.argv[1:])
  File "do.py", line 659, in main
    elif cmd == 'build-octave': build_octave()    
  File "do.py", line 410, in build_octave
    run('code-experiments/build/matlab', ['octave', '--no-gui', 'setup.m'])
  File "C:\builds\workspace\Coco-experiments-test1-windows-mingw-octave\dotype\build-octave\label\numbbo-win32bitwithjremingw\code-experiments\tools\cocoutils.py", line 103, in run
    universal_newlines=True)
  File "C:\Anaconda\lib\subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['octave', '--no-gui', 'setup.m']' returned non-zero exit status -1073741511

C:\builds\workspace\Coco-experiments-test1-windows-mingw-octave\dotype\build-octave\label\numbbo-win32bitwithjremingw>exit 1 
Build step 'Execute Windows batch command' marked build as failure

**Comment by brockho** [comment]
Might be related to a known issue: `octave` has to be run first once in the same shell where `python do.py build-octave` is run. I am already working on a fix where we will provide our own `octave-coco.bat` file for Windows that does not mess anymore with the Windows path.

**Comment by dtusar** [comment]
Was there any change since two days ago when this worked?

**Comment by dtusar** [comment]
This was fixed.
