### ISSUE TITLE
Update logger_bbob and observer_bbob

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#591]
The C code has evolved quite a bit in the last months, while `logger_bbob` and `observer_bbob` have been left behind. The most important things to do are:
- Remove all global variables from `logger_bbob`. These can put in an `observer_bbob_data_t` object instead. If this is handled differently and there is no need for an `observer_bbob_data_t` object, the `observer_bbob_data_t` type should be removed.
- Resolve the many (10+) TODOs still left the code (most should be easy to do because of the redefinition of observers and the introduction of observer options).
- Use `precision_x` and `precision_f` from `coco_observer` when outputting double values.
- Document the file in doxygen style. 

The triggers for logging in `dat` and `tdat` files have already been updated to use the new trigger functions from `coco_observer.c`.

**Comment by oaelhara** [comment]
Is there a way the observer can, beforehand, know the total number of dimensions (have access to the suite options)? 
In the documentation of the structure coco_observer_s, it's stated that the observer is independent of the suite.

**Comment by ttusar** [comment]
This is a tough one... There are two ways to wrap a problem with the observer's logger:
- coco_suite_hetproblem_

**Comment by ttusar** [comment]
I guess we would also need a getter `coco_problem_get_suite` that checks that the pointer to the suite is not NULL, before returning it...

**Comment by nikohansen** [comment]
As a general rule it is better to implement and use getter functions, because it allows to make changes to the underlying structure without breaking (much of the) code.

**Comment by brockho** [comment]
Removed the issue from the v0.9 milestone as it is not critical.

**Comment by nikohansen** [comment]
Is already available in the Python interface as `suite` attribute (property) of the problem instance.

**Comment by ttusar** [comment]
Additionally, the reimplementation of the bbob logger should support logging of values better than the optimum (needed for real-world and bi-objective scenarios where the optimum can be unknown in advance)

**Comment by brockho** [comment]
Discussed today with @ttusar, @olafmersmann and @nikohansen: can be closed.
