### ISSUE TITLE
evaluate json whether it could replace pickle

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#60]
```
pickle is not human-readable and can be a security issue. 

One question is whether (g)zipped json files meet our storage and performance 
demands. In particular, do they actually improve over just reading the gzipped 
raw data? 
```

Original issue reported on code.google.com by `nikolaus...@gmail.com` on 20 Jun 2014 at 10:38

**Comment by brockho** [comment]
As for now all data sets are already provided in textfile format (`.info`, `.dat`, `.tdat`, ...) only and the `bestalg` files are in the transition to become also human-readable in the same format, I will close this issue.

**Comment by nikohansen** [comment]
Just for clarification: these are _zipped_ text files, right?
