### ISSUE TITLE
sharing result views

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#608]
We are facing constantly the situation, that someone talks about a result which the other person in the communication does not see, see e.g. #600. Hence, a simple and quick way to pass around views on results is desired. 

Out of my head I could think of this:

```
python -m bbob_pproc push ppdata-output-folder
    ...folder pushed to 2016-Feb-22-22h22m22-ppdata-output-folder.gzip
```

and

```
python -m bbob_pproc pull 2016-Feb-22-22h22:22-ppdata-output-folder.gzip
```

while the latter downloads a zip file, unzips the file and opens `2016-Feb-22-22h22m22-ppdata-output-folder/index.html` in the browser.

**Comment by brockho** [comment]
see also #1618

**Comment by nikohansen** [comment]
How could we deal with the problem that pushing data usually needs to have specific access rights?

Reviewing this issue, it seems to me that the pusher/publisher could and should just use a tool independently of COCO and then everybody can download or (preferably) browse the data?

**Comment by brockho** [comment]
I also don't see how we can deal with access rights in Coco. What would be sufficient is the functionality to produce the data archive locally and to access it remotely - the copying of the data from a user's local storage to the server should be dealt with outside COCO.

**Comment by brockho** [comment]
Decision of today: we open a new issue where we start collecting the links towards postprocessed data, we have (in particular on the GForge server).
