### ISSUE TITLE
virtual dream-best biobjective algorithm

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#624]
Pursuing the idea to find normative reference target values. 

Assume we have given a problem and its non-dominated reference set. From this we want to generate a pseudo-`DataSet`, a best-algorithm or reference algorithm data set. This data set maps each number between `1` and `|reference set|` to the largest hyper-volume achievable with a subset of the reference set with the respective size. 

We need to work out (from the implementation perspective) how such a data set should be constructed such that it can be used to compute run-length-based target values like with `pproc.RunlengthBasedTargetValues`.

**Comment by ttusar** [comment]
Does the fact that the reference set will change year after year (mostly by getting larger, although not always) represent any problem for comparing algorithms from different years?

**Comment by nikohansen** [comment]
Yes, of course it does. Ideally we would use the pareto-set, instead of the current reference set.

**Comment by nikohansen** [comment]
The idea here is to construct realistic target values over a wider range. Currently, we use only the best ever observed hyper-volume from experimental data, but construct all other targets somewhat blindly.

**Comment by nikohansen** [comment]
A less involved approach: compute only the first (and last) of the above targets, and all other values independently of the problem.

**Comment by nikohansen** [comment]
After some discussion: values generated with the above method tend to be already quite difficult. 

For the time being it might be sufficient to have a method to choose the largest and the smallest target of interested for the display.

**Comment by ttusar** [comment]
Maybe you have already considered this in your discussion, but just in case: if the targets are set as proposed, we cannot assure that the curves of target achievements will be always monotonically increasing.

**Comment by nikohansen** [comment]
> we cannot assure that the curves of target achievements will be always monotonically increasing.
I don't understand this remark. The created target HV values are AFAICS monotonous in the number of points: adding a point can never decrease the HV. So maybe I don't understand what _curves of target achievements_ means.

**Comment by ttusar** [comment]
Adding a point does not increase the HV, but we are measuring the HV difference, and this can become worse in this case (i.e. it can increase, which means the curve that shows how many targets are reached by an algorithm can decrease in time).

**Comment by nikohansen** [comment]
> Adding a point does not increase the HV

I still don't follow. Adding a point to a set can never worsen the HV indicator of this set. Can you give a counter example?

**Comment by ttusar** [comment]
Typo, sorry, I meant decrease.

**Comment by nikohansen** [comment]
You can edit your comments. I still do not get at all what your post of -7h is talking about, because, AFAICS, the indicator value of a set is monotonous in adding points to the set.

**Comment by ttusar** [comment]
FTR, we clarified the misunderstanding over skype :)
