### ISSUE TITLE
post-processing multiple algorithms asserts

### ISSUE THREAD

**Issue by TGlas** [numbbo/coco#625]
I have run two algorithms, both in 5 dimensions. I can run post-processing for both individually with the current development branch (11.2.2016). However, if I try post-processing with the results of both algorithms in the exdata folder then I get an assertion. The error message is as follows:

```
$ python2 -m bbob_pproc exdata
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/exdata
  this might take several minutes.
  Data consistent according to test in consistency_check() in pproc.DataSet
/Users/tobi/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungeneric1.py:318: UserWarning: Data with multiple algId [('mytest', '% mytest'), ('MOCMA', '% Shark Default Implementation')] will be processed together.
  'will be processed together.')
Scaling figures...
Traceback (most recent call last):
  File "/Users/tobi/anaconda/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/tobi/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/tobi/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/__main__.py", line 287, in <module>
    rungeneric.main(args)
  File "/Users/tobi/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungeneric.py", line 282, in main
    + ["-o", outputdir, alg])
  File "/Users/tobi/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/rungeneric1.py", line 349, in main
    outputdir, genericsettings.verbose)
  File "/Users/tobi/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/ppfigdim.py", line 531, in main
    plot(dictFunc[func], _valuesOfInterest, styles=styles)  # styles might have changed via config
  File "/Users/tobi/.local/lib/python2.7/site-packages/bbob_pproc-0.0.0-py2.7.egg/bbob_pproc/ppfigdim.py", line 359, in plot
    assert len(dictFunc[func][dim]) == 1
AssertionError

```

**Comment by dtusar** [comment]
Usually you have to specify separately the path to each algorithm, e.g. python2 -m bbob_pproc exdata/alg1 exdata/alg2. I think that we don't support the case when you specify just one path for multiple algorithms.

**Comment by nikohansen** [comment]
Agreed. That means the thrown error should not be an assertion error, because it is a case to be expected to appear on non-compliant user input.

**Comment by TGlas** [comment]
Thanks for the clarification. Specifying the algorithms individually works. However, this feels inconsistent, because for a single algorithm I can specify the exdata directory, for multiple algorithms the same fails. I'd like to propose to simply scan the directory to simulate the effect of python2 -m bbob_pproc exdata/* .

There is another small bug, in case of processing multiple algorithms the links to the single algorithm data in index.html are broken: the link text is empty (therefore not clickable), and the href starts with a slash (absolute path), therefore the link would not work, even if it was clickable.

**Comment by nikohansen** [comment]
> I'd like to propose to simply scan the directory to simulate the effect of python2 -m bbob_pproc exdata/* .

The problem with this is the following: the user is allowed to distribute data from the same algorithm into several subfolders (and even subsubfolders). This interface would be broken if we would scan the folder for subfolders and feed each as if it came from a different algorithm. We could make an exception on the folder name `exdata`. I am not if this is too much of a hack though.

**Comment by nikohansen** [comment]
FTR, I added the bug label because the 

> raised error should not be an assertion error

**Comment by TGlas** [comment]
Agreed, a constructive diagnostic message would do the job.

**Comment by dtusar** [comment]
An error with the explanation is now raised.
