### ISSUE TITLE
Reference point as part of an bi-objective problem

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#628]
Following up a discussion with TGlas, we should consider to add an assessment reference point (ARP) to the problem interface thereby defining an assessment area. Then, solutions that do _not dominate_ the ARP, which are therefore outside of the assessment area, will have no effect on the performance assessment. In other words, solutions that do not satisfy a minimum requirement in each objective "don't count". 

Rationale: the optimum for a single objective, i.e. the extreme point of the pareto front, is often an entirely useless solution from the practitioners perspective, because it is too bad in the other objectives. Otherwise we would not have a multi-objective problem in the first place. 

This question does not generalize to the single-objective case, because a solver will quickly pass a reference value and never look back, because there is no trade-off between objectives.

Implementation: 
- the problem- and instance-dependent information about the setting of the ARP must be passed to the post-processing, i.e. written into the info files (f-values or indicator values?)
- for the normalized HV indicator with value zero in the nadir point, a uniform distribution between 0.1 and 1.1 to set the value of the ARP in each objective comes in mind.

**Comment by ttusar** [comment]
Is here implicitly assumed that until we get to the first point that dominates the ARP, we log the distances to the assessment area (as we have been doing now for the ROI)?

**Comment by ttusar** [comment]
> a uniform distribution between 0.1 and 1.1 to set the value of the ARP comes in mind.

I don't understand this - would we have more than one ARP?

**Comment by ttusar** [comment]
Also, does this mean that the reference indicator values need to be recomputed w.r.t. the ARP?

**Comment by nikohansen** [comment]
> I don't understand this - would we have more than one ARP?

For each problem instance one, with as many elements as number of objectives. 

It needs to be discussed whether the ARP should be more similar over all instances of a single problem.

**Comment by nikohansen** [comment]
> Also, does this mean that the reference indicator values need to be recomputed w.r.t. the ARP?

The set of targets of interest apparently would depend on the ARP. Renormalizing the indicator values seems confusing to me.

**Comment by nikohansen** [comment]
> Is here implicitly assumed that until we get to the first point that dominates the ARP, we log the distances to the assessment area (as we have been doing now for the ROI)?

In some way the distance to ARP is meaningless, because it is by definition not part of the assessment. Having said that, I do like the idea that introducing ARP would change anything in how we log data or compute the indicator values. It seems however that we need indeed log an additional bit of information, namely whether a solution is in the ARP. I don't like this too, but is there a way out?

**Comment by nikohansen** [comment]
The added value of this feature is in the end rather unclear, so the issue can IMHO be close.
