### ISSUE TITLE
aggregated ECDFs for single functions

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#629]
The empirical run-length distributions aggregated over a wide range of target values have become one of our main tools (if not _the_ main tool) to assess performance, together with scaling vs dimension graphs. These graphs however are usually only generated when algorithms are compared. This should change. 

In the single-algorithm display, we should consider to have 
- one figure for each function with one graph for each dimension.
- (less important) one figure for each dimension with one graph for each function, displaying either all functions or a subgroup of functions, depending on the size of the benchmark suite.

**Comment by nikohansen** [comment]
We also want to be able to do aggregations in the same graphs (technically this should be comparatively simple). For example, we definitely want to aggregate over all problems (all targets) with the same dimension, thereby presenting all data in 5 or 6 graphs (one per dimension) in a single figure.

**Comment by nikohansen** [comment]
This is a super critical issue now, as we still cannot look at the graphs we consider the most important ones.

**Comment by dtusar** [comment]
> One figure for each function with one graph for each dimension.
This part is done.

**Comment by nikohansen** [comment]
Nice. For mnemonic reasons I suggest that we use the same symbols and color-code for these and for the scatterplots. For the scatterplots I tried to use symbols that "reflect" the dimension (like a triangle for dimension 3, a pentagon for dimension 5...).

**Comment by dtusar** [comment]
The last comment was moved to #836, the rest is done.
