### ISSUE TITLE
cocoex version numbering

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#632]
Could a Windows user paste the result of 

```python
import cocoex
print(cocoex.__file__)
```
in IPython for a current installation? 

On a Mac I get
```
'/Users/hansen/.local/lib/python2.7/site-packages/cocoex-0.7b0-py2.7-macosx-10.5-x86_64.egg/cocoex/__init__.pyc'
```

I am wondering in particular if the version number `0.7b0` looks similar.

**Comment by dtusar** [comment]
I get this:
C:\Users\dejan\AppData\Roaming\Python\Python27\site-packages\cocoex-0.5b0-py2.7-win-amd64.egg\cocoex\__init__.pyc
