### ISSUE TITLE
release process

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#635]
We should revisit `howtos/release-howto.md` on its status to be up-to-date. In particular, it seems to be necessary to edit several files by hand for adding the release number to create a proper release. This seems not at all practical or reasonable to me.

**Comment by brockho** [comment]
The file `howtos/release-howto.md` has been updated now and describes a simple release strategy (without updating the documentation) and a more complicated one (if the documentation shall be updated and/or if the `development` branch shall not be entirely included in the release).
