### ISSUE TITLE
post-processing incomplete?

### ISSUE THREAD

**Issue by markuswagnergithub** [numbbo/coco#656]
Given that some Git issues are on advanced features, maybe the following is an actual problem: the latex file and the html file appear incomplete.

What I have done:

Markuss-MBP:bbob2016coco wagner$ python -m bbob_pproc code-experiments/build/javaTEST/
Post-processing: will generate output data in folder ppdata
  this might take several minutes.
Post-processing (1): will generate output data in folder ppdata/javaTEST
  this might take several minutes.
/Users/wagner/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.7.beta.3-py2.7.egg/bbob_pproc/pproc.py:827: UserWarning: There is a difference between the maxevals in the *.info file and in the data files.
  warnings.warn('There is a difference between the maxevals in the '
/Users/wagner/Library/Python/2.7/lib/python/site-packages/bbob_pproc-0.7.beta.3-py2.7.egg/bbob_pproc/pproc.py:915: UserWarning:   double instances in [1, 2, 3, 4, 5, 1, 2, 3, 4, 5] (f1, 2D)
  + 'D)')
Scaling figures...   done (Tue Feb 16 21:17:29 2016).
TeX tables...   done (Tue Feb 16 21:17:30 2016).
ECDF graphs...   done (Tue Feb 16 21:17:43 2016).
ERT loss ratio figures and tables...   done (Tue Feb 16 21:17:43 2016).
Output data written to folder ppdata/javaTEST
  done (Tue Feb 16 21:17:43 2016).

Markuss-MBP:bbob2016coco wagner$ cd ppdata

Markuss-MBP:ppdata wagner$ ls
bbob_pproc_commands.tex index.html              javaTEST
_javaTEST is a run of the example experiment_

Markuss-MBP:ppdata wagner$ cat index.html 

<HTML>
<HEAD>
   <META NAME="description" CONTENT="COCO/BBOB figures by function">
   <META NAME="keywords" CONTENT="COCO, BBOB">
   <META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
   <TITLE> Post processing results </TITLE>
   <SCRIPT SRC="sorttable.js"></SCRIPT>
</HEAD>
<BODY>
<H1> Post processing results
</H1>
<H2>Single algorithm data</H2>
<H3>&nbsp;<a href="/templateBBOBarticle.html"></a></H3>

</BODY>
</HTML>
_damn it: there is HTML inside, which you can see when you edit this report, but of course it does not get shown to you now...._

_that file does not link to too much, and there is only a single tex file_

**Comment by markuswagnergithub** [comment]
ps: I have seen code-postprocessing/latex-templates, however, I do have issues with that one, e.g. [wrong figure file names](https://github.com/numbbo/coco/issues/518)

**Comment by brockho** [comment]
Dear Markus,

Thanks again for your input. LaTeX templates are not yet supported with the biobjective benchmark suite. We are working on it and will provide some with the next bigger release. Until then, you can have a look at the html output but even there, the current Coco version does not provide much insights because we did not fix reasonable targets yet. This is going to be solved in the next hours or days.

**Comment by markuswagnergithub** [comment]
Very cool, looking forward to the next bigger release then!
