### ISSUE TITLE
Bug in bi-objective tables?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#662]
When postprocessing simple RANDOMSEARCH data for the bbob-biobj suite, I get quite a lot of '1's in the ERT tables:
```
 ERT in number of function evaluations

5-D
Δ f 	1e+1 	1e+0 	1e-1 	1e-2 	1e-3 	1e-5 	1e-7 	#succ
f1 	1 	1 	1 	1 	1 	1 	1 	0/5
f2 	1 	3.8 (4) 	2332 (3250) 	2332 	2332 	2332 	2332 	0/5
f3 	1 	1.4 (1) 	2214 (1625) 	2214 	2214 	2214 	2214 	0/5
f4 	1 	1 	1 	1 	1 	1 	1 	0/5
f5 	1 	1 	1 	1 	1 	1 	1 	0/5
f6 	1 	1 	2253 (1500) 	2253 	2253 	2253 	2253 	0/5
f7 	1 	1.2 (0.2) 	1.2 	1.2 	1.2 	1.2 	1.2 	0/5
```
This cannot be correct and must be caused by a bug.

**Comment by brockho** [comment]
Just as additional information: the ERTs are correctly displayed in the LaTeX tables, see here the same algorithm data:

![ert-randomsearch-latex](https://cloud.githubusercontent.com/assets/13706996/13140775/45e65d98-d634-11e5-83a2-d9b87c20b8bd.png)

**Comment by dtusar** [comment]
Closed with #666.

**Comment by brockho** [comment]
Though the problem does not appear anymore in the single-algorithm tables, the wrong table entries are still there in the 2-algorithm postprocessing output (not checked for the many-algorithms tables).

**Comment by dtusar** [comment]
Now should be fixed in all tables.
