### ISSUE TITLE
postprocessing does not always extract correctly

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#673]
The postprocessing does not extract correctly our data set SMSEMOAnorestart_on_bbob-biobj-1e3DIMfunevals.tar.gz in the svn GForge repository `bbob-biobj/data`. It stops at the `3-ill-conditioned_3-ill-conditioned` folder and then crashes because the data is not complete. If I extract the archive myself before, however, the postprocessing runs through.

Not clear whether this is related to the fact that the data set is quite old and, for example, does not yet have `.tdat` files but I would guess no.

**Comment by dtusar** [comment]
I had a similar problem on CI windows slaves when the paths were too long.

**Comment by brockho** [comment]
Yeah, that's it. Thanks @dtusar.

However, we should try to figure this out from the post-processing and display a message to the user how to circumvent the problem.

**Comment by dtusar** [comment]
An error is raised if one or more files cannot be extracted because its path is too long.
