### ISSUE TITLE
formating of RLD figure algorithm name annotation

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#678]
<img width="1310" alt="screen shot 2016-02-21 at 15 22 50" src="https://cloud.githubusercontent.com/assets/7316439/13203150/b02f834a-d8b0-11e5-8924-5b235b57b2d8.png">
The problem: about 1/2 of the visible area is empty useless space. A solution is to cut the annotated name to the minimum needed to differentiate between all shown algorithms plus, say, 2 letters. Or to cut the figures when displayed in the html.

**Comment by dtusar** [comment]
The description of the algorithm was removed from the legend.

**Comment by nikohansen** [comment]
That doesn't necessarily solve the issue. The name can still be too long, or the names can be the same, but the parameter setting is different.

**Comment by dtusar** [comment]
Ok, I can shorten the name and make sure that the names are not equal. This does apply for all figures (`eps`, `svg` and `pdf`), right?

**Comment by brockho** [comment]
@nikohansen suggested yesterday to normally cut to 6 letters and to lengthen this if the 6 letters do not allow to distinguish the algorithms.

**Comment by nikohansen** [comment]
Right, all figures, unless we find a good reason why it would be preferable to cut the figure borders away afterwards.

**Comment by dtusar** [comment]
The minimal number of letters is now 9 because of the name `best 2009` for best single objective algorithm and lengthen if necessary.

**Comment by nikohansen** [comment]
I still don't like 9: it means that in the above example roughly 25\% of the space is useless and wasted. That seems just too much to me. 

Can we (easily) drop the annotation when only a single algorithm is displayed? This would make perfectly sense to me. We could also write a legend instead, if there are no more than 2 algorithms plus the best. 

BTW: all legends should use the `legend(framealpha=0.2)` parameter to prevent them from completely hiding the actual data. I have no idea why this isn't default in `matplotlib`.
