### ISSUE TITLE
browsing previous post processing results

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#679]
With the current browsing entry point, `ppdata.html`, we cannot look at previously generated results, even if they are still available (i.e. not overwritten or deleted). It seems preferable to keep or update all pointers to subfolders in the current folder, such that all processed data can be investigated.

**Comment by dtusar** [comment]
It is possible that the existing plots are completely unrelated to the currently generated. Wouldn't it be confusing for the user to have links to those plots?

**Comment by nikohansen** [comment]
I find it quite confusing (and annoying) as a user that my results silently disappear. If I want them to disappear I delete them or move them somewhere else or overwrite them (by using the very same algorithm/output name).

It would probably be useful to add the last modification time to the link, and/or sort the links according to their last modification time. This is more like nice-to-have, but probably not quite urgent to do.

**Comment by nikohansen** [comment]
FTR, it probably means that the root page does not show any figures, or just a single overview figure that accompanies the link.

**Comment by dtusar** [comment]
The `html` pages now have also links to the previously generated data.
