### ISSUE TITLE
add gray-scale 'colors' for graphs

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#68]
```
check that gray-scale figures can be produced and that the used colors are 
"nice"
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 1 Aug 2014 at 9:36

**Comment by brockho** [comment]
See also the latest entry of #1077 for two additional points to check: the readability of the dots on the left and the missing graphs for smaller function evaluations than 1e0.

**Comment by brockho** [comment]
I think this issue can eventually be closed. I checked again the grayscale plots for multiple algorithms and everything looks readable to me. This also holds for the two aspects of issue #1077 mentioned above.
