### ISSUE TITLE
Matlab/Octave should call cocoCall from within the provided .m files

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#682]
In the Matlab/Octave wrapper, we have one big ``cocoCall.c`` file now which wraps around Coco's C code. However, for each function, a ``.m`` file exists which only takes care of providing the documentation. @tobiaswagner suggested to also provide the old functionality of directly calling these .m files for example as
```
cocoProblemFinalTargetHit(problem)
```
instead of the ugly and less readable
```
cocoCall('cocoProblemFinalTargetHit', problem)
```

**Comment by nikohansen** [comment]
I don't see a big advantage, if it is only about readability. It certainly should not have high priority, should it?

**Comment by brockho** [comment]
agreed

**Comment by brockho** [comment]
Thanks to @tobiaswagner, this issue can be closed now.
