### ISSUE TITLE
Make all algorithm data easily available on web page

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#69]
```
There should be a single web page that lists all available data files (for all 
algorithms). This web page should be linked prominently on the main page of the 
wiki.
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 14 Oct 2014 at 7:43

**Comment by brockho** [comment]
With the advent of new test suites, @nikohansen and I propose to have a first summary Google spreadsheet of all data sets, with one data set per row and the suite name mentioned as additional field. Whether we use these data indirectly on other web pages like now or whether we provide the link to the Google sheet can be decided later on. At least, there is no need for a data base.

**Comment by brockho** [comment]
With the advent of the data archive in the postprocessing (issue #1580), there seems to be no need for the above suggested Google Spreadsheet.

As improvements, we have now a single algorithm table per test suite on the GForge wiki:

http://coco.gforge.inria.fr/doku.php?id=algorithms-bbob
http://coco.gforge.inria.fr/doku.php?id=algorithms-bbob-noisy
and
http://coco.gforge.inria.fr/doku.php?id=algorithms-bbob-biobj

What shall be done in the coming days (I will try to take care of it) is:
- [ ] remove the entries for which we have only pickle files
- [ ] rename some of the algorithm data sets such that the algorithm name is searchable (for example `BSrr` should become `BrentSTEPrr`)
- [ ] add the algorithms from http://pasky.or.cz/sci/cocopf-scipy/ by Petr Baudiš as official `bbob` algorithms before we fix the algorithm indices

Something else, I forgot?

**Comment by brockho** [comment]
The only thing that needs to be done before closing this issue is to potentially rename the folder 2015-GECCO` to `2015` as suggested in #1580.

**Comment by brockho** [comment]
Decision of today: anyone who wants to change the folder name can change it, but we keep it as is for now.
