### ISSUE TITLE
post-processing: missing description of figures and tables

### ISSUE THREAD

**Issue by Ulfgard** [numbbo/coco#692]
Hi,

I am working with the newest development version. 

I am trying to compare different algorithms using the post-processing and i am failing horribly. I am looking at templateBBOBcmp.html

Here are a number of issues:

For two algorithms

1. scatter plots per function
    - missing axis description
    - missing key: What are the red boxes and blue stars?
    - What does it mean that a red box is at a specific spot?
2.  Empirical cumulative distribution functions (ECDFs) per function group 
    - Left hand side:
        - missing key: which algorithm is described by the circles and which by the diamonds?
        - Export knowledge told me that the graph depicts number of trials that got closer to the target volume than a specific value. No hint about that on the page. 
  - Right hand side:
    - I have totally no clue what this means. 
    - missing axis description y-Axis, assuming 0.0 to 1.
3. Table showing the ERT in number of function evaluations 
  - Names truncated after three letters - bad for algorithm variants
  - unclear what the numbers mean. is it mean(median)?
4. I am missing the most simple of graphs: a plot showing median log distance to optimal volume over log function evaluations for each algorithm considered. This would be super helpful to compare algorithm performance on unimodal problems and would give a hint about the convergence behaviour.

If needed i can get a similar list for the other pages and graphs as well.

**Comment by nikohansen** [comment]
Thanks for the detailed description! We are working on exposing the figure descriptions. Meanwhile you find the papers from previous workshop with figure captions [here](http://coco.gforge.inria.fr/doku.php?id=bbob-2013-algorithms), specifically:
single algorithm: https://hal.archives-ouvertes.fr/inria-00382093/document
two algorithms (scatter plots): https://www.lri.fr/~hansen/ws1p32-hansen.pdf 
many algorithms: http://coco.gforge.inria.fr/lib/exe/fetch.php?media=pdf2013:w0306-loshchilov.pdf, https://www.lri.fr/~hansen/ws1p34.pdf

**Comment by Ulfgard** [comment]
Thank you. This clarified a lot.

Could I suggest the following changes:

1. Scaling of ERT with dimension: smaller target value, e.g. 1.e-2 or even 1.e-1. 1.e-4 is really hard to obtain with small budgets - effectively excluding any expensive optimization setting

2.  Scatter plots per function : Add algorithm names to the x and y axis. Right now i can not see which algorithm is better only that *one* algorithm is better.

**Comment by nikohansen** [comment]
Agreed with both points.

**Comment by nikohansen** [comment]
> I am missing the most simple of graphs: a plot showing median log distance to optimal volume over log function evaluations for each algorithm considered.

The run-length distribution plots (you can click on from `ppdata.html`) come reasonably close. They are arguably even slightly more informative.

**Comment by dtusar** [comment]
With all the descriptions now included in the `html` files, we can probably close this issue?

**Comment by Ulfgard** [comment]
yes
