### ISSUE TITLE
Long Paths to Data seem to cause 'nothing to do' error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [numbbo/coco#70]
```
It seems as if long paths causes a 'Nothing to do' error such as:

Traceback (most recent call last):
  File "..\..\code\python\bbob_pproc\rungeneric.py", line 308, in <module>
    res = main()
  File "..\..\code\python\bbob_pproc\rungeneric.py", line 287, in main
    + ["-o", tmpoutputdir, alg])
  File "..\..\code\python\bbob_pproc\..\bbob_pproc\rungeneric1.py", line 294, in
 main
    raise Usage("Nothing to do: post-processing stopped.")
bbob_pproc.rungeneric1.Usage

when calling

C:\Users\dimo\Desktop\coco\BBOB\templates\latex>python 
..\..\code\python\bbob_pproc\rungeneric.py 
..\..\..\..\canadafrance\metamodels\CEC-BBOB2015\lmmCMAThreshold7-500D-noisy-ini
tIn0-Lille\lmmCMAThreshold7-500D-noisy-Instances31till40\bbobdata-lmmCMAThreshol
d-noisy-500Dbudget

on a Windows machine.

Note that copying the folder to the current directory does not cause the 
problem and the postprocessing runs smoothly.
```

Original issue reported on code.google.com by `dimo.bro...@inria.fr` on 19 Nov 2014 at 9:55

**Comment by ttusar** [comment]
There seems to be no solution to this. We should at least change the error message to "path too long".

**Comment by dtusar** [comment]
The "nothing to do" error comes from the logic that any error in loading the dat or tdat files results in not loading data for the corresponding info file. So in the path too long case none of the info files is loaded, so "nothing to do". 

I can raise an error if the path is too long but the outcome will still be the same. And I'm afraid that the users won't notice the actual problem.

**Comment by nikohansen** [comment]
You can put a hint into the error message what the possible reason(s) might be / what reasons for this exception to be raised have been seen before.

**Comment by dtusar** [comment]
A more specific error message is written to the output for the files which have too long paths. Some improvements will be added in #570.
