### ISSUE TITLE
broken link in gforge homepage

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#718]
The [All papers published in the proceedings](http://sci2s.ugr.es/eamhco/contributionsGECCO10.php) link at http://coco.gforge.inria.fr/doku.php?id=bbob-2010-results is broken.

**Comment by brockho** [comment]
None of the previous links to papers from BBOB-2010 is working, it seems. They all link to external pages at http://sci2s.ugr.es/ which do not exist anymore.

**Comment by brockho** [comment]
I will take care of putting at least the doi for all papers. However, this has low priority at the moment.
