### ISSUE TITLE
post-processing multiple algorithms documentation issue?

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#721]
The text "We can also compare more than one algorithm by specifying several data result folders generated by different algorithms." suggests that I can launch 
python -m bbob_pproc SMSEMOA SMSEMOA2 
to compare the two algorithms
It does not work for me and I get the same plots as if I would post-process only one algorithm
Instead I tried 
python -m rungenericmany SMSEMOA SMSEMOA2 
and it generated curves I wanted
I suspect that the documentation is imprecise or bbob_pproc does not work as expected or I misunderstood something

I use the latest github code

**Comment by dtusar** [comment]
If you call `python -m bbob_pproc SMSEMOA SMSEMOA2` you should get the single algorithm plots for both algorithms and additionally some comparison plots like ppfigs and ppscatter. The same comparison plots (but here without the single algorithm ones) are generated if you call `python -m rungeneric2 SMSEMOA SMSEMOA2`
The `rungenericmany` is used for comparing more than two algorithms. It is also called when you specify three or more algorithms after `python -m bbob_pproc`.

**Comment by nikohansen** [comment]
Just for the record, I assume the module call for `rungeneric*` will go away at some point. `python -m cocopp.runmany ...` or `python -m cocopp -runmany ...` would be the alternatives.

**Comment by brockho** [comment]
@loshchil: Is this issue still open for you? Can you in the meantime postprocess more than one algorithm? 

Note: we will most likely not be able to provide a LaTeX template on time for displaying more than one algorithm, but you can always look at the html output.

**Comment by loshchil** [comment]
I use rungenericmany for postprocessing of one or more algorithms. 
I plan to use only rungenericmany to make figures I need, so I will probably make some paper myself.

**Comment by dtusar** [comment]
Since @loshchil can plot what he needs I will close this issue.
