### ISSUE TITLE
post-processing multiple algorithms: curves of the same algorithm/data diverge?

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#722]
after 
python -m rungenericmany SMSEMOA SMSEMOA2 
with SMSEMOA and SMSEMOA2 as two copies of the same data
I found that while the curves on
pprldmany_20D_noiselessall.pdf 
look identical, the other individual figures, e.g., 
pprldmany_05D_3-ill-conditioned_4-multi-modal.pdf 
show some divergence before the cross, i.e., within the budget used
this should not be the case for exactly the same data

**Comment by nikohansen** [comment]
Can you drop such a plot here (Github supports drag and drop)?

**Comment by loshchil** [comment]
for 2D
[pprldmany_f001_02D.pdf](https://github.com/numbbo/coco/files/149596/pprldmany_f001_02D.pdf)
[pprldmany_02D_noiselessall.pdf](https://github.com/numbbo/coco/files/149597/pprldmany_02D_noiselessall.pdf)

**Comment by loshchil** [comment]
the data + the output that I get
[bbob_pproc.zip](https://github.com/numbbo/coco/files/149606/bbob_pproc.zip)

**Comment by nikohansen** [comment]
This can actually happen, if there are runs that get stuck with very bad indicator values, while some reach the same indicator values very quickly (which is likely, as they are bad). In this case the run length is computed from randomly drawn simulated restarts. My current hunch is that we don't see a bug, but a feature.

**Comment by loshchil** [comment]
I don't understand. The data is the same, not two runs, by the same folder
copied twice.

**Comment by nikohansen** [comment]
[In this paper](https://hal.archives-ouvertes.fr/hal-00545727) is described (first page) how simulated runs/run lengths are generated. Like for bootstrapping, we don't expect the very same outcome each time even on the very same data set.

**Comment by loshchil** [comment]
Thanks for the reference. I didn't know that this is the case. 
Technically, the outcome then depends of the seed? 
I attached another example for the same data
[pprldmany_03D_1-separable_1-separable.pdf](https://github.com/numbbo/coco/files/149628/pprldmany_03D_1-separable_1-separable.pdf)
The difference after 10D evaluations is a factor of 2. 
It does not look good at all: one can start to draw some design conclusions from this difference.

**Comment by nikohansen** [comment]
You can set 
```
simulated_runlength_bootstrap_sample_size_rld
```
in the file `bbob_pproc/genericsettings.py` to a larger value, if you want the stochastics to go away. On the other hand: these stochastics should reflect the actual variation we will observe in a real repetition (you might want to try). If you tend to draw design decisions from such deviations, you might want to readjusts your decision thresholds.

**Comment by loshchil** [comment]
The last attached figure pprldmany_03D_1-separable_1-separable.pdf shows a non-negligible difference for 10D evals from 45 instances and all it comes from the post-processing. I think that it adds some noise which should not be set by default as it can be perceived as a difference in the tested algorithms. Of course after looking at this difference I would drop everything and design a new algorithm from scratch ;-)

I tried to set in_a_hurry to 0 (to adjust simulated_runlength_bootstrap_sample_size_rld) and the curves now coincide. 
I suggest to change the current default in_a_hurry=1000 to 0 (if the time difference is not too big, 30% difference is mentioned in the comment for in_a_hurry) or decrease it a bit.

**Comment by nikohansen** [comment]
<img width="403" alt="screen shot 2016-02-28 at 1 32 27" src="https://cloud.githubusercontent.com/assets/7316439/13376389/547ee2d8-ddbb-11e5-9148-5f485ab690b1.png">
The deviation looks non-negligible, however it probably is what we will see on simple repetitions.

The `in_a_hurry` variable is indeed supposed to be set to zero for the final display of data generated for an article.

**Comment by brockho** [comment]
> shows a non-negligible difference for 10D evals from 45 instances and all it comes from the post-processing.

@loshchil: Just a small remark: what you see in the last plot you showed (in case it was generated from the standard postprocessing) is data drawn from 15 instances "only" (1 dimension * 3 functions * 5 instances).

**Comment by loshchil** [comment]
Thanks for the note, Dimo.
I checked the content of the 1-separable_1-separable_hyp.info in the bbob_pproc.zip that I attached before. 
function =  1, dim =  3, bbob-biobj_f01_d03_hyp.dat, 1:3001|2.8e-003, 2:3001|1.4e-003, 3:3001|4.3e-003, 4:3001|2.5e-003, 5:3001|1.9e-003, 6:3001|1.7e-001, 7:3001|1.7e-001, 8:3001|1.7e-001, 9:3001|1.7e-001, 10:3001|1.7e-001
function =  2, dim =  3, bbob-biobj_f02_d03_hyp.dat, 1:3001|4.5e-003, 2:3001|1.2e-003, 3:3001|1.7e-003, 4:3001|2.7e-003, 5:3001|2.7e-003, 6:3001|5.4e-002, 7:3001|1.3e-001, 8:3001|2.7e-002, 9:3001|2.2e-002, 10:3001|9.1e-003
function = 11, dim =  3, bbob-biobj_f11_d03_hyp.dat, 1:3001|2.3e-003, 2:3001|2.3e-003, 3:3001|9.6e-004, 4:3001|9.1e-004, 5:3001|1.2e-003, 6:3001|1.7e-001, 7:3001|1.7e-001, 8:3001|1.8e-001, 9:3001|1.8e-001, 10:3001|1.9e-001
So it seems like 1 dimension * 3 functions * 10 instances = 30 ;-)
I don't think I made any modifications of the MATLAB SMSEMOA example.

**Comment by loshchil** [comment]
pproc.py has 
instancesOfInterestBiobj2016 = {1:1, 2:1, 3:1, 4:1, 5:1}
only 5 out 10 instances are used for the post-processing?

**Comment by nikohansen** [comment]
This leads me to two conclusions:

- The figures should give the number of "data points" used (functions times instances), as they give the dimension
- The post-processing should have an option to process, or not, double- or triple-... data for the same instances.

**Comment by nikohansen** [comment]
> only 5 out 10 instances are used for the post-processing?

I believe this is correct. The other instances will serve as a (weak) test for generalization.

**Comment by loshchil** [comment]
I see, it makes perfect sense.

**Comment by Ulfgard** [comment]
How is this test performed? When browsing through the files, i see that trials 6-10 all always have the same value (dependent on the function/dimensionality). so are they thrown away?

i also feel that it is really hard to evaluate the algorithms based on so little trials, especially on the multi-modal functions.

**Comment by nikohansen** [comment]
> How is this test performed? 

It is currently *not* done, but it will be done with the submitted data. 

> When browsing through the files, i see that trials 6-10 all always have the same value (dependent on the function/dimensionality). so are they thrown away?

They are not used *at the moment* when you run the post-processing. Indeed, if you want safe time, you can filter away the non-processed instances for the time being. 

> i also feel that it is really hard to evaluate the algorithms based on so little trials, especially on the multi-modal functions.

Agreed. There is fortunately a *very* simple way out of this dilemma: conduct independent restarts *within* the instances, as the example experiment(s) already suggest and even have implemented.

**Comment by brockho** [comment]
Just to make clear and bring the issue again to our attention, I cite the summary of @nikohansen from 23 days ago:

> * The figures should give the number of "data points" used (functions times instances), i.e.
>    the number of possible runtimes seen, like they give the dimension
> * The post-processing should have an option to process, or not, double- or triple-... data for
>    the same instances.

**Comment by nikohansen** [comment]
For the time being this could be written in the figure caption, if this is simpler to do.

**Comment by brockho** [comment]
What about displaying the number of instances like that in the ECDF plots:

![numberofinstancesdisplayed](https://cloud.githubusercontent.com/assets/13706996/14056781/eb63c91c-f2f0-11e5-9230-ab860d2db4c2.png)

The number of instances displayed (per algorithm) is extracted from the first entry in the loaded `dictAlg`, i.e., we do not detect if the number of instances change over the problems. Should not happen anyway with the current experiments, but maybe, we want to check this and raise a warning?

**Comment by nikohansen** [comment]
Looks good, I'd just prefer a smaller font. 

> we do not detect if the number of instances change over the problems. Should not happen anyway with the current experiments, but maybe, we want to check this and raise a warning?

This is a kind of warning which should be raised/given during/at the end of the post-processing when data-consistency is analyzed. 

Ideally we would have such checkers as part of the `DataSetDictionary` class.

**Comment by brockho** [comment]
The smaller font size and the reordering in the rightmost figure are implemented now in the doc branch. 

Still missing: the ppfidgim.py plots, hence, the issue stays open.

**Comment by brockho** [comment]
The missing labels in the ppfigdim.py plots are not too critical and will be provided in some of the next minor releases. Hence, this issue is not addressed fully with the v1.0 release.

**Comment by dtusar** [comment]
@brockho I saw that you added the number of instances to the ppfigdim plots. Can this issue be closed now?

**Comment by brockho** [comment]
Yes, it can. I simply forgot to close it.
