### ISSUE TITLE
BBOB 2016 missing in the navigation bar of coco.gforge.inria.fr

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#723]
To find the BBOB website, I always google "bbob coco lri" 
and http://coco.gforge.inria.fr/doku.php?id=cec-bbob-2015 is the top-1 website which I click. 
The right navigation bar does not have BBOB 2016 with its 'downloads' section, etc. 
I know that the link is in the text of the main paper and this seems to be the least urgent think to do, but   it might be better to add some pages with cross-links to make sure no user will be lost.

**Comment by brockho** [comment]
Thanks Ilya for pointing out this issue. It has been indeed of low priority, but it has been naggering me as well that the new page was not easy to find. I hence added the missing links in the old navigation bar although the entire old web page should be updated with this respect, I guess.
