### ISSUE TITLE
observer/logger should write suite name

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#728]
The problem: some parts of the post-processing depend on the benchmark suite (e.g. choice of target values). Therefore there should be an explicit way to signal the suite ID (name) to the post-processing. This should **not** be done implicitly by having different data formats (which is IMHO **very** undesirable). Consequently, the logger must write the suite name into the index file(s), which is where most meta-information belongs to.

CAVEAT: first, the post-processing should be in a state (updated, if necessary) such that the new index file is read in smoothly.

**Comment by ttusar** [comment]
Let me know when it's time to update the logger.

**Comment by dtusar** [comment]
You can update the logger to write a new key/value pair (where the key is suite) to the `info` files.

**Comment by ttusar** [comment]
@dtusar and I have just realized this is not so simple - the logger can output the suite name ('bbob' or 'bbob-biobj'), but the post-processing actually needs the testbed name. The functionality of outputting the suite name is already implemented in `logger_bbob.c` and `logger_biobj.c`, but has been commented out for the time being.

**Comment by nikohansen** [comment]
What is the difference between a suite name and a testbed name? I have been using the words suite and testbed as synonyms so far.

**Comment by ttusar** [comment]
I can try to explain (@dtusar will correct me if I'm wrong): a testbed is a suite + postprocessing settings, such as the targets to display etc. So you could have multiple testbeds for the same suite. Suite names are 'bbob' and 'bbob-biobj', while testbed names are 'GECCOBBOBTestbed' and 'GECCOBiObjBBOBTestbed'.

**Comment by nikohansen** [comment]
It seems what you refer to is the post-processing _testbed settings_ class. I don't see the problem though, as AFAICS the mapping from testbed/suite name to class name can be defined anywhere, preferably probably in some configuration file like `genericsettings.py`.

**Comment by dtusar** [comment]
Now we have a mapping in the post-processing from the suite name to the `testbed settings` class. Also the logger now writes the suite name again.
