### ISSUE TITLE
Plotting "--expensive" vs "regular" results

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#739]
When the results of different algorithms are plotted together, the curves are computed w.r.t. different sets of target objective function values. I find it a bit misleading (see below why) and tend to prefer the case when hard targets are used in contrast to the case "--expensive". 
The "--expensive" case is based on some "easy" targets obtained by, possibly, an algorithm A. This was already a problem to me in the past when some target function values reached by an algorithm B but not reached by A were "not shown" in the plots because they were not reached by the algorithm A. 
It also seems to be a problem for the targets used in the bi-objective "--expensive" BBOB. I suspect that the targets are based on SMS-EMOA. As a consequence, it might happen that the algorithm which will perform a way better (also, in the default, non-expensive plots) than SMS-EMOA will not "look better" in the "expensive" plots, more likely for the budgets 100D-1000D.
The best and simplest solution I see is to use the same targets as for long runs and simply zoom figures with x_limit_default = 1e3 and change ylimit to e.g. 0.5. I don't know how to do it, instead, I use a hack in pprldmany.py "y = 3.0 * np.cumsum(list(dictx[i] for i in x))", i.e., 3.0 instead of 1.0.

**Comment by nikohansen** [comment]
I tend to agree: it should not be possible to activate the `--expensive` setting (that is, runlength-based targets) in the bi-objective case (more generally, in the case where no best algorithm data are available).

**Comment by brockho** [comment]
Closed by pull request #930.
