### ISSUE TITLE
GetFileAttributesA instead of GetFileAttributes under Windows?

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#740]
I am trying to use the C code. 
I created an empty project in Microsoft Visual Studio Express 2013, it is free to use, so can be quite popular. The project has "Use Unicode Character Set" by default in project settings. I added coco.h, coco.c and example_experiment.c to the project. When I run the code, "exdata" folder is created but  the code then fails. Interestingly, the trick of "#line ..." does not allow to debug the code inside coco functions. I investigated a bit and found that coco_file_exists does not work as expected. I replaced GetFileAttributes with GetFileAttributesA and now the check whether the folder exists works as expected. There is one more appearance of GetFileAttributes. When both are set to GetFileAttributesA, I can finally test the example code. 
I don't know whether GetFileAttributesA or GetFileAttributesW or something else should be used under Windows. 
See also http://stackoverflow.com/questions/8233842/how-to-check-if-directory-exist-using-c-and-winapi

**Comment by ttusar** [comment]
Thanks for the report, I'll have a look.

**Comment by ttusar** [comment]
The change from GetFileAttributes to GetFileAttributesA works also on both our Windows slaves, so I pushed it to development now.
