### ISSUE TITLE
post-processings dependencies on the benchmark suite

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#741]
The dependency of the post-processing code on the benchmark suite should preferably be *entirely* managed via the `Testbed` class. Code like
```
        maxFunctionIndex = 55 if isBiobjective else 24
```
(line 185 in `ppfig.py`) seems very versatile and bound to be broken with any new testbed arriving. Something like

```
    maxFunctionIndex = genericsettings.current_testbed.number_of_functions
```

seems to be a much more generic way to do this.

**Comment by dtusar** [comment]
number_of_functions was moved to testbed.
