### ISSUE TITLE
multiple experiments

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#745]
Referring to https://github.com/numbbo/coco/issues/733#issuecomment-192544551, https://github.com/numbbo/coco/issues/733#issuecomment-192342356, and #707, the bi-objective post-processing seems not to be able to digest multiple experiments from a single optimizer. This is unfortunate, in particular as we cannot change or increase the number of different instances. 

Data with several runs/trials on the very same instance should lead to a warning, but otherwise the data should be digested and processed (as this seems to be the case for single-objective data).

**Comment by dtusar** [comment]
The logic for checking the number of instances and the instance numbers is the same in both the single-objective case and the bi-objective case. I run the post-processing with data containing six times the same instance and it went through (with a warning). Did I missed something or can we close this issue?

**Comment by nikohansen** [comment]
Is the problem maybe if they are presented in different subfolders?

**Comment by nikohansen** [comment]
the current situation seems to be that additional (repeated) instances are ignored and a warning is issued: `UserWarning: same DataSet found twice, second one from [...] is disregarded for instances [...]`. 

Ignoring these data is rather undesirable in particular of _all_ instances are repeated the same number of times. Printing a message is fine, but such data we should be able to digest.

**Comment by nikohansen** [comment]
The open question is still which data to reject and which to accept (preferable easy to implement).

A few thoughts:

* We should always accept data with the same instance ids multiset (i.e. also repeated) on all problems. 

* If we want to process also ongoing experiments, we probably have to accept pretty much anything.

**Comment by brockho** [comment]
For me, the postprocessing runs through (with warnings on the number of instances) if I have some instances twice. Also with less than the supposed number, things work.

However, the display in the scaling figures is not correct anymore as it displays only one number for all dimensions: if one dimension has less or more instances (and this dimension is not the last, I guess), the number displayed will be wrong.

**Comment by brockho** [comment]
I think that this issue can be closed. For me, `bbob-biobj` data with different numbers of instances (duplicated or not) can be compared for some time now.

The last point of the display of inconsistent instance numbers has been also corrected now in the scaling plots with d8db4584ee5e672e7b4bd75b10b93455509460d1.

**Comment by nikohansen** [comment]
Does that mean that additional (repeated) instances are not ignored anymore?
