### ISSUE TITLE
Matlab output stops with restarts

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#767]
The output when a restart is performed, as written from C, is too long. On the one hand, it makes all output unreadable and in Matlab, it creates quickly a "too long line" error and stops writing:

```
[...] INFO: algorithm restartedINFO: algorithm restartedINFO: algorithm restarted.INFO: algorithm restartedINFO: algorithm restartedINFO: algorithm restarted... Output truncated.  Text exceeds maximum line length of 25,000 characters for Command Window display.
```

**Comment by ttusar** [comment]
This string comes from Matlab's example experiment, not the C code. The fix is now in the development branch.
