### ISSUE TITLE
return overflow value

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#773]
There are apparently several outcomes when an overflow is encountered: 
 
```python
>>> p = suite['bbob_f003_i01_d03']
>>> print(p([2,3,4e80]))
nan
>>> p = suite['bbob_f006_i01_d03']
>>> print(p([2,3,4e80]))
inf
```

This is rather undesirable and it should probably be caught in `coco_evaluate_function` to become uniformly `inf`, as this is less likely to produce unpredictable or unforeseen states in the algorithms.

See also #769

**Comment by nikohansen** [comment]
fix for large values, paraphrasing in `C`:
```C
#define MAX_X 7e77  // should be smaller than NAN to keep NAN out of the range of accepted values

for (i = 0; i < number_of_variables; ++i)
  if (fabs(x[i]) >= MAX_X) {
    for (j = 0; j < number_of_objectives; ++j) 
      y[j] = fabs(x[i]);
    return;
  } 
```

**Comment by loshchil** [comment]
from
http://stackoverflow.com/questions/570669/checking-if-a-double-or-float-is-nan-in-c

According to the IEEE standard, NaN values have the odd property that
comparisons involving them are *always* false. That is, for a float f, f !=
f will be true *only* if f is NaN.
I guess you should add " || (x[i] != x[i])"

**Comment by ttusar** [comment]
The examples above now both produce inf (on a computer with a "smart" compiler)

**Comment by ttusar** [comment]
Note that `coco_is_inf(NAN)` returns true on computers without "smart" compilers.

**Comment by ttusar** [comment]
Solved by a telling pull request number #888

**Comment by nikohansen** [comment]
> Note that coco_is_inf(NAN) returns true on computers without "smart" compilers.

Isn't this a bug? Shouldn't `coco_is_inf` instead test for `NAN` first and return `False` if it finds an `NAN`?

**Comment by ttusar** [comment]
Good point, will take care of it.

**Comment by ttusar** [comment]
Solved, we can keep the issue closed :)
