### ISSUE TITLE
ART replaces ERT ? Change in post-processing (caption, ...)

### ISSUE THREAD

**Issue by anneauger** [numbbo/coco#797]
Average Running Time (ART) seems to be a better name that Expected Running Time (ERT). The current version of the performance assessment documentation is now talking about ART.

This change of naming impacts the labels / captions of many graphs produced by the postprocessing code that should consequently be changed.

**Comment by nikohansen** [comment]
Maybe aRT would be even better than ART?

**Comment by dtusar** [comment]
Please decide what should it be. Because I will change it today.

**Comment by anneauger** [comment]
Let us go for aRT then (@brockho agrees as well). Thanks for doing the changes in the postprocessing. I will take care of the changes in the documentation.

**Comment by dtusar** [comment]
ERT is now replaced with aRT in various labels and captions.
