### ISSUE TITLE
Storage/space Complexity

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#806]
I am running some experiments for 20-D problems and only on 1 instance.
The results for 30000D evaluations takes about 0.5GB. I still want to run my algorithm for 100000D evaluations. 
This could take 1-1.5GB of memory. For all instances this would take about 10-15GB. This is only for 20D. If I include all dimensions below 20-D, it could take 20-30GB of memory. Certainly, this would be an upper bound for me and for most users. 
One way to reduce the memory is to have a better storage in the .dat files, e.g., by removing dominated points. I expect that this would drastically reduce the memory cost. However, if it is done in a naive way, then the computational complexity might become huge. 
Not sure whether the minimal cost to check for pareto dominance in the 2-objective case is linear or log(npoints) or some other. If a naive linear implementation is used, then the overall complexity may grow quadratically. An option might be to remove all dominated points only every 100 or 1000 evaluations and only if more than say 10000 points are collected. 
Sure, it does not seems as the number one priority. However, the more one uses the framework, the more it becomes an issue. 
As a side thing. If nothing changes, then  what will happen when the users will want to compare different algorithms, say 10 of them. Will they downloads tens of gigabytes? You probably plan to clean all .adat files after the workshop. Then, there might be a need to use the same little tool locally to reduce the space complexity.

**Comment by ttusar** [comment]
Just a clarification, you mean the archive files (the `adat` files, not the `dat` ones, right)?

We are aware of this problem, but the decision to record all points that are non-dominated at construction time was well motivated. This is the only way to be able to reconstruct algorithm performance without having to re-run the algorithms. Such reconstructions can be used, for example, to measure algorithm performance w.r.t. some new performance indicator that is not implemented yet or to update the algorithm performance w.r.t. a better hypervolume reference set. We might need to do this in the future. However, this is "a burden" for us, not the users. 

If/when the users will want to compare their algorithms with existing ones, they won't need to download any `adat` files, just the `info`, `dat` and `tdat` ones, which are much smaller in size.

**Comment by loshchil** [comment]
Yes, .adat files.
If a better hypervolume reference set is found but you already know hypervolume values of your algorithm w.r.t. the old reference set, then it seems that there is no need to recompute hypervolume values as they can be shifted. If you also want to change the reference point, then I doubt that the old data obtained/optimized based on the old reference point can be used.  
I agree that all points might be needed to compute some future indicators. However, depending on the indicator, some dominated points (i.e., not stored anyway) may need to be taken into account.

**Comment by ttusar** [comment]
>If a better hypervolume reference set is found but you already know hypervolume values of your algorithm w.r.t. the old reference set, then it seems that there is no need to recompute hypervolume values as they can be shifted.

Actually, you cannot just shift them because we are recording the algorithm performance when a target was hit, not when the hypervolume was improved.

**Comment by loshchil** [comment]
I see, then the imprecision might be in order of one target per function.
Sound like not a big deal given that the BBOB plots can look different if
the same data is plotted twice (there was a ticket about it).

**Comment by brockho** [comment]
Just to add some information for comparison reasons: running a simple weighted sum based algorithm (IPOP-CMA-ES on 100 scalarizations, 3 restarts) as baseline for different numbers of function evaluations, results in the following total file sizes (uncompressed, incl. 40-D):

`10^3 * DIM` (~4min): 71KB for ``f4`` only, i.e. estimated over all 55 functions if we assume ``f4`` to be representative: 3.8MB in <4h
`10^4 * DIM` (~30min): 20MB for ``f4``, i.e., for all functions ~1GB in ~27.5h
`10^5 * DIM` (~2.5h): 130MB for ``f4``, i.e. for all functions ~7GB in 5.7d

We see (i) that the factor of produced data is almost linear with the number of function evaluations for longer experiments (factor 6.5 between 10^4 * DIM and 10^5 * DIM) and (ii) that your estimations seem reasonable.

In any case, we are looking forward to your submission. I am confident that we will be able to handle the resulting file sizes.

**Comment by loshchil** [comment]
Thank you for the data.
One useful thing that is missing in this thread is:
observer_biobj->log_nondom_mode = LOG_NONDOM_NONE;
When added to static void observer_biobj(), it allows to stop logging of
the non-dom. points, it is useful for testing and can be reverted for the
data submission.
It can be somehow be set with options, but I am not quite sure how to pass
it, "log_nondominated:none" ?

**Comment by ttusar** [comment]
Exactly, see also http://numbbo.github.io/coco-doc/C/

**Comment by loshchil** [comment]
Thank you for the link. Sorry, I overlooked that.

**Comment by brockho** [comment]
This issue seems solved to me.

**Comment by loshchil** [comment]
My runs on 10 instances of 2D...20D problems for 300K  times D  evaluations generated 200 GB of data. Things happening between 100KD and 300KD do matter. How can I transfer this data to you?
