### ISSUE TITLE
coco-doc

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#811]
From my side, the general documentation of the Coco platform (docs/coco-doc) can also go online now. Any objections?

**Comment by nikohansen** [comment]
OK, great, I synchronized the abstract (it's a copy-paste between `conf.py` and `index.rst`), so go ahead.

**Comment by brockho** [comment]
Thanks Niko. The documentation is now online at http://numbbo.github.io/coco-doc/ and also already linked from the README.md in the development branch (to be available to everybody after the next release).
