### ISSUE TITLE
The definition of Schwefel function seems inconsistent with the implementation 

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#837]
If we respect to the implementation : 
1) The `x_opt` in the formula `z = 100(Lambda^10(z^hat - x_opt) + x_opt)` should be `2*abs(x_opt)`.
2) The formula `- frac{1}{D} sum(...)` should be `- frac{1}{100D} sum(...)`.

(Thanks Niko, I've updated some expressions such that the context is more clear)

**Comment by nikohansen** [comment]
Thanks for spotting these! There is a third mistake in the description: `x_i^opt` in the second bullet point must be `2 * abs(x_i^opt)` as well. It's the same problem as with 1), a confusion of what x_opt is supposed to mean in the given context. Re 2), I guess this also cancels the `100` in front of the penalty term, not sure though...

**Comment by nikohansen** [comment]
Also: in f23 and f24 "+ f_opt" is missing.

**Comment by brockho** [comment]
I started to have a look at the above as well as at #1266.

The only unclear thing was whether the 100 should appear in front of the penalty term or not. It is not obvious to see that the implementation follows the LaTeX definition here but after checking the code carefully, I am convinced that @NDManh was correct in the sense that the `100` should stay in the LaTeX definition in front of the penalty term to coincide with the implementation. 

The coco svn repository has now the updated LaTeX code (in `coco/BBOB/doc/latexFunctions/`) and it will be nice if somebody can check (with me) whether everything is actually correct now in the pdf. We then have to update the HAL version and the links from the web pages.

**Comment by nikohansen** [comment]
It seems I spotted another mistake: Section 2.7, Step-Ellipsoid function, ``if \hat z_i > 0.5`` must read ``if |\hat z_i| > 0.5``, see also the [implementation here](https://github.com/numbbo/coco/blob/master/code-experiments/src/f_step_ellipsoid.c#L62).

**Comment by brockho** [comment]
Nice catch!

**Comment by nikohansen** [comment]
There is another small glitch in the definition of the Rosenbrock function `f8`: `x_opt` is chosen in `[-3, 3]^n`. This should have been mentioned explicitly in the definition.

**Comment by nikohansen** [comment]
All above errors are now addressed in the source file.

**Comment by nikohansen** [comment]
The fixed document were uploaded to [HAL](https://hal.inria.fr/inria-00362633) and to `http://coco.gforge.inria.fr/downloads/download16.00` and are used at the [COCO gforge home](http://coco.gforge.inria.fr) and in the links at the [latest old release](http://coco.gforge.inria.fr/doku.php?id=downloads).
