### ISSUE TITLE
\fopt in bbob-biobj output

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#839]
`\fopt` should be replaced by something like `HV_{\text{ref}}` in the captions of LaTeX and HTML output when the data comes from an algorithm run on the `bbob-biobj` suite.

**Comment by ttusar** [comment]
I'm looking over the latex template. Should I do this change as well?

**Comment by nikohansen** [comment]
Looks like being fixed in the biobj LaTeX template.

**Comment by brockho** [comment]
But I am not sure yet whether we also see the correct output in the html. I suggest to keep the issue open until we merge the doc branch back into dev and have updated the html captions.

**Comment by dtusar** [comment]
I updated the captions also for the `html` output.
