### ISSUE TITLE
Create tests for archive updates

### ISSUE THREAD

**Issue by ttusar** [numbbo/coco#843]
Use `doctest` (see existing Python tests).

**Comment by ttusar** [comment]
I've made some integration tests to check whether the python scripts for processing the archives and reconstructing logger output work as they should. Before committing these changes I want to check if it's OK to add some test data to the repository (a total of 370 kB) or would it be better that the tests download this data by themselves? I have the download-as-you-go functionality already implemented, because I thought the data will be bigger, but now its size turned out not to be significant, so I'm not sure what to do. Note that this data/tests won't ever be used by the users, it's a developer-only functionality.

In the case you want the data to be downloadable, where should I put the `tgz` files?

**Comment by brockho** [comment]
Because it is only 370kB, I think, we should go for the option of including it in the repository. We just experience (again) a place without internet here in Nagano where the `python do.py test-postprocessing-all` for example does not work if the data has not been downloaded before. Hence, we better include everything for these new tests.

**Comment by ttusar** [comment]
I'm almost done with this issue, one (hopefully) last question: To run these tests, the `pytest` module needs to be installed. It seems to be installed by default in anaconda, but I had to install it manually on the slaves. Should this requirement be noted somewhere in the documentation? Where?

**Comment by ttusar** [comment]
I put the requirement description into `code-preprocessing/README.md`
This issue can now be closed.
