### ISSUE TITLE
negative target values

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#848]
For the bi-objective testbed, I suggest that we could add a few negative target values to the default `pprldmany` targets. Between 5 and 10% negative values could be a reasonable choice.

**Comment by dtusar** [comment]
What should be the range of the negative values?

**Comment by nikohansen** [comment]
Here would be my current proposal: 

`{-10^{-4}, -10^{-4.2}, -10^{-4.4}, -10^{-4.6}, -10^{-4.8}, -10^{-5}, 0, 10^{-5}, 10^{-4.8}, 10^{-4.6}, \dots, 10^{-0.2}, 10^0}`

**Comment by nikohansen** [comment]
See https://github.com/numbbo/coco/pull/855#issuecomment-198659160

**Comment by dtusar** [comment]
Now we have 58 targets.
