### ISSUE TITLE
There is no boundary handling procedure for the f_linear_slope.

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#849]
I and Wassim try but don't find boundary handling for f_linear_slope. Could you check it?

**Comment by oaelhara** [comment]
I'll add that calling:
`f_linear_slope_evaluate(problem, tmp_x, &y);`
with `tmp_x[i] = 2 * problem->best_parameter[i];`
triggers:
`assert(y[0] + 1e-13 >= problem->best_value[0]);`

**Comment by oaelhara** [comment]
Was there a plan to use `problem->smallest_values_of_interest` and `problem->largest_values_of_interest` to map all solution outside of the region of interest inside anyway that was, just, not yet implemented?

**Comment by nikohansen** [comment]
Not quite, a "boundary handling" is only applied if the x-value becomes better than the best x-value, see http://coco.lri.fr/downloads/download15.01/bbobdocfunctions.pdf#page=21

Does this mean, that the test procedure which compares function values to the original test bed implementation does not cover solutions outside of the domain [-5, 5]?

**Comment by oaelhara** [comment]
> Does this mean, that the test procedure which compares function values to the original test bed implementation does not cover solutions outside of the domain [-5, 5]?

Not necessarily but probably. For a point to be mapped back to [-5,5], it needs to agree, sign-wise, with x_opt on at least one coordinate and have the value of this agreeing coordinate outside [-5, 5]

**Comment by NDManh** [comment]
According to the definition of function ```z_i = x_i if x_i^opt*x_i < 5^2 and z_i = x_i^opt otherwise, for i = 1,...,D```, it means ```z_i in [-5, 5], for all i```. However, the implementation of f_linear_slope_raw has not covered this requirement.

**Comment by nikohansen** [comment]
> it means `z_i in [-5, 5], for all i`

no, it doesn't. I `x_i^opt = 5`, `z_i` can be `-100`.

**Comment by NDManh** [comment]
@nikohansen : Sorry, I'am confused, the correct condition for `z_i`must be : if `x_i^opt = 5` then `z_i <= 5`, and if `x_i^opt = -5` then `z_i >= -5`.

**Comment by nikohansen** [comment]
Yes, correct, and how is this different from the definition of the function?

**Comment by NDManh** [comment]
In the implementation, `x[i]` plays a role as `z_i, i=1,...,D`, in the definition and there is no restriction for these variables.

**Comment by nikohansen** [comment]
Any takers?

**Comment by NDManh** [comment]
It seems I have no permission to push. Could you take care of solving this issue, Wassim?

**Comment by oaelhara** [comment]
Neither do I.
But you should still be able to make a pull request.

**Comment by brockho** [comment]
Exactly: The standard way of contributing to the code should almost always be to
1) work in your own fork, commit, change, and test until you have a version, you want to share
2) pull the latest change from the development branch (you should do item 2 regularly, in particular before to make changes)
3) create a pull request from the branch you worked on to any of the three test branches `devel-test1`, `devel-test2`, or `devel-test3` in the numbbo/coco repository. The easiest might be to do item 3 on the github web page after you pushed your changes to your own fork (you should see a link popping up on top after you did the push).

I agree that git is not easy to understand in the first place, but eventually, it is learnable.

**Comment by NDManh** [comment]
Thanks Dimo, I'll try to follow your advices.

**Comment by ttusar** [comment]
Can this issue be closed now?

**Comment by NDManh** [comment]
Yes, closed.
