### ISSUE TITLE
Updating reference hypervolume values

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#853]
I would like to suggest better reference hypervolume values for a few problems. I am aware of your possible/planned update and found that some values can be further improved. What would be the procedure in this case? I don't log x-values and objective values, but the difference with the reference values is so small that I can exclude that it is due to a bug. 
Could you please let me know when is the latest date for this BBOB edition when I can submit my reference hypervolume values?  I guess that this date will coincide with the time since when all users should update their code to rerun the experiments to have updated logs and plots. 
This would reduce the problem of negative hypervolume targets.

**Comment by ttusar** [comment]
We need the archives (the `adat`) files to update our reference sets and their hypervolume values. If you are willing to upload the archives somewhere and send us the link (probably by email) that would be perfect. 

I will let others comment on the deadlines.

**Comment by loshchil** [comment]
Thanks for the reply. The "bug" part was to say that I don't think there is a need to collect x-values as the results are very close to the reference values. In my values would be e.g. two times better than the reference, then I would think I have a bug somewhere.

**Comment by loshchil** [comment]
Can I use the archive-update tool to reduce the size of the .adat file?
So far it does not work as I cannot run setup 
interface\coco_archive.c:732:3: error: unknown type name 'coco_archive_t' 
coco_archive_t *archive;
is it supposed to work?

**Comment by ttusar** [comment]
It should :)
You need to first run `python do.py install-preprocessing` and only then call the `archive_update.py`. You could also just do `python do.py run-preprocessing`, which installs the preprocessing first and then runs the archive update. 

Note that you need to set the paths in `archive_update.py` (sorry for the user-unfriendliness here, but this was supposed to be used only by "us", not the users). I will try to fix this soon, but there are some other issues with higher priorities that demand my attention...
