### ISSUE TITLE
region of interested of bbob-biobj suite

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#860]
We should very rapidly decide on a suitable region of interested for the ``bbob-biobj`` benchmark suite.

**Comment by brockho** [comment]
If I recall your previous e-mail correctly, let me precise that you mean the `coco_problem_get_smallest_values_of_interest` and `coco_problem_get_largest_values_of_interest` here and not the region in objective space between ideal and nadir point (which we also sometiimes called "region of interest").

**Comment by brockho** [comment]
Decision of today: we go with [-100, 100] for the moment, based on the data we have seen (number and range of points in the reference set that is outside of [-5,5]).

**Comment by loshchil** [comment]
I believe that there should be some newsletters telling BBOB users about such major news.

**Comment by nikohansen** [comment]
> I believe that there should be some newsletters telling BBOB users about such major news.

+1

**Comment by ttusar** [comment]
Solved by a telling pull request number #888

**Comment by brockho** [comment]
Issue has been announced to all registered COCO users and can be closed now.
