### ISSUE TITLE
How many instances are used for plots?

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#867]
I use 10 runs on 10 instances (1 run per instance) on 2-D Sphere to make plots when 
i) all 10 instances are used, 'res' folder
ii) only the first 5 are used, 'res2' folder 
[bbob_pproc.zip](https://github.com/numbbo/coco/files/183129/bbob_pproc.zip)
I was told that only the first 5 instances are used, but this is not the case as can be seen from the figure 
[pprldmany_02D_noiselessall.pdf](https://github.com/numbbo/coco/files/183139/pprldmany_02D_noiselessall.pdf)
curves are differwent because the ref target hypervolume is 1 for instances 6 .. 10 so the results look worse. 
Should all 10 instances be used for plots? If not, then it looks like a bug.

**Comment by dtusar** [comment]
Thank you for pointing this out. There is actually a bug in the code. In this case all the 10 instances are used. We are going to fix this as soon as possible.

**Comment by loshchil** [comment]
If it is one line of code, could you please tell me how to fix it?

**Comment by dtusar** [comment]
The fix is now available on the development branch.

**Comment by loshchil** [comment]
"python -m bbob_pproc res" with the attached data of 10 instances  fails
in line 847 of pproc.py, list index out of range
but python -m bbob_pproc res2 works

**Comment by dtusar** [comment]
You can comment the assert in the line 847 of pproc.py in order to run the postprocessing. The fix will be ready shortly.

**Comment by loshchil** [comment]
It works, thanks!

**Comment by dtusar** [comment]
Fixed.
