### ISSUE TITLE
An issue in Rosenbrock function

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#906]
According to the definition (also to the old code) of Rosenbrock function, I think that we should remove the line code 131: ```if (row == column)``` in the current implementation of this function. Although, there is no effect on current platform (since when ```D <= 40, then max(1, sqrt(D)/8) = 1```), on large scale platform, it'll bring a problem.

**Comment by NDManh** [comment]
In the old C implementation (it's the rotated rosenbrock function):
```
for (i = 0; i < DIM; i ++)
        {
            for (j = 0; j < DIM; j++)
                linearTF[i][j] = scales * rotation[i][j];
        }
```

**Comment by brockho** [comment]
I agree, it looks like a bug in higher dimensions. Thanks for spotting this. It also suggests to extend the tests to higher dimensions than just 40-D.

**Comment by NDManh** [comment]
I close this issue.
