### ISSUE TITLE
ppdata.html not produced

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#922]
When running the postprocessing with 3 algorithms, the `ppdata.html` overview file is not written although it is referenced from within the single algorithms' `templateBBOBarticle.html`.

**Comment by dtusar** [comment]
If I run the `bbob_pproc` module with 3 algorithms then the `ppdata.html` is generated. Only I if call directly rungenericmany.py the overview file is not generated. @brockho is this the same for you?

**Comment by brockho** [comment]
Calling bbob_pproc with 3 algorithms as `python -m bbob_pproc ALG1 ALG2 ALG3` after installing the postprocessing (with the code in the doc branch though) does not produce the `ppdata.html` file for me.

**Comment by dtusar** [comment]
I run it on the development branch. So probably you messed up something on the doc branch. :) I'm going to check the doc branch.

**Comment by dtusar** [comment]
I got this error:
  File "C:\Users\dejan\AppData\Roaming\Python\Python27\site-packages\bbob_pproc-
0.8b1-py2.7.egg\bbob_pproc\compall\pptables.py", line 617, in main
    with open(filename) as infile:
IOError: [Errno 2] No such file or directory: 'ppdata\\templateBBOBmany.html'

This is something I already fixed on the development branch. In my `ppdata` folder the file `templateBBOBmany.html` existed from a previous run, so I spotted the problem by chance. 

But this should be caught by the CI, so I have to update the testing procedure.

**Comment by brockho** [comment]
You are right, @dtusar, the problem occurred in the doc branch which is now solved with your latest changes and the merge by @nikohansen into the doc branch. For me, the postprocessing with 3 algorithms runs through again correctly, producing the `ppdata.html` file.
