### ISSUE TITLE
Baseline algorithms?

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#924]
Would it be possible to have the data for some baseline algorithms before the deadline? This might include random search, NSGA-2, SMS-EMOA, RMMEDA or others, excluding the favorite ones the organizers want submit themself. This would allow to have more readable ECDF curves, i.e., not a lonely algorithm. This would also reduce the time (wallclock and CPU) each user would spend if she/he would decide to have some baselines. I don't think this would need any additional tuning to perform by the organizers as we are talking about the baselines in some naive settings. Moreover, I guess that you may have some of them available, e.g. (random search, NSGA-2, SMS-EMOA, RMMEDA). I am not asking for more since very strong baselines could repel potential participants, but random search and NSGA-2 normally should not have this effect. 
If you disagree, then please let me know the reason.

**Comment by Ulfgard** [comment]
we could offer the results for SteadyStateMOCMA and SMS-EMOA with mu=10

**Comment by loshchil** [comment]
This would be great to have! I would use them as the baselines if BBOBies would somewhat say, "yes, we are going to put them as the baselines available online, so you and other users may refer to them". In this case, if I submit my BBOB plots somewhere (e.g., PPSN) I could just say that these are the  BBOB baselines and so I don't have to justify why I use such baselines and their hyperparameters, e.g., the choice of the initial step-size and search ranges in MOCMA while/if they are somehow different from some other sources. In other words, it should go via the organizers. 

Another important details is that these baselines should be computed w.r.t. the finalized hypervolume references so that their plotting makes sense. To my best understanding, the references are not yet decided/validated.

**Comment by Ulfgard** [comment]
(before it gets understood wrongly, we=our group, we are not affiliated with the benchmark :), we are just offering our own reference results) 

What should this reference include?
1. all results
2. the program used to generate the results (will depend on Shark 3.1 because i won't find the time to make it standalone) 
3. ???

**Comment by loshchil** [comment]
I understood "we" as you and your collaborators.  I don't understand what you mean by to be "affiliated with the benchmark", you benchmarked it but you are not the benchmark, this I understand :-)

Note that the " finalized hypervolume references" are the best hypervolumes values found so far, they are given for all instances and dimensions in coco.c/h files. When running an algorithm, its performance is computed and logged w.r.t. these reference values. In the current settings, once the hypervolume references are updated, you should rerun your algorithm again to update your data (or you at least rerun some script to replay your archive points, I guess). 
Therefore, the data provided for the baselines should be computed w.r.t. the finalized reference hypervolume values.

What the reference baseline algorithm should include is better to ask the BBOBies (if they will go for it at all). I think that it should include
1. all the results w.r.t. the reference hypervolume values used for the papers to be submitted this year
2. a short description sufficient for readers/reviewers to understand what is benchmarked
3. link to the source code is optional, but nice to have

**Comment by nikohansen** [comment]
> Would it be possible to have the data for some baseline algorithms before the deadline?

For the moment I would prioritize time-wise the creation of a many-algorithms template. Only then it will even be possible to display several algorithms in the papers by default.

**Comment by loshchil** [comment]
When do you plan to finalize the reference hypervolume values? To my best
understand, all the data generated for algorithms before that date can be
basically discarded.
