### ISSUE TITLE
ECDFs for one function/algorithm/dimension still needed?

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#927]
In the single-algorithm output: Do we really need all the pprldmany_fXXX_02D.*, pprldmany_fXXX_03D.*, pprldmany_fXXX_05D.*, pprldmany_fXXX_10D.*, pprldmany_fXXX_20D.*, pprldmany_fXXX_40D.* now that we have the summarizing files pprldmany_fXXX.*?

I would at least opt for a switch in the postprocessing (which can produce these files if someone wants them) but to not produce them in the default setting. It really takes a lot of time and space to produce and store all those 3*6*55 files (in the biobjective case). At the same time, it will also make the testing quicker.

**Comment by dtusar** [comment]
I wouldn't generate them at all. @nikohansen What do you think?

**Comment by nikohansen** [comment]
Right, for the moment I also don't really see a use-case for which we would need these. It is of course different if we have more than one algorithm.

**Comment by dtusar** [comment]
Now I know. In the single objective case we also draw a best algorithm graph. OK, I will skip these figures for the bi-objective case.

**Comment by brockho** [comment]
Well spotted. Having the best algorithm displayed is an interesting use-case for the single-objective tested(s), and later on also for the biobjective one. For the moment, however, it might be okay to have them taken out as in pull request #929 until we have a best algorithm displayed. I suggest to close the issue.
