### ISSUE TITLE
Duplicate code in toolsdivers.py and cocoutils.py

### ISSUE THREAD

**Issue by brockho** [numbbo/coco#931]
Quite some code related to git commands and retrieving the git version is duplicate in `toolsdivers.py` and `cocoutils.py`. Isn't there a way to "import" the `cocoutils.py` when installing the postprocessing?

**Comment by nikohansen** [comment]
It would create a probably undesirable dependency. The post-processing is meant to be a stand-alone tool for data presentation and analysis.

**Comment by brockho** [comment]
Okay, I understand. @dtusar agreed to put comments at both places to point to the other (duplicate) code which will hopefully allow to keep both codes the same if somebody changes something. Issue can be deleted from my side.

**Comment by dtusar** [comment]
Added comments with the reference to the other file.
