### ISSUE TITLE
Not good link `Runtime distribution plots (per dimension)` in `templateBBOBarticle.html`

### ISSUE THREAD

**Issue by NDManh** [numbbo/coco#950]
After post-processing procedure, I try to click the link ```Runtime distribution plots (per dimension)``` in ```templateBBOBarticle.html``` and obtain an error since there is no link to ```.../RS_on_bbob-biobj/pprldmany-single-functions/pprldmany_02D.html```. I think that ```pprldmany_02D.html```should be ```pprldmany_gr_02D.html```, because I found it in the folder ``````.../RS_on_bbob-biobj/pprldmany-single-functions/```

**Comment by brockho** [comment]
Dear @NDManh, thanks for pointing this out. It seems as if this still stems from the fact that we decided recently to not produce the dimension-wise pprldmany plots anymore because the data is now displayed for all dimensions in the `pprldmany.html` file. We simply have to clean this up.

**Comment by dtusar** [comment]
The link was removed.
