### ISSUE TITLE
Non-dominated point in relation to the ideal

### ISSUE THREAD

**Issue by olacirjr** [numbbo/coco#966]
In the problem 48 when using two decision variables I am having an issue where the algorithm finds a point that is non-dominated in relation to the ideal point, where the ideal is:
-48.21999999999999886313 -6.29999999999999804601
and the point found is:
128.22275361291164585964 -6.29999999999999893419
with a decision vector of:
2.10484373228308641046 -2.10484373102991639826

When this point is found, the algorithm stops, since it assumes all the new solutions are dominated by the ideal point.
Is anyone else having this issue?
How should I proceed in this case?
Thank you.

**Comment by ttusar** [comment]
This is a precision problem and we will take care of it (a new release will contain a fix). Thanks for the report!

**Comment by brockho** [comment]
With the newest release 1.0.2, this bug should be fixed. Thanks @ttusar ! And thanks @olacirjr for catching this.
