### ISSUE TITLE
Data submission

### ISSUE THREAD

**Issue by loshchil** [numbbo/coco#967]
Instead of suggesting to use free/limited data transfer services, could you organize a FTP, or
register a www.wetransfer.com transfer account such that 
you can receive up to 20GB files in one shot  (not 2GB) 
[https://wetransfer.zendesk.com/hc/en-us/articles/207479946-Allow-your-friends-and-clients-to-send-20GB-transfers-to-you](url)

**Comment by brockho** [comment]
Dear Ilya,

We are trying our best to get something set-up at Inria at the moment, but cannot promise anything. For the time being, I found that https://transfer.pcloud.com/ seems to offer up to 5GB transfers for free which is already an improvement over wetransfer.

**Comment by loshchil** [comment]
Thank you, Dimo! 
I registered an account at wetransfer, I have about 200GB of tar.gz's, I hope to send it in 10 shots by tomorrow. I hope that the problem then will be solved for me. 
All I wanted to say is that you could similarly make an account as I did (https://ilya.wetransfer.com/) so that all the users could send you big files with no issues.

**Comment by brockho** [comment]
I think, we can safely close this issue after all submission came in well.
