### ISSUE TITLE
Error on compiling with g++

### ISSUE THREAD

**Issue by olacirjr** [numbbo/coco#971]
In my machine, when compiling the framework using g++ I have the following error:
In file included from MOPSO-COCO.c:13:0:
code-experiments/src/transform_vars_x_hat.c: In function ‘coco_problem_t\* transform_vars_x_hat(coco_problem_t_, long int)’:
code-experiments/src/transform_vars_x_hat.c:76:18: error: invalid conversion from ‘const char_’ to ‘char*’ [-fpermissive]

To solve this error I just have to change the line 65 of code-experiments/src/transform_vars_x_hat.c from:
char *result;
to:
const char *result;

Althrough it is not a critical problem and have a trivial fix, it would be nice if you can include it in the next versions.

Thank you.

**Comment by ttusar** [comment]
Thanks for the report, this is now fixed and the fix will be included in the next release. 

@nikohansen and @brockho, should we add a C++ test to our CI?

**Comment by nikohansen** [comment]
That might be a good idea. In this case, I thought that the right C compiler options should also generate a warning which could be caught already during development before testing.

**Comment by nikohansen** [comment]
Can this be closed?

**Comment by ttusar** [comment]
There are no more errors when compiling with g++, but we still don't have a test for it and we have two conversion warnings.

**Comment by brockho** [comment]
Decision of today: This issue seems to be solved right now.
