### ISSUE TITLE
Bonferroni correction

### ISSUE THREAD

**Issue by nikohansen** [numbbo/coco#980]
The file `latex_commands_for_html.html` contains the phrase "Bonferroni correction by the number of instances". This is probably wrong, or if true, it seems not an appropriate application of the Bonferroni correction. The original idea/implementation did, I believe, the correction by number of functions times number of displayed algorithms, which is (very) roughly the number of independent tests.

**Comment by brockho** [comment]
@nikohansen and I checked the code and it does (in both the 2 algorithm and the many algorithm case) a Bonferroni correction of #dimensions * #functions for the tables. This is corrected now in the development branch with pull requests #1009 and #1010.
